ballerina-platform/ballerina-distribution

resources/executables/windows/ballerina.bat, resources/executables/windows/composer.bat
Fix long path issue in windows.
relates to https://github.com/ballerina-platform/ballerina-lang/issues/7420
Fix long path issue in windows when running ballerina or composer.
Add all libraries to the ballerina class path using wildcard.
=> Fix long path issue in windows

resources/executables/windows/ballerina.bat, resources/executables/windows/composer.bat
This commits fixes the issue of ballerina files are not getting executed if they are on a different drive than of BVM.
Related to https://github.com/ballerina-platform/ballerina-lang/issues/8364
=> Fix windows ballerina runtime issues

resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
This will mandate java version 1.8 for ballerina runtime. Related to https://github.com/ballerina-platform/ballerina-lang/issues/3017
=> Mandate java version 1.8 for ballerina runtime

resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
This commit resolves throwing CNF exception for org.omg.PortableServer.ThreadPolicyOperations.
In JDK9 onwards this package is exposed through the dynamic package of java.corba.
This commit resolves https://github.com/ballerina-platform/ballerina-lang/issues/9184
=> Fix CNF issue in JDK9

resources/executables/windows/ballerina.bat
> Fix the issue of depending JAVA_HOME to check java version. Since Ballerina distribution depends on its own JVM; need to check JVM version with the `%BVM_HOME%\bin\java` instead of `%JAVA_HOME%\bin\java`.
=> Fix the issue of depending JAVA_HOME to check java version

resources/executables/linux/ballerina
Signed-off-by: AbhishekKr <abhikumar163@gmail.com>
This fixes reported issue#112.
It will allow linux resource to infer BALLERINA_HOME if auto-configured env var is missing or wrong.
If auto-configured env var BALLERINA_HOME is missing or wrong, it checks for relevant dir-names under `/usr/lib64/ballerina/` and fixes the value.
This fixes BALLERINA_HOME issue causng `Error: JAVA_HOME is not defined correctly.` for linux (at least rpm) release `v0.983.0-1`.
N/A. This is just a fix for already existing flow.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> fixing BALLERINA_HOME inference issue for linux resource, fixes #112

resources/tools/bin/ballerina
<BAL_CMD> "this is a space"
The above quoted string is parsed as four different string arguments [this, is, a, space]. I think the quotes are getting removed. But this is observed in a Linux environment only, but it is working as expected in a Mac environment, i.e the quoted string is treated as a single argument. The issue was with the bash script proxy file which does not honor the quoted string args.
Resolves https://github.com/ballerina-platform/ballerina-lang/issues/19547
=> Fix quoted args getting trimmed by the bash script

ballerina-command/src/main/java/org/ballerinalang/command/cmd/DistributionCommand.java, ballerina-command/src/main/resources/cli-help/ballerina-dist-update.help, ballerina-command/src/main/resources/cli-help/ballerina-dist.help, ballerina-command/src/main/resources/cli-help/ballerina-help.help, ballerina-command/src/main/resources/cli-help/ballerina-list.help, ballerina-command/src/main/resources/cli-help/ballerina-pull.help, ballerina-command/src/main/resources/cli-help/ballerina-remove.help, ballerina-command/src/main/resources/cli-help/ballerina-update.help, ballerina-command/src/main/resources/cli-help/ballerina-use.help
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/336
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/334
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/332
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/328
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/327
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/326
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/324
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/323
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/322
=> Fix help text

ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java, ballerina-command/src/main/resources/cli-help/ballerina-dist-update.help, ballerina-command/src/main/resources/cli-help/ballerina-dist.help, ballerina-command/src/main/resources/cli-help/ballerina-list.help, ballerina-command/src/main/resources/cli-help/ballerina-pull.help, ballerina-command/src/main/resources/cli-help/ballerina-remove.help, ballerina-command/src/main/resources/cli-help/ballerina-use.help
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/351
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/352
=> Update help text and update command output with accurate terms

resources/tools/bin/ballerina.bat
> Reverts the changes introduced by PR #370 to the ballerina.bat file for verifying the JRE version and directing the user to the INSTALL.txt file.
=> Revert JRE verification logic in bat script

examples/index.json, examples/table/table.bal, examples/table/table.description, examples/table/table.out, examples/table/tests/table_test.bal
> $title
Issue: https://github.com/ballerina-platform/ballerina-lang/issues/23060 …
=> Add BBE for new Table implementation

ballerina/build.gradle, ballerina/resources/stdlib-configs.json, build.gradle
$subject
Pack standard library socket external module to the final pack.
- Include build configs (zip, mac, linux, and windows)
- https://github.com/ballerina-platform/module-ballerina-socket/pull/2
- https://github.com/ballerina-platform/ballerina-lang/pull/22782
- Java 8
- Ballerina 1.2.0
- MacOS
Find more details about this migration here [1].
[1] https://groups.google.com/forum/#!topic/ballerina-dev/RssHIxkR1XA
=> Add ballerina socket stdlib module build configs

ballerina/build.gradle, ballerina/resources/stdlib-configs.json
$subject
- Change the jar path in the config file
- Use socket API docs in the artifact
- https://github.com/ballerina-platform/module-ballerina-socket/pull/8
- https://github.com/ballerina-platform/ballerina-lang/issues/23506
- Java 8
- Ballerina 2.0.0-SNAPSHOT
- macOS
=> Pack socket API docs and fix jar path

ballerina/build.gradle, ballerina/resources/stdlib-configs.json, build.gradle, examples/index.json, gradle.properties
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/23648
Currently, pack the socket balos and birs as follows:
```
jballerina-2.0.0-SNAPSHOT/cache/
├── balo
│   └── ballerina
│       └── socket
│           └── 0.6.0
│               ├── Ballerina.toml
│               └── socket-2020r1-java8-0.6.0.balo
└── bir
└── ballerina
└── socket
└── 0.6.0
```
- Java 8
- Ballerina 2.0.0-SNAPSHOT
- ballerina/socket 0.6.0
- macOS
=> Introduce common cache for balos, birs, and jars

examples/object-methods/object_methods.description
Update object methods description
> ## Summary of changes from 2019R1 to 2019R2
> The ability to define a method outside the object type has been removed.
=> Cannot create methods outside objects now

examples/abstract-objects/abstract_objects.bal, examples/anonymous-objects/anonymous_objects.bal, examples/any-type/any_type.bal, examples/object-assignability/object_assignability.bal, examples/object-initializer/object_initializer.bal, examples/object-methods/object_methods.bal, examples/object-type-reference/object_type_reference.bal
Object `__init` method is changed to `init`. This PR fixes it in BBEs.
Refer: https://github.com/ballerina-platform/ballerina-lang/issues/23358
=> Migrate `__init` methods to `init`

examples/object-type-reference/object_type_reference.bal, examples/object-type-reference/object_type_reference.description
Objects can now include non-abstract objects. This PR updates description.
Refer spec change: https://github.com/ballerina-platform/ballerina-lang/issues/23359
May need to improve the BBEs too.
=> Update details of BBE : Objects can now refer non-abstract objects

examples/let-expression/let_expression.bal, examples/let-expression/let_expression.out
The new parser does not support binding patterns. Hence removing from this example temporary.
=> Remove binding patters from let-expression BBE

ballerina/build.gradle
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/24373
Pack `index.json` to final packs.
Note that, there has been a recent fix to change the jBallerina path as well. The BBE path with that recent fix as follows:
```sh
ballerina-swan-lake-preview1-SNAPSHOT/distributions/ballerina-slp1/examples/index.json
```
Ballerina swan-lake preview1-M6
=> Enable packing index.json to the final packs

examples/records/records.bal
Reverts ballerina-platform/ballerina-distribution#687
Reverting JSON formatting changes to be consistent with https://jslint.com/.
=> Revert "Update records.bal"

examples/testerina-assertions/testerina_assertions.bal, examples/testerina-assertions/testerina_assertions.out
> Update examples for testing assertions with the introduction of "assertExactEquals" functionality
Addresses a task in https://github.com/ballerina-platform/ballerina-lang/issues/22048
> Update examples for testing assertions with the introduction of "assertExactEquals" functionality
=> Add more examples for test assertions

ballerina/build.gradle
> The Kafka BBEs are ignored in tests, because to Kafka BBEs to run, there should be an active Kafka cluster is running
=> Update comment on Kakfa examples ignoring

ballerina/build.gradle
The existing logic is as follows:
If a BBE is in the `buildIgnoreList` it is skipped from compiling and running at all. Then the remaining BBEs are considered for further actions.
- If remaining BBEs are in the `runIgnoreList`, they are tested after compiling. (run test cases)
- If remaining BBEs are not in `runIgnoreList`, they are used for output verification after compiling.
This logic skip compiling and testing (run test cases) the BBEs which are not in the `runIgnoreList`.
The updated logic will do followings:
If a BBE is in the `buildIgnoreList` it is skipped from compiling and running at all. Then the remaining BBEs are considered for further actions.
- Compile and test (run test cases) all the remaining BBEs.
- If remaining BBEs are not in the `outputVerificationIgnoreList`, they …
=> Fix a bug in BBE verification logic

stdlib-integration-tests/email/tests/email_test.bal, stdlib-integration-tests/index.json
Add a test to verify the existence of the Email library. Resolves https://github.com/ballerina-platform/module-ballerina-email/issues/14
=> Add a test to check the existance of the Email library

examples/error-destructure-binding-pattern/error_destructure_binding_pattern.bal, examples/error-destructure-binding-pattern/error_destructure_binding_pattern.out
$Subject
Named arg binding pattern bug fixed with https://github.com/ballerina-platform/ballerina-lang/pull/26000
=> Fix broken error-destructure-binding-pattern BBE

stdlib-integration-tests/ftp/tests/ftp_test.bal
Add a simple FTP test to make sure FTP module is included in the standard library distribution.
=> Add a simple FTP module test to test the existence of the FTP module

stdlib-integration-tests/websocket/tests/web_socket_test.bal
Ignoring as this is not required for that test. Having this will intermittently fail the build because when the network is slow it takes a lot of time to send back the close frame.
=> Ignore the connection close in websocket test

doc-guidelines.md
* Update API doc guidelines for examples
* Remove redundant information regarding function description formatting - already available in https://ballerina.io/learn/documenting-ballerina-code/.
=> Update API Doc Guidelines for Examples

ballerina/build.gradle, gradle.properties, stdlib-integration-tests/index.json, stdlib-integration-tests/io/tests/io_socket_tests.bal, stdlib-integration-tests/io/tests/server.bal
- Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/568
- Upgrade stdlib versions
Add new channel API tests to test socket and IO compatibility.
> Yes
https://github.com/ballerina-platform/module-ballerina-io/pull/31
- SLP6
- macOS
- Java11
=> Add socket IO tests and upgrade versions

stdlib-integration-tests/index.json, stdlib-integration-tests/oauth2/tests/mock-servers/secured_service_with_oauth2.bal
This PR enables the OAuth2 integration tests which was disabled by https://github.com/ballerina-platform/ballerina-distribution/pull/937, since it was failing due to the update by https://github.com/ballerina-platform/module-ballerina-oauth2/pull/32
=> Enable OAuth2 integration tests

.github/workflows/daily-build.yml, .github/workflows/main.yml, .github/workflows/pull-request.yml
1. Mark on the zip distribution as upload artefact
2. Continue build even if there is a task failure. This is so that we don't have to wait and fix tests sequentially,
=> Improve build actions

ballerina/build.gradle, build.gradle
- Convert AWS Lambda artifacts to GitHub packages
- Resolves https://github.com/ballerina-platform/module-ballerinax-aws.lambda/issues/234
=> Convert AWS Lambda artifacts to GitHub packages

ballerina-test/build.gradle, ballerina/build.gradle, devtools-integration-tests/build.gradle, gradle.properties
Currently, all the tests inside the `ballerina-distribution` are running even when we specify `-x test`. This is happening because all the tests are now a part of the Gradle `build` task, instead of the Gradle `test` task.
WIth this PR, all the testing tasks are added to the Gradle `test` task.
=> Migrate tests to grade test task

ballerina/build.gradle
> Excluding ```websub``` related integration tests from the ballerina-distribution.
=> Excluding WebSub related integration tests from ballerina-distribution

examples/https-listener/https_listener.bal, examples/https-listener/https_listener.server.out
Remove config api from http BBE because config api is deprecated.
=> Remove config api from http BBE

examples/byte-io/byte_io.bal, examples/csv-io/csv_io.bal, examples/text-io/text_io.bal
Previously, I/O streams returned a stream error with a null, however, the recent changes return a stream without a null as below.
`stream<anydata, io:Error>`.
=> Fix the deprecated null return in I/O streams

ballerina/build.gradle, build.gradle, gradle.properties
- Remove messaging modules under `ballerinax` org from distribution.
- Removed modules: `ballerinax/stan`, `ballerinax/nats`, `ballerinax/kafka`, `ballerinax/rabbitmq`.
- Disable messaging examples from building against the distribution. 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/861 
**PRs enabling pushing the modules to central**
https://github.com/ballerina-platform/module-ballerinax-kafka/pull/83
https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/71
https://github.com/ballerina-platform/module-ballerinax-stan/pull/18
https://github.com/ballerina-platform/module-ballerinax-nats/pull/75
=> Remove messaging modules from distribution 

stdlib-integration-tests/auth/tests/Config.toml, stdlib-integration-tests/auth/tests/auth_test.bal
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/862
=> Enable tests for basic auth file user store

ballerina/build.gradle, examples/any-type/any_type.bal, examples/any-type/tests/any_type_test.bal, examples/time/tests/time_test.bal, examples/time/time.bal, gradle.properties
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1081
- redesign and implement the time BBE
- modify time changes in any-type BBE
- temporarily disable the following BBEs until time changes added(https://github.com/ballerina-platform/ballerina-distribution/commit/9c0b5fafd02bdca0117d7dc83a7f04d8d709c0db)
- mysql-complex-type-queries
- jdbc-complex-type-queries
- Unit tests 
> Yes
- macOS
- Java 11
- SLA 3
=> Implement a new BBE for time standard library 

examples/tcp-listener/tcp_listener.bal, stdlib-integration-tests/tcp/tests/mock_servers.bal, stdlib-integration-tests/udp/tests/mock_servers.bal
> Replace 'readonly & Error err' with 'Error err' in udp and tcp modules
=> Replace 'readonly & Error err' with 'Error err' in udp and tcp modules

examples/configurable/Config.toml, examples/configurable/configurable.bal, examples/configurable/configurable.description, examples/configurable/configurable.out
$subject
The record example is re-added as the support for configurable records are not removed.
N/A
- Unit tests 
ubuntu 20.04, jdk 11.0.9
=> Re-add record example for configurable

examples/the-main-function/tests/the_main_function_test.bal, examples/the-main-function/the_main_function.description, examples/the-main-function/the_main_function.out
> 
> N/A
> This was broken due to changes to the support of command line arguments. Now the example is modified to use command line options.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
- Ran FindSecurityBugs plugin and verified report? yes/no
> This is a sample
> N/A
> N/A
> N/A
> N/A
=> Fix "The Main Function" example

examples/tcp-transport-security/tcp_transport_security_listener.bal, stdlib-integration-tests/tcp/tests/mock_servers.bal, stdlib-integration-tests/udp/tests/mock_servers.bal
> Remove readonly return type-descriptor from onBytes(), onDatagram() methods in both UDP, TCP module
=> Remove readonly return type-descriptor from onBytes(), onDatagram() methods

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java
- Update AWS Lambada version
- Depends on https://github.com/ballerina-platform/module-ballerinax-aws.lambda/pull/341
=> Update AWS Lambada version in tests

examples/async/async.bal, examples/async/tests/async_test.bal, examples/threads-and-strands/threads_and_strands.bal
> This was caused by the changes to the return values of wait expressions on a future.
=> Fix compilation errors on threads-and-strand

new-examples/http-client-basic-auth/http_client_basic_auth.metatags, new-examples/http-client-bearer-token-auth/http_client_bearer_token_auth.metatags, new-examples/http-client-mutual-ssl/http_client_mutual_ssl.metatags, new-examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.metatags, new-examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.metatags, new-examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.metatags, new-examples/http-client-self-signed-jwt-auth/http_client_self_signed_jwt_auth.metatags, new-examples/http-client-ssl-tls/http_client_ssl_tls.metatags, new-examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.metatags, new-examples/http-service-basic-auth-ldap-user-store/http_service_basic_auth_ldap_user_store.metatags, new-examples/http-service-jwt-auth/http_service_jwt_auth.metatags, new-examples/http-service-mutual-ssl/http_service_mutual_ssl.metatags, new-examples/http-service-oauth2/http_service_oauth2.metatags, new-examples/http-service-ssl-tls/http_service_ssl_tls.metatags
$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1763
=> Update metatags of REST API security BBEs

examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.description, examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.description, examples/graphql-service-jwt-auth/graphql_service_jwt_auth.description, examples/graphql-service-oauth2/graphql_service_oauth2.description, examples/http-client-mutual-ssl/http_client_mutual_ssl.bal, examples/http-client-ssl-tls/http_client_ssl_tls.bal, examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.description, examples/http-service-mutual-ssl/http_service_mutual_ssl.bal, examples/http-service-ssl-tls/http_service_ssl_tls.bal
$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1763
=> Fix few issues in security BBE descriptions

examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.server.out, examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.server.out, examples/graphql-service-jwt-auth/graphql_service_jwt_auth.server.out, examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.out, examples/graphql-service-oauth2/graphql_service_oauth2.server.out, examples/graphql-service-ssl-tls/graphql_service_ssl_tls.out, examples/http-client-basic-auth/http_client_basic_auth.out, examples/http-client-bearer-token-auth/http_client_bearer_token_auth.out, examples/http-client-mutual-ssl/http_client_mutual_ssl.out, examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.out, examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.out, examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.out, examples/http-client-self-signed-jwt-auth/http_client_self_signed_jwt_auth.out, examples/http-client-ssl-tls/http_client_ssl_tls.out, examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.server.out, examples/http-service-basic-auth-ldap-user-store/http_service_basic_auth_ldap_user_store.server.out, examples/http-service-jwt-auth/http_service_jwt_auth.server.out, examples/http-service-mutual-ssl/http_service_mutual_ssl.out, examples/http-service-oauth2/http_service_oauth2.server.out, examples/http-service-ssl-tls/http_service_ssl_tls.out, examples/security-crypto/security_crypto.out, examples/security-jwt-issue-validate/security_jwt_issue_validate.out, examples/url-encode-decode/url_encode_decode.out
$subject
Removed the instruction:
```
```
Related to: Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Update instructions of security BBEs

examples/index.json
$Subject
The output verification of these BBEs are disabled due to https://github.com/ballerina-platform/ballerina-standard-library/issues/1505.
This should be merged after merging https://github.com/ballerina-platform/module-ballerina-graphql/pull/306
=> Enable Output Verification for GraphQL BBEs

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, ballerina/build.gradle, build.gradle, gradle.properties
> Fix https://github.com/ballerina-platform/ballerina-openapi/issues/469
> Introduce the new  `ballerinaOpenAPILibs` gradle configuration for packing the openAPI jars to the final distribution.
=> Change build.gradle configuration for OpenAPI Tool

examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client.out, examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client.proto, examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.bal, examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.description, examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.metatags, examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.out, examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.bal, examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal, examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.description, examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.metatags, examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.out, examples/index.json, examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.bal, examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.description, examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.metatags, examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.out, gradle.properties
This PR adds JWT bearer grant type BBEs for HTTP, WebSocket and gRPC.
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/1788
=> Add JWT bearer grant type BBEs for HTTP, WebSocket and gRPC

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java, devtools-integration-tests/src/test/resources/debug/project-based-tests/service-tests/hello_service.bal
This PR adds debugger integration test to verify debug instructions handling for service level variables.
https://github.com/ballerina-platform/ballerina-lang/pull/32732
Should be merged after https://github.com/ballerina-platform/ballerina-lang/pull/32732
=> Add debugger integration test for service variables

.github/workflows/publish-release.yml
Generate hashes for release artifacts (installers) in the automated process.
Automate the release process as much as possible.
Generate sha256 hashes for installers using openssl dgst tool.
##Fixes
https://github.com/ballerina-platform/ballerina-distribution/issues/2338
=> Generate hashes for release artifacts

.github/workflows/daily-build.yml, ballerina-test-automation/installer-test/build.gradle, ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/ProjectTest.java, ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
Build BBEs against installers to check the installers.
To run more tests on installers.
Added a new test 'testBBEs' to project tests. In the gradle build, the test will run and build BBEs.
running command - `bal init && bal build`
=> Add BBEs for installer tests as project tests

examples/dynamic-listener/dynamic_listener.bal
$title.
Made the `httpListener` variable `final` to get rid of the `isolated` warning.
=> Fix the dynamic listener BBE

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml, ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
Run installer tests for windows msi installer in daily build and release workflows.
Increase the tests for release artifacts.
https://github.com/ballerina-platform/ballerina-distribution/issues/2427
=> Run installer tests for windows msi installer

.github/workflows/test-installers.yml
Test signed pkg installer by running installer tests
Test release artifacts after the signing process
https://github.com/ballerina-platform/ballerina-distribution/issues/2424
=> Create a workflow to test signed pkg installer

.github/workflows/publish-release.yml
Automate UUID generation during release workflow
Automate the release workflow
https://github.com/ballerina-platform/ballerina-distribution/issues/2431
=> Automate UUID generation during release workflow

ballerina/build.gradle, examples/http-trace-logs/http_trace_logs.bal
Run tests on BBEs to reduce failures.
Currently BBEs are only built using `bal build` command. This will run `bal test` command on BBEs
https://github.com/ballerina-platform/ballerina-distribution/issues/2430
https://github.com/ballerina-platform/ballerina-standard-library/issues/2554
=> Run tests on BBEs

ballerina/build.gradle
> Add support to generate cache for modules with same name but different org name. (https://github.com/ballerina-platform/ballerina-lang/issues/33195)
=> Add support to generate cache for modules with same name but different org names

ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/ProjectTest.java, ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
Currently there are some issues regarding the directory paths with spaces where the `bal` command is not working properly. This test will the `bal` command in directories with spaces in different operating systems.
Increase the tests to reduce failures in installers
Added a new project test called `testDirectoryPath` in installer tests checking three different scenarios.
https://github.com/ballerina-platform/ballerina-distribution/issues/2504
=> Add test to check directory path with spaces

examples/index.json
We were using `ws://echo.websocket.org` for this example and now they have shut down that echo server.
=> Disable playground for WebSocket Client BBEs

examples/ordering/ordering.bal, examples/ordering/ordering.out
Having two `order by` clauses to sort two items does not show the functionality clearly
=> Update ordering BBE with a detailed output

examples/raw-templates/Ballerina.toml, examples/raw-templates/raw_templates.bal, examples/raw-templates/raw_templates.description, examples/raw-templates/raw_templates.out
This is just giving instructions for users to run the BBE. It  may be better to remove SQL dependency as H2 driver is no longer included in the distribution by default.
=> Update raw template bbe with instructions to run

gradle.properties
$subject because the term `version` within the comment breaks the release build scripts
=> Fix comment on automatic version bumping

installers/mac/build-ballerina-macos-x64.sh, installers/mac/darwin/scripts/postinstall
>Currently MacOS installation via installer takes a lot of time due executing permissions for all distribution versions.
This will fix that issue
=> Fix MacOS installation

examples/ftp-listener/ftp_listener.bal, examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.description, examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.description, examples/kafka-consumer-client/kafka_consumer_client.description, examples/kafka-consumer-group-service/kafka_consumer_group_service.description, examples/kafka-consumer-service/kafka_consumer_service.description, examples/kafka-producer-transactional/kafka_producer_transactional.description, examples/kafka-producer/kafka_producer.description
$subject
Related to https://github.com/ballerina-platform/ballerina-dev-website/issues/3154
=> Remove redundant `example` usage in kafka BBEs 

build.gradle, gradle.properties
> Add Graphql client generation tool to the Ballerina distribution
Resolves https://github.com/ballerina-platform/graphql-tools/issues/39
> Add Graphql client generation tool to the Ballerina distribution
> Add GraphQL client generation tool to build.gradle and gradle.properties
> Add Graphql client generation tool
> 
Ballerina Version: 2201.0.1
Operating System: Ubuntu 20.04
Java SDK: 11
=> Add Graphql client generation tool

gradle.properties
> Update GraphQL tool version
with following changes
- Removed documentation of generated records to avoid warning messages during project build
- Renamed utils template to avoid conflict with OpenAPI template in Ballerina distribution
> Update GraphQL tool version to latest
> Bump tool version to 0.1.0-20220510-134000-e55482f
> Update GraphQL tool version
- Unit tests 
> Done
> None
> 
Ballerina Version: 2201.1.0-rc1.4
Operating System: Ubuntu 20.04
Java SDK: 11
=> Update GraphQL tool version

devtools-integration-tests/src/test/resources/testng.xml
$subject as a temporary fix for the distribution build failures.  Created https://github.com/ballerina-platform/ballerina-distribution/issues/2783 to track the current test failures.
=> Disable service debug tests

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml
Currently with version change short version and long is the same. therefore the we need to add `-swan-lake` for creating pack.
Fix generating hashes for ballerina zip in daily build and release workflows.
https://github.com/ballerina-platform/ballerina-distribution/issues/2844
=> Fix generating hashes in master

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml
Currently with version change short version and long is the same. therefore the we need to add `-swan-lake` for creating pack.
Fix generating hashes for ballerina zip in daily build and release workflows.
https://github.com/ballerina-platform/ballerina-distribution/issues/2844
=> Fix generating hashes in 2201.1.x

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java, devtools-integration-tests/src/test/resources/testng.xml
Partially fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3027. 
With this PR, only one test failure (`org.ballerina.devtools.debug.ExpressionEvaluationTest`) is remaining to be fixed. 
Created https://github.com/ballerina-platform/ballerina-distribution/issues/3034 to track the progress.
=> Enable service and module breakpoints debugger tests

examples/graphql-documentation/graphql_documentation.bal, examples/graphql-returning-record-values/graphql_returning_record_values.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3065
=> Make the record types used in GraphQL examples closed

examples/arrays/arrays.bal
commented line which represents length of array as 3 is incorrect and hence updated with the correct length as 4
> This PR resolves bug in Array Examples at this [https://ballerina.io/learn/by-example/arrays/](https://ballerina.io/learn/by-example/arrays/). The length of the array in last 3rd line (commented) is incorrect.
> The correct length of the array is 4, and the typo is now corrected.
> visit ballerina-platform/ballerina-distribution/examples/arrays/arrays.bal , where the bug is located
>  [https://ballerina.io/learn/by-example/arrays/](https://ballerina.io/learn/by-example/arrays/)
>
> N/A as this is just a typo in documnetation.
>
- Unit …
=> Bug Fix for Typo in Array Examples

examples/foreach-statement/foreach_statement.out, examples/while-statement/while_statement.out
> This PR resolves error in Foreach example at https://ballerina.io/learn/by-example/foreach-statement/ and While example at https://ballerina.io/learn/by-example/while-statement/. The $ sign was missing in the output, due to this while clicking the copy to clipboard button the command was not copied. To fix this the $ sign was added
=> Fix typo error in output of Ballerina By Example

.github/workflows/publish-release-artifacts-1.2.x.yml, .github/workflows/publish-release-artifacts.yml
Currently docker build fails with `--squash` flag because of experimental features not being enabled in ubuntu. This will enable experimental features which will enable the `--squash` flag along with docker build as well.
Docker build with `--squash` flag will reduce the docker image size of ballerina from ~210MB to ~160MB.
=> Fix docker build in publishing release artifacts workflow

dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
With recent change done with https://github.com/ballerina-platform/ballerina-distribution/pull/3226 will throw exception in windows build since bala paths have more characters than the maximum. This will skip the API docs generation in windows build.
=> Skip API docs gen in windows

examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal, examples/rabbitmq-consumer/rabbitmq_consumer.bal, examples/rabbitmq-secure-connection/consumer.bal, examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
Update usages of the deprecated record type `Message` in RabbitMQ BBEs and use data binding instead. 
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/5657
=> Update Message record in RabbitMQ BBEs

examples/graphql-client/graphql_client.bal, examples/graphql-client/graphql_client.md, examples/graphql-client/graphql_client.out, examples/graphql-context/graphql_context.bal, examples/graphql-context/graphql_context.md, examples/graphql-directives/graphql_directives.bal, examples/graphql-directives/graphql_directives.md, examples/graphql-documentation/graphql_documentation.bal, examples/graphql-documentation/graphql_documentation.md, examples/graphql-hello-world/graphql_hello_world.md, examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md, examples/graphql-input-objects/graphql_input_objects.bal, examples/graphql-input-objects/graphql_input_objects.md, examples/graphql-input-types/graphql_input_types.md, examples/graphql-interceptors/graphql_interceptors.md, examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.bal, examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md, examples/graphql-interfaces/graphql_interfaces.bal, examples/graphql-interfaces/graphql_interfaces.md, examples/graphql-mutations/graphql_mutations.md, examples/graphql-returning-record-values/graphql_returning_record_values.bal, examples/graphql-returning-record-values/graphql_returning_record_values.md, examples/graphql-returning-service-objects/graphql_returning_service_objects.bal, examples/graphql-returning-service-objects/graphql_returning_service_objects.md, examples/graphql-subscriptions/graphql_subscriptions.md
To make all the BBEs consistent, the type definitions including record and service types are moved to the top of the bal file.
=> Move record and service type definitions to top in GraphQL BBEs

examples/index.json
Due to changes in the `fileReadCsv`, `fileReadCsvAsStream` APIs, full build pipeline is failing. Until the issue is solved this PR disable the BBE check.
disable the BBE for csv-datamapping until the issue in the io library is solved
=> Disable csv-datamappingBBE due to the full build pipeline failure

examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.md, examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md, examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md, examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md, examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md, examples/graphql-graphiql/graphql_graphiql.md, examples/graphql-interceptors/graphql_interceptors.md, examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md, examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md, examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md, examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md, examples/graphql-service-oauth2/graphql_service_oauth2.md, examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
GraphQL spec has been updated recently. Hence some of the links will not work properly. This PR will update those links.
=> Update GraphQL spec links in BBEs

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java, project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java, project-api-tests/src/test/resources/hierarchical-packages/PackageI/Dependencies.toml
> $Subject
> Fixes #2839
> Give test resource packages used in hierarchical package tests random names to avoid conflicts among parallel releases etc.
=> Replace hierarchical packages with random package names

examples/aggregation/aggregation.bal, examples/aggregation/aggregation.md, examples/aggregation/aggregation.metatags, examples/aggregation/aggregation.out
=> Add bbe for group by/collect

.github/workflows/publish-release.yml
The `update markdown` logic has been updated to now only update the markdown file for official releases, in the case of `pre-releases` the markdown will be empty.
=> Update logic to provide release note for official Releases

.github/workflows/publish-release-artifacts.yml
Publish the Ballerina Image to Github Container Registry and sign the Ballerina Image using `Notary Project's Notation Tool`.
There currently is no Official Github Action for `Notation` Tool, therefore I've referred to the prototype `Notation` Action as mentioned [here](https://github.com/duffney/setup-notation). The details for the official Github Action can be tracked via this [issue](https://github.com/notaryproject/.github/issues/30)
Fixes #4636 
**Note:** Secrets have been added in the workflow, the format of each `secret` is mentioned:
Azure Credentials for Resource login - `${{ secrets.AZURE_CREDENTIALS }}` - [setup credentials as follows](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-a-service …
=> Integrate `Notation` to sign Ballerina Images

examples/graphql-input-constraint-validation/graphql_input_constraint_validation.bal, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.client.out, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.graphql, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.metatags, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.server.out, examples/index.json
=> [2201.7.x] Add GraphQL Input Constraint Validation BBE

examples/graphql-input-constraint-validation/graphql_input_constraint_validation.bal, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.client.out, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.graphql, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.metatags, examples/graphql-input-constraint-validation/graphql_input_constraint_validation.server.out, examples/index.json
Fixes: [#4589](https://github.com/ballerina-platform/ballerina-standard-library/issues/4589)
=> Add GraphQL Input Constraint Validation BBE

examples/stop-handler/stop_handler.client.out, examples/stop-handler/stop_handler.md, examples/stop-handler/stop_handler.server.out
$title
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/7239
> Link(s) to product documentation that …
=> Improve `StopHandler` BBE

.trivyignore
There is a security vulnerability (CVE-2024-21742) in `apache-mime4j-core` 0.8.6 version and it is used as a dependency for `axiom-api` 1.4.0 version. Since there is no new version with a fix for this in `axiom-api` library, the
`CVE-2024-21742` vulnerability is skipped for the moment.
Once the `axiom-api` is updated with `apache-mime4j-core:0.8.10` version, it should be updated in the lang repo and remove this vulnerability from the `.trivyignore` file
=> Skip CVE-2024-21742 vulnerability for 2201.8.6 release

examples/index.json
$subject. Failing due to the URL in the BBE is giving 503 HTTP error code.
=> Temporary disable output verification for `sequence-diagrams` BBE

examples/index.json
Sending same PR #5273 to 8.x. 
Verification is failing due to url in the bbe is giving 503 http error code.
=> [2201.8.x] Temporary disable output verification for `sequence-diagrams` BBE

gradle.properties
$subject, please. This is to bump the persist tools version with the latest `persist-googlesheets` version and fix disabled test cases.
=> Bump persist tools version with latest googlesheets version

examples/conditional-send/conditional_send.bal, examples/conditional-send/conditional_send.md, examples/conditional-send/conditional_send.metatags, examples/conditional-send/conditional_send.out, examples/index.json
$subject
Part of ballerina-platform/ballerina-dev-website#8856
=> [2201.9.x] Add `conditional-send` bbe

examples/index.json
> Fix the build failure https://github.com/ballerina-platform/ballerina-distribution/actions/runs/9102412265/job/25021940100 which occurs due to log output mismatch.
```
Failed due to output did not match. Line 0: ballerina/avro:1.0.0 [central.ballerina.io ->/home/runner/.ballerina/repositories/central.ballerina.io/bala/ballerina/avro/1.0.0]   17% [>
ballerina/avro:1.0.0 [central.ballerina.io ->/home/runner/.ballerina/repositories/central.ballerina.io/bala/ballerina/avro/1.0.0]  100% [
Failed due to output did not match. Line 1: ballerina/avro:1.0.0 pulled from central successfully
```
=> Disable output verification of Avro BBE

examples/http-service-and-resource-paths/http_service_and_resource_paths.bal
> $Subject
Related to: https://github.com/ballerina-platform/ballerina-dev-website/issues/8734
=> Fix the explanation on dot resource path

examples/index.json
> This is to fix intermittent errors occurs when connecting to the external SOAP endpoint.
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6743
=> Fix intermittent errors in a BBE

examples/anydata-to-yaml-string/any_data_to_yaml_string.metatags, examples/anydata-to-yaml-string/anydata_to_yaml_string.bal, examples/anydata-to-yaml-string/anydata_to_yaml_string.md, examples/anydata-to-yaml-string/anydata_to_yaml_string.metatags, examples/anydata-to-yaml-string/anydata_to_yaml_string.out, examples/index.json, examples/xml-from-record-conversion/xml_from_record_conversion.bal, examples/yaml-to-anydata-with-projection/yaml_to_anydata_with_projection.bal, examples/yaml-to-anydata-with-projection/yaml_to_anydata_with_projection.md, examples/yaml-to-anydata-with-projection/yaml_to_anydata_with_projection.metatags, examples/yaml-to-anydata-with-projection/yaml_to_anydata_with_projection.out, examples/yaml-to-anydata/yaml_to_anydata.bal, examples/yaml-to-anydata/yaml_to_anydata.md, examples/yaml-to-anydata/yaml_to_anydata.metatags, examples/yaml-to-anydata/yaml_to_anydata.out, gradle.properties
$subject
This BBEs are related to the [data.yaml module](https://github.com/ballerina-platform/ballerina-library/issues/6089) implementation.
=> Add BBEs related to the data.yaml module

examples/index.json, examples/multiple-receive/multiple_receive.bal, examples/multiple-receive/multiple_receive.md, examples/multiple-receive/multiple_receive.metatags, examples/multiple-receive/multiple_receive.out
$subject
Part of ballerina-platform/ballerina-dev-website#8856
=> Add `multiple-receive` bbe

examples/alternate-receive/alternate_receive.bal, examples/alternate-receive/alternate_receive.md, examples/alternate-receive/alternate_receive.metatags, examples/alternate-receive/alternate_receive.out, examples/index.json
$subject
Part of ballerina-platform/ballerina-dev-website#8856
=> Add `alternate receive` bbe

examples/alternate-receive/alternate_receive.bal, examples/alternate-receive/alternate_receive.md, examples/alternate-receive/alternate_receive.metatags, examples/alternate-receive/alternate_receive.out, examples/index.json
Sending this https://github.com/ballerina-platform/ballerina-distribution/pull/5290 to 2201.9.x …
=> [2201.9.x] Add alternate receive bbe

examples/persist-create/persist_create.md, examples/persist-create/persist_generate.out, examples/persist-create/persist_init.out, examples/persist-delete/persist_delete.md, examples/persist-delete/persist_generate.out, examples/persist-delete/persist_init.out, examples/persist-filtering/persist_filtering.md, examples/persist-filtering/persist_generate.out, examples/persist-filtering/persist_init.out, examples/persist-get-all/persist_generate.out, examples/persist-get-all/persist_get_all.md, examples/persist-get-all/persist_init.out, examples/persist-get-by-key/persist_generate.out, examples/persist-get-by-key/persist_get_by_key.md, examples/persist-get-by-key/persist_init.out, examples/persist-relation-queries/persist_generate.out, examples/persist-relation-queries/persist_init.out, examples/persist-relation-queries/persist_relation_queries.md, examples/persist-select-fields/persist_generate.out, examples/persist-select-fields/persist_init.out, examples/persist-select-fields/persist_select_fields.md, examples/persist-update/persist_generate.out, examples/persist-update/persist_init.out, examples/persist-update/persist_update.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/8704 …
=> Update the examples and fix the line break issue

examples/index.json
=> Reorganize examples landing page columns

.github/workflows/daily-build-2201.10.x.yml, .github/workflows/daily-build-2201.3.x.yml, .github/workflows/daily-build-2201.4.x.yml, .github/workflows/daily-build-2201.5.x.yml, .github/workflows/daily-build-2201.6.x.yml, .github/workflows/daily-build-2201.7.x.yml, .github/workflows/daily-build-2201.8.x.yml, .github/workflows/daily-build-2201.9.x.yml, .github/workflows/daily-build-editor.yml, .github/workflows/daily-build.yml, .github/workflows/language_server_simulator_fhir.yml, .github/workflows/language_server_simulator_nballerina.yml, .github/workflows/main.yml, .github/workflows/publish-release-artifacts-1.2.x.yml, .github/workflows/publish-release-artifacts.yml
GitHub has deprecated the artifact action v1 and v2 which leads to build failures in release workflows.
https://github.com/ballerina-platform/ballerina-release/actions/runs/10826921877/job/30038931866
**Deprecation notice:**  https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions
=> Update the deprecated artifact action version in workflow files to v4

.github/workflows/daily-build-2201.10.x.yml, .github/workflows/daily-build-2201.3.x.yml, .github/workflows/daily-build-2201.4.x.yml, .github/workflows/daily-build-2201.5.x.yml, .github/workflows/daily-build-2201.6.x.yml, .github/workflows/daily-build-2201.7.x.yml, .github/workflows/daily-build-2201.8.x.yml, .github/workflows/daily-build-2201.9.x.yml, .github/workflows/daily-build.yml
GitHub has deprecated the download and upload artifact action v1 and v2 which leads to build failures in release workflows.
https://github.com/ballerina-platform/ballerina-release/actions/runs/10826921877/job/30038931866
**Deprecation notice:**  https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions
=> Update the download artifact action version to v4 in workflow files

examples/gauge-metrics/gauge_metrics.md, examples/index.json
* Fix https://github.com/ballerina-platform/ballerina-dev-website/issues/9302 …
=> [2201.10.x] Rearrange observability bbe menus and fix content

examples/boolean/boolean.md, examples/floating-point-numbers/floating_point_numbers.md, examples/integers/integers.md, examples/match-statement/match_statement.bal, examples/match-statement/match_statement.md, examples/open-records/open_records.md, examples/type-definitions/type_definitions.md, examples/xml-access/xml_access.md
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9430 - Invalid description in the open records BBE
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9429 - The match statement BBE doesn't follow the naming convention for the constant
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9321 - Remove statements that compare Ballerina syntaxes with other programming languages from BBEs
=> Fix several issues in BBEs

examples/index.json, examples/time-utc-and-civil/time_utc_and_civil.md, examples/time-utc/time_utc.md, examples/time-zone/time_zone.bal, examples/time-zone/time_zone.md, examples/time-zone/time_zone.metatags, examples/time-zone/time_zone.out
> Subject
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/9362
> **Note:** Even though we expose a `time:loadSystemZone()` API to get the system time zone, I have used the `time:TimeZone()` in this BBE. This is due a [compiler error we are getting when we have ballerina cache](https://github.com/ballerina-platform/ballerina-lang/issues/43420). Once that is fixed we can update this BBE as well.
=> Add time zone BBE

examples/csv-streams-to-record-arrays/csv_streams_to_record_array.bal, examples/csv-streams-to-record-arrays/csv_streams_to_record_array.md, examples/csv-streams-to-record-arrays/csv_streams_to_record_array.metatags, examples/csv-streams-to-record-arrays/csv_streams_to_record_array.out, examples/index.json
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9452
=> Ad bbe for parsing csv byte streams

examples/backtick-templates/backtick_templates.bal, examples/backtick-templates/backtick_templates.out
Closes #https://github.com/ballerina-platform/ballerina-dev-website/issues/9061 …
=> Add string template splitting section 

examples/logging/logging.bal, examples/logging/logging.out
> Fix: https://github.com/ballerina-platform/ballerina-dev-website/issues/9301
> Update the BBEs for https://discord.com/channels/957996897782616114/1236901247781572708/1236920131582431254
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> …
=> Update Ballerina by example for Logging Ballerina records

examples/docker-hello-world/docker_hello_world.md, examples/kubernetes-hello-world/kubernetes_hello_world.md
- Document the required command for c2c build in MacOS
- https://github.com/ballerina-platform/ballerina-dev-website/issues/9431
=> Document the required command for c2c build in MacOS

examples/unions/unions.bal, examples/unions/unions.out
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9300
=> Improve the unions BBE for type narrowing

examples/check-expression/check_expression.bal, examples/check-expression/check_expression.md, examples/check-expression/check_expression.out, examples/error-reporting/error_reporting.bal, examples/error-reporting/error_reporting.md, examples/error-reporting/error_reporting.out, examples/error-subtyping/error_subtyping.bal, examples/error-subtyping/error_subtyping.md, examples/error-subtyping/error_subtyping.out, examples/error-type-intersection/error_type_intersection.bal, examples/error-type-intersection/error_type_intersection.md, examples/error-type-intersection/error_type_intersection.out, examples/index.json, examples/panics/panics.md, examples/trap-expression/trap_expression.bal, examples/trap-expression/trap_expression.md, examples/trap-expression/trap_expression.metatags, examples/trap-expression/trap_expression.out
$subject
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/9293
=> Improve Error Handling related BBEs

.github/workflows/daily-build.yml, ballerina/build.gradle, gradle.properties, installers/linux-deb/build-ballerina-linux-deb-x64.sh
=> Generate linux-arm zip and installer

examples/regexp-type/regexp_type.bal, examples/regexp-type/regexp_type.md, examples/regexp-type/regexp_type.out
$title.
Closes https://github.com/ballerina-platform/ballerina-dev-website/issues/9316
=> Update the RegExp type BBE

examples/index.json, examples/regexp-find-operations/regexp_find_operations.bal, examples/regexp-find-operations/regexp_find_operations.md, examples/regexp-find-operations/regexp_find_operations.metatags, examples/regexp-find-operations/regexp_find_operations.out
Part of https://github.com/ballerina-platform/ballerina-dev-website/issues/9318
=> Add BBE for `Regexp` find operations

examples/index.json, examples/regexp-find-operations/regexp_find_operations.bal, examples/regexp-find-operations/regexp_find_operations.md, examples/regexp-find-operations/regexp_find_operations.metatags, examples/regexp-find-operations/regexp_find_operations.out
Sending the same PR to 10.x https://github.com/ballerina-platform/ballerina-distribution/pull/5677
=> [2201.10.x] Add BBE for Regexp find operations

examples/raw-templates/Ballerina.toml, examples/raw-templates/raw_templates.bal, examples/raw-templates/raw_templates.md, examples/raw-templates/raw_templates.out
$subject
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/9323
=> Update raw-template BBE to remove external dependency

.github/workflows/publish_release_bi.yml
=> Upddate Kola release workflow to run on schedule

examples/default-values-for-function-parameters/default_values_for_function_parameters.md, examples/functions/functions.md, examples/index.json, examples/provide-function-arguments-by-name/provide_function_arguments_by_name.md, examples/rest-arguments/rest_arguments.bal, examples/rest-arguments/rest_arguments.md, examples/rest-arguments/rest_arguments.metatags, examples/rest-arguments/rest_arguments.out
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9311
=> Add a BBE for rest arguments

examples/distinct-object-types/distinct_object_types.bal, examples/distinct-object-types/distinct_object_types.md, examples/distinct-object-types/distinct_object_types.out
$subject
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/9304 …
=> Update distinct object examples

examples/soap-client-security-inbound-security-config/soap_client_security_inbound_security_config.bal, examples/soap-client-security-outbound-security-config/soap_client_security_outbound_security_config.bal
> This is to fix build failures in the ballerina distribution daily builds
https://github.com/ballerina-platform/ballerina-distribution/actions/runs/11879224039/job/33100869216#step:4:3959
=> Fix build failures in SOAP examples

examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.md, examples/jms-consumer-consume-message/jms_consumer_consume_message.md, examples/jms-service-consume-message/jms_service_consume_message.md
=> Fix broken links in the JMS consumer BBEs

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/publish_release_bi.yml
$subject
Moved the installer generation scripts to the root folder (`D:\a`).
Fixes #5883
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers …
=> Fix windows installer build

.github/workflows/publish-release-artifacts.yml, .github/workflows/publish-release.yml
- Remove load parameter from Docker action
=> Add multi-arch support for base image

.github/workflows/publish-release-artifacts.yml
$subject
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/5751 …
=> Include publishing linux-arm installer

.github/workflows/publish_release_bi.yml
The Kola releases follow a rolling update for the testing period. Therefore, this release shouldn't be affected by low vulnerabilities.
=> Only consider high and critical Trivy vulnerabilities

ballerina/build.gradle
The responsibility for deciding which JAR files belong in the bre-lib versus the ls-libs is now delegated to the dev-tools. This removes the necessity to update the distribution configurations every time there is an update to the ls extension
=> Update the artifacts copying related to LS extensions
