examples/request-with-multiparts/request_with_multiparts.bal

Fix request with multipart BBE

---

ballerina/pom.xml
ballerina/src/assembly/dist-linux.xml
ballerina/src/assembly/dist-macos.xml
ballerina/src/assembly/dist-windows.xml
ballerina/src/assembly/dist-zip.xml
pom.xml
resources/tools/distributions/ballerina-version

> Migrate 1.2.x to ballerina update tool 1.3.1

Migrate 1.2.x to ballerina update tool 1.3.1

---

gradle.properties

Change data mapper compiler version

Change data mapper compiler extension version

---

examples/csv-io/csv_io.bal
examples/strings-io/strings_io.bal

$subject
https://github.com/ballerina-platform/module-ballerina-io/pull/102
- macOS
- SLA3
- Java11

Fix the I/O streaming writing APIs in BBEs

---

examples/websub-webhook-sample/github_webhook_service.bal
examples/websub-webhook-sample/github_webhook_service.out

Fix line lengths in BBE to 80-character limit

---

examples/error-match-statement/error_match_statement.bal
examples/error-match-statement/tests/error_match_statement_test.bal
examples/maps/maps.bal
examples/raw-template/raw_template.bal
examples/tuple-match-statement/tests/tuple_match_statement_test.bal
examples/tuple-match-statement/tuple_match_statement.bal

$subject
- Unit tests 
> Yes
https://github.com/ballerina-platform/module-ballerina-io/pull/100
- macOS
- Java 11
- SLA 3

Replace the I/O sprintf API with string templates

---

examples/dynamic-listener/dynamic_listener.bal

> Fix compilation error
> Fix compilation error
> Fixed compilation error due to invalid error format
> N/A
> N/A
> N/A
> N/A
> N/A
>N/A
- Unit tests 
> Code coverage information
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and platforms on which migration has been tested
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix …

Fix compilation error

---

examples/workers/tests/worker_test.bal

Fix unassigned error issue in workers bbe.

Fix unassigned error issue in workers bbe

---

examples/query-expression-to-table/query_expression_to_table.bal

Set id type explicitly as int

---

ballerina/src/assembly/dist-linux.xml
pom.xml

Release 1.2.14 updates

---

examples/strings/strings.bal
examples/strings/strings.out
stdlib-integration-tests/grpc/modules/grpc_bidirectional_streaming/tests/grpc_bidirectional_streaming_test.bal
stdlib-integration-tests/grpc/modules/grpc_client_streaming/tests/grpc_client_streaming_test.bal
stdlib-integration-tests/grpc/modules/grpc_secured_unary/tests/grpc_secured_unary_test.bal
stdlib-integration-tests/grpc/modules/grpc_server_streaming/tests/grpc_server_streaming_test.bal
stdlib-integration-tests/grpc/modules/grpc_service_with_http_proxy_gateway/tests/grpc_chat_client.bal
stdlib-integration-tests/grpc/modules/grpc_unary_blocking/tests/grpc_unary_blocking_test.bal
stdlib-integration-tests/grpc/modules/grpc_unary_non_blocking/tests/grpc_unary_non_blocking_test.bal

$subject
For
- strings BBE
- gRPC integration tests

Replace I/O Sprintf with string templates

---

examples/arrays/arrays.bal
examples/arrays/arrays.out

This is to incorporate changes done in 
https://github.com/ballerina-platform/ballerina-lang/issues/28514
Fixes #1441
> Link to …

Fix arrays.bal for slalpha3

---

examples/json-to-xml-conversion/json_to_xml_conversion.bal
examples/json-to-xml-conversion/json_to_xml_conversion.description
examples/json-to-xml-conversion/json_to_xml_conversion.metatags

Fix json_to_xml_conversion BBE

---

gradle.properties

> Updated Observability Extension versions

Updated Observability Extension versions

---

gradle.properties

Release dev tools repo

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTest.java
devtools-integration-tests/src/test/resources/central/projectD/main.bal

> Removed asserting run output since cannot access printing logs.
Fixes: https://github.com/ballerina-platform/ballerina-distribution/issues/1440
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Fix 'testBuildAndRunPackageD' test

---

examples/error-match-statement/error_match_statement.bal
examples/tuple-match-statement/tuple_match_statement.bal

Fix line length in error match and tuple match BBEs

---

examples/counter-metrics/counter_metrics.bal
examples/gauge-metrics/gauge_metrics.bal
examples/tracing/tracing.bal

> update observability BBEs for alpha3

Update observability BBEs

---

build.gradle

Fail Release on Snapshot Dependencies

---

examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.bal

Fix output verification error in GraphQL BBE

---

examples/http-client-endpoint/http_client_endpoint.bal
examples/index.json

Update websub-bbe category correctly

---

README.md

Update readme with correct location to the ballerina distribution being built

Update location of built distribution directory in README

---

examples/index.json

Remove the Docker BBEs from the index.json file. …

Remove the Docker BBEs from the "index.json" File

---

examples/tcp-listener/tcp_listener.description
examples/udp-listener/udp_listener.description

Fix the TCP and UDP module links in BBEs. …

Fix the TCP and UDP Module Links in BBEs

---

examples/tcp-client/tcp_client.description
examples/tcp-listener/tcp_listener.description
examples/tcp-transport-security/tcp_transport_security.description
examples/udp-client/udp_client.description
examples/udp-connect-client/udp_connect_client.description
examples/udp-listener/udp_listener.description

Fix module link in udp, tcp BBEs

---

build.gradle
examples/java-arrays/java_arrays.bal
examples/java-arrays/java_arrays.description

$Subject
Related issues:
[#1171](https://github.com/ballerina-platform/ballerina-standard-library/issues/1171)

Change java.arrays org and module name

---

gradle.properties

Upgrade java.array version

---

examples/response-with-multiparts/response_with_multiparts.bal

Fix the comments of the multipart response BBE. …

Fix the Comments of the Multipart Response BBE

---

examples/time/time.out

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1173
https://github.com/ballerina-platform/ballerina-distribution/pull/1384
- macOS
- Java 11
- SLAlpha 3

Correct the output verification of the time BBE

---

ballerina/build.gradle
build.gradle
devtools-integration-tests/build.gradle
dist-repo-builder/build.gradle
gradle.properties

Standardize the dependency version names

---

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
examples/kafka-consumer-client/kafka_consumer_client.bal
examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
examples/kafka-consumer-service/kafka_consumer_service.bal
examples/kafka-producer-transactional/kafka_producer_transactional.bal
examples/kafka-producer/kafka_producer.bal
examples/nats-basic-client/publisher.bal
examples/nats-basic-client/subscriber.bal
examples/nats-streaming-client/publisher.bal
examples/nats-streaming-client/subscriber.bal
examples/nats-streaming-durable-subscriptions/publisher.bal
examples/nats-streaming-durable-subscriptions/subscriber.bal
examples/nats-streaming-queue-group/publisher.bal
examples/nats-streaming-queue-group/queue-group.bal
examples/nats-streaming-start-position/publisher.bal
examples/nats-streaming-start-position/subscriber.bal
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
examples/rabbitmq-consumer/rabbitmq_consumer.bal
examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

Update messaging examples with updates in swan lake-alpha4

---

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.description
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.description
examples/kafka-consumer-client/kafka_consumer_client.description
examples/kafka-consumer-group-service/kafka_consumer_group_service.description
examples/kafka-consumer-service/kafka_consumer_service.description
examples/kafka-producer-transactional/kafka_producer_transactional.description
examples/kafka-producer/kafka_producer.description
examples/nats-basic-client/nats_basic_client.description
examples/nats-streaming-client/nats_streaming_client.description
examples/nats-streaming-durable-subscriptions/nats_streaming_durable_subscriptions.description
examples/nats-streaming-queue-group/nats_streaming_queue_group.description
examples/nats-streaming-start-position/nats_streaming_start_position.description
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.description
examples/rabbitmq-consumer/rabbitmq_consumer.description
examples/rabbitmq-producer/rabbitmq_producer.description
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.description
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.description

Fix messaging module links

---

gradle.properties

Bump to new snapshot

---

ballerina-test/src/test/resources/testing-line-length.xml
examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
examples/kafka-consumer-service/kafka_consumer_service.bal
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
examples/rabbitmq-consumer/rabbitmq_consumer.bal
examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

Fix line length in messaging bbes

---

examples/testerina-mocking-objects/testerina_mocking_objects_main.bal
examples/testerina-mocking-objects/testerina_mocking_objects_test.bal

Fix testerina-mocking-objects BBE

---

ballerina-test/src/test/resources/openapi/expected/filtered_tags.bal
examples/ballerina-to-openapi/ballerina_to_openapi.bal

> Fix  [[Bal -> OpenAPI] Examples are not up to date with latest log changes ](https://github.com/ballerina-platform/ballerina-openapi/issues/147)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Up to date OpenAPI BBE with latest log changes

---

ballerina-test/src/test/resources/testng.xml
gradle.properties

Update transaction version

---

examples/raw-template/raw_template.bal

Fix raw templates example

---

examples/testerina-assertions/testerina_assertions.out
examples/testerina-before-and-after-suite/testerina_before_and_after_suite.out
examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.out
examples/testerina-mocking-functions/testerina_mocking_functions_test.out
examples/testerina-mocking-objects/testerina_mocking_objects_main.bal
examples/testerina-mocking-objects/testerina_mocking_objects_test.bal
examples/testerina-mocking-objects/testerina_mocking_objects_test.out

Update BBE tests for Alpha4

---

examples/check/check.description

> $title
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/2025 …

Align the description of `check` BBE with the spec

---

examples/query-action/query_action.bal
examples/query-expression-to-stream/query_expression_to_stream.bal
examples/query-expression/query_expression.bal

> Update looping stream to use stream function
> Remove unused var with inferred error type …

Update query bbes

---

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
examples/kafka-consumer-client/kafka_consumer_client.bal
examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
examples/kafka-consumer-service/kafka_consumer_service.bal
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal

Fix compilation errors in messaging examples

---

ballerina/build.gradle
examples/local-transactions-with-handlers/local_transactions_with_handlers.bal
examples/local-transactions-with-handlers/tests/local_transactions_with_handlers.bal
examples/xa-transactions/xa_transactions.bal

Fix transaction related BBEs

---

ballerina/build.gradle
examples/log-api/tests/log_api_test.bal

Enable log-api BBE tests

---

ballerina/build.gradle

Enable basic-documentation BBE in build

---

ballerina/build.gradle

Enable raw template BBE build

---

ballerina/build.gradle

Enable  `function-pointers` and `anonymous-functions` BBE verifications

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

- Archive daily builds
- Include release publish workflow

Include release publish workflow and improve daily builds

---

.github/workflows/publish-release.yml

Remove extra bracket

---

ballerina/build.gradle
examples/any-type/any_type.bal
examples/any-type/any_type.out
examples/any-type/tests/any_type_test.bal

Conflict resolved version of PR #1503

---

ballerina/build.gradle
examples/any-type/any_type.bal
examples/any-type/any_type.out
examples/any-type/tests/any_type_test.bal

Fix any-type bbe intermittent fail

---

ballerina/build.gradle

Conflict resolved version of PR #1501

---

ballerina/build.gradle

Enable few BBE tests

---

ballerina/build.gradle
examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal
stdlib-integration-tests/index.json
stdlib-integration-tests/websocket/tests/web_socket_test.bal

Re-enable websocket tests

---

examples/configurable/Config.toml
examples/configurable/configurable.bal
examples/configurable/configurable.description
examples/configurable/configurable.out

$subject
Improve the configurable BBE with latest changes
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
jdk 11.0.9 , ubuntu 20.04

Improve configurable BBE

---

examples/jdbc-complex-type-queries/jdbc_complex_type_queries.out
examples/mysql-complex-type-queries/mysql_complex_type_queries.out

> $Subject
> Related PRs
> https://github.com/ballerina-platform/module-ballerina-sql/pull/167
> https://github.com/ballerina-platform/module-ballerina-sql/pull/161

Fix output in BBE for java.jdbc and mysql

---

ballerina/build.gradle

Enable rest of the flow control bbes

---

ballerina/build.gradle

$subject
Remove repetitive JARs from the XSLT `Ballerina.toml`
https://github.com/ballerina-platform/module-ballerina-xslt/pull/80
- macOS
- SLAlpha 4
- Java 11

Enable the XSLT BBE build and output verification

---

examples/xa-transactions/xa_transactions.bal

Update XA Transactions BBE

---

examples/http-client-with-self-signed-jwt-auth/http_client_with_self_signed_jwt_auth.bal
examples/jwt-issue-validate/jwt_issue_validate.bal
examples/jwt-issue-validate/tests/jwt_issue_validate_test.bal

Update JWT claims in security BBEs

---

ballerina/build.gradle
examples/range-expressions/range_expressions.bal

Enable and update range-expression bbe

---

examples/file/file.out

Update the file BBE output

---

examples/the-main-function/tests/the_main_function_test.bal
examples/the-main-function/the_main_function.bal
examples/the-main-function/the_main_function.description
examples/the-main-function/the_main_function.out

Fix "The Main Function" example

Fix "The Main Function" example

---

.github/workflows/publish-release.yml

Fix distribution name

---

.github/workflows/publish-release.yml

Include build task

---

.github/workflows/publish-release.yml

Update jdk version

---

.github/workflows/publish-release.yml
build.gradle

Fix build task dependency

---

.github/workflows/publish-release.yml
build.gradle

Fix release version passing

---

.github/workflows/publish-release.yml

> Skip tests for relesae builds

Skip tests for relesae builds

---

build.gradle

Fix build task issue

---

.github/workflows/publish-release.yml

Fix short version reference

---

.github/workflows/publish-release.yml

Fix artifact naming

---

.github/workflows/publish-release.yml

Remove echo short version

---

.github/workflows/publish-release.yml

Fix publish release issues

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java

> Update open api version in tests

Update open api version in tests

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update ballerina lang version to `2.0.0-alpha7-20210403-234900-bdd55df1`

[Automated] Update lang version to  bdd55df1

---

gradle.properties

Update release versions

---

examples/udp-listener/udp_listener.bal

> $title
> https://github.com/ballerina-platform/ballerina-dev-website/issues/2012

Remove Caller from the remote function in udp listener BBE

---

examples/java-arrays/java_arrays.description

Fix broken link in the Java Arrays BBE. …

Fix Broken Link in the Java Arrays BBE

---

examples/udp-listener/udp_listener.bal

Fix BBE length in udp_listener.bal

---

examples/configurable/configurable.description

Update the Configurable BBE for SLAlpha4. …

Update the Configurable BBE for SLAlpha4

---

examples/configurable/configurable.description

Update the description of the Configurable BBE. …

Update the Description of the Configurable BBE

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java

Update OpenAPI tests with OpenAPI version

---

ballerina/build.gradle

Fix bal commands to test standard libs

---

ballerina/build.gradle

> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/29679 …

Copy completion script to the pack

---

examples/log-api/log_api.bal

> $Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1189

Update log BBE configs to include ballerina org name

---

build.gradle

Clean up dependency repositories

---

.github/workflows/daily-build.yml
.github/workflows/main.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTestUtils.java

> Fix loading central token from secrets

Fix loading central token from secrets

---

ballerina/build.gradle
build.gradle
gradle.properties

> Remove observability extensions

Remove observability extensions

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java

This PR will enable `ServiceDebugTest`
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1421

Enable ServiceDebugTest

---

stdlib-integration-tests/auth/tests/Config.toml
stdlib-integration-tests/auth/tests/auth_test.bal

These tests were failed in https://github.com/ballerina-platform/ballerina-distribution/pull/1606 which has the update of https://github.com/ballerina-platform/ballerina-lang/pull/29924.
This PR fixes the tests for latest requirements.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1608

Fix auth integration tests to support latest requirements

---

gradle.properties

Bump openAPI timestamp version

---

ballerina-test/src/test/resources/testng.xml

Enable OpenAPI build tests

---

ballerina/build.gradle
examples/isolated-objects/isolated_objects.bal
examples/isolated-variables/isolated_variables.bal

With the changes introduced in https://github.com/ballerina-platform/ballerina-lang/pull/28441 we no longer need some of the clone calls in the isolated variables BBE.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1607.

Fix the isolated variables and isolated objects BBEs

---

examples/tcp-transport-security/tcp_transport_security_listener.bal

Fix port numbers in TCP listener

---

.github/workflows/daily-build.yml
.github/workflows/main.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTestUtils.java

Fix central token issue

---

examples/http-client-with-oauth2-client-credentials-grant-type/http_client_with_oauth2_client_credentials_grant_type.bal
examples/http-client-with-oauth2-password-grant-type/http_client_with_oauth2_password_grant_type.bal
examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.bal
examples/http-service-with-basic-auth-file-user-store/Config.toml
examples/http-service-with-basic-auth-file-user-store/http_service_with_basic_auth_file_user_store.out
examples/http-service-with-basic-auth-ldap-user-store/http_service_with_basic_auth_ldap_user_store.bal
examples/http-service-with-oauth2/http_service_with_oauth2.bal

Improve Access Control BBEs for Swan Lake Alpha5

---

examples/distributed-transactions/distributed_transactions.description

Fix transaction doc link

---

gradle.properties

Add installer version

---

gradle.properties

Release dev tools

---

gradle.properties

Bump grpc version

---

examples/websub-webhook-sample/websub_webhook_sample.bal

Remove optional configuration from WebSub BBE

---

gradle.properties

Update version display text

---

examples/index.json
examples/regex/regex.bal
examples/regex/regex.description
examples/regex/regex.metatags
examples/regex/regex.out

$Subject
Related issue: [#1289](https://github.com/ballerina-platform/ballerina-standard-library/issues/1289)

Add regex BBE

---

examples/xa-transactions/xa_transactions.description

Fix bbe doc link

---

.github/workflows/daily-build.yml

> Include docker hub push for daily builds

Include docker hub push for daily builds

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java

Update OpenAPI version in OpenAPI tests

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java

Fix issue with OpenAPI tests

---

gradle.properties

Update installer version

---

ballerina-test/src/test/resources/openapi/expected/filtered_tags.bal

Fix OpenAPI test issue

---

ballerina/build.gradle

> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30124 …

Copy zsh scripts

---

gradle.properties

Change to beta1 version

---

gradle.properties

Bump dev tools

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
build.gradle
gradle.properties

Update the OpenAPI version and Group ID

---

gradle.properties

Update ballerina command version

---

ballerina/build.gradle
gradle.properties
stdlib-integration-tests/index.json

$Subject
Related issue: [#1637](https://github.com/ballerina-platform/ballerina-distribution/issues/1637)

Enable task BBE and integration test

---

examples/the-main-function/tests/the_main_function_test.bal
examples/the-main-function/the_main_function.bal
examples/the-main-function/the_main_function.out

>  Fix failure in the-main-function example

Fix failure in the-main-function example

---

ballerina/build.gradle
examples/access-mutate-java-fields/access_mutate_java_fields.bal
examples/log-api/tests/log_api_test.bal
examples/streams/streams.bal
examples/the-main-function/tests/the_main_function_test.bal
examples/the-main-function/the_main_function.bal
examples/the-main-function/the_main_function.out
gradle.properties
stdlib-integration-tests/index.json

Beta1 BBE migration

---

examples/http-client-with-basic-auth/http_client_with_basic_auth.bal
examples/http-client-with-bearer-token-auth/http_client_with_bearer_token_auth.bal
examples/http-client-with-oauth2-client-credentials-grant-type/http_client_with_oauth2_client_credentials_grant_type.bal
examples/http-client-with-oauth2-password-grant-type/http_client_with_oauth2_password_grant_type.bal
examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.bal
examples/http-client-with-self-signed-jwt-auth/http_client_with_self_signed_jwt_auth.bal
examples/http-service-with-basic-auth-file-user-store/Config.toml
examples/http-service-with-basic-auth-file-user-store/http_service_with_basic_auth_file_user_store.bal
examples/http-service-with-basic-auth-ldap-user-store/http_service_with_basic_auth_ldap_user_store.bal
examples/http-service-with-jwt-auth/http_service_with_jwt_auth.bal
examples/http-service-with-oauth2/http_service_with_oauth2.bal

This PR updates the access control BBEs in order to maintain the cross compatibility with servers and clients.

Update access control BBEs

---

gradle.properties

[Gradle Release Plugin] - new version commit:  'vswan-lake-beta2-rc1'.

---

.github/workflows/daily-build.yml

Include latest nightly tag

---

gradle.properties

Bump update tool version

---

.github/workflows/daily-build.yml

Trigger connector version bump after daily build

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java
ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java
gradle.properties

 Change name of the file for OpenAPI tests generated file 

---

.github/workflows/daily-build.yml

Fix ballerina version variable not resolving

---

new-examples/converting-from-json-to-user-defined-type/converting_from_json_to_user_defined_type.bal
new-examples/converting-from-json-to-user-defined-type/converting_from_json_to_user_defined_type.description
new-examples/converting-from-json-to-user-defined-type/converting_from_json_to_user_defined_type.metatags
new-examples/converting-from-json-to-user-defined-type/converting_from_json_to_user_defined_type.out
new-examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.bal
new-examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.description
new-examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.metatags
new-examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.out
new-examples/converting-to-user-defined-type/converting_to_user_defined_type.bal
new-examples/converting-to-user-defined-type/converting_to_user_defined_type.description
new-examples/converting-to-user-defined-type/converting_to_user_defined_type.metatags
new-examples/converting-to-user-defined-type/converting_to_user_defined_type.out
new-examples/match-statement-with-maps/match_statement_with_maps.bal
new-examples/match-statement-with-maps/match_statement_with_maps.description
new-examples/match-statement-with-maps/match_statement_with_maps.metatags
new-examples/match-statement-with-maps/match_statement_with_maps.out
new-examples/resource-method-typing/resource_method_typing.bal
new-examples/resource-method-typing/resource_method_typing.client.out
new-examples/resource-method-typing/resource_method_typing.description
new-examples/resource-method-typing/resource_method_typing.metatags
new-examples/resource-method-typing/resource_method_typing.server.out

Add several new lang data BBEs

---

new-examples/annotations/annotations.bal
new-examples/annotations/annotations.description
new-examples/annotations/annotations.metatags
new-examples/annotations/annotations.out
new-examples/asynchronous-function-calls/asynchronous_function_calls.bal
new-examples/asynchronous-function-calls/asynchronous_function_calls.description
new-examples/asynchronous-function-calls/asynchronous_function_calls.metatags
new-examples/asynchronous-function-calls/asynchronous_function_calls.out
new-examples/documentation/documentation.bal
new-examples/documentation/documentation.description
new-examples/documentation/documentation.metatags
new-examples/documentation/documentation.out
new-examples/function-values/function_values.bal
new-examples/function-values/function_values.description
new-examples/function-values/function_values.metatags
new-examples/function-values/function_values.out
new-examples/type-inference/type_inference.bal
new-examples/type-inference/type_inference.description
new-examples/type-inference/type_inference.metatags
new-examples/type-inference/type_inference.out

Added following BBEs
- Type inference
- Function values
- Asynchronous function calls
- Annotations
- Documentation

Add new lang BBEs

---

gradle.properties

Bump dev tools to snapshot

---

gradle.properties

Move to dev tools stable version

---

ballerina-test/src/test/resources/openapi/petstore.bal
gradle.properties

Fix syntax issue in OpenAPI tests

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync after Release 1.2.14

---

ballerina-test/pom.xml
ballerina/pom.xml
ballerina/src/assembly/dist-linux.xml
ballerina/src/assembly/dist-macos.xml
ballerina/src/assembly/dist-windows.xml
ballerina/src/assembly/dist-zip.xml
pom.xml
resources/tools/distributions/ballerina-version

Sync and bump ballerina lang/ballerinax versions to 1.2.15

---

examples/bytes-io/bytes_io.bal
examples/csv-io/csv_io.bal
examples/json-io/json_io.bal
examples/strings-io/strings_io.bal
examples/time/time.bal
examples/xml-io/xml_io.bal

Standardise the I/O and time BBEs

---

examples/receive-email-using-client/receive_email_using_client.bal
examples/receive-email-using-listener/receive_email_using_listener.bal
examples/send-email/send_email.bal
examples/udp-client/udp_client.bal
examples/udp-connect-client/udp_connect_client.bal
examples/udp-listener/udp_listener.bal

Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1355

Update BBEs of Email and UDP modules

---

examples/crypto/crypto.bal
examples/http-client-with-basic-auth/http_client_with_basic_auth.bal
examples/http-client-with-bearer-token-auth/http_client_with_bearer_token_auth.bal
examples/http-client-with-oauth2-client-credentials-grant-type/http_client_with_oauth2_client_credentials_grant_type.bal
examples/http-client-with-oauth2-password-grant-type/http_client_with_oauth2_password_grant_type.bal
examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.bal
examples/http-client-with-self-signed-jwt-auth/http_client_with_self_signed_jwt_auth.bal
examples/jwt-issue-validate/jwt_issue_validate.bal
examples/jwt-issue-validate/jwt_issue_validate.description
examples/jwt-issue-validate/jwt_mock_server.bal
examples/jwt-issue-validate/tests/jwt_issue_validate_test.bal
examples/url-encode-decode/url_encode_decode.description

Improve access-control BBEs and security BBEs by removing anti-patterns.

Improve access-control BBEs and security BBEs

---

ballerina/build.gradle
examples/absolute-path-and-path/absolute_path_and_path.client.out
examples/http-default-resource/http_default_resource.bal
examples/http-default-resource/http_default_resource.client.out
examples/http-default-resource/http_default_resource.description
examples/http-default-resource/http_default_resource.metatags
examples/http-default-resource/http_default_resource.server.out
examples/http-default-resource/tests/http_default_resource_test.bal
examples/http-path-matrix-param/http_path_matrix_param.bal
examples/http-path-matrix-param/http_path_matrix_param.client.out
examples/http-path-matrix-param/http_path_matrix_param.description
examples/http-path-matrix-param/http_path_matrix_param.metatags
examples/http-path-matrix-param/http_path_matrix_param.server.out
examples/http-path-matrix-param/tests/http_path_matrix_param_test.bal
examples/http-query-parameter/http_query_parameter.bal
examples/http-query-parameter/http_query_parameter.client.out
examples/http-query-parameter/http_query_parameter.description
examples/http-query-parameter/http_query_parameter.metatags
examples/http-query-parameter/http_query_parameter.server.out
examples/http-query-parameter/tests/http_query_parameter_test.bal
examples/http-resource-returns/http_resource_returns.bal
examples/http-resource-returns/http_resource_returns.client.out
examples/http-resource-returns/http_resource_returns.description
examples/http-resource-returns/http_resource_returns.metatags
examples/http-resource-returns/http_resource_returns.server.out
examples/http-resource-returns/tests/http_resource_returns_test.bal
examples/index.json
examples/query-path-matrix-param/query_path_matrix_param.client.out
examples/query-path-matrix-param/query_path_matrix_param.description
examples/query-path-matrix-param/query_path_matrix_param.metatags

> Add http-default-resource BBE
> Add http-query-param BBE
> Add resource return type BBE
> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1140

Introduce new HTTP BBEs

---

gradle.properties

Reverts ballerina-platform/ballerina-distribution#1701

Revert "[AUTO MERGE] Update Dependencies (Ballerina Lang : 2.0.0-beta.1-20210517-074800-e91ff627)"

---

new-examples/xml-navigation/xml_navigation.bal
new-examples/xml-navigation/xml_navigation.description
new-examples/xml-navigation/xml_navigation.metatags
new-examples/xml-navigation/xml_navigation.out
new-examples/xml-operations/xml_operations.bal
new-examples/xml-operations/xml_operations.description
new-examples/xml-operations/xml_operations.metatags
new-examples/xml-operations/xml_operations.out
new-examples/xml-subtyping/xml_subtyping.bal
new-examples/xml-subtyping/xml_subtyping.description
new-examples/xml-subtyping/xml_subtyping.metatags
new-examples/xml-subtyping/xml_subtyping.out
new-examples/xml-templates/xml_templates.bal
new-examples/xml-templates/xml_templates.description
new-examples/xml-templates/xml_templates.metatags
new-examples/xml-templates/xml_templates.out

Add few XML BBEs

---

devtools-integration-tests/src/test/resources/debug/project-based-tests/service-tests/tests/hello_service_test.bal
devtools-integration-tests/src/test/resources/debug/single-file-tests/hello_service.bal

> This PR will fix service debug test failures in the distribution master.

Fix service debug test failures

---

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.bal
examples/http-client-data-binding/http_client_data_binding.bal
examples/http-cookies/http_client.bal
examples/http-failover/http_failover.bal
examples/http-redirects/http_redirects.bal
examples/http-retry/http_retry.bal
examples/http-streaming/http_streaming.bal
examples/http-timeout/http_timeout.bal
examples/passthrough/passthrough.bal
examples/request-with-multiparts/request_with_multiparts.bal

Fix BBE test failures

---

.github/workflows/publish-release.yml

Divide build and release commands

---

examples/https-client/https_client.description
examples/https-mutual-ssl/https_mutual_ssl.description

Update description of HTTP SSL BBEs

---

ballerina/build.gradle
gradle.properties

$title
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1387

Enable the gRPC BBE build

---

examples/http-client-with-basic-auth/http_client_with_basic_auth.bal
examples/http-client-with-basic-auth/http_client_with_basic_auth.out
examples/http-client-with-bearer-token-auth/http_client_with_bearer_token_auth.bal
examples/http-client-with-bearer-token-auth/http_client_with_bearer_token_auth.out
examples/http-client-with-oauth2-client-credentials-grant-type/http_client_with_oauth2_client_credentials_grant_type.bal
examples/http-client-with-oauth2-client-credentials-grant-type/http_client_with_oauth2_client_credentials_grant_type.out
examples/http-client-with-oauth2-password-grant-type/http_client_with_oauth2_password_grant_type.bal
examples/http-client-with-oauth2-password-grant-type/http_client_with_oauth2_password_grant_type.out
examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.bal
examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.out
examples/http-client-with-self-signed-jwt-auth/http_client_with_self_signed_jwt_auth.bal
examples/http-client-with-self-signed-jwt-auth/http_client_with_self_signed_jwt_auth.out
examples/https-client/https_client.bal
examples/https-client/https_client.out
examples/https-mutual-ssl/https_mutual_ssl_client.bal
examples/https-mutual-ssl/https_mutual_ssl_client.out

Update secured client BBEs

---

examples/udp-client/udp_client.bal

Add example code properly inside backticks

---

examples/udp-connect-client/udp_connect_client.bal
examples/udp-listener/udp_listener.bal

Correct code snippets with backticks

---

examples/udp-connect-client/udp_connect_client.bal
examples/udp-listener/udp_listener.description

Add backticks for missing code snippets

---

.github/workflows/main.yml

Standardise build name

---

gradle.properties

Bump installer version

---

gradle.properties

> Update spec version. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30765

Update spec version

---

examples/http-client-data-binding/http_client_data_binding.description

Fix client data binding description

---

examples/http-cookies/cookie_server.bal
examples/http-cookies/http_client.bal

Update cookie BBE

---

new-examples/http-client-mutual-ssl/http_client_mutual_ssl.bal
new-examples/http-service-mutual-ssl/tests/http_service_mutual_ssl_test.bal

$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1763

Fix a bug in mtls BBE

---

gradle.properties

Move dev tools to stable version

---

new-examples/io-bytes/io_bytes.bal
new-examples/io-csv/io_csv.bal
new-examples/io-json/io_json.bal
new-examples/io-strings/io_strings.bal
new-examples/io-xml/io_xml.bal

Remove tainted annotation from I/O BEEs

---

new-examples/time-formatting-and-parsing/time_formatting_and_parsing.description
new-examples/time-utc-and-civil/time_utc_and_civil.description
new-examples/time-utc/time_utc.description

Add descriptions for time BBEs

---

ballerina/build.gradle

Disable bbe testing temporarily

---

new-examples/hello-world/hello_world.description

Fix the description file of the hello world BBE

---

new-examples/tcp-transport-security/tcp_transport_security.description

Fix tcp BBE description

---

new-examples/variables-and-types/variables_and_types.description

Fix the description of the variables and types BBE

---

new-examples/providing-services/providing_services.description
new-examples/providing-services/providing_services.out

Fix the providing services BBE

---

new-examples/bbenavswanlake.yml
new-examples/index.json

Remove OpenAPI BBEs 

---

new-examples/dynamic-listener/dynamic_listener.bal
new-examples/dynamic-listener/dynamic_listener.client.out
new-examples/dynamic-listener/dynamic_listener.description
new-examples/dynamic-listener/dynamic_listener.metatags
new-examples/dynamic-listener/dynamic_listener.server.out

> Add dynamic-listener example to new-examples

Add dynamic-listener example to new-examples

---

new-examples/nats-streaming-durable-subscriptions/nats_streaming_durable_subscriptions.description
new-examples/nats-streaming-pub-sub/nats_streaming_pub_sub.description
new-examples/nats-streaming-queue-group/nats_streaming_queue_group.description
new-examples/nats-streaming-start-position/nats_streaming_start_position.description

Fix the module link in nats streaming examples

---

new-examples/counter-metrics/counter_metrics.bal
new-examples/counter-metrics/counter_metrics.client.out
new-examples/counter-metrics/counter_metrics.description
new-examples/counter-metrics/counter_metrics.metatags
new-examples/counter-metrics/counter_metrics.server.out
new-examples/counter-metrics/tests/counter_metrics_test.bal
new-examples/gauge-metrics/gauge_metrics.bal
new-examples/gauge-metrics/gauge_metrics.client.out
new-examples/gauge-metrics/gauge_metrics.description
new-examples/gauge-metrics/gauge_metrics.metatags
new-examples/gauge-metrics/gauge_metrics.server.out
new-examples/gauge-metrics/tests/gauge_metrics_test.bal
new-examples/tracing/tests/tracing_test.bal
new-examples/tracing/tracing.bal
new-examples/tracing/tracing.client.out
new-examples/tracing/tracing.description
new-examples/tracing/tracing.metatags
new-examples/tracing/tracing.server.out

> Copy observability examples to the new-examples folder.
> We need to move the following BBEs to the new location
1. Counter metrics example
2. Gauge metrics example
3. Tracing example

Copy observability examples to new examples

---

new-examples/bbenavswanlake.yml
new-examples/index.json

Remove Directory listener from Listener and Add file BBE in the index.json

Fix issues for the file BBEs

---

new-examples/query-expressions/query_expressions.bal

Limit comment for select clause

---

new-examples/bbenavswanlake.yml
new-examples/index.json

Added transactions BBEs to index.json

---

examples/testerina-mocking-objects/testerina_mocking_objects_main.bal
examples/testerina-mocking-objects/testerina_mocking_objects_test.bal

Object mocking member access doesnt work with Http clients anymore …

Update Object mocking tests

---

new-examples/error-reporting/error_reporting.bal

Update error reporting bbe

---

new-examples/bbenavswanlake.yml

Fix IO BBE Links

---

new-examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.bal
new-examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.description
new-examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.metatags
new-examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.out
new-examples/inferring-isolated/inferring_isolated.bal
new-examples/inferring-isolated/inferring_isolated.description
new-examples/isolated-functions/isolated_functions.bal
new-examples/isolated-functions/isolated_functions.description
new-examples/isolated-functions/isolated_functions.out
new-examples/isolated-methods/isolated_methods.bal
new-examples/isolated-methods/isolated_methods.description
new-examples/isolated-objects/isolated_objects.bal
new-examples/isolated-objects/isolated_objects.description
new-examples/isolated-variables/isolated_variables.bal
new-examples/isolated-variables/isolated_variables.description
new-examples/lock-statement/lock_statement.bal
new-examples/lock-statement/lock_statement.description
new-examples/readonly-and-isolated/readonly_and_isolated.bal
new-examples/readonly-and-isolated/readonly_and_isolated.out

Fix concurrency safety BBEs

---

examples/index.json
examples/proto-to-ballerina/proto_to_ballerina.description
examples/proto-to-ballerina/proto_to_ballerina.metatags
examples/proto-to-ballerina/proto_to_ballerina.out
examples/proto-to-ballerina/proto_to_ballerina.proto

Add missing Proto to Ballerina Example

---

examples/bbenavswanlake.yml
examples/index.json

Remove the BBEs with no BAL files  …

Remove the BBEs with no BAL files

---

examples/graphql-input-types/graphql_input_types.bal
examples/graphql-returning-service-objects/graphql_returning_service_objects.bal

Fix Warnings in GraphQL BBEs

---

examples/index.json

Add flags to enable bbe tests

---

examples/index.json
examples/optional-fields/optional_fields.bal
examples/optional-fields/optional_fields.description
examples/optional-fields/optional_fields.metatags
examples/optional-fields/optional_fields.out

Add optional fields BBE

---

examples/graphql-hello-world/graphql_hello_world.bal
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.bal
examples/graphql-returning-record-values/graphql_returning_record_values.bal
examples/graphql-returning-service-objects/graphql_returning_service_objects.bal

Remove graphql:Service and isolated Keyword from Services in GraphQL BBEs

---

examples/bbenavswanlake.yml

$Subject
New structure
```
Deployment
Code to cloud -> Kubernetes, Docker(later)
Function as a service - > Azure Functions, AWS Lambda
```
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …

Change Deployment BBE structure

---

examples/bbenavswanlake.yml

$title
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/2298

Fix the strings I/O sublink

---

examples/index.json

Disable playground for StdLib BBEs that cannot be run

---

examples/backtick-templates/backtick_templates.description
examples/decimal-type/decimal_type.description
examples/identifiers/identifiers.bal
examples/index.json
examples/inferring-isolated/inferring_isolated.description
examples/isolated-functions/isolated_functions.description
examples/isolated-objects/isolated_objects.description
examples/isolated-variables/isolated_variables.description
examples/json-type/json_type.description
examples/langlib-functions/langlib_functions.bal
examples/raw-templates/raw_templates.description
examples/readonly-type/readonly_type.bal
examples/variables-and-types/variables_and_types.bal
examples/xml-data-model/xml_data_model.description
examples/xml-templates-and-query/xml_templates_and_query.bal

Fix some lang BBEs

---

examples/index.json
examples/working-directly-with-json/working_directly_with_json.bal
examples/working-directly-with-json/working_directly_with_json.description
examples/working-directly-with-json/working_directly_with_json.metatags
examples/working-directly-with-json/working_directly_with_json.out

Add BBE on working directly with JSON

---

examples/named-workers/named_workers.bal

Fix issue with comments in named_workers BBE

---

examples/index.json

Mark lang BBEs that cannot be run on the playground

---

examples/bbenavswanlake.yml
examples/index.json

Disable playground for deployment bbes

---

examples/named-workers-and-futures/named_workers_and_futures.bal

Fix compilation issues with wait in BBEs

---

ballerina/build.gradle
build.gradle

Remove c2c BBE dependencies

---

examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
examples/kafka-producer-transactional/kafka_producer_transactional.bal

Fix error message in kafka producers

---

examples/nats-basic-pub-sub/publisher.bal
examples/nats-basic-request-reply/publisher.bal
examples/nats-streaming-durable-subscriptions/publisher.bal
examples/nats-streaming-pub-sub/publisher.bal
examples/nats-streaming-queue-group/publisher.bal
examples/nats-streaming-start-position/publisher.bal

Remove untainted keyword from from nats examples

---

examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-complex-type-queries/mysql_complex_type_queries.bal

> $title
> https://github.com/ballerina-platform/ballerina-distribution/pull/1751

Adjust comments and add new comments to java.jdbc and mysql BBEs

---

examples/http-absolute-path-and-path/http_absolute_path_and_path.bal
examples/http-absolute-path-and-path/tests/http_absolute_path_and_path_test.bal
examples/http-client-data-binding/http_client_data_binding.bal
examples/http-client-data-binding/http_client_data_binding.description
examples/http-data-binding/http_data_binding.bal
examples/http-default-resource/http_default_resource.bal
examples/http-default-resource/http_default_resource.client.out
examples/http-default-resource/tests/http_default_resource_test.bal

Update HTTP BBEs

---

examples/bbenavswanlake.yml

> Remove duplicated BBE Observability side nav bar items

Remove duplicated BBE Observability side nav bar items

---

examples/http-different-payload-types/http_different_payload_types.bal
examples/http-path-matrix-param/http_path_matrix_param.bal
examples/http-path-matrix-param/tests/http_path_matrix_param_test.bal
examples/http-resource-returns/http_resource_returns.bal
examples/http-resource-returns/http_resource_returns.client.out
examples/http-resource-returns/tests/http_resource_returns_test.bal
examples/http-restrict-by-media-type/http_restrict_by_media_type.bal
examples/http-restrict-by-media-type/http_restrict_by_media_type.description

Update REST API BBEs

---

stdlib-integration-tests/index.json

$subject.
This was disabled by https://github.com/ballerina-platform/ballerina-distribution/pull/1841

Enable auth integration tests

---

examples/index.json

Update the order of REST API security BBE section

---

examples/http-compression/http_compression.bal
examples/http-compression/http_compression.client.out
examples/http-compression/http_compression.description
examples/http-compression/tests/http_compression_test.bal

Simplify http compression BBE

---

examples/index.json

Correct category for Testing and Deployment

---

examples/bbenavswanlake.yml

Remove entries for unavailable BBEs

---

examples/http-disable-chunking/http_disable_chunking.bal
examples/http-disable-chunking/http_disable_chunking.client.out
examples/http-disable-chunking/http_disable_chunking.description

Fix chunking BBE

---

examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

Fix rabbitmq transaction BBEs

---

examples/jdbc-atomic-batch-execute-operation/jdbc_atomic_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal
examples/jdbc-execute-operation/jdbc_execute_operation.bal
examples/jdbc-query-operation/jdbc_query_operation.bal
examples/mysql-atomic-batch-execute-operation/mysql_atomic_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-complex-type-queries/mysql_complex_type_queries.bal
examples/mysql-execute-operation/mysql_execute_operation.bal
examples/mysql-query-operation/mysql_query_operation.bal

Remove spaces around -> in java.jdbc and mysql BBEs

---

examples/http-client-data-binding/http_client_data_binding.bal
examples/http-client-data-binding/http_client_data_binding.client.out
examples/http-client-data-binding/http_client_data_binding.server.out
examples/http-client-data-binding/tests/http_client_data_binding_test.bal

Reduce client DB BBE

---

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.bal
examples/http-2-0-server-push/http_client.bal
examples/http-retry/http_retry.bal
examples/http-retry/http_retry.server.out
examples/http-retry/tests/http_retry_test.bal
examples/http-timeout/http_timeout.bal

Update Retry BBE

---

examples/bbenavswanlake.yml

Change positioning of 'Testing' section …

Change positioning of 'Testing' section

---

examples/testerina-mocking-functions/testerina_mocking_functions_test.out
examples/testerina-mocking-objects/testerina_mocking_objects_test.out

> Update description in Testerina output file …

Update description in Testerina output file

---

examples/receive-email-using-client/receive_email_using_client.out
examples/receive-email-using-listener/receive_email_using_listener.out
examples/send-email/send_email.out
examples/udp-client/udp_client.out
examples/udp-connect-client/udp_connect_client.out
examples/udp-listener/udp_listener.out

Remove unwanted content from Email and UDP BBEs

---

examples/graphql-hello-world/graphql_hello_world.server.out
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.server.out
examples/graphql-input-types/graphql_input_types.server.out
examples/graphql-returning-record-values/graphql_returning_record_values.server.out
examples/graphql-returning-service-objects/graphql_returning_service_objects.server.out

Remove Redundant Information from GraphQL BBEs

---

examples/tcp-client/tcp_client.out
examples/tcp-listener/tcp_listener.out
examples/tcp-transport-security/tcp_transport_security_client.out
examples/tcp-transport-security/tcp_transport_security_listener.out
examples/websocket-basic-sample/websocket_basic_sample.out
examples/websocket-binary-client/websocket_binary_client.out
examples/websocket-text-client/websocket_text_client.out

Remove the description 
```
```

Update WebSocket and TCP BBEs

---

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.server.out
examples/http-100-continue/http_100_continue.server.out
examples/http-2-0-server-push/http_2_0_service.out
examples/http-2-0-server-push/http_client.out
examples/http-absolute-path-and-path/http_absolute_path_and_path.server.out
examples/http-circuit-breaker/http_circuit_breaker.server.out
examples/http-compression/http_compression.server.out
examples/http-cookies/cookie_server.out
examples/http-cookies/http_client.out
examples/http-cors/http_cors.server.out
examples/http-data-binding/http_data_binding.server.out
examples/http-default-resource/http_default_resource.server.out
examples/http-different-payload-types/http_different_payload_types.server.out
examples/http-disable-chunking/http_disable_chunking.server.out
examples/http-failover/http_failover.server.out
examples/http-load-balancer/http_load_balancer.server.out
examples/http-matrix-param/http_matrix_param.server.out
examples/http-passthrough/http_passthrough.server.out
examples/http-path-param/http_path_param.server.out
examples/http-query-parameter/http_query_parameter.server.out
examples/http-redirects/http_redirects.server.out
examples/http-request-with-multiparts/http_request_with_multiparts.server.out
examples/http-resource-returns/http_resource_returns.server.out
examples/http-response-with-multiparts/http_response_with_multiparts.server.out
examples/http-restrict-by-media-type/http_restrict_by_media_type.server.out
examples/http-retry/http_retry.server.out
examples/http-streaming/http_streaming.server.out
examples/http-timeout/http_timeout.server.out

Update instructions of HTTP BBEs

---

examples/testerina-mocking-functions/testerina_mocking_functions_test.out
examples/testerina-mocking-objects/testerina_mocking_objects_test.out

Update description in output file …

Update description in output file

---

examples/asynchronous-function-calls/asynchronous_function_calls.description
examples/booleans/booleans.description
examples/check-expression/check_expression.description
examples/covariance/covariance.description
examples/documentation/documentation.description
examples/error-handling/error_handling.description
examples/error-subtyping/error_subtyping.description
examples/function-values/function_values.description
examples/init-return-type/init_return_type.description
examples/maps/maps.description
examples/match-statement/match_statement.description
examples/object/object.description
examples/panics/panics.description
examples/strings/strings.description
examples/structural-typing/structural_typing.description
examples/unions/unions.description

Fix language BBE descriptions

---

examples/index.json

This is due to https://github.com/ballerina-platform/playground/issues/68

Disable a few BBEs on the playground

---

examples/nats-basic-pub-sub/publisher.out
examples/nats-basic-pub-sub/subscriber.out
examples/nats-basic-request-reply/publisher.out
examples/nats-basic-request-reply/subscriber.out
examples/nats-streaming-durable-subscriptions/publisher.out
examples/nats-streaming-durable-subscriptions/subscriber.out
examples/nats-streaming-pub-sub/publisher.out
examples/nats-streaming-pub-sub/subscriber.out
examples/nats-streaming-queue-group/publisher.out
examples/nats-streaming-queue-group/queue-group.out
examples/nats-streaming-start-position/publisher.out
examples/nats-streaming-start-position/subscriber.out
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.out
examples/rabbitmq-consumer/rabbitmq_consumer.out
examples/rabbitmq-producer/rabbitmq_producer.out
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.out
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.out

Update nats, stan and rabbitmq BBEs

---

examples/bbenavswanlake.yml

Function as a service -> Function as a Service …

Fix faas capital issue

---

examples/environment-variables/environment_variables.out
examples/logging-configuration/logging_configuration.out
examples/logging-with-context/logging_with_context.out
examples/logging/logging.out
examples/random-numbers/random_numbers.out
examples/uuid-generation/uuid_generation.out
examples/uuid-operations/uuid_operations.out

Remove unnecessary contents from the output files

---

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.out
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.out
examples/kafka-consumer-client/kafka_consumer_client.out
examples/kafka-consumer-group-service/kafka_consumer_group_service.out
examples/kafka-consumer-service/kafka_consumer_service.out
examples/kafka-producer-transactional/kafka_producer_transactional.out
examples/kafka-producer/kafka_producer.out

Update Kafka BBE outputs

---

central-tests/src/test/java/org/ballerina/central/CentralTest.java
central-tests/src/test/resources/central/projectB/Ballerina.toml

Incorporate central test to push a package with platform dependency

---

gradle.properties

Update dependencies to stable version

---

examples/bbenavswanlake.yml
examples/index.json

Fix working over the network BBE structure

---

examples/bbenavswanlake.yml
examples/index.json

Re-order HTTP BBEs on bbeswanlake.yml

---

examples/index.json

Remove the Play option in the observability BBEs. …

Remove the Play option in the observability BBEs

---

examples/inferring-isolated/inferring_isolated.description
examples/isolated-functions/isolated_functions.description
examples/isolated-objects/isolated_objects.description
examples/isolated-variables/isolated_variables.description
examples/raw-templates/raw_templates.description
examples/xml-data-model/xml_data_model.description

Fix bullet points rendering issue in BBEs. …

Fix Bullet Points Rendering Issue in BBEs

---

examples/http-client-basic-auth/http_client_basic_auth.bal
examples/http-client-bearer-token-auth/http_client_bearer_token_auth.bal
examples/http-client-mutual-ssl/http_client_mutual_ssl.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/http-client-self-signed-jwt-auth/http_client_self_signed_jwt_auth.bal
examples/http-client-ssl-tls/http_client_ssl_tls.bal

Improve secured BBEs of HTTP client

---

ballerina/build.gradle
examples/index.json

Enable bbe tests 

---

central-tests/src/test/resources/testng.xml

> $subject due to migration for dev BC to a different tenant(wso2.com) in Azure

Disable central related test cases temporarily

---

examples/graphql-returning-service-objects/graphql_returning_service_objects.bal
examples/index.json

Enable GraphQL BBE Tests

---

examples/graphql-service-mutual-ssl/tests/graphql_service_mutual_ssl_test.bal
examples/graphql-service-ssl-tls/tests/graphql_service_ssl_tls_test.bal
examples/index.json

Enable GraphQL Security BBE Tests

---

central-tests/src/test/resources/testng.xml

Reverts ballerina-platform/ballerina-distribution#1921

Revert "Disable central related test cases temporarily"

---

central-tests/src/test/java/org/ballerina/central/CentralNegativeTest.java
central-tests/src/test/java/org/ballerina/central/CentralTestUtils.java
central-tests/src/test/resources/testng.xml

> $Title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/11232 …

Add central negative test for pushing package with invalid access token

---

.github/ISSUE_TEMPLATE/type_bug.md
.github/ISSUE_TEMPLATE/type_improvement.md
.github/ISSUE_TEMPLATE/type_new_feature.md
.github/ISSUE_TEMPLATE/type_task.md

Add issue templates

---

examples/sequence-diagrams/sequence_diagrams.description

Improve the Sequence Diagram BBE. …

Improve the Sequence Diagram BBE

---

examples/jdbc-atomic-batch-execute-operation/jdbc_atomic_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal
examples/jdbc-query-operation/jdbc_query_operation.bal
examples/mysql-atomic-batch-execute-operation/mysql_atomic_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-complex-type-queries/mysql_complex_type_queries.bal
examples/mysql-query-operation/mysql_query_operation.bal

> $title
fixes : https://github.com/ballerina-platform/ballerina-standard-library/issues/1456 …

Update java.jdbc and mysql BBEs

---

.github/workflows/trigger-bbe-generation.yml

Run bbe generation only for master branch cheanges

---

.github/workflows/daily-build.yml

Include trivy scan

---

examples/xml-json-conversion/xml_json_conversion.description

Fix incorrect wording in the xmldata package BBE

---

examples/websocket-basic-sample/websocket_basic_sample.bal
examples/websocket-basic-sample/websocket_basic_sample.out

Fix the issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1482

Refactor the WebSocket listener BBE

---

.github/workflows/daily-build.yml

Include all the severities

---

.github/workflows/publish-release.yml
build.gradle

Test installer version updation

---

.github/workflows/publish-release.yml

Test updating installer version with upstream secrets

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
ballerina-test/src/test/resources/openapi/expected/filtered_tags.bal

Fix OpenAPI tests failures 

---

devtools-integration-tests/testerina-object-mocking-test/client.bal

Correct the usage of toJsonString in test function …

Correct the usage of toJsonString

---

ballerina-test/src/test/resources/openapi/expected/filtered_tags.bal

Fix OpenAPI test failure 

---

examples/jdbc-atomic-batch-execute-operation/jdbc_atomic_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-execute-operation/jdbc_execute_operation.bal
examples/jdbc-query-operation/jdbc_query_operation.bal
examples/mysql-atomic-batch-execute-operation/mysql_atomic_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-complex-type-queries/mysql_complex_type_queries.bal
examples/mysql-execute-operation/mysql_execute_operation.bal
examples/mysql-query-operation/mysql_query_operation.bal

Reformat SQL bbes

---

examples/index.json

$title
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/31118

Enable Retry Transaction Statement BBE verification

---

examples/table-concept/table_concept.description
examples/table-concept/table_concept.metatags
examples/table-syntax/table_syntax.description

Improve Table Syntax BBE description

---

.github/workflows/publish-release.yml
build.gradle
gradle.properties

Setup release workflow to release artifacts as RC

---

examples/testerina-data-driven-tests/testerina_data_driven_tests.bal
examples/testerina-data-driven-tests/testerina_data_driven_tests.out

Update BBE for data provider

---

.github/workflows/publish-release.yml
build.gradle

This PR modifies the publish release workflow to allow publishing releases with pre-release tags.

Add parameters for publishing releases with pre-release tags

---

examples/index.json

Update the column structure in the `index.json` file. …

Update the Column Structure in the `index.json` File 

---

examples/index.json

Add the `isLearnByExample` property to the examples `index.json` file. …

Add the `isLearnByExample` property to the examples `index.json` file

---

examples/http-headers/http_headers.bal
examples/http-headers/http_headers.client.out
examples/http-headers/http_headers.description
examples/http-headers/http_headers.metatags
examples/http-headers/http_headers.server.out
examples/index.json

> $subject
Fixes [#1483](https://github.com/ballerina-platform/ballerina-standard-library/issues/1483)

Add BBE for `@http:Header` annotation usage

---

build.gradle
gradle.properties

Test updating installer version fix

---

.github/workflows/daily-build.yml
build-time-tests/build.gradle
build-time-tests/samples/build-samples.sh
build-time-tests/samples/c2c-sample7/.gitignore
build-time-tests/samples/c2c-sample7/.svnignore
build-time-tests/samples/c2c-sample7/Ballerina.toml
build-time-tests/samples/c2c-sample7/Cloud.toml
build-time-tests/samples/c2c-sample7/README.md
build-time-tests/samples/c2c-sample7/coffe.bal
build-time-tests/samples/c2c-sample7/menus/coffe.json
build-time-tests/samples/c2c-sample7/menus/tea.json
build-time-tests/samples/c2c-sample7/modules/tea/tea.bal
build-time-tests/src/main/java/org/ballerina/packages/buildtime/GenerateBuildDataCsv.java
settings.gradle

> Add build-time-tests module. The daily build workflow is configured to run this module as the last step which will produce build time information for a set of samples and archive a CSV file.

 Add build-time-tests module

---

.github/workflows/publish-release.yml
ballerina/build.gradle
examples/c2c-deployment/c2c_deployment.bal
examples/cache-invalidation/tests/cache_test.bal
examples/filepaths/tests/filepath_test.bal
examples/ignoring-return-values-and-errors/ignoring_return_values_and_errors.out
examples/index.json
examples/panics/panics.out
examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal
examples/while-statement/while_statement.bal
stdlib-integration-tests/index.json

$subject part of https://github.com/ballerina-platform/ballerina-distribution/issues/1920

[Phase 2] Enable BBE builds

---

examples/index.json
examples/websub-webhook-sample/websub_webhook_sample.bal

> $subject
Part of [#1920](https://github.com/ballerina-platform/ballerina-distribution/issues/1920)

Enable WebSub BBE build verification

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync after Release 1.2.15

---

pom.xml

Update lang and ballerinax module dependency versions

---

pom.xml

Update staging URLs of ballerinax modules

---

.github/workflows/daily-build.yml

> Rearrange workflow steps to run build performance samples

Rearrange workflow steps to run build performance samples

---

.github/workflows/daily-build.yml

Rearrange connector version bump step

---

gradle.properties

Update dependency versions to beta2 stable versions

---

.github/workflows/publish-release.yml

> Test updating installer version to release

Modify git command to update installer version

---

central-tests/src/test/resources/testng.xml

Disable central tests temporarily

---

examples/http-resource-returns/http_resource_returns.bal
examples/http-resource-returns/http_resource_returns.client.out
examples/http-resource-returns/tests/http_resource_returns_test.bal

> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1686

Fix Return resource BBE

---

examples/index.json
examples/nats-basic-secure-connection/nats_basic_secure_connection.description
examples/nats-basic-secure-connection/nats_basic_secure_connection.metatags
examples/nats-basic-secure-connection/publisher.bal
examples/nats-basic-secure-connection/publisher.out
examples/nats-basic-secure-connection/subscriber.bal
examples/nats-basic-secure-connection/subscriber.out
examples/nats-streaming-secure-connection/nats_streaming_secure_connection.description
examples/nats-streaming-secure-connection/nats_streaming_secure_connection.metatags
examples/nats-streaming-secure-connection/publisher.bal
examples/nats-streaming-secure-connection/publisher.out
examples/nats-streaming-secure-connection/subscriber.bal
examples/nats-streaming-secure-connection/subscriber.out
examples/rabbitmq-secure-connection/consumer.bal
examples/rabbitmq-secure-connection/consumer.out
examples/rabbitmq-secure-connection/producer.bal
examples/rabbitmq-secure-connection/producer.out
examples/rabbitmq-secure-connection/rabbitmq_secure_connection.description
examples/rabbitmq-secure-connection/rabbitmq_secure_connection.metatags

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1578
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1579

Add security examples for messaging modules

---

central-tests/src/test/resources/testng.xml

Reverts ballerina-platform/ballerina-distribution#2053

Revert "Disable central tests temporarily"

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync ballerina-1.2.x After 1.2.16 Release

---

examples/jdbc-atomic-batch-execute-operation/jdbc_atomic_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal
examples/jdbc-query-operation/jdbc_query_operation.bal
examples/mysql-atomic-batch-execute-operation/mysql_atomic_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-complex-type-queries/mysql_complex_type_queries.bal
examples/mysql-query-operation/mysql_query_operation.bal

> $title
> fix BBEs with newer stream API change 
> Type “Sent” when you have provided new/updated certification …

Update java.jdbc and mysql BBEs as stream API change

---

examples/http-resource-returns/http_resource_returns.bal
examples/http-resource-returns/http_resource_returns.client.out
examples/http-resource-returns/tests/http_resource_returns_test.bal

> Related to ballerina-platform/ballerina-standard-library#1686

Change HTTP method in Return resource BBE

---

.github/workflows/daily-build.yml

Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2067

Exclude update tool from docker image

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x Branch After 1.2.17 Release

---

.github/workflows/daily-build.yml

> Include short version for docker image

Include short version for docker image

---

examples/index.json

Disable output verification for task BBEs

---

examples/index.json

Disable output verification in BBEs

---

ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java

Enable tests for windows build

Fix resolving bal file path in windows build

---

examples/graphql-service-ssl-tls/graphql_service_ssl_tls.bal
examples/http-client-basic-auth/http_client_basic_auth.bal
examples/http-client-bearer-token-auth/http_client_bearer_token_auth.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/http-client-self-signed-jwt-auth/http_client_self_signed_jwt_auth.bal
examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.bal
examples/http-service-basic-auth-ldap-user-store/http_service_basic_auth_ldap_user_store.bal
examples/http-service-jwt-auth/http_service_jwt_auth.bal
examples/http-service-oauth2/http_service_oauth2.bal
examples/http-service-ssl-tls/http_service_ssl_tls.bal
examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal
examples/tcp-transport-security/tcp_transport_security_service.bal
examples/websocket-client-basic-auth/websocket_client_basic_auth.bal
examples/websocket-client-bearer-token-auth/websocket_client_bearer_token_auth.bal
examples/websocket-client-oauth2-client-credentials-grant-type/websocket_client_oauth2_client_credentials_grant_type.bal
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.bal
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.bal
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.bal
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.bal
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.bal
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.bal
examples/websocket-service-oauth2/websocket_service_oauth2.bal
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.bal

$subject was done to improve comments of security related BBEs with adhering to the suggestion of gRPC BBEs.

Improve comments of security related BBEs

---

README.md
resources/tools/INSTALL.txt

> Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1007 and https://github.com/ballerina-platform/ballerina-distribution/issues/1346

Imorove Building the source section

---

examples/strings/strings.out

Update string BBE output for lang changes

---

examples/strands/strands.bal
examples/strands/strands.description

Fix typo in "between" word (was "been").

---

pom.xml

Update lang and ballerinax dependency versions

---

examples/http-service-mutual-ssl/http_service_mutual_ssl.client.out
examples/http-service-ssl-tls/http_service_ssl_tls.client.out

$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1701

Add curl commands for HTTP SSL related BBEs

---

examples/index.json

Enable output verification for strings BBE

---

pom.xml

Update urls for release

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java

This PR will add service call stack debug test
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/31304

[Debugger] Add service call stack debug test

---

.github/workflows/pull-request.yml

Add Concurrency to Cancel Concurrent PR Builds

---

examples/graphql-mutations/graphql_mutations.bal
examples/graphql-mutations/graphql_mutations.client.out
examples/graphql-mutations/graphql_mutations.description
examples/graphql-mutations/graphql_mutations.metatags
examples/graphql-mutations/graphql_mutations.server.out
examples/graphql-returning-service-objects/graphql_returning_service_objects.bal
examples/index.json

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1748

Add BBE for GraphQL Mutations

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x Branch After 1.2.18 Release

---

central-tests/src/test/resources/testng.xml

> $subject. This is to look into the build failure. Please note @pramodya1994

Disable central tests

---

examples/json-numbers/json_numbers.out

Fix JSON Numbers BBE output

---

examples/index.json

Enable output verification in transaction BBEs

---

central-tests/src/test/resources/testng.xml

Reverts ballerina-platform/ballerina-distribution#2118

Revert "Disable central tests"

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x Branch After 1.2.19 Release

---

examples/security-crypto/security_crypto.bal

Fix an invalid variable name

---

ballerina/build.gradle
gradle.properties

Resolves issue #1030 in ballerina-release …

Sort stdlibs based on dependency tree

---

gradle.properties

Update ftp version

---

gradle.properties

Update open-api version

---

central-tests/src/test/java/org/ballerina/central/CentralTest.java
central-tests/src/test/resources/central/projectC/Ballerina.toml
central-tests/src/test/resources/central/projectC/modules/sub/main.bal
central-tests/src/test/resources/central/projectE/Ballerina.toml
central-tests/src/test/resources/central/projectE/Package.md
central-tests/src/test/resources/central/projectE/main.bal

Fixes and enable central integration tests

Fix central tests

---

examples/index.json

Remove the testing BBEs from the Learn By Examples. …

Remove the Testing BBEs from the Learn By Examples

---

project-api-tests/src/test/java/org/ballerina/projectapi/BuildTimeTest.java

Disable test case for resolution time check …

Disable test case for resolution time check

---

.github/workflows/publish-release.yml

Fix release workflow to build linux installers

Fix passing the distribution version to build linux installers

---

project-api-tests/src/test/java/org/ballerina/projectapi/BuildTimeTest.java
project-api-tests/src/test/resources/build-time/Project1/main.bal

The failed cases had time reduction less than 500ms. See https://scans.gradle.com/s/k4d2n75odnew2/tests/:project-api-tests:test/org.ballerina.projectapi.BuildTimeTest/testResolutionTimeReduction?expanded-stacktrace=WyIwIl0&top-execution=1, the time reduction was 475ms. 
In order to fix this, added more packages to resolve to the project being built increasing the resolution time.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2160
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature …

Enable test case for resolutionTime reduction

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Run release without creating macos pkg installer

Remove macos pkg installer from release workflow

---

.github/workflows/daily-build.yml

Include test image support

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Remove jenkins from the release pipeline.

Add MacOS pkg installer for daily-build & release workflows

---

examples/testerina-mocking-objects/testerina_mocking_objects_test.bal

Fix object mocking tests for beta3 changes …

Fix object mocking tests for beta3 changes

---

project-api-tests/src/test/resources/testng.xml

Disable project api tests

---

examples/index.json

Remove module name from BBE index.json

---

project-api-tests/src/test/resources/testng.xml

Reverts ballerina-platform/ballerina-distribution#2184

Revert "Disable project api tests"

---

.github/workflows/daily-build.yml

This triggers the choreo-compiler-plugins repo's daily build and enables nightly support.  …

Add choreo-compiler-plugins build trigger

---

examples/index.json

Rearrange the lang BBEs.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/2858. …

Rearrange the Lang BBEs

---

examples/index.json

Reverts ballerina-platform/ballerina-distribution#2173

Revert "Rearrange the Lang BBEs"

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralNegativeTest.java

Disable failing test method

---

.github/workflows/daily-build.yml

Include build args

---

.github/workflows/daily-build.yml

Temporarily remove choreo-compiler-plugins daily build trigger …

Remove choreo-compiler-plugins build triger

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralNegativeTest.java

Enable project-api negative central test

---

.github/workflows/publish-release.yml

> Include docker image build and scan for release pipeline

Include docker image build and scan for release pipeline

---

.github/workflows/daily-build.yml

Add plugin build trigger

---

examples/index.json
examples/websocket-retry-client/websocket_retry_client.bal
examples/websocket-retry-client/websocket_retry_client.description
examples/websocket-retry-client/websocket_retry_client.metatags
examples/websocket-retry-client/websocket_retry_client.out

$subject.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1885

Add a BBE for WebSocket retry

---

examples/http-access-logs/http_access_logs.bal
examples/http-access-logs/http_access_logs.client.out
examples/http-access-logs/http_access_logs.description
examples/http-access-logs/http_access_logs.metatags
examples/http-access-logs/http_access_logs.server.out
examples/http-access-logs/tests/http_access_logs_test.bal
examples/http-trace-logs/http_trace_logs.bal
examples/http-trace-logs/http_trace_logs.client.out
examples/http-trace-logs/http_trace_logs.description
examples/http-trace-logs/http_trace_logs.metatags
examples/http-trace-logs/http_trace_logs.server.out
examples/http-trace-logs/tests/http_trace_logs_test.bal
examples/index.json

> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1833

Add BBEs for trace/access logs

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Increase trivy timeout

---

examples/websocket-text-client/websocket_text_client.bal
examples/websocket-text-client/websocket_text_client.description

Fix the WebSocket module broken link. …

Fix the WebSocket Module Broken Link

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

> Update OpenAPI version in tests

Update OpenAPI Tool version 

---

.github/workflows/daily-build.yml

Change notification sending to notification chat form ballerina chat

Migrate notification to notification chat

---

devtools-integration-tests/src/test/resources/testng.xml

$subject.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2247 …

Enable disabled debugger integration tests

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x after release 1.2.20

---

project-api-tests/src/test/resources/testng.xml

Enable disabled central tests

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java

Disable "testBuildAndRunPackageD" test case

---

pom.xml

Update lang/ballerinax versions to 1.2.21

---

examples/kafka-consumer-client/kafka_consumer_client.bal
examples/kafka-consumer-group-service/kafka_consumer_group_service.bal
examples/kafka-consumer-service/kafka_consumer_service.bal
examples/kafka-producer/kafka_producer.bal

This reverts commit 69a3323fd93321ee1870fecb46494dcabde950b8. …

Revert "Add explicit return statements"

---

examples/nats-basic-pub-sub/publisher.bal
examples/nats-basic-pub-sub/subscriber.bal
examples/nats-basic-request-reply/publisher.bal
examples/nats-basic-secure-connection/publisher.bal
examples/nats-basic-secure-connection/subscriber.bal
examples/nats-streaming-durable-subscriptions/publisher.bal
examples/nats-streaming-pub-sub/publisher.bal
examples/nats-streaming-queue-group/publisher.bal
examples/nats-streaming-secure-connection/publisher.bal
examples/nats-streaming-start-position/publisher.bal
examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-secure-connection/producer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

This reverts commit fa6c70e3
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …

Revert "Fix NATS, STAN and RabbitMQ BBEs"

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x after release 1.2.21

---

examples/arrays/arrays.bal
examples/arrays/arrays.out
examples/binary-data/binary_data.bal
examples/identity/identity.bal
examples/langlib-functions/langlib_functions.bal
examples/langlib-functions/langlib_functions.out
examples/querying-with-streams/querying_with_streams.bal
examples/table-syntax/table_syntax.bal
examples/table-syntax/table_syntax.out
examples/type-inference/type_inference.bal

Fix bbes with unused vars

---

ballerina-test/src/test/resources/openapi/petstore.bal
gradle.properties

> $Subject
> Java JDK 11 Ubuntu 20.04
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

Update OpenAPI Tool version

---

examples/xml-subtyping/xml_subtyping.bal

Fix unused vars in xml subtyping BBE

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralNegativeTest.java

> $Title
- Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2316 …

Fix testPushPackageWithInvalidAccessToken test

---

pom.xml

Update lang/ballerinax versions to 1.3.0

---

examples/security-crypto/security_crypto.bal
examples/security-crypto/tests/security_crypto_test.bal
examples/security-jwt-issue-validate/tests/security_jwt_issue_validate_test.bal
examples/url-encode-decode/tests/url_encode_decode_test.bal

Fix unused variable warning of security BBEs

---

examples/http-circuit-breaker/tests/http_circuit_breaker_test.bal

Fix  unused variable warning in Circuit breaker BBE

---

examples/ftp-client/ftp_client.bal
examples/receive-email-using-client/receive_email_using_client.bal
examples/send-email/send_email.bal
examples/sftp-client/sftp_client.bal
examples/udp-client/udp_client.bal
examples/udp-connect-client/udp_connect_client.bal

$subject in https://github.com/ballerina-platform/ballerina-distribution/pull/2258

Revert adding return statements for nil values

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java

Fix service debbug test

---

examples/binary-data/binary_data.bal

Update binary data bbe

---

examples/websub-webhook-sample/websub_webhook_sample.out

> $subject
Related to [#2040](https://github.com/ballerina-platform/ballerina-standard-library/issues/2040)

Remove unwanted logs from bbe

---

examples/nats-basic-pub-sub/subscriber.out
examples/nats-basic-request-reply/subscriber.out
examples/nats-basic-secure-connection/subscriber.out
examples/nats-streaming-durable-subscriptions/subscriber.out
examples/nats-streaming-pub-sub/subscriber.out
examples/nats-streaming-secure-connection/subscriber.out
examples/nats-streaming-start-position/subscriber.out
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.out
examples/rabbitmq-consumer/rabbitmq_consumer.out
examples/rabbitmq-secure-connection/consumer.out
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.out

Remove listener logs from NATS and RabbitMQ examples

---

examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.server.out
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.server.out
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.server.out
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.server.out
examples/graphql-service-oauth2/graphql_service_oauth2.server.out
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.service.out
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.server.out
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.server.out
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.server.out
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.server.out
examples/grpc-service-oauth2/grpc_service_oauth2.server.out
examples/grpc-service-ssl-tls/grpc_service_ssl_tls.server.out
examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.server.out
examples/http-service-basic-auth-ldap-user-store/http_service_basic_auth_ldap_user_store.server.out
examples/http-service-jwt-auth/http_service_jwt_auth.server.out
examples/http-service-mutual-ssl/http_service_mutual_ssl.server.out
examples/http-service-oauth2/http_service_oauth2.server.out
examples/http-service-ssl-tls/http_service_ssl_tls.server.out
examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.out
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.server.out
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.server.out
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.server.out
examples/websocket-service-mutual-ssl/websocket_service_mutual_ssl.server.out
examples/websocket-service-oauth2/websocket_service_oauth2.server.out
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.server.out

Remove listener start logs from security BBEs

---

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.out
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.out
examples/kafka-consumer-group-service/kafka_consumer_group_service.out
examples/kafka-consumer-service/kafka_consumer_service.out
examples/kafka-producer-transactional/kafka_producer_transactional.out
examples/tcp-listener/tcp_listener.bal

Remove kafka logs from BBEs and update TCP service

---

examples/index.json

Disable unwanted output verification from security BBEs

---

examples/index.json

> $subject as a result of https://github.com/ballerina-platform/ballerina-standard-library/issues/2040
Related Issue : https://github.com/ballerina-platform/ballerina-distribution/issues/2343

Disable output verification temporarily due to logic failure

---

examples/tcp-transport-security/tcp_transport_security_service.bal
stdlib-integration-tests/tcp/tests/mock_servers.bal

$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2398

Fix failures related to distinct services in tcp

---

gradle.properties

To fix the grpc command not found issue.

Upgrade the gRPC stdlib version

---

gradle.properties

Update SQL version

---

examples/dynamic-listener/dynamic_listener.bal

Fix build failure

---

gradle.properties

Automated/dependency version update-4b039e51)

---

examples/testerina-assertions/testerina_assertions.bal

Update Testerina Assertion BBE example

---

examples/websocket-retry-client/websocket_retry_client.description

Fix the API Docs Link

---

README.md
project-api-tests/src/test/java/org/ballerina/projectapi/CentralNegativeTest.java
project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
project-api-tests/src/test/resources/central/projectA/Ballerina.toml
project-api-tests/src/test/resources/central/projectB/Ballerina.toml
project-api-tests/src/test/resources/central/projectC/Ballerina.toml
project-api-tests/src/test/resources/central/projectC/main.bal
project-api-tests/src/test/resources/central/projectD/Ballerina.toml
project-api-tests/src/test/resources/central/projectD/main.bal
project-api-tests/src/test/resources/central/projectSnapshot/Ballerina.toml

Update dev central test org details
Resolves part of https://github.com/wso2-enterprise/ballerina-registry/issues/1183
> Link to …

Update dev central test org details

---

.github/workflows/daily-build.yml

Generate hashes for daily build artifacts (installers)
https://github.com/ballerina-platform/ballerina-distribution/issues/2338

Generate hashes for artifacts in daily build

---

examples/receive-email-using-client/receive_email_using_client.bal

Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2432

Remove unwanted close status

---

examples/jdbc-atomic-batch-execute-operation/jdbc_atomic_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal
examples/jdbc-execute-operation/jdbc_execute_operation.bal
examples/jdbc-query-operation/jdbc_query_operation.bal
examples/mysql-atomic-batch-execute-operation/mysql_atomic_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-complex-type-queries/mysql_complex_type_queries.bal
examples/mysql-execute-operation/mysql_execute_operation.bal
examples/mysql-query-operation/mysql_query_operation.bal

$subject fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2434

Remove unused variables in sql bbes

---

examples/manage-scheduled-jobs/manage_scheduled_jobs.bal
examples/task-one-time-job-execution/task_one_time_job_execution.bal

Remove unused variables from task BBE

---

.github/workflows/pull-request.yml
ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update dependency versions for SLBeta5 RC

---

examples/cache-basics/cache_basics.bal
examples/cache-invalidation/cache_invalidation.bal
examples/directories/directories.bal
examples/filepaths/filepaths.bal
examples/filepaths/tests/filepath_test.bal
examples/files/files.bal
examples/http-access-logs/tests/http_access_logs_test.bal
examples/http-compression/tests/http_compression_test.bal
examples/http-cors/tests/http_cors_test.bal
examples/http-redirects/tests/http_redirects_test.bal
examples/http-trace-logs/tests/http_trace_logs_test.bal
examples/random-numbers/random_numbers.bal
examples/regular-expressions/regular_expressions.bal
examples/task-frequency-job-execution/task_frequency_job_execution.bal
examples/task-one-time-job-execution/task_one_time_job_execution.bal
examples/uuid-generation/uuid_generation.bal
examples/uuid-operations/uuid_operations.bal
examples/websocket-binary-client/websocket_binary_client.bal
examples/websocket-retry-client/websocket_retry_client.bal
examples/websocket-text-client/websocket_text_client.bal
examples/xml-json-conversion/xml_json_conversion.bal
examples/xml-operations/xml_operations.bal

$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/2244

Revert adding explicit return statement for stdlib BBEs

---

examples/http-caching-client/http_caching_client.bal
examples/http-caching-client/http_caching_client.client.out
examples/http-caching-client/http_caching_client.description
examples/http-caching-client/http_caching_client.metatags
examples/http-caching-client/http_caching_client.server.out
examples/http-caching-client/tests/http_caching_client_test.bal
examples/index.json

> $subject as the tracelog is back
> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2429

Add HTTP caching client BBE

---

pom.xml

Update nexus links

---

ballerina-test-automation/gradle.properties

Update the display text

---

gradle.properties

Move dependencies to stable versions

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java

Fix OpenAPI tests

---

project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

Fix issues in hierarchical package test case …

Fix issues in hierarchical package test case

---

.github/workflows/daily-build.yml

Use common workflow for failure notification

---

project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

Temporarily disable failing tests …

Temporarily disable failing tests

---

.github/workflows/pull-request.yml
gradle.properties

Update ballerina lang release version

---

project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

> Disable failing hierarchical package test

Disable failing hierarchical package test

---

examples/http-caching-client/http_caching_client.bal
examples/http-caching-client/http_caching_client.client.out
examples/http-caching-client/http_caching_client.description
examples/http-caching-client/http_caching_client.metatags
examples/http-caching-client/http_caching_client.server.out
examples/http-caching-client/tests/http_caching_client_test.bal
examples/index.json

Reverts ballerina-platform/ballerina-distribution#2394

Revert "Revert "Add HTTP caching client BBE""

---

examples/index.json
examples/xml-json-conversion/xml_json_conversion.out

Eable output verification for xml-json bbe

---

examples/xml-json-conversion/xml_json_conversion.out
gradle.properties

Update xml-json BBE output

---

ballerina-test-automation/gradle.properties

Update version for installer tests

Update version for installer tests

---

doc-guidelines.md

Link to the "Standard Library API Documentation Guide". …

Link to the "Standard Library API Documentation Guide"

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Generate hashes for balllerina zips in release and daily build
##Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2400

Generate hashes for balllerina zips in release and daily build

---

installers/linux-deb/resources/DEBIAN/postrm
installers/linux-rpm/resources/ballerina-runtime.spec
installers/linux-rpm/resources/ballerina-tools.spec

Fix ballerina uninstallation error in linux
https://github.com/ballerina-platform/ballerina-update-tool/issues/67

Fix ballerina uninstallation error in linux

---

gradle.properties

Move dependencies to stable version

---

pom.xml

Update nexus URLs

---

ballerina/LICENSE
ballerina/build.gradle

Pack LICENSE file

---

examples/http-request-error-interceptor/http_request_error_interceptor.bal
examples/http-request-error-interceptor/http_request_error_interceptor.description
examples/http-request-error-interceptor/http_request_error_interceptor.server.out
examples/http-request-interceptor-at-service/http_request_interceptor_at_service.bal
examples/http-request-interceptor-at-service/http_request_interceptor_at_service.client.out
examples/http-request-interceptor-at-service/http_request_interceptor_at_service.description
examples/http-request-interceptor-at-service/tests/http_request_interceptor_at_service_test.bal

Make interceptor examples simple

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
ballerina-test/build.gradle
ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java
ballerina/build.gradle
build.gradle
devtools-integration-tests/build.gradle
gradle.properties
project-api-tests/build.gradle

Update versions with new release naming and change the tests according to new 'bal -v' command

Update versions with semver

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

> $Subject
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts of marketing content …

Update OpenAPI version in tests

---

.github/workflows/daily-build.yml
.github/workflows/main.yml
.github/workflows/publish-release.yml

Update short version in workflow

---

project-api-tests/src/test/resources/testng.xml

Disable failing central tests

---

ballerina-test-automation/gradle.properties
ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java

Fix installer tests

---

.github/workflows/daily-build.yml

Skip tests

---

ballerina-test-automation/gradle.properties
ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
gradle.properties

Sync stage swan lake

---

.github/workflows/daily-build.yml

> Include dev container image pushing

Include dev container image pushing

---

project-api-tests/src/test/resources/testng.xml

Enable central tests

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Rearrange installer version names

---

installers/linux-rpm/resources/ballerina-runtime.spec
installers/linux-rpm/resources/ballerina-tools.spec
installers/windows/build-ballerina-windows-x64.bat

Fix installer path

---

.github/workflows/main.yml

Rearrange artifact names

---

examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal

Fix the websocket_basic_sample test case

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1812

Add a comment about the generated code mismatch in bidirectional gRPC service

---

.github/workflows/daily-build.yml

> Remove performance sample builds

Remove performance sample builds

---

build.gradle
gradle.properties

> Add observability modules for distribution
> Integrate observability modules
> https://github.com/ballerina-platform/ballerina-lang/issues/33195
1. Removed ballerina-lang observability modules
2. Created new modules: `module-ballerina-observe` and `module-ballerinai-observe`
3. Update standard lib modules
> JDK 11, Ubuntu

Add observability modules

---

examples/aws-lambda-deployment/aws_lambda_deployment.out
examples/azure-functions-deployment/azure_functions_deployment.description
examples/azure-functions-deployment/azure_functions_deployment.out

$Subject as we encourage users to use ballerina projects instead of single file projects since new compiler extesnion code generators does not support single files. …

Modify FaaS modules BBEs to use ballerina projects

---

ballerina/build.gradle
gradle.properties

Update stdlibs resource file

---

.github/workflows/daily-build.yml

Update deb installer name

---

gradle.properties

Update patch version `beta6.1`

---

ballerina/build.gradle
gradle.properties

> Dependency version update (these are the same commits from ballerina-bot automatic version bump PR sent for the corresponding timestamp)

Dependency version update

---

.github/workflows/daily-build.yml

Fix installer version

---

.github/workflows/daily-build.yml
ballerina-test-automation/gradle.properties
gradle.properties

Fix build issues

---

gradle.properties

Update timestamps for patch 6.1

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync branch 1.2.x after 1.2.22 release

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Update nexus urls for 1.2.24 release

---

examples/index.json

Fix HTTP service OAuth2 BBE URL

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x with release 1.2.24 branch

---

pom.xml

Update nexus staging urls for 1.2.25 release

---

ballerina-test-automation/gradle.properties

Fix test failures in installers
Change language specification version from `2021R1` to `2022R1`

Change language specification version

---

pom.xml

$subject related to https://github.com/wso2-enterprise/internal-support-ballerina/issues/17
```
+--------------------------------------+------------------+----------+-------------------+------------------------+---------------------------------------+
|               LIBRARY                | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |     FIXED VERSION      |                 TITLE                 |
+--------------------------------------+------------------+----------+-------------------+------------------------+---------------------------------------+
| commons-io:commons-io                | CVE-2021-29425   | MEDIUM   |               2.6 |                    2.7 | apache-commons-io: Limited            |
|                                      |                  |          | …
```

Bump commons-io dependency

---

examples/http-cors/http_cors.client.out

Fix CORS BBE client out

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal
examples/grpc-client-streaming/grpc_client_streaming_service.bal

$title
Replace stream for each with a query expression.

Make gRPC bidirectional and client streaming services isolated using query expression 

---

examples/graphql-context/graphql_context.client.out
examples/index.json

Fix GraphQL Context BBE

---

examples/cache-invalidation/cache_invalidation.out
examples/files/files.bal
examples/files/files.out
examples/index.json

Fix cache, file and task BBE

---

examples/identifiers/identifiers.bal

Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3413

Fix comment in Identifiers BBE

---

ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java

Currently testDirectoryPath test in installer tests fails. This will fix the test failure.

Fix test failures in testDirectoryPath

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update OpenAPI version in test

---

gradle.properties

Update datamapper version

---

examples/booleans/booleans.bal
examples/function-values/function_values.description
examples/match-statement/match_statement.description
examples/structural-typing/structural_typing.description

Update bbe descriptions

---

examples/c2c-deployment/c2c_deployment.out

$Subject. Added a minor comment on kubernetes deployment.
As docker-env step directly deploys container into the cluster. and user can't execute the docker image on the local machine.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …

Add note for docker-env on Kubernetes deployment BBE

---

examples/limit-clause/limit_clause.description

```diff
-The `limit` clause limits the number of results from the earlier clauses.
+The `limit` clause limits the number of results from the query.
```

Minor update to limit clause description

---

examples/destructuring-records/destructuring_records.metatags
examples/join-clause/join_clause.metatags
examples/let-clause/let_clause.metatags
examples/limit-clause/limit_clause.metatags
examples/ordering/ordering.metatags
examples/querying-tables/querying_tables.metatags
examples/querying-with-streams/querying_with_streams.metatags

Add query meta tags to all BBEs under query expression

---

examples/creating-tables-with-query/creating_tables_with_query.bal

Update BBE creating tables with query expression

---

examples/xml-operations/xml_operations.description

Change the description of xml operations

---

examples/asynchronous-function-calls/asynchronous_function_calls.description
examples/inter-worker-failure-propagation/inter_worker_failure_propagation.bal
examples/inter-worker-failure-propagation/inter_worker_failure_propagation.description
examples/inter-worker-message-passing/inter_worker_message_passing.description
examples/named-worker-return-values/named_worker_return_values.bal
examples/named-worker-return-values/named_worker_return_values.description
examples/named-workers-and-futures/named_workers_and_futures.bal
examples/named-workers-and-futures/named_workers_and_futures.description

Fix BBE descriptions

---

gradle.properties

[`stage-swan-lake`] Update dependencies to released versions

---

.github/workflows/daily-build.yml

[`stage-swan-lake`] Update daily-build.yml

---

.github/workflows/pull-request.yml

Fix concurrency request cancellation due to same branch name

---

examples/creating-tables-with-query/creating_tables_with_query.bal
examples/limit-clause/limit_clause.description
examples/ordering/ordering.bal

Some changes are invalid according to spec this PR reverts them

Revert spec deviations

---

examples/querying-with-streams/querying_with_streams.bal
examples/querying-with-streams/querying_with_streams.out

Updated the below change thought the bal file
```diff
-type LS stream<string, Error?>;
+type StringStream stream<string, Error?>;
```
```diff
-Input line count:5
-Non blank line count:3
---
+Input line count : 5
+Non blank line count : 3
```

Update querying with streams

---

examples/xml-data-model/xml_data_model.description

Change the description of xml data model

---

gradle.properties

Update dependencies to stable versions

---

examples/xml-operations/xml_operations.description

Revert pr 2550

---

examples/annotations/annotations.bal
examples/annotations/annotations.description
examples/const-and-final/const_and_final.description
examples/documentation/documentation.bal
examples/documentation/documentation.description
examples/enumerations/enumerations.bal
examples/identity/identity.bal
examples/identity/identity.description
examples/identity/identity.out
examples/immutability/immutability.bal
examples/json-type/json_type.bal
examples/match-statement-with-maps/match_statement_with_maps.bal
examples/panics/panics.bal

Fix bbe descriptions and formatting

---

examples/querying-tables/querying_tables.bal
examples/querying-tables/querying_tables.out

Return type of query expression on a table can be a table too

Update querying tables BBE

---

examples/check-semantics/check_semantics.bal
examples/check-semantics/check_semantics.description
examples/retry-transaction-statement/retry_transaction_statement.description
examples/retry-transaction-statement/retry_transaction_statement.metatags
examples/rollback/rollback.bal
examples/rollback/rollback.metatags
examples/transaction-statement/transaction_statement.bal
examples/transaction-statement/transaction_statement.description
examples/transactional-qualifier/transactional_qualifier.description

Fix few bbe descriptions and formatting

---

examples/isolated-variables/isolated_variables.description

Fix BBE description

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ExpressionEvaluationTest.java
devtools-integration-tests/src/test/resources/debug/project-based-tests/breakpoint-tests/Ballerina.toml
devtools-integration-tests/src/test/resources/debug/project-based-tests/evaluation-tests/Ballerina.toml
devtools-integration-tests/src/test/resources/debug/project-based-tests/evaluation-tests/main.bal
devtools-integration-tests/src/test/resources/testng.xml

This PR adds debugger integration test cases for standard libraries related expression evaluation scenarios.
https://github.com/ballerina-platform/ballerina-lang/pull/34775

[Debugger Integration Tests] Add standard libraries related evaluation tests

---

.github/workflows/daily-build.yml

> Ignore devcontainer trivy failures

Ignore devcontainer trivy failures

---

.github/workflows/daily-build.yml

> Remove exit code for devcontainer

Remove exit code for devcontainer

---

gradle.properties

Update dependency versions to stable-versions

---

docs/building-from-source.md

$subject
To provide complete guideline on how to build the distribution from source.

Add building from source guide

---

.github/workflows/daily-build.yml

Avoid counting ballerina updates when we are running tests on it.

Add TEST_MODE_ACTIVE env variable

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralNegativeTest.java

Disable test `testPushPackageWithInvalidAccessToken`

---

.github/workflows/pull-request.yml
gradle.properties

Update lang version

---

gradle.properties

Related release - https://github.com/ballerina-platform/module-ballerina-grpc/releases/tag/v1.2.1

Upgrade the gRPC patch version 1.2.0 -> 1.2.1

---

ballerina-test-automation/installer-test/build.gradle
ballerina-test-automation/test-automation/build.gradle
ballerina-test-automation/update-tool-test/build.gradle
ballerina/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

>Update gradle wrapper version from `6.2` to `7.1`.
>https://github.com/ballerina-platform/ballerina-distribution/issues/2594

Update gradle wrapper version

---

examples/index.json

Change the BBE titles to sentence case. …

Change the BBE Titles to Sentence Case

---

gradle.properties

Update dependency versions for 2201.0.1 release

---

ballerina-test-automation/gradle.properties

Update update-tool version

---

.github/workflows/add_reason_labels.yml

Add reason label workflow

---

pom.xml

Update nexus staging URLs for 1.2.26 release

---

gradle.properties

Update version for email-module

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update OpenAPI patch version

---

gradle.properties

Bump c2c and docker versions

---

gradle.properties

Version update 2201.0.2

---

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.description
examples/http-2-0-server-push/http_2_0_server_push.description
examples/http-compression/http_compression.description
examples/http-cookies/http_cookies.description
examples/http-cors/http_cors.description
examples/http-disable-chunking/http_disable_chunking.description
examples/http-redirects/http_redirects.description

> $subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3158

Update HTTP BBE descriptions

---

examples/tcp-transport-security/tcp_transport_security.description
examples/websocket-basic-sample/websocket_basic_sample.description

$subject.
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/3160

Remove the "example" word from BBE

---

.github/workflows/daily-build.yml

> Run daily build in 2201.0.x branch

Run daily build in 2201.0.x branch

---

.github/workflows/daily-build.yml

> Switch all the jobs patch branch

Switch all the jobs patch branch

---

examples/index.json

Fix small typo of Floating point numbers BBE

---

.github/workflows/daily-build.yml

> Include checkout step for notification job

Include checkout step for notification job

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming.description
examples/grpc-client-streaming/grpc_client_streaming.description
examples/grpc-server-streaming/grpc_server_streaming.description
examples/grpc-simple-with-headers/grpc_simple_with_headers.description
examples/grpc-simple/grpc_simple.description
examples/io-bytes/io_bytes.description
examples/io-csv/io_csv.description
examples/io-json/io_json.description
examples/io-strings/io_strings.description
examples/io-xml/io_xml.description
examples/time-formatting-and-parsing/time_formatting_and_parsing.description
examples/time-utc-and-civil/time_utc_and_civil.description
examples/time-utc/time_utc.description
examples/xslt-transformation/xslt_transformation.description

Related to https://github.com/ballerina-platform/ballerina-dev-website/issues/3154

Improve the description of gRPC, I/O, time, and XSLT BBEs

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming.out
examples/grpc-client-basic-auth/grpc_client.out
examples/grpc-client-bearer-token-auth/grpc_client.out
examples/grpc-client-mutual-ssl/grpc_client.out
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client.out
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client.out
examples/grpc-client-oauth2-password-grant-type/grpc_client.out
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client.out
examples/grpc-client-self-signed-jwt-auth/grpc_client.out
examples/grpc-client-ssl-tls/grpc_client.out
examples/grpc-client-streaming/grpc_client_streaming.out
examples/grpc-server-streaming/grpc_server_streaming.out
examples/grpc-service-basic-auth-file-user-store/grpc_service.out
examples/grpc-service-basic-auth-ldap-user-store/grpc_service.out
examples/grpc-service-jwt-auth/grpc_service.out
examples/grpc-service-mutual-ssl/grpc_service.out
examples/grpc-service-oauth2/grpc_service.out
examples/grpc-service-ssl-tls/grpc_service.out
examples/grpc-simple-with-headers/grpc_simple_with_headers.out
examples/grpc-simple/grpc_simple.out

Fix the Proto to Ballerina BBE link in the gRPC BBEs. …

Fix the Proto to Ballerina BBE Link in the gRPC BBEs

---

.github/workflows/trigger-bbe-generation.yml

> Switch BBE generation to patch branch

Switch BBE generation to patch branch

---

.github/workflows/daily-build.yml
.github/workflows/trigger-bbe-generation.yml

Set daily build for 2201.0.x branch

Set daily build for 2201.0.x branch

---

examples/xml-json-conversion/xml_json_conversion.bal

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2828

Remove parenthesis from the if block

---

gradle.properties

> Update gradle.properties observe version to 1.0.3

Update gradle.properties observe version to 1.0.3

---

examples/c2c-deployment/c2c_deployment.bal
examples/c2c-deployment/c2c_deployment.description
examples/c2c-deployment/c2c_deployment.out

Proof Read the C2C BBE

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync ballerina 1.2.x with release 1.2.27

---

examples/c2c-deployment/c2c_deployment.bal
examples/c2c-deployment/c2c_deployment.description
examples/c2c-deployment/c2c_deployment.out

Add the C2C BBE updates to the patch branch

---

examples/c2c-deployment/c2c_deployment.description
examples/c2c-deployment/c2c_deployment.out

Update the C2C deployment BBE on the master branch. …

Update the C2C Deployment BBE on the Master Branch

---

examples/c2c-deployment/c2c_deployment.description
examples/c2c-deployment/c2c_deployment.out

Update the C2C deployment BBE on the `2201.0.x` branch. …

Update the C2C Deployment BBE on the `2201.0.x` Branch

---

examples/graphql-file-upload/graphql_file_upload.client.out

$subject related to [ballerina-platform/ballerina-standard-library#2838](https://github.com/ballerina-platform/ballerina-standard-library/issues/2838)

Update GraphQL file-upload bbe

---

examples/c2c-deployment/c2c_deployment.out

Update the `c2c_deployment.out`. …

Update the `c2c_deployment.out`

---

gradle.properties

Update lang version rc1.6

---

examples/jdbc-query-operation/jdbc_query_operation.bal
examples/jdbc-query-operation/jdbc_query_operation.out
examples/mysql-query-operation/mysql_query_operation.bal
examples/mysql-query-operation/mysql_query_operation.out

$subject fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2840

Improve sql bbe to include queryRow sample

---

gradle.properties

Update WebSubHub version

---

examples/index.json

Update Basic Auth title case in `index.json`. …

Update Basic Auth Title Case in `index.json`

---

examples/c2c-deployment/c2c_deployment.out

Update `c2c_deployment.out` to test the BBE update workflow. …

Update `c2c_deployment.out` to test the BBE update workflow

---

stdlib-integration-tests/http/tests/http_1_1_passthrough_test.bal

Fix distribution HTTP test failures

---

gradle.properties

Update sql stdlib version to 1.4.x

---

gradle.properties

Update WebSocket, TCP, UDP module timestamp versions

---

stdlib-integration-tests/udp/tests/mock_servers.bal

Fix udp module test failure

---

gradle.properties

Update lang version to 2201.1.0-rc1

---

gradle.properties

Bump c2c version patch versions

---

examples/http-data-binding/http_data_binding.bal
examples/http-data-binding/http_data_binding.client.out
examples/http-data-binding/tests/http_data_binding_test.bal

Refactor HTTP BBEs

---

ballerina/build.gradle

Update cache generation order for standard libraries

---

gradle.properties

Update c2c versions to latest in patch branch

---

gradle.properties

Update lang version `2201.0.3`

---

ballerina/build.gradle
ballerina/lib/run.bat
ballerina/lib/run.sh

> Removing `experimental` tag from ballerina lang via https://github.com/ballerina-platform/ballerina-lang/pull/35835. Removing its usages in distribution.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of …

Remove experimental usages in distribution

---

gradle.properties

Update uuid, os, random modules timestamp versions

---

examples/index.json

Update `Refresh Token` titles to sentence case in BBEs.
> Link(s) to product documentation that addresses the changes of this …

Change sentence case of terminology related to security BBEs

---

examples/index.json

Convert BBE titles to sentence case. …

Convert BBE Titles to Sentence Case

---

build.gradle
gradle.properties

Update c2c to timestamped version

---

examples/regular-expressions/regular_expressions.bal
gradle.properties

Update regex and file modules timestamp versions

---

gradle.properties

Update HTTP to latest timestamp version

---

gradle.properties

Update lang version to 2201.1.0-rc1.2

---

gradle.properties

Update lang version to 2201.1.0-rc1.3

---

gradle.properties

Update lang version to 2201.1.0-rc1.4

---

gradle.properties

Update lang version to 2201.1.0-rc1.5

---

gradle.properties

Update lang version to 2201.1.0-rc1.6

---

gradle.properties

Bump latest c2c timestamp version

---

gradle.properties

Update WebSocket version

---

gradle.properties

Update GraphQL version to the latest timestamp build

---

gradle.properties

Update log, protobuf modules' timestamp versions

---

gradle.properties

Update WebSub/WebSubHub/Email versions

---

gradle.properties

Update Ftp version to latest timestamp build

---

build.gradle
gradle.properties

Add AsyncAPI module to Ballerina Distribution
PR sent to ballerina-release: https://github.com/ballerina-platform/ballerina-release/pull/1891

Add AsyncAPI module

---

gradle.properties

Update xmldata, task and cache modules timestamp versions

---

gradle.properties

Update io, javaArrays, time and xslt modules timestamp versions

---

gradle.properties

Update openAPI version with changes in PR #955 in openapi-tools

---

ballerina/build.gradle

Change extensions.json path

---

ballerina-test-automation/gradle.properties

Bump verisons in installer tests

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync ballerina-1.2.x with release 1.2.28

---

pom.xml

Update nexus staging urls for 1.2.29 release

---

examples/websocket-basic-sample/websocket_basic_sample.bal
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.bal
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.bal
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.bal
examples/websocket-service-mutual-ssl/websocket_service_mutual_ssl.bal
examples/websocket-service-oauth2/websocket_service_oauth2.bal
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.bal

$subject.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2887

Remove isolated keyword from WebSocket BBEs

---

examples/testerina-mocking-objects/testerina_mocking_objects_test.bal

Update Mocking BBE's

---

examples/websub-webhook-sample/websub_webhook_sample.bal

Refactor WebSub BBE

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java
ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java
ballerina-test/src/test/resources/openapi/expected/client.bal
ballerina-test/src/test/resources/openapi/expected/types.bal
ballerina-test/src/test/resources/openapi/expected/utils.bal
ballerina-test/src/test/resources/openapi/openapi_client.yaml

> Currently there is not integration tests available to test the ballerina openapi-tools client generation.
> This PR add an integration test for openapi client generation 
Resolves https://github.com/ballerina-platform/openapi-tools/issues/970
- 
> Ballerina 2201.1.0 RC1

Add integration test for openapi client generation

---

gradle.properties

Update lang version to 2201.1.0-rc1.7

---

examples/graphql-documentation/graphql_documentation.bal
examples/graphql-documentation/graphql_documentation.client.out
examples/graphql-documentation/graphql_documentation.description
examples/graphql-documentation/graphql_documentation.md
examples/graphql-documentation/graphql_documentation.metatags
examples/graphql-documentation/graphql_documentation.server.out
examples/graphql-interfaces/graphql_interfaces.bal
examples/graphql-interfaces/graphql_interfaces.client.out
examples/graphql-interfaces/graphql_interfaces.description
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-interfaces/graphql_interfaces.metatags
examples/graphql-interfaces/graphql_interfaces.server.out
examples/index.json

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2922

Add GraphQL Interfaces and Documentation BBEs

---

gradle.properties

> Updated the stdlibs versions in the AsyncAPI tool and did a timestamped version release, hence updated the released version here

Update AsyncAPI Tool Version

---

gradle.properties

Update ballerinaLangVersion to 2201.1.0-rc1.8

---

gradle.properties

Update email module version

---

ballerina-test-automation/gradle.properties

Update the spec version to 2022R2 in installer tests

---

gradle.properties

Update c2c timestamp to latest

---

gradle.properties

Updated Stdlibs to the latest timestamp

---

gradle.properties

Update ballerinaLangVersion to 2201.1.0-rc1.9

---

ballerina/build.gradle

Change stdlibs resolving order

---

gradle.properties

Update the Stdlib Versions to Latest Timestamp Versions

---

gradle.properties

> Update GraphQL tool version
with following changes
- Update the Ballerina version to 2201.1.0-rc1.12
> Update GraphQL tool version to latest
> Bump tool version to 0.1.0-20220520-101000-1775a7c
> Update GraphQL tool version
- Unit tests 
> Done
> None
> 
Ballerina Version: 2201.1.0-rc1.12
Operating System: Ubuntu 20.04
Java SDK: 11

Update GraphQL tool version

---

project-api-tests/src/test/resources/hierarchical-packages/PackageK/Ballerina.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageM/Ballerina.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageN/Ballerina.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageP/Ballerina.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageR/Ballerina.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageS/Ballerina.toml

> These tests failed due to added warning in the following PR
- https://github.com/ballerina-platform/ballerina-lang/pull/36201
> …

Fix failing 'HierarchicalPackagesTest'

---

examples/index.json

Hide GraphQL Interfaces BBE

---

gradle.properties

> Updated the stdlibs versions in the AsyncAPI tool and did a timestamped version release, hence updated the released version here

Update AsyncAPI version

---

examples/graphql-context/graphql_context.description
examples/graphql-documentation/graphql_documentation.description
examples/graphql-file-upload/graphql_file_upload.description
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.description
examples/graphql-input-types/graphql_input_types.description
examples/graphql-interfaces/graphql_interfaces.description
examples/graphql-mutations/graphql_mutations.description
examples/graphql-returning-service-objects/graphql_returning_service_objects.description
examples/http-client-data-binding/http_client_data_binding.description
examples/http-data-binding/http_data_binding.description
examples/http-error-handling/http_error_handling.description
examples/http-interceptor-error-handling/http_interceptor_error_handling.description
examples/http-interceptors/http_interceptors.description
examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.description
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.description
examples/kafka-consumer-client-poll-consumer-record/kafka_consumer_client_poll_consumer_record.description
examples/kafka-consumer-client-poll-payload/kafka_consumer_client_poll_payload.description
examples/kafka-consumer-service/kafka_consumer_service.description
examples/kafka-producer-transactional/kafka_producer_transactional.description
examples/kafka-producer/kafka_producer.description
examples/nats-basic-pub-sub/nats_basic_pub_sub.description
examples/nats-basic-request-reply/nats_basic_request_reply.description
examples/nats-basic-secure-connection/nats_basic_secure_connection.description

Updated HTTP BBE descriptions

---

gradle.properties

Update grpc timestamp version

---

cache-generator/src/main/java/io/ballerina/gencache/cmd/GenCacheCmd.java

Add extra logs to detect issues related to Ballerina backend

Add extra logs

---

gradle.properties

Bump c2c version for patch branch

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
gradle.properties

Fix identified security vulnerabilities

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Sync Trivy config flags across the versions

---

gradle.properties

Reverts ballerina-platform/ballerina-distribution#2810

Update stdlibs for latest timestamped patch version

---

gradle.properties

$subject related to 2201.1.0 release

Update stdlib versions for UUID version fix

---

gradle.properties

Move stdlibs to stable version

---

gradle.properties

Bump c2c to 2.2.0 release version

---

gradle.properties

> Update the AsyncAPI tool version to 0.1.4

Update AsyncAPI version to 0.1.4

---

gradle.properties

> Update observe module versions

Update observe module versions

---

ballerina/build.gradle
examples/regular-expressions/regular_expressions.bal

Fix regex and xmldata BBEs output verification failure

---

gradle.properties

Update stdlib stable patch versions

---

examples/meta.json

GitHub BBE Base URL changed

---

ballerina/build.gradle

To pack transitive minor version dependencies of Standard Libraries along with the distribution.  
fixes ballerina-platform/ballerina-lang#36047

Pack minor version dependencies of standard libraries

---

.github/workflows/daily-build-2201.0.x.yml
.github/workflows/daily-build.yml

https://github.com/ballerina-platform/ballerina-distribution/issues/2790

Add daily build for both 2201.0.x and master branches

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Fix generating hashes

---

docs/building-from-source.md

Remove the -ing form and update the titles of `Build from source` to sentence case to comply with the Google style guide and to preserve consistency with the other Ballerina documentation components.
> Brief …

Update Tiles of `Build from source`

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal
examples/grpc-client-streaming/grpc_client_streaming_service.bal
examples/grpc-server-streaming/grpc_server_streaming_service.bal
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.bal
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.bal
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.bal
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.bal
examples/grpc-service-oauth2/grpc_service_oauth2.bal
examples/grpc-service-ssl-tls/grpc_service_ssl_tls.bal
examples/grpc-simple-with-headers/grpc_simple_with_headers_service.bal
examples/grpc-simple/grpc_simple_service.bal
gradle.properties

Update descriptor name and remove get desc function

---

.github/workflows/daily-build-2201.0.x.yml
.github/workflows/daily-build-2201.1.x.yml

Currently daily build is running for only `master` and `2201.0.x` branches. We need to run daily build for `2201.1.x` branch as well.

Add 2201.1.x daily build

---

gradle.properties

Update the GraphQL version

---

.github/workflows/daily-build-2201.0.x.yml
.github/workflows/daily-build-2201.1.x.yml
.github/workflows/daily-build.yml

> Fix nightly tags in ballerina and dev container images

Fix nightly tags in ballerina and dev container images

---

gradle.properties

Reverts ballerina-platform/ballerina-distribution#2877

Revert "Update the GraphQL version"

---

.github/workflows/daily-build-2201.0.x.yml
.github/workflows/daily-build-2201.1.x.yml
.github/workflows/daily-build.yml

Fix nightly tag issue

---

examples/hello-world-service/hello_world_service.client.out
examples/hello-world-service/hello_world_service.description
examples/hello-world-service/hello_world_service.md
examples/hello-world-service/hello_world_service.server.out

Update the hello world service BBE MD file. …

Update the `Hello world service` BBE MD File

---

pom.xml

Update staging URLs for release 1.2.31

---

examples/index.json

Update sentence case in index.json
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …

Update sentence case in index.json

---

examples/environment-variables/environment_variables.md
examples/logging-configuration/logging_configuration.bal
examples/logging-configuration/logging_configuration.md
examples/logging-with-context/logging_with_context.bal
examples/logging-with-context/logging_with_context.md
examples/logging/logging.bal
examples/logging/logging.md
examples/random-numbers/random_numbers.md
examples/uuid-generation/uuid_generation.md
examples/uuid-operations/uuid_operations.md

Update Log, OS, UUID, Random BBEs

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync after release 1.2.31

---

build.gradle
gradle.properties

Add constraint standard library

---

.github/workflows/daily-build-2201.0.x.yml
.github/workflows/daily-build-2201.1.x.yml
.github/workflows/daily-build.yml

https://github.com/ballerina-platform/ballerina-distribution/issues/2942
> Link(s) to product documentation that addresses the …

Run daily build only in ballerina-platform

---

ballerina/build.gradle

$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2933
To automate integration tests for releases

Add task to test stdlibs with staging

---

examples/graphql-subscriptions/graphql_subscriptions.bal
examples/graphql-subscriptions/graphql_subscriptions.client.out
examples/graphql-subscriptions/graphql_subscriptions.description
examples/graphql-subscriptions/graphql_subscriptions.md
examples/graphql-subscriptions/graphql_subscriptions.metatags
examples/graphql-subscriptions/graphql_subscriptions.server.out
examples/index.json

Add BBE for GraphQL subscriptions

---

examples/hello-world-service/hello_world_service.bal
examples/hello-world-service/hello_world_service.client.out
examples/hello-world-service/hello_world_service.md
examples/hello-world/hello_world.md
examples/hello-world/hello_world.out
examples/identifiers/identifiers.bal
examples/identifiers/identifiers.out
examples/programs-and-modules/programs_and_modules.bal
examples/programs-and-modules/programs_and_modules.md
examples/programs-and-modules/programs_and_modules.out
examples/variables-and-types/variables_and_types.md
examples/variables-and-types/variables_and_types.out

Update the Hello World and Basics BBEs 

---

examples/strings/strings.bal
examples/strings/strings.md
examples/strings/strings.out

Update BBEs for String Datatype

Update BBEs for String Datatype

---

examples/decimal-type/decimal_type.bal
examples/decimal-type/decimal_type.md
examples/decimal-type/decimal_type.out
examples/floating-point-numbers/floating_point_numbers.bal
examples/floating-point-numbers/floating_point_numbers.md
examples/floating-point-numbers/floating_point_numbers.out
examples/integers/integers.md
examples/integers/integers.out
examples/nil/nil.bal
examples/nil/nil.md
examples/nil/nil.out

Update Basic Datatype BBEs

---

examples/booleans/booleans.bal
examples/booleans/booleans.md
examples/booleans/booleans.out
examples/match-statement/match_statement.bal
examples/match-statement/match_statement.md
examples/match-statement/match_statement.out

> Update BBEs for Conditional Statements

Update BBEs for Conditional Statements

---

examples/langlib-functions/langlib_functions.bal
examples/langlib-functions/langlib_functions.md
examples/langlib-functions/langlib_functions.out

Update Lang Library BBEs

---

examples/configurable-variables/configurable_variables.md
examples/configurable-variables/configurable_variables.out

> Update BBEs in Configurable Variables

Update BBEs in Configurable Variables

---

examples/function-values/function_values.bal
examples/function-values/function_values.md
examples/function-values/function_values.out
examples/functions/functions.bal
examples/functions/functions.md
examples/functions/functions.out

Update the function and function value BBEs

---

examples/arrays/arrays.md
examples/arrays/arrays.out
examples/binary-data/binary_data.bal
examples/binary-data/binary_data.md
examples/binary-data/binary_data.out
examples/structural-typing/structural_typing.bal
examples/structural-typing/structural_typing.md
examples/structural-typing/structural_typing.out

- arrays.md
- binary_data
- structural typing …

Update Types and Typing

---

examples/covariance/covariance.bal
examples/covariance/covariance.md
examples/covariance/covariance.out
examples/type-inference/type_inference.bal
examples/type-inference/type_inference.md
examples/type-inference/type_inference.out

update covariance.md and type_inference.md

---

examples/open-records/open_records.md
examples/optional-fields/optional_fields.md

Update record BBEs

---

examples/foreach-statement/foreach_statement.md
examples/while-statement/while_statement.md

Change md files for iterations bbes

Change md files for iterations bbes

---

examples/ignoring-return-values-and-errors/ignoring_return_values_and_errors.bal
examples/ignoring-return-values-and-errors/ignoring_return_values_and_errors.md

> Changed the md files and bal file to update the BBEs.

Update BBEs for  ignoring return values and errors

---

examples/const-and-final/const_and_final.bal
examples/const-and-final/const_and_final.md
examples/enumerations/enumerations.bal
examples/enumerations/enumerations.md
examples/identity/identity.bal
examples/identity/identity.md
examples/immutability/immutability.bal
examples/immutability/immutability.md

> Change the md files and bal file to update the BBEs.

Update BBEs for mutability and identity

---

examples/check-expression/check_expression.bal
examples/check-expression/check_expression.md
examples/error-handling/error_handling.bal
examples/error-handling/error_handling.md
examples/error-subtyping/error_subtyping.bal
examples/error-subtyping/error_subtyping.md
examples/panics/panics.bal
examples/panics/panics.md
examples/panics/panics.out

> Change the md files and bal file to update the BBEs.

Update md and bal files for error handling bbes

---

examples/defining-classes/defining_classes.md
examples/defining-classes/defining_classes.out
examples/init-return-type/init_return_type.bal
examples/init-return-type/init_return_type.md
examples/init-return-type/init_return_type.out
examples/object/object.md
examples/object/object.out

Update md files for
- object.md
- defining_classed.md
- init_return_type.md
> Link to the PR for changes to the training content …

Update objects category

---

examples/maps/maps.bal
examples/maps/maps.md
examples/records/records.bal
examples/records/records.md

> Change the md files and bal file to update the BBEs.

Update md and bal files for mappings bbes

---

examples/creating-tables-with-query/creating_tables_with_query.bal
examples/creating-tables-with-query/creating_tables_with_query.md
examples/destructuring-records/destructuring_records.bal
examples/destructuring-records/destructuring_records.md
examples/join-clause/join_clause.bal
examples/join-clause/join_clause.md
examples/let-clause/let_clause.bal
examples/let-clause/let_clause.md
examples/limit-clause/limit_clause.bal
examples/ordering/ordering.bal
examples/ordering/ordering.md
examples/query-expressions/query_expressions.bal
examples/query-expressions/query_expressions.md
examples/querying-tables/querying_tables.bal
examples/querying-tables/querying_tables.md
examples/querying-with-streams/querying_with_streams.bal
examples/querying-with-streams/querying_with_streams.md
examples/stream-type/stream_type.bal
examples/stream-type/stream_type.md

Update query expression related BBEs

---

examples/backtick-templates/backtick_templates.md
examples/raw-templates/raw_templates.bal
examples/raw-templates/raw_templates.md
examples/raw-templates/raw_templates.out
examples/xml-templates/xml_templates.bal
examples/xml-templates/xml_templates.md

Update backtick templates related BBEs

---

examples/strands/strands.bal
examples/strands/strands.md
examples/strands/strands.out

Strand annotation changes

---

examples/alternate-wait/alternate_wait.out
examples/asynchronous-function-calls/asynchronous_function_calls.md
examples/asynchronous-function-calls/asynchronous_function_calls.out
examples/inter-worker-failure-propagation/inter_worker_failure_propagation.bal
examples/inter-worker-failure-propagation/inter_worker_failure_propagation.md
examples/inter-worker-failure-propagation/inter_worker_failure_propagation.out
examples/inter-worker-message-passing/inter_worker_message_passing.bal
examples/inter-worker-message-passing/inter_worker_message_passing.md
examples/inter-worker-message-passing/inter_worker_message_passing.out
examples/multiple-wait/multiple_wait.bal
examples/multiple-wait/multiple_wait.md
examples/multiple-wait/multiple_wait.out
examples/named-worker-return-values/named_worker_return_values.bal
examples/named-worker-return-values/named_worker_return_values.md
examples/named-worker-return-values/named_worker_return_values.out
examples/named-workers-and-futures/named_workers_and_futures.bal
examples/named-workers-and-futures/named_workers_and_futures.md
examples/named-workers-and-futures/named_workers_and_futures.out
examples/named-workers/named_workers.bal
examples/named-workers/named_workers.md
examples/named-workers/named_workers.out
examples/sequence-diagrams/sequence_diagrams.bal
examples/sequence-diagrams/sequence_diagrams.md
examples/sequence-diagrams/sequence_diagrams.out
examples/waiting-for-workers/waiting_for_workers.md
examples/waiting-for-workers/waiting_for_workers.out

Update concurrency category BBEs except strands BBE

---

examples/annotations/annotations.bal
examples/annotations/annotations.md
examples/annotations/annotations.out
examples/documentation/documentation.bal
examples/documentation/documentation.md
examples/documentation/documentation.out

Update metadata related BBEs

---

examples/inferring-isolated/inferring_isolated.bal
examples/isolated-methods/isolated_methods.bal
examples/isolated-objects/isolated_objects.bal
examples/isolated-variables/isolated_variables.bal

Update Isolated related BBEs

---

examples/index.json
examples/strands/strands.bal
examples/strands/strands.out

Removed deprecated strand annotation
Partially fix https://github.com/ballerina-platform/ballerina-dev-website/issues/3276
> Link …

[Update 2] Update strands BBE

---

examples/multiple-key-fields/multiple_key_fields.bal
examples/multiple-key-fields/multiple_key_fields.md
examples/multiple-key-fields/multiple_key_fields.out
examples/structured-keys/structured_keys.md
examples/structured-keys/structured_keys.out
examples/table-syntax/table_syntax.bal
examples/table-syntax/table_syntax.md
examples/table-syntax/table_syntax.out

Update Table related BBEs

---

examples/io-bytes/io_bytes.md
examples/io-csv/io_csv.bal
examples/io-csv/io_csv.md
examples/io-json/io_json.bal
examples/io-json/io_json.md
examples/io-strings/io_strings.bal
examples/io-strings/io_strings.md
examples/io-xml/io_xml.bal
examples/io-xml/io_xml.md
examples/time-formatting-and-parsing/time_formatting_and_parsing.md
examples/time-utc-and-civil/time_utc_and_civil.md
examples/time-utc/time_utc.md

Update io and time BBEs

---

examples/controlling-openness/controlling_openness.out

add '$' for bal run command in controlling openness BBE  …

Add '$' for controlling openness BBE

---

examples/inferring-isolated/inferring_isolated.md
examples/isolated-methods/isolated_methods.md
examples/isolated-objects/isolated_objects.md
examples/isolated-variables/isolated_variables.md
examples/lock-statement/lock_statement.md

Update few isolated BBEs

---

examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.bal
examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.md

Update Combining isolated functions and Lock BBE

---

examples/http-access-logs/http_access_logs.server.out
examples/http-caching-client/http_caching_client.server.out

> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3072 …

Remove single quote used in the Caching client BBE

---

examples/converting-from-json-to-user-defined-type/converting_from_json_to_user_defined_type.bal
examples/converting-from-json-to-user-defined-type/converting_from_json_to_user_defined_type.md
examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.bal
examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.md
examples/converting-to-user-defined-type/converting_to_user_defined_type.bal
examples/converting-to-user-defined-type/converting_to_user_defined_type.md
examples/json-numbers/json_numbers.bal
examples/json-numbers/json_numbers.md
examples/json-type/json_type.md
examples/match-statement-with-maps/match_statement_with_maps.bal
examples/match-statement-with-maps/match_statement_with_maps.md
examples/resource-method-typing/resource_method_typing.bal
examples/resource-method-typing/resource_method_typing.md
examples/working-directly-with-json/working_directly_with_json.bal
examples/working-directly-with-json/working_directly_with_json.md

Update Json BBEs

---

examples/dynamic-listener/dynamic_listener.bal
examples/dynamic-listener/dynamic_listener.client.out

> Improve the dynamic listener BBE by including resource path as the second parameter of listener `attach` function. 
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/3157.

Improve dynamic listener BBE

---

examples/index.json

Remove the `-ing` form from all BBE titles. …

Remove the `-ing` form from all BBE titles

---

examples/environment-variables/environment_variables.out
examples/logging-configuration/logging_configuration.out
examples/logging-with-context/logging_with_context.out
examples/logging/logging.out
examples/random-numbers/random_numbers.out
examples/uuid-generation/uuid_generation.out
examples/uuid-operations/uuid_operations.out

Add '$' sign for Log, OS, UUID, Random BBEs

---

examples/check-semantics/check_semantics.bal
examples/check-semantics/check_semantics.md
examples/check-semantics/check_semantics.out
examples/commit-rollback-handlers/commit_rollback_handlers.bal
examples/commit-rollback-handlers/commit_rollback_handlers.md
examples/commit-rollback-handlers/commit_rollback_handlers.out
examples/retry-transaction-statement/retry_transaction_statement.bal
examples/retry-transaction-statement/retry_transaction_statement.md
examples/retry-transaction-statement/retry_transaction_statement.out
examples/rollback/rollback.bal
examples/rollback/rollback.out
examples/transaction-statement/transaction_statement.bal
examples/transaction-statement/transaction_statement.md
examples/transaction-statement/transaction_statement.out
examples/transactional-named-workers/transactional_named_workers.bal
examples/transactional-named-workers/transactional_named_workers.out
examples/transactional-qualifier/transactional_qualifier.bal
examples/transactional-qualifier/transactional_qualifier.md
examples/transactional-qualifier/transactional_qualifier.out

Update transaction related bbes

---

gradle.properties

Bump c2c timestamp

---

examples/receive-email-using-client/receive_email_using_client.bal
examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-client/receive_email_using_client.out
examples/receive-email-using-listener/receive_email_using_listener.bal
examples/receive-email-using-listener/receive_email_using_listener.md
examples/receive-email-using-listener/receive_email_using_listener.out
examples/send-email/send_email.bal
examples/send-email/send_email.md
examples/send-email/send_email.out
examples/websub-webhook-sample/websub_webhook_sample.bal
examples/websub-webhook-sample/websub_webhook_sample.md
examples/websub-webhook-sample/websub_webhook_sample.out

> $subject
Fixes [#3169](https://github.com/ballerina-platform/ballerina-standard-library/issues/3169)

Update WebSub/Email BBEs

---

examples/index.json
examples/xml-from-record-conversion/xml_from_record_conversion.bal
examples/xml-from-record-conversion/xml_from_record_conversion.description
examples/xml-from-record-conversion/xml_from_record_conversion.metatags
examples/xml-from-record-conversion/xml_from_record_conversion.out
examples/xml-to-record-conversion/xml_to_record_conversion.bal
examples/xml-to-record-conversion/xml_to_record_conversion.description
examples/xml-to-record-conversion/xml_to_record_conversion.metatags
examples/xml-to-record-conversion/xml_to_record_conversion.out
gradle.properties

Add new xmldata BBE to the conversion between XML and record

---

examples/io-bytes/io_bytes.out
examples/io-csv/io_csv.out
examples/io-json/io_json.out
examples/io-strings/io_strings.out
examples/io-xml/io_xml.out
examples/time-formatting-and-parsing/time_formatting_and_parsing.out
examples/time-utc-and-civil/time_utc_and_civil.out
examples/time-utc/time_utc.out

Add '$' sign for io and time BBEs

---

ballerina-test-automation/gradle.properties

Bump tool version to 1.3.10

---

examples/index.json
examples/serdes-simple/serdes_simple.bal
examples/serdes-simple/serdes_simple.md
examples/serdes-simple/serdes_simple.metatags
examples/serdes-simple/serdes_simple.out

> $Subject
Related issue: [#3075](https://github.com/ballerina-platform/ballerina-standard-library/issues/3075)
> Link to the PR …

Add serdes bbe

---

examples/graphql-interceptors/graphql_interceptors.bal
examples/graphql-interceptors/graphql_interceptors.client.out
examples/graphql-interceptors/graphql_interceptors.description
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interceptors/graphql_interceptors.metatags
examples/graphql-interceptors/graphql_interceptors.server.out
examples/index.json

>$subject
Fixes: [ballerina-standard-library/#3135](https://github.com/ballerina-platform/ballerina-standard-library/issues/3135)

Add GraphQL Interceptor BBE

---

.github/workflows/daily-build-2201.0.x.yml
.github/workflows/daily-build-2201.1.x.yml
.github/workflows/daily-build.yml

Currently we have 3 daily builds running daily for `master`, `2201.0.x` and `2201.1.x` branches. But in the notification chat branch is not specified when there is a failure.
With this PR, branch name has been passed as a payload for repository dispatch to notify build failure with branch name.
https://github.com/ballerina-platform/ballerina-distribution/issues/2943
> Link(s) to …

Specify branch for daily build failure

---

examples/index.json

Rename `Work over the network` category to `Network libraries`. …

Rename `Work over the network` category to `Network libraries`
