ballerina-platform/src/assembly/dist.xml
> Rename platform unzipped directory
=> Rename platform unzipped directory

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/pom.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml, pom.xml
> 
Include distribution generation with JREs
=> Include distribution generation with JREs 

ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml
> Remove including extension jars in assembly
=> Remove including extension jars in assembly

pom.xml
=> Update JRE artifact version

ballerina-platform/src/assembly/dist.xml, ballerina-runtime/src/assembly/dist.xml, release-notes.md
> Remove ballerina x files from assembly plugin and Include release note template
=> Remove ballerina x files from assembly plugin

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
> Update jre dependency version
=> Update jre dependency version

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/pom.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml, pom.xml
> Include ballerina dependencies
=> Include ballerina dependencies

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, pom.xml, resources/executables/common/broker, resources/executables/common/broker.bat, resources/executables/linux/broker, resources/executables/macos/broker, resources/executables/windows/broker.bat
> Include message broker to ballerina distribution
=> Include message broker to ballerina distribution

pom.xml
=> Include parent in the pom

pom.xml
=> Include version

resources/executables/linux/broker, resources/executables/macos/broker
> Include JRE Home directory for mac, linux brokers
=> Include JRE Home directory for mac, linux brokers

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
> Update versions and ballerinax group ids
=> Update versions and ballerinax group ids

resources/executables/common/broker, resources/executables/linux/broker, resources/executables/macos/broker, resources/executables/windows/broker.bat
> Include passing all the arguments to the broker
=> Include passing all the arguments to the broker

ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml
=> Fix ballerinax group id

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Merge release 0.970.0 beta3

pom.xml
=> Update ballerina parent

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Merge release 0.970.0 beta4

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, pom.xml
> Include ballerina-examples in all the platform distributions
=> Include ballerina-examples in all the platform distributions

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Merge release 0.970.0 beta5

pom.xml
=> Bump parent version

pom.xml
update broker version to 0.1.66
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> update broker version to 0.1.66

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Merge release 0.970.0 beta6

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta7

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta8

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta9

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta10

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta11

resources/executables/linux/composer, resources/executables/macos/composer
> Improve composer script's /bre/lib/*.jar import
=>  Improve composer script's /bre/lib/*.jar import

ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml
> Update examples directory to docs/examples
=> Update examples directory to docs/examples

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta13

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta14

resources/executables/linux/composer, resources/executables/macos/composer, resources/executables/windows/composer.bat
> Fix composer directory changes
=> Fix composer directory changes

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta15

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml
> Include ballerinax api in docs/api/ballerinax
=> Include ballerinax api in docs/api/ballerinax

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta17

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta18

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 beta19

pom.xml
update broker version to 0.970.0.rc1 …
=> Update broker version to 0.970.0.rc1

resources/executables/windows/composer.bat
> Remove if check for ballerina home
=> Remove if check for ballerina home

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0 rc1

pom.xml
Update broker version to 0.970.0
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Update broker version to 0.970.0

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.0

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.970.1

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.972.0

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.973.0

pom.xml
=> Fix kubernetes version

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.974.0

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/pom.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml, pom.xml
> Include ballerinax balo files in platform and run time distributions
=> Include ballerinax balo files in platform and runtime distributions

ballerina-platform/pom.xml
> Add property plugin for docerina
=> Add property plugin for docerina

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.975.0

ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml, pom.xml
> Add permission for ballerinax balo files
=> Add permission for ballerinax balo files

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.976.0

ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml
> Add permission for ballerinax balo files
=> Permission fix

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, pom.xml
> Remove ballerina-examples from platform as its already included
=> Remove ballerina-examples from platform as its already included

resources/executables/common/broker.bat, resources/executables/windows/broker.bat
> Fix broker path issue. resolves https://github.com/ballerina-platform/ballerina-message-broker/issues/440
=> Fix broker path issue

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, pom.xml
> Fix ballerinax docerina generation
=> Fix ballerinax docerina generation

ballerina-platform/pom.xml
> Generate docerina in offline mode
=> Generate docerina in offline mode

resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
> Removing the Java version mandate checks since the distro already shipped with a JVM.
=> Removing the java version check from the distro

ballerina-platform/pom.xml, ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml, ballerina-runtime/pom.xml, pom.xml, resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
=> Release 0.980.0

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.980.1

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.981.0

ballerina-platform/pom.xml, ballerina-runtime/pom.xml, pom.xml
=> Release 0.981.1

resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
Update ballerina scripts for the change from "java.debug" to "BAL_JAVA_DEBUG"
https://github.com/ballerina-platform/ballerina-lang/pull/10462
=> Update ballerina scripts for the change from "java.debug" to "BAL_JAVA_DEBUG"

ballerina-platform/src/assembly/dist-linux.xml, ballerina-platform/src/assembly/dist-macos.xml, ballerina-platform/src/assembly/dist-windows.xml, ballerina-platform/src/assembly/dist.xml
=> Move ballerinax api docs

ballerina/pom.xml
> Update platform artifact name
=> Update platform artifact name

ballerina/pom.xml
=> Improve distribution name

ballerina-runtime/pom.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml, ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml, pom.xml
=> Include jdbc extension to the distribution

ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml, pom.xml
> Include ballerinax examples to the distributions
=> Include ballerinax examples to the distributions

ballerina-runtime/pom.xml, ballerina/pom.xml, pom.xml
=> Release 0.990.0

ballerina-runtime/pom.xml, ballerina/pom.xml, pom.xml
=> Release 0.990.2

ballerina-runtime/pom.xml, ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina-runtime/src/assembly/dist.xml, ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml, pom.xml
> Include AWS Lambda extension to the distribution
=> Include AWS Lambda extension to the distribution

ballerina-runtime/pom.xml, ballerina/pom.xml, pom.xml
=> Release 0.990.3

ballerina/pom.xml
=> Include awslmabda api docs

pom.xml, resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
> Update installer distribution jre
=> Update installer distribution jre

ballerina-runtime/pom.xml, ballerina/pom.xml, pom.xml
=> Sync release branch

pom.xml
> Update distribution dependencies
=> Update distribution dependencies

pom.xml
> Update dependencies to SNAPSHOT versions
=> Update dependencies to SNAPSHOT versions

ballerina-runtime/src/assembly/dist-linux.xml, ballerina-runtime/src/assembly/dist-macos.xml, ballerina-runtime/src/assembly/dist-windows.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, resources/executables/linux/language-server-launcher.sh, resources/executables/macos/language-server-launcher.sh, resources/executables/windows/language-server-launcher.bat
This commit will fix language server launcher scripts not getting updated upon JRE change.
Resolves https://github.com/ballerina-platform/ballerina-lang/issues/15248
=> Add language server launcher scripts into distro repo

ballerina/src/assembly/dist-macos.xml, resources/executables/linux/ballerina, resources/executables/macos/ballerina, resources/executables/windows/ballerina.bat
> Update executables to support jballerina
=> Update executables to support jballerina

ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml, pom.xml
Include docker and k8 extensions
=> Include docker and k8 extensions

pom.xml
=> Include stage repo

resources/executables/linux/language-server-launcher.sh, resources/executables/macos/language-server-launcher.sh
> Fix language server is not starting up
=> Fix language server is not starting up

pom.xml
=>  Include stage 

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml
> Remove filtered option from file copy
=> Remove filtered option from file copy

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml, pom.xml
=> Update dependency versions

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml
> Improve assembly directories
=> Improve assembly directories

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, resources/tools/ballerina-tools-version, resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat, resources/tools/distributions/ballerina-version
> Include ballerina tools artifacts
=> Include ballerina tools artifacts

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml
=> Update cache file name

resources/executables/linux/language-server-launcher.sh, resources/executables/macos/language-server-launcher.sh, resources/executables/windows/language-server-launcher.bat
=> Add trace log flag

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, resources/executables/linux/ballerina, resources/executables/linux/language-server-launcher.sh, resources/executables/macos/ballerina, resources/executables/macos/language-server-launcher.sh, resources/executables/windows/ballerina.bat, resources/executables/windows/language-server-launcher.bat, resources/tools/ballerina-tools-version, resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat
> Include installation structure change for distributions
=> Include installation structure change for distributions

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, resources/tools/bin/ballerina.bat
> Include filtering for ballerina version
=> Include filtering for ballerina version

ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, resources/tools/bin/ballerina
> Fix permission and path issues
=> Fix permission and path issues

resources/tools/bin/ballerina
=> Fix path linux issues

resources/tools/bin/ballerina
=> Fix current path to symlink

resources/tools/bin/ballerina
=> Fix linux shell execution

resources/tools/bin/ballerina
=> Fix mac directory issue

resources/tools/bin/ballerina
=> Fix path shell issue

resources/tools/bin/ballerina
> Set user ballerina version only if exists
=> Set user ballerina version only if exists

resources/tools/bin/ballerina
> Fix directory path check issue
=> Fix directory path check issue

ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist.xml
> Remove docker and k8 packing at ballerina distribution
=> Remove docker and k8 packing at ballerina distribution

resources/executables/windows/ballerina.bat
Fix debugging for windows(add --debug flag) …
=> Fix debugging for windows(add --debug flag)

ballerina/pom.xml, ballerina/src/assembly/dist-zip.xml, pom.xml
=> Include ballerina zip file

ballerina/pom.xml, pom.xml
=> Release 1.0.1

ballerina/pom.xml, pom.xml
=> Release 1.0.3

ballerina/pom.xml, pom.xml
=> Release 1.0.4

ballerina-runtime/pom.xml, ballerina/pom.xml, pom.xml
=> Release 0.990.6

ballerina/pom.xml, pom.xml
=> Release 1.0.5

resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat
=> Update tool client work

resources/tools/bin/ballerina.bat
> Fix windows executable issues
=> Fix windows executable issues

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
=> Seperate out download and unzip functions

ballerina-command/pom.xml, ballerina-command/src/main/java/org/ballerinalang/command/BallerinaCliCommands.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, ballerina/pom.xml, pom.xml
=> Include progress bar

ballerina-command/src/main/java/org/ballerinalang/command/cmd/ListCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/OSUtils.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
=> Fix windows path issue

resources/tools/bin/ballerina.bat
> Fix user home accessing in windows
=> Fix user home accessing in windows

resources/tools/bin/ballerina.bat, resources/tools/scripts/install.bat
=> Fix windows batch script update issue

resources/tools/bin/ballerina.bat, resources/tools/scripts/install.bat
=> Sync master

ballerina-command/src/main/java/org/ballerinalang/command/cmd/FetchCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, pom.xml
=> Update tool fixes

ballerina-command/src/main/java/org/ballerinalang/command/Main.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/Command.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/FetchCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/HelpCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/ListCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/PullCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UseCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/VersionCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/exceptions/CommandException.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ErrorUtil.java, ballerina-command/src/main/java/org/ballerinalang/command/util/OSUtils.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/246
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/247
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/278
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/275
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/279
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/243
=> Fix permission and error messages

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
=> Fix build issue

ballerina-command/src/main/java/org/ballerinalang/command/cmd/ListCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, ballerina-command/src/main/resources/cli-help/ballerina-dist.help, ballerina-command/src/main/resources/cli-help/ballerina-help.help, ballerina-command/src/main/resources/cli-help/ballerina-update.help, resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat
=> Fix update tool bugs

ballerina-command/pom.xml, pom.xml
=> Fix ballerina command version to 0.8.0

resources/tools/bin/ballerina.bat
=> Fix update tool issues

ballerina-command/pom.xml, pom.xml
This reverts commit 5703e2a8295141a8f036df3c8ddd7f442b23af86.
> Revert "fix ballerina command version to 0.8.0"
=> Revert "fix ballerina command version to 0.8.0"

ballerina-command/pom.xml, pom.xml
This reverts commit 69aeb00aa8ea47f1b8523561144b04a57e422b0a. …
=> Revert "Revert "fix ballerina command version to 0.8.0""

ballerina-command/pom.xml
> Skip ballerina command module for release
=> Skip ballerina command module for release

ballerina-command/pom.xml, pom.xml
> Change ballerina command parent
=> Change ballerina command parent

pom.xml
=> Change module order

ballerina-command/pom.xml
=> Include a fix version

ballerina-command/pom.xml
> Enable ballerina command release deploy
=> Enable ballerina command release deploy

ballerina-command/pom.xml, pom.xml
> Separate ballerina command as a project
=> Separate ballerina command as a project

ballerina-command/pom.xml
=> Fix command version

ballerina-command/src/main/resources/META-INF/tool.properties
> Fix command version reference
=> Fix command version reference

ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat, resources/tools/scripts/install, resources/tools/scripts/install.bat
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/290
=> Fix `ballerina update` command should be atomic in nature

ballerina-command/src/main/resources/cli-help/ballerina-remove.help
=> Fix dist-remove name in help text

ballerina-command/src/main/java/org/ballerinalang/command/cmd/ListCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java, ballerina-command/src/main/resources/cli-help/ballerina-dist.help
=> Fix sorting local files

ballerina-command/src/main/java/org/ballerinalang/command/cmd/DistributionCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/FetchCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/ListCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/PullCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UseCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/VersionCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ErrorUtil.java
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/331
=> Improve usage help to specify exact help command

ballerina-command/src/main/java/org/ballerinalang/command/util/OSUtils.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
=> Fix command issues

pom.xml
=> Update dependencies to 1.1.0-beta2

ballerina-command/src/main/java/org/ballerinalang/command/BallerinaCliCommands.java, ballerina-command/src/main/java/org/ballerinalang/command/Main.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/BuildCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/OSUtils.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat, resources/tools/scripts/install.bat
=> Update alert message on new dist versions availability

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/354
=> Use response message instead of code in error messages

ballerina-command/src/main/java/org/ballerinalang/command/cmd/HelpCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/VersionCommand.java
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/380
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/376
=> Fix issues with help command/flag

ballerina/src/assembly/dist-zip.xml
=> Fix tool bugs

ballerina-command/src/main/java/org/ballerinalang/command/cmd/Command.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/HelpCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, ballerina-command/src/main/resources/cli-help/ballerina-dist-pull.help, ballerina-command/src/main/resources/cli-help/ballerina-dist-remove.help, ballerina-command/src/main/resources/cli-help/ballerina-dist-update.help, ballerina-command/src/main/resources/cli-help/ballerina-dist-use.help, ballerina-command/src/main/resources/cli-help/ballerina-update.help
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/255
=> Fix several issues

ballerina-command/src/main/java/org/ballerinalang/command/cmd/BuildCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat, resources/tools/scripts/install.bat
=> Fix few issues related to windows

ballerina-command/src/main/java/org/ballerinalang/command/Main.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/HelpCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/ListCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ErrorUtil.java, ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
$Subject
Fix https://github.com/ballerina-platform/ballerina-distribution/issues/377
=> Improve the error message of dist commands when there is no network connection

ballerina-command/src/main/java/org/ballerinalang/command/cmd/HelpCommand.java, ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java
> Fix checking write permission before remove
=> Fix checking write permission before remove

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
=> Fix duplicate message

resources/tools/bin/ballerina.bat
=> Fix JRE verification in ballerina.bat

ballerina-command/src/main/java/org/ballerinalang/command/cmd/UpdateToolCommand.java
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/397
=> Fix 'ballerina update -h' printing dist-update help

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
$title.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/388
=> Log a message when the distribution is already available

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java, ballerina/src/assembly/dist.xml
=> Ballerina command fixes

resources/tools/COPYRIGHT.txt, resources/tools/LICENSE.txt, resources/tools/PATENTS.txt
> $subject. These docs were taken from the https://github.com/ballerina-platform/ballerina-lang repo
=> Add license, copyright info docs to the zip

ballerina-command/src/main/resources/cli-help/ballerina-dist-remove.help
=> Fix consistency issues in dist-remove help text

ballerina/src/assembly/dist.xml
> Fix awslambda packing in the zip
=> Fix awslambda packing in the zip

pom.xml
=> Bump ballerina command version

ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist-zip.xml, ballerina/src/assembly/dist.xml, pom.xml
> $subject. Depends on https://github.com/ballerinax/docker/pull/329 and https://github.com/ballerinax/kubernetes/pull/453
=> Adding Docker Kubernetes artifacts from nexus

ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java
=> Fix stage url support

ballerina-command/pom.xml, ballerina/pom.xml, pom.xml
=> Release 1.1.1

resources/tools/bin/ballerina, resources/tools/bin/ballerina.bat
> $title. 
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/14276 and https://github.com/ballerina-platform/ballerina-lang/issues/20967
=> Exit the system with the non-zero status code if error occurs

pom.xml
=> Update staging url and versions

ballerina-command/pom.xml, ballerina/pom.xml, pom.xml
=> Merge 1.1.2 release branch

ballerina/src/assembly/dist.xml
=> Fix correct path in dist.xml for ballerina dist

ballerina-test/.github/workflows/main.yml
=> Add GitHub Actions for Push and PRs

ballerina-test/pom.xml, ballerina-test/src/test/java/org/ballerinalang/distribution/test/ArtifactBuildTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestListener.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java, ballerina-test/src/test/resources/docker/hello_world_docker.bal, ballerina-test/src/test/resources/istio/travel_agency_service.bal, ballerina-test/src/test/resources/knative/hello_world_knative.bal, ballerina-test/src/test/resources/kubernetes/hello_world_k8s.bal, ballerina-test/src/test/resources/openshift/hello_world_oc.bal, ballerina-test/src/test/resources/testng.xml, pom.xml
=> Add test cases to check if docker, kubernetes, istio, openshift, knative artifacts are included in the distribution correctly.

ballerina-command/pom.xml, ballerina/pom.xml, pom.xml
=> Release 1.1.3

.github/workflows/main.yml
> The github action workflow was placed on an invalid directory. Moved to the correct directory.
=> Fix github actions build

ballerina-test/pom.xml, pom.xml
=> Bump dependency versions

pom.xml
=> Add https maven repository to ballerina-distribution

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Merge release-1.1.4 with ballerina-1.1.x

pom.xml
=> Add stable version of the ballerina command

ballerina-test/pom.xml, ballerina-test/src/test/java/org/ballerinalang/distribution/test/ArtifactBuildTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestListener.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java, ballerina-test/src/test/resources/docker/hello_world_docker.bal, ballerina-test/src/test/resources/istio/travel_agency_service.bal, ballerina-test/src/test/resources/knative/hello_world_knative.bal, ballerina-test/src/test/resources/kubernetes/hello_world_k8s.bal, ballerina-test/src/test/resources/openshift/hello_world_oc.bal, ballerina-test/src/test/resources/testng.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist-zip.xml, ballerina/src/assembly/dist.xml, pom.xml
=> Import docker,kubernetes and etc artifact tests from ballerina-1.1.x branch.

pom.xml
=> Update stage urls

pom.xml
=> Include https

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync stage with 1.2.x

pom.xml
=> Update staging URLs

pom.xml
=> Update ballerina stage repos and bump the versions

pom.xml
=> Update nexus repo link for ballerina 1.2.2 release

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync ballerina-1.1.x with 1.1.5 release

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync ballerina-1.2.x with the release 1.2.2

gradle.properties
=> Update version to 1.3.0-SNAPSHOT

build.gradle, gradle.properties
=> Add gradle release plugin

build.gradle
=> Add maven local repository to build

build.gradle
=> Update command version

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync stage with 1.2.x branch

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync 1.2.x with 1.2.3 release

ballerina/build.gradle
$subject
https://github.com/ballerina-platform/ballerina-distribution/pull/493
- macOS
- Java 8
- ballerina 1.3.0-SNAPSHOT
=> Correct the docker, k8s, and awslambda example paths

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync stage with ballerina-1.2.x

build.gradle
=> Add staging repos for ballerina lang and ballerinax repos

build.gradle
=> Update staging repos for ballerina lang and ballerinax repos

build.gradle
=> Update staging repos for the 2.0.0-Preview1-M3 release

build.gradle
=> Update socket version to 2.0.0-Preview1-M4

build.gradle
=> Update staging urls for 2.0.0-Preview1-M4 release

examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.bal, examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.description
=> Update JWT BBE for JWK sample

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal, examples/grpc-client-streaming/grpc_client_streaming_service.bal
$Subject
Depends on ballerina-platform/ballerina-lang#23821 being merged to master
=> Updated the examples for Client streaming and Bi directional streaming

examples/http-caching-client/http_caching_client.bal, examples/http-caching-client/http_caching_client.description
This updates BBEs related to the PR https://github.com/ballerina-platform/ballerina-lang/pull/24043
=> Update HTTP Caching BBEs

examples/http-cookies/cookie_server.bal, examples/http-cookies/cookie_server.out, examples/http-cookies/http_client.bal, examples/http-cookies/http_client.out, examples/http-cookies/http_cookies.description, examples/index.json
=> Add a BBE for http cookies

examples/tcp-socket-listener-client/tcp_socket_listener_client.metatags, examples/udp-socket-client/udp_socket_client.bal, examples/udp-socket-client/udp_socket_client.metatags, gradle.properties
$subject and upgrade the socket version
- macOS
- IDEA
- Java 8
- Ballerina 2.0.0-SNAPSHOT
=> Fix socket BBE error messages

ballerina/build.gradle, build.gradle, gradle.properties
> Update distribution versions
=> Update distribution versions

build.gradle
Pack the Ballerina [Data Mapper Compiler Extension](https://github.com/ballerina-platform/module-ballerinax-datamapper) with the Ballerina distribution.
Pack the Ballerina Data Mapper Compiler Extension with the Ballerina distribution.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
JDK 1.8
N/A
=> Add data mapper compiler extension

build.gradle
=> Update datamapper stage

build.gradle
=> Include stable version

ballerina/build.gradle, build.gradle
=> Fix permission issue

ballerina/build.gradle, build.gradle, examples/http-circuit-breaker/http_circuit_breaker.bal, examples/http-circuit-breaker/http_circuit_breaker.metatags, examples/http-failover/http_failover.bal, examples/http-failover/http_failover.metatags, examples/http-load-balancer/http_load_balancer.bal, examples/http-load-balancer/http_load_balancer.metatags, examples/http-retry/http_retry.bal, examples/http-retry/http_retry.metatags, examples/http-timeout/http_timeout.bal, examples/http-timeout/http_timeout.metatags, examples/task-scheduler-appointment/tests/task_scheduler_appointment_test.bal, examples/task-scheduler-timer/task_scheduler_timer.bal, examples/task-scheduler-timer/tests/task_scheduler_timer_test.bal
- Update code to the new syntax
- Enable tests
=> Enable Task and HTTP Resiliency Example Tests

ballerina/build.gradle
> Add functionality to combine docs from various repos.
=> Add combine docs

ballerina/build.gradle
=> Remove mysql bbe from build

examples/http-circuit-breaker/http_circuit_breaker.bal, examples/http-failover/http_failover.bal, examples/http-load-balancer/http_load_balancer.bal, examples/http-retry/http_retry.bal, examples/http-timeout/http_timeout.bal
=> Update comments in http resiliency BBEs

examples/csv-io/csv_io.bal, examples/csv-io/csv_io.description, examples/csv-io/csv_io.metatags
> Added `metatags` file.
> Updated BBE.
=> Update csv-io example with metadata files

examples/crypto/crypto.bal
Add API Doc links in the Crypto BBE. …
=> Add API Doc Links in the Crypto BBE

examples/math-functions/math_functions.bal, examples/math-functions/math_functions.description, examples/math-functions/math_functions.metatags
=> Update math description with metadata files

examples/send-and-receive-emails/send_and_receive_emails.metatags, examples/send-and-receive-emails/send_and_receive_emails_1_smtp.bal, examples/send-and-receive-emails/send_and_receive_emails_2_pop.bal, examples/send-and-receive-emails/send_and_receive_emails_3_imap.bal, examples/send-and-receive-emails/send_and_receive_emails_4_listener.bal, examples/send-and-receive-emails/send_and_receive_emails_4_listener.out
Update BBEs related to Email Connector for Ballerina 2.0 release.
=> Update BBEs for Email Connector for Ballerina 2.0

examples/log-api/log_api.bal, examples/log-api/log_api.out
> Change `__init()` to `init()`
=> Update object initialization in log BBE and update output

examples/object-initializer/object_initializer.bal
Change error.reason to error.message
=> Fix object_initializer for new error syntaxes

examples/all-bbes.json
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/495
https://github.com/ballerina-platform/ballerina-distribution/pull/494
- Ballerina lang 1.3.0-SNAPSHOT
- Java 8
- macOS
=> Enable kafka SASL examples

examples/base-path-and-path/base_path_and_path.bal, examples/base-path-and-path/base_path_and_path.metatags, examples/different-payload-types/different_payload_types.bal, examples/different-payload-types/different_payload_types.metatags, examples/http-access-logs/http_access_logs.metatags, examples/http-caching-client/http_caching_client.bal, examples/http-caching-client/http_caching_client.metatags, examples/http-compression/http_compression.bal, examples/http-compression/http_compression.metatags, examples/http-cors/http_cors.bal, examples/http-cors/http_cors.metatags, examples/http-data-binding/http_data_binding.bal, examples/http-data-binding/http_data_binding.metatags, examples/http-data-binding/tests/http_data_binding_test.bal, examples/http-disable-chunking/http_disable_chunking.bal, examples/http-disable-chunking/http_disable_chunking.metatags, examples/http-disable-chunking/tests/http_disable_chunking_test.bal, examples/http-filters/http_filters.bal, examples/http-filters/http_filters.metatags, examples/http-streaming/http_streaming.bal, examples/http-streaming/http_streaming.metatags, examples/http-trace-logs/http_trace_logs.bal, examples/http-trace-logs/http_trace_logs.metatags, examples/query-path-matrix-param/query_path_matrix_param.bal, examples/query-path-matrix-param/query_path_matrix_param.metatags, examples/restrict-by-media-type/restrict_by_media_type.bal, examples/restrict-by-media-type/restrict_by_media_type.metatags
=> Migrate BBEs for Swan Lake Preview 1

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist-zip.xml, ballerina/src/assembly/dist.xml, pom.xml
=> Include azure functions artifacts for ballerina-1.2.x branch

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina/build.gradle
=> Fix resolving docker,kubernetes,awslambda artifact

ballerina/build.gradle
=> Add all-bbes.json to examples folder

examples/http-cookies/http_cookies.description
=> Add missing '//' in the description

examples/local-transactions-with-handlers/tests/local_transactions_with_handlers_test.bal, examples/local-transactions/tests/local_transactions_test.bal, examples/non-transaction-retry/tests/non_transaction_retry_test.bal, examples/retry-transactions/tests/retry_transactions_test.bal
=> Fix tests related to transaction BBEs

examples/counter-metrics/counter_metrics.bal, examples/counter-metrics/counter_metrics.description, examples/counter-metrics/counter_metrics.metatags, examples/counter-metrics/counter_metrics.server.out, examples/gauge-metrics/gauge_metrics.bal, examples/gauge-metrics/gauge_metrics.description, examples/gauge-metrics/gauge_metrics.metatags, examples/gauge-metrics/gauge_metrics.server.out, examples/tracing/tracing.bal, examples/tracing/tracing.client.out, examples/tracing/tracing.description, examples/tracing/tracing.metatags, examples/tracing/tracing.server.out
=> Make observability bbe compatible with swan lake

examples/json-record-map-conversion/json_record_map_conversion.bal
=> Fix JSON/Record/Map Conversion sample

examples/crypto/crypto.bal, examples/jwt-issue-validate/jwt_issue_validate.bal, examples/jwt-issue-validate/jwt_mock_server.bal, examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal, examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.bal, examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal, examples/secured-client-with-oauth2/secured_client_with_oauth2.bal, examples/url-encode-decode/url_encode_decode.bal
=> Reformat security and access control BBEs

examples/byte-io/byte_io.bal, examples/http-streaming/http_streaming.bal
=> Incorrect annotation in byte io

examples/testerina-data-driven-tests/testerina_data_driven_tests.bal, examples/testerina-group-tests/testerina_group_tests.out
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts of marketing …
=> Update Testerina BBEs

examples/deprecation/deprecation.out
=> Update deprecation BBE test case ouput

ballerina/build.gradle, resources/tools/distributions/ballerina-version
> Rename default packed distribution to short version
=> Rename default packed distribution to short version

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal, examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service_client.bal, examples/grpc-client-streaming/grpc_client_streaming_service.bal, examples/grpc-client-streaming/grpc_client_streaming_service_client.bal, examples/grpc-secured-unary/grpc_secured_unary_service.bal, examples/grpc-secured-unary/grpc_secured_unary_service_client.bal, examples/grpc-server-streaming/grpc_server_streaming_service.bal, examples/grpc-server-streaming/grpc_server_streaming_service_client.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service_client.bal, examples/grpc-unary-non-blocking/grpc_unary_non_blocking_service.bal, examples/grpc-unary-non-blocking/grpc_unary_non_blocking_service_client.bal
Fixed the gRPC BBEs using the error.reason() and fixed the formatting as well
=> Fixed the gRPC BBEs

examples/all-bbes.json, examples/raw-template/raw_template.bal, examples/raw-template/raw_template.description, examples/raw-template/raw_template.metatags, examples/raw-template/raw_template.out
=> Add raw template BBE

examples/all-bbes.json, examples/readonly-objects-and-fields/readonly_objects_and_fields.bal, examples/readonly-objects-and-fields/readonly_objects_and_fields.description, examples/readonly-objects-and-fields/readonly_objects_and_fields.out, examples/readonly-objects-and-fields/tests/readonly_objects_and_fields_test.bal, examples/record-readonly-fields/record_readonly_fields.bal, examples/record-readonly-fields/record_readonly_fields.description, examples/record-readonly-fields/record_readonly_fields.out, examples/record-readonly-fields/tests/record_readonly_fields_test.bal
=> Add BBEs for readonly objects and readonly record/object fields

examples/check/tests/check_test.bal, examples/checkpanic/tests/checkpanic_test.bal, examples/error-handling/error_handling.bal, examples/error-handling/error_handling.description, examples/error-handling/error_handling.out, examples/error-handling/tests/error_handling_test.bal, examples/panic/panic.bal, examples/panic/panic.out, examples/panic/tests/panic_test.bal, examples/trap/trap.bal, examples/trap/trap.description, examples/user-defined-error/tests/user-defined-error.bal, examples/user-defined-error/user_defined_error.bal, examples/user-defined-error/user_defined_error.description, examples/user-defined-error/user_defined_error.out
Fixes
- error handling BBE
- check BBE
- checkpanic BBE
- trap BBE
- user defined error BBE …
=> Fix and align error related BBEs

examples/anonymous-functions/anonymous_functions.bal, examples/anonymous-functions/anonymous_functions.description, examples/function-pointers/function_pointers.bal, examples/function-pointers/function_pointers.description
=> Fix function related BBEs

examples/all-bbes.json, examples/error-handling/error_handling.bal, examples/trap/trap.description, examples/user-defined-error/user_defined_error.bal, examples/user-defined-error/user_defined_error.description
$title.
Fixes suggestions for https://github.com/ballerina-platform/ballerina-distribution/pull/586.
=> Fix suggestions for error BBEs

examples/taint-checking/taint_checking.bal, examples/taint-checking/taint_checking.out
=> Fix taint checking BBE

examples/all-bbes.json, examples/never-type/never_type.bal, examples/never-type/never_type.description, examples/never-type/never_type.metatags, examples/never-type/never_type.out
=> Add BBE for `never` type

examples/byte-io/byte_io.out
byte io output has a small diff
=> fix small change in byte_io output

ballerina/build.gradle
> Include dependencies directory in ballerina zip file
=> Include dependencies directory in ballerina zip file

examples/all-bbes.json
=> Fix including AWS Lambda example

ballerina/build.gradle
> Add testerina mocking BBEs to ignore list
=> Add testerina mocking BBEs to ignore list

examples/table/table.bal, examples/table/table.out
=> Fix table.bal format and output

build.gradle
=> Update the tool version

build.gradle
> Remove data mapper from distribution
=> Remove data mapper from distribution

examples/hello-world-client/hello_world_client.bal, examples/hello-world-service/hello_world_service.bal
=> Update Hello World Samples to simplify the code using 'check' expressions

examples/hello-world-service/hello_world_service.bal
=> Fix long line hello_world_service.bal

pom.xml
> Update Ballerina update tool version
=> Update Ballerina update tool version

pom.xml
=> Update ballerina lang staging repo

pom.xml
=> Update stage repo URLs

build.gradle, gradle.properties
$subject
The above modules reside in:
- https://github.com/ballerina-platform/module-ballerina-encoding
- https://github.com/ballerina-platform/module-ballerina-jwt
- https://github.com/ballerina-platform/module-ballerina-websub
https://github.com/ballerina-platform/ballerina-lang/issues/21313
=> Add jwt, encoding, and websub stdlibs

pom.xml
=> Update versions and stage repo URLs

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Release 1.2.5

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync ballerina-1.2.x with release-1.2.4 and release-1.2.5 branches

pom.xml
=> Update staging URLs and dependency versions

ballerina/pom.xml, ballerina/src/assembly/dist-linux.xml, ballerina/src/assembly/dist-macos.xml, ballerina/src/assembly/dist-windows.xml, ballerina/src/assembly/dist-zip.xml, ballerina/src/assembly/dist.xml, pom.xml
> $subject. Depends on https://github.com/ballerina-platform/ballerina-lang/pull/24671 and https://github.com/ballerina-platform/module-ballerinax-azure.functions/pull/10
=> Include Azure Functions BBE

pom.xml
=> Update staging URL for Azure Functions

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync ballerina-1.2.x with release-1.2.6

ballerina-test/build.gradle, ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java, ballerina/build.gradle, settings.gradle
> Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/628
* $subject
* fix broken test cases(https://github.com/ballerina-platform/ballerina-distribution/issues/628) 
* improve tests to check examples and docs
* Fix gradle build scanning
=> Include kubernetes, openshift, istio, knative, aws lambda API docs and improve testing

ballerina/build.gradle, build.gradle, gradle.properties
$subject
- Pack RabbitMQ stdlib
- Escape the failing JWT BBEs
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
Ballerina swan lake preview 2 snaphsot
=> Pack RabbitMQ standard library

examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal, examples/rabbitmq-consumer-with-data-binding/rabbitmq_consumer_with_data_binding.bal, examples/rabbitmq-consumer-with-qos-settings/rabbitmq_consumer_with_qos_settings.bal, examples/rabbitmq-consumer/rabbitmq_consumer.bal, examples/rabbitmq-producer/rabbitmq_producer.bal, examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal, examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/686
$title
=> Update org-name in RabbitMQ examples

build.gradle
> Update the update tool version
=> Update the update tool version

examples/websocket-cookie/websocket_cookie.bal
=> Make the changes in the websocket cookie BBE

build.gradle
Pack the [Ballerina Data Mapper Compiler Extension](https://github.com/ballerina-platform/module-ballerinax-datamapper) with the Ballerina distribution.
Pack the Ballerina Data Mapper Compiler Extension with the Ballerina distribution.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Add data mapper compiler extension for swan lake preview 2 release

examples/enums/enums.bal, examples/enums/enums.description, examples/enums/enums.out, examples/index.json
Sending a new PR in place of #611 by @irshadnilam, incorporating the suggestions made by @lafernando.
#611
=> Add the updated enums bbe

examples/testerina-mocking-functions/testerina_mocking_functions.description, examples/testerina-mocking-functions/testerina_mocking_functions_main.bal, examples/testerina-mocking-functions/testerina_mocking_functions_test.bal
>Update function mocking BBE with preview2 syntax
=> Update function mocking BBE with preview2 syntax

examples/testerina-mocking-functions/testerina_mocking_functions_test.out, examples/testerina-mocking-objects/testerina_mocking_objects_test.out
> Update mocking bbe out files
=> Update mocking bbe out files

gradle.properties
=> Upgrade rabbitmq version

examples/record-type-reference/record_type_reference.bal
Reverts ballerina-platform/ballerina-distribution#690
It seems, we are following https://jslint.com/ for formatting, in this case, the earlier representation was correct.
=> Revert "Update record_type_reference.bal"

examples/byte-io/byte_io.bal, examples/character-io/character_io.bal, examples/csv-io/csv_io.bal, examples/data-io/data_io.bal, examples/json-csv/json_csv.bal, examples/json-io/json_io.bal, examples/record-io/record_io.bal, examples/xml-io/xml_io.bal
$subject
Remove unnecessary `@tainted` annotations
https://github.com/ballerina-platform/ballerina-lang/pull/24844
=> Remove unnecessary taint checks from io BBEs

build.gradle, gradle.properties
=> Pack xslt standard library

ballerina/build.gradle, ballerina/lib/run.bat, ballerina/lib/run.sh, examples/anonymous-functions/tests/anonymous_functions_test.bal, examples/any-type/tests/any_type_test.bal, examples/anydata-type/tests/anydata_type_test.bal, examples/byte-type/tests/byte_type_test.bal, examples/constants/tests/constants_test.bal, examples/elvis-operator/tests/elvis_operator_test.bal, examples/function-pointers/tests/function_pointers_test.bal, examples/immutable-values/tests/immutable_values_test.bal, examples/record-optional-fields/tests/record_optional_fields_test.bal, examples/type-test-expression/tests/type_test_expression_test.bal, examples/union-type/tests/union_type_test.bal
> Display failed BBEs at the end of testExamples task.
=> Display failed BBEs at the end of testExamples task

ballerina/build.gradle, ballerina/lib/run.bat, ballerina/lib/run.sh
>  Verify the output file of each ballerina example.
=> Add BBE output verification task

examples/anonymous-functions/tests/anonymous_functions_test.bal, examples/any-type/tests/any_type_test.bal, examples/foreach/foreach.bal, examples/foreach/foreach.out, examples/foreach/tests/foreach_test.bal, examples/function-pointers/tests/function_pointers_test.bal, examples/functional-iteration/tests/functional_iteration_test.bal, examples/json-access/tests/json_access_test.bal, examples/local-transactions-with-handlers/tests/local_transactions_with_handlers_test.bal, examples/local-transactions/tests/local_transactions_test.bal, examples/non-transaction-retry/tests/non_transaction_retry_test.bal, examples/optional-type/tests/optional_type_test.bal, examples/retry-transactions/tests/retry_transactions_test.bal, examples/while/tests/while_test.bal, examples/xml-access/tests/xml_access_test.bal, examples/xml-functions/tests/xml_functions_test.bal
=> BBE Test Fixes

.github/workflows/daily-build.yml
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/714
=> Enable GitHub action for daily build

examples/object-assignability/object_assignability.description
Add bullets to the description of the Object Assignability BBE. …
=> Add Bullets to the Object Assignability BBE

examples/nats-basic-client/publisher.bal, examples/nats-basic-client/subscriber.bal, examples/nats-streaming-client/publisher.bal, examples/nats-streaming-client/subscriber.bal, examples/nats-streaming-consumer-with-data-binding/publisher.bal, examples/nats-streaming-consumer-with-data-binding/subscriber.bal, examples/nats-streaming-durable-subscriptions/publisher.bal, examples/nats-streaming-durable-subscriptions/subscriber.bal, examples/nats-streaming-queue-group/publisher.bal, examples/nats-streaming-queue-group/queue-group.bal, examples/nats-streaming-start-position/publisher.bal, examples/nats-streaming-start-position/subscriber.bal
=> Update org-name in NATS examples

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync 1.2.x branch with 1.2.7 release

examples/testerina-assertions/testerina_assertions.bal
Correct function name to assertNotExactEquals
=> Correct function name to assertNotExactEquals

examples/check/check.description, examples/error-handling/error_handling.description, examples/panic/panic.description, examples/user-defined-error/tests/user-defined-error.bal, examples/user-defined-error/user_defined_error.bal, examples/user-defined-error/user_defined_error.out
=> Fix errors BBEs

ballerina/build.gradle, examples/index.json, examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal, examples/mysql-call-stored-procedures/mysql_call_stored_procedures.description, examples/mysql-call-stored-procedures/mysql_call_stored_procedures.metatags, examples/mysql-call-stored-procedures/mysql_call_stored_procedures.out
=> Add mysql stored procedure BBE

examples/index.json, examples/testerina-assertions/testerina_assertions.out, examples/testerina-before-and-after-each/testerina_before_and_after_each.bal, examples/testerina-before-and-after-each/testerina_before_and_after_each.description, examples/testerina-before-and-after-each/testerina_before_and_after_each.out, examples/testerina-before-and-after-groups/testerina_before_and_after_groups.bal, examples/testerina-before-and-after-groups/testerina_before_and_after_groups.description, examples/testerina-before-and-after-groups/testerina_before_and_after_groups.out, examples/testerina-before-and-after-suite/testerina_before_and_after_suite.out, examples/testerina-before-and-after-test/testerina_before_and_after_test.out, examples/testerina-before-each-test/testerina_before_each_test.description, examples/testerina-data-driven-tests/testerina_data_driven_tests.out, examples/testerina-mocking-functions/testerina_mocking_functions.description
> Adds a new BBE for @test:BeforeGroups and @test:AfterGroups annotations
> Updates the @test:BeforeEach @test:AfterEach BBEs
> Fix description of function mocking and other BBEs
=> Update testerina BBEs 

examples/locks/locks.bal, examples/locks/locks.description, examples/locks/locks.out
=> Fix Lock BBEs

examples/raw-template/raw_template.bal
=> Fix raw template BBE

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync 1.2.x branch with 1.2.8 release

build.gradle
=> Fix urls of cache and task stdlibs

examples/index.json
Add the Edit links of the deployment BBEs. …
=> Add the Edit Links of the Deployment BBEs

build.gradle, gradle.properties
=> Add math, jsonutils, xmlutils and log stdlib modules

build.gradle, gradle.properties
=> Add kafka module to distribution 

examples/testerina-assertions/testerina_assertions.description, examples/testerina-before-and-after-each/testerina_before_and_after_each.description, examples/testerina-before-and-after-groups/testerina_before_and_after_groups.description, examples/testerina-before-and-after-suite/testerina_before_and_after_suite.description, examples/testerina-before-and-after-test/testerina_before_and_after_test.description, examples/testerina-data-driven-tests/testerina_data_driven_tests.description, examples/testerina-group-tests/testerina_group_tests.description, examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.description, examples/testerina-mocking-functions/testerina_mocking_functions.description, examples/testerina-mocking-objects/testerina_mocking_objects.description
Change the links in the Function mocking and Object mocking webpages to redirect to 'how to test ballerina code' rather than API docs
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Change Testerina mocking links

examples/meta.json
Add the "meta.json" file to the "/examples" folder. …
=> Add the "meta.json" File to the "/examples" Folder

examples/byte-io/byte_io.bal, examples/data-io/data_io.out
$subject
https://github.com/ballerina-platform/module-ballerina-io/pull/5
- SLP4
- Java 8
- macOS
=> Make I/O BBEs to be compatible with class support

examples/cache/cache.bal, examples/cache/cache.description, examples/cache/cache.out, examples/cache/tests/cache_test.bal, examples/time/tests/time_test.bal, examples/time/time.bal, examples/time/time.description, examples/time/time.out
=> Common Libs BBE Fixes - 1

examples/jwt-issue-validate/tests/jwt_issue_validate_test.bal
=> Fix security BBEs for toString change

examples/create-java-objects/create_java_objects.bal, examples/overloaded-methods-constructors/overloaded_methods_constructors.bal
=> Java-Interop BBE Fixes

ballerina/build.gradle
=> Add kafka examples to outputVerificationIgnoreList

examples/query-action/query_action.out, examples/query-expression-to-stream/query_expression_to_stream.bal, examples/query-expression-to-stream/query_expression_to_stream.out, examples/query-expression-to-table/query_expression_to_table.bal, examples/query-expression-to-table/query_expression_to_table.out, examples/query-expression-to-xml/query_expression_to_xml.bal, examples/query-expression/query_expression.bal, examples/query-expression/query_expression.out, examples/query-join/query_join.bal, examples/query-join/query_join.out
=> Fix query clauses order change

ballerina/build.gradle
$subject migration task is tracked in https://github.com/ballerina-platform/ballerina-distribution/issues/789
=> Ignore object related BBE temporarily

examples/abstract-objects/abstract_objects.bal, examples/any-type/any_type.bal, examples/basic-documentation/basic_documentation.bal, examples/iterable-objects/iterable_objects.bal, examples/log-api/log_api.bal, examples/object-assignability/object_assignability.bal, examples/object-initializer/object_initializer.bal, examples/object-methods/object_methods.bal, examples/object-type-reference/object_type_reference.bal, examples/objects/objects.bal, examples/readonly-objects-and-fields/readonly_objects_and_fields.bal, examples/retry-transactions/retry_transactions.bal, examples/testerina-assertions/testerina_assertions.bal
This is just to fix the build failure due to class/obj change. 
Properly aligning the `class` example wil be done in a separate PR.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Migrate to new class/object defn syntax

ballerina/build.gradle, examples/any-type/any_type.bal, examples/any-type/any_type.out, examples/any-type/tests/any_type_test.bal, examples/anydata-type/anydata_type.out, examples/iterable-objects/iterable_objects.bal, examples/object-type-reference/object_type_reference.bal, examples/range-expressions/range_expressions.bal, examples/readonly-objects-and-fields/readonly_objects_and_fields.bal
Reverts ballerina-platform/ballerina-distribution#790 as fixes are sent in https://github.com/ballerina-platform/ballerina-distribution/pull/791
=> Revert "Ignore object related BBE temporarily"

ballerina/build.gradle
=> Disabling anonymous-objects BBE

examples/cache/cache.description, examples/config-api/config_api.bal, examples/config-api/config_api.description, examples/config-api/config_api.out, examples/config-api/tests/config_api_test.bal, examples/file/file.bal, examples/file/file.out, examples/filepath/filepath.bal, examples/filepath/filepath.description, examples/filepath/tests/filepath_test.bal, examples/log-api/log_api.bal, examples/log-api/log_api.description, examples/log-api/log_api.out, examples/log-api/tests/log_api_test.bal, examples/math-functions/math_functions.bal, examples/math-functions/math_functions.out, examples/strings/strings.bal, examples/strings/strings.description
=> Common Libs BBE Fixes - 2

doc-guidelines.md
Fix issues in the guidelines doc. …
=> Fix Issues in the Guidelines Doc

ballerina/build.gradle
=> Remove log-api BBE from build ignore list

doc-guidelines.md
=> Improve the Doc Guidelines

ballerina/build.gradle
=> Mark ldap docker image start as part of tests

stdlib-integration-tests/index.json
$subject as docker is not enabled presently
=> Disable ldap tests temporarily

examples/file/file.out
=> Update File BBE output with toString change

examples/log-api/log_api.out
=> Update log BBE output with toString change

examples/arrays/arrays.bal, examples/arrays/arrays.out, examples/query-expression/query_expression.bal, examples/query-expression/query_expression.out
> $title to reflect new features and changes added/done.  …
=> Update Arrays and Query Expression BBEs

.github/workflows/daily-build.yml, .github/workflows/main.yml, ballerina-test/src/test/resources/testing-line-length.xml
=> Enable validation tests

ballerina/build.gradle, examples/crypto/tests/crypto_test.bal, examples/secured-service-with-basic-auth/tests/secured_service_with_basic_auth_test.bal
=> Remove security BBEs from build-ignore-list

examples/cache/cache.bal, examples/cache/cache.out, examples/cache/tests/cache_test.bal
=> Update the cache BBE output file

examples/testerina-before-and-after-suite/testerina_before_and_after_suite.bal, examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.out, examples/testerina-mocking-objects/testerina_mocking_objects_test.bal
=> Fix testerina bbe examples

examples/testerina-before-and-after-suite/testerina_before_and_after_suite.bal, examples/testerina-data-driven-tests/testerina_data_driven_tests.bal, examples/testerina-mocking-objects/testerina_mocking_objects_test.bal
Address previous PR's review changes …
=> Address review changes

examples/local-transactions-with-handlers/local_transactions_with_handlers.out, examples/local-transactions/local_transactions.out, examples/retry-transactions/retry_transactions.out
=> Fix transaction related BBE outputs

examples/http-caching-client/http_caching_client.client.out, examples/http-caching-client/http_caching_client.server.out
=> Update HTTP caching client BBE output

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.server.out, examples/response-with-multiparts/response_with_multiparts.bal
=> Fix http bbe

examples/quoted-identifiers/quoted_identifiers.bal, examples/quoted-identifiers/quoted_identifiers.description, examples/quoted-identifiers/quoted_identifiers.out
> Add more information in BBE
- Unit tests 
> Code coverage information
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and platforms on which migration has been tested
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to …
=> Update quoted identifiers BBE

ballerina/build.gradle, stdlib-integration-tests/index.json
=> Include ldap tests in distribution

examples/error-handling-in-single-place/error_handling_in_single_place.bal, examples/error-handling-in-single-place/error_handling_in_single_place.description, examples/error-handling-in-single-place/error_handling_in_single_place.metatags, examples/error-handling-in-single-place/error_handling_in_single_place.out, examples/error-handling-in-single-place/tests/error_handling_in_single_place_test.bal
=> Fix the name of the BBE

examples/send-and-receive-emails/send_and_receive_emails.bal
Fix issues in BBE proposed by Anjana in the PR review https://github.com/ballerina-platform/ballerina-distribution/pull/837 and some other identified issues.
=> Add changes proposed in the PR review

examples/csv-io/csv_io.bal, examples/http-caching-client/http_caching_client.bal, examples/http-client-endpoint/http_client_endpoint.bal, examples/http-cookies/cookie_server.bal, examples/http-filters/http_filters.bal, examples/http-streaming/http_streaming.bal, examples/http-to-websocket-upgrade/http_to_websocket_upgrade.bal, examples/request-with-multiparts/request_with_multiparts.bal, examples/response-with-multiparts/response_with_multiparts.bal, examples/task-scheduler-timer/task_scheduler_timer.description, examples/websocket-cookie/upgrade_service.bal, examples/websub-hub-client-sample/publisher.bal, examples/websub-internal-hub-sample/publisher.bal
Fix object API Docs links in BBEs. …
=> Fix Object API Docs Links in BBEs

examples/error-handling-at-single-place/tests/error_handling_in_single_place_test.bal
=> Update on fail bbe test

stdlib-integration-tests/index.json, stdlib-integration-tests/sql/tests/jdbc-integration-test.bal, stdlib-integration-tests/sql/tests/mysql-integration-test.bal
=> Add SQL connector integration test cases

examples/websocket-cookie/websocket_cookie.bal
Fix an API Docs link in a BBE. …
=> Fix an API Docs Link in a BBE

.github/workflows/daily-build.yml
=> Improve secrets name

examples/modules/modules.bal, examples/modules/modules.description
Change `alias` to `prefix` in the Module BBE. This is a fix for https://github.com/ballerina-platform/ballerina-lang/issues/22481.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Change `alias` to `prefix` in the Module BBE

examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.description, examples/jdbc-execute-operation/jdbc_execute_operation.description, examples/jdbc-query-operation/jdbc_query_operation.description, examples/mysql-batch-execute-operation/mysql_batch_execute_operation.description, examples/mysql-call-stored-procedures/mysql_call_stored_procedures.description, examples/mysql-complex-type-queries/mysql_complex_type_queries.description, examples/mysql-execute-operation/mysql_execute_operation.description, examples/mysql-init-options/mysql_init_options.description, examples/mysql-parameterized-query/mysql_parameterized_query.description, examples/mysql-query-operation/mysql_query_operation.description
Fix the JDBC/MySQL driver path. …
=> Fix the JDBC/MySQL Driver Path

.github/workflows/daily-build.yml, ballerina/build.gradle, build.gradle, settings.gradle
=> Update to jdk 11

.github/workflows/main.yml, build.gradle
=> Update JRE version

examples/config-api/config_api.out
Improve the ".out" file description of the Config BBE. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/20355.
> …
=> Improve the ".out" file Description of the Config BBE

examples/testerina-assertions/testerina_assertions.bal, examples/testerina-before-and-after-suite/testerina_before_and_after_suite.description, examples/testerina-data-driven-tests/testerina_data_driven_tests.bal, examples/testerina-data-driven-tests/testerina_data_driven_tests.description, examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.bal, examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.description, examples/testerina-mocking-functions/testerina_mocking_functions.description, examples/testerina-mocking-objects/testerina_mocking_objects_main.bal, examples/testerina-mocking-objects/testerina_mocking_objects_test.bal
=> Testing BBE Fixes

examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
$subject related to https://github.com/ballerina-platform/module-ballerina-sql/pull/32
=> Migrate BBE for outparameter type

.github/workflows/daily-build.yml, .github/workflows/main.yml
=> Disable bbe example test

examples/index.json
Remove "Observability" BBEs for SLP5. Will be added back in SLP6 via https://github.com/ballerina-platform/ballerina-dev-website/issues/1406.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
=> Remove "Observability" BBEs for SLP5

ballerina/build.gradle, build.gradle
- Add c2c modules to distribution
=> Add c2c modules to distribution

build.gradle, gradle.properties
> $subject
> Pack OpenAPI tool to distribution
> Type “Sent” when you have provided new/updated certification questions, …
=> Pack OpenAPI to distribution

stdlib-integration-tests/http/tests/http_1_1_passthrough_test.bal
=> Fix http passthrough test

ballerina-test/src/test/java/org/ballerinalang/distribution/lengthValidation/LengthValidator.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, examples/url-encode-decode/url_encode_decode.bal, gradle.properties
=> Disable failing tests

stdlib-integration-tests/auth/tests/integration-tests/auth_with_custom_providers_handlers_test.bal, stdlib-integration-tests/auth/tests/integration-tests/auth_without_annotations_test.bal, stdlib-integration-tests/auth/tests/integration-tests/authn_config_inheritance_test.bal, stdlib-integration-tests/auth/tests/integration-tests/authn_config_pattern_test.bal, stdlib-integration-tests/auth/tests/integration-tests/authz_cache_test.bal, stdlib-integration-tests/auth/tests/integration-tests/authz_config_inheritance_test.bal, stdlib-integration-tests/auth/tests/integration-tests/authz_config_pattern_test.bal, stdlib-integration-tests/auth/tests/integration-tests/resource_level_auth_config_test.bal, stdlib-integration-tests/auth/tests/integration-tests/service_level_auth_config_test.bal, stdlib-integration-tests/auth/tests/mock-servers/auth_with_custom_providers_handlers.bal, stdlib-integration-tests/jwt/tests/integration-tests/authn_with_expired_certificate_tests.bal, stdlib-integration-tests/jwt/tests/integration-tests/authn_with_multiple_handlers_tests.bal, stdlib-integration-tests/jwt/tests/integration-tests/authz_tests.bal, stdlib-integration-tests/jwt/tests/integration-tests/signature_validation_tests.bal, stdlib-integration-tests/jwt/tests/integration-tests/token_propagation_tests.bal, stdlib-integration-tests/jwt/tests/mock-servers/token_propagation_basic_auth.bal, stdlib-integration-tests/jwt/tests/mock-servers/token_propagation_disabled.bal, stdlib-integration-tests/jwt/tests/mock-servers/token_propagation_jwt.bal, stdlib-integration-tests/jwt/tests/mock-servers/token_propagation_jwt_reissuing.bal, stdlib-integration-tests/jwt/tests/mock-servers/token_propagation_jwt_reissuing_negative.bal, stdlib-integration-tests/ldap/tests/integration-tests/auth_with_ldap_test.bal, stdlib-integration-tests/oauth2/tests/integration-tests/oauth2_client_test.bal, stdlib-integration-tests/oauth2/tests/integration-tests/oauth2_service_test.bal, stdlib-integration-tests/oauth2/tests/utils.bal
=> Refactor http error type of auth integration tests

examples/index.json
=> Add back missing java arrays example

examples/config-api/config_api.out
Fix a typo in the config API BBE. …
=> Fix a Typo in the config API BBE

build.gradle, gradle.properties
Add FTP module to Ballerina Distribution. Resolves https://github.com/ballerina-platform/module-ballerina-ftp/issues/110
=> Add FTP module to distribution

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina/build.gradle
- Fix azure function version
- Enable test cases
=> Fix azure function tests

examples/object-methods/object_methods.bal, examples/object-type-reference/object_type_reference.bal, examples/object-type/object_type.description
=> Fix typo and removal of few extra lines

examples/deprecation/deprecation.out
=> Fix the output of the "Deprecation" BBE

examples/crypto/crypto.bal, examples/crypto/crypto.description, examples/crypto/crypto.metatags, examples/crypto/crypto.out, examples/crypto/tests/crypto_test.bal, examples/jwt-issue-validate/jwt_issue_validate.bal, examples/jwt-issue-validate/jwt_mock_server.bal, examples/jwt-issue-validate/tests/jwt_issue_validate_test.bal, examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal, examples/secured-client-with-basic-auth/secured_service_with_basic_auth.bal, examples/secured-client-with-jwt-auth/secured_client_with_jwt_auth.bal, examples/secured-client-with-jwt-auth/secured_service_with_jwt_auth.bal, examples/secured-client-with-oauth2/secured_client_with_oauth2.bal, examples/secured-service-with-basic-auth/secured_service_with_basic_auth.bal, examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.bal, examples/secured-service-with-ldap/secured_service_with_ldap.bal, examples/url-encode-decode/url_encode_decode.bal
=> Update and format security BBEs

examples/http-to-websocket-upgrade/http_to_websocket_upgrade.bal, examples/http-to-websocket-upgrade/http_to_websocket_upgrade.out
$subject
fixes: https://github.com/ballerina-platform/module-ballerina-http/issues/97
=> Remove extra information from the Websocket upgrade BBE

examples/basic-https-listener-client/https_client.bal, examples/content-based-routing/content_based_routing.bal, examples/header-based-routing/header_based_routing.bal, examples/hello-world-client/hello_world_client.bal, examples/http-caching-client/http_caching_client.bal, examples/http-circuit-breaker/http_circuit_breaker.bal, examples/http-cookies/http_client.bal, examples/http-failover/http_failover.bal, examples/http-load-balancer/http_load_balancer.bal, examples/http-redirects/http_redirects.bal, examples/http-retry/http_retry.bal, examples/mutual-ssl/ssl_client.bal, examples/passthrough/passthrough.bal
=> Revamp HTTP BBEs with recent changes

examples/maps/maps.bal, examples/maps/maps.out
=> Align maps BBE with mapping-constructor-expression new changes

build.gradle
=> Update c2c version

build.gradle
=> Update update tool version

examples/websocket-cookie/websocket_cookie.bal
Fix the "getCookie" link in the Websocket Cookie BBE. …
=> Fix the "getCookie" Link in the Websocket Cookie BBE

examples/http-client-data-binding/http_client_data_binding.bal, examples/index.json
=> Fix BBE url in index.json

gradle.properties
=> Update websub version

.github/workflows/daily-build.yml, .github/workflows/main.yml, ballerina/build.gradle, examples/crypto/tests/crypto_test.bal, examples/http-to-websocket-upgrade/tests/http_to_websocket_upgrade_test.bal
=> Enable bbe tests

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Release 1.2.9

examples/testerina-assertions/testerina_assertions.bal, examples/testerina-assertions/testerina_assertions.out
Improve BBE for test assertions …
=> Improve BBE for test assertions

examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
> Update BBE with explicitly closing `sql:ProcedureCallResult` in order to release the connection resources.
=> Update MySQL Stored Proc call BBE

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Release 1.2.10

ballerina/build.gradle, examples/task-scheduler-appointment/task_scheduler_appointment.bal, examples/task-service-appointment/task_service_appointment.bal
$Subject
Fixes [#924](https://github.com/ballerina-platform/ballerina-distribution/issues/924)
=> Remove task examples from buildIgnoreList

examples/log-api/log_api.bal
=> Update log bbe with API changes

build.gradle, examples/file/file.bal, examples/file/file.out, examples/filepath/filepath.bal, examples/filepath/filepath.description, examples/filepath/filepath.out, examples/filepath/tests/filepath_test.bal, gradle.properties, stdlib-integration-tests/grpc-secured-unary/tests/constants.bal, stdlib-integration-tests/grpc-service-with-http-proxy-gateway/tests/constants.bal, stdlib-integration-tests/kafka/tests/client_tests.bal, stdlib-integration-tests/sql/tests/jdbc-integration-test.bal
=> Update file BBEs with new API changes

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java, ballerina-test/src/test/resources/openapi/expected/filteredTags.bal, ballerina-test/src/test/resources/openapi/integration-tests/Ballerina.toml, ballerina-test/src/test/resources/openapi/integration-tests/src/openapi-validator-off/openapi-validator-off.bal, ballerina-test/src/test/resources/openapi/integration-tests/src/openapi-validator-off/resources/openapi_validator_off.yaml, ballerina-test/src/test/resources/openapi/integration-tests/src/openapi-validator-on/openapi-validator-on.bal, ballerina-test/src/test/resources/openapi/integration-tests/src/openapi-validator-on/resources/openapi_validator_on.yaml, ballerina-test/src/test/resources/openapi/petstore.bal, ballerina-test/src/test/resources/openapi/petstore.yaml, ballerina-test/src/test/resources/openapi/petstoreTags.yaml, ballerina-test/src/test/resources/testng.xml
On behalf of @lnash94 and duplicate of https://github.com/ballerina-platform/ballerina-distribution/pull/921
> fix #901
> Check all the openAPI artifacts pack to the distribution properly.  
Add tests for the following commands 
- `ballerina openapi -i <openapi contract file>`
- `ballerina openapi -i <openapi contract file> --mode [service]`
- `ballerina openapi -i <openapi contract file> --tags [tags that want to filter]`
- `ballerina openapi -i <ballerina file>`
> Add integration tests for openapi compiler plugin validator enable and disable tasks
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up …
=> Add tests for OpenAPI

ballerina/build.gradle
=> Extract platform dependancies to balo cache

examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal, examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.description, examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal, examples/jdbc-complex-type-queries/jdbc_complex_type_queries.description, examples/jdbc-execute-operation/jdbc_execute_operation.bal, examples/jdbc-execute-operation/jdbc_execute_operation.description, examples/jdbc-init-options/jdbc_init_options.bal, examples/jdbc-init-options/jdbc_init_options.description, examples/jdbc-parameterized-query/jdbc_parameterized_query.bal, examples/jdbc-parameterized-query/jdbc_parameterized_query.description, examples/jdbc-query-operation/jdbc_query_operation.bal, examples/jdbc-query-operation/jdbc_query_operation.description, examples/local-transactions/local_transactions.bal, examples/retry-transactions/retry_transactions.bal, stdlib-integration-tests/sql/tests/jdbc-integration-test.bal
Updates changes as per introduced in https://github.com/ballerina-platform/module-ballerina-java.jdbc/pull/31
=> Migrate jdbc package name change

ballerina/build.gradle
$subject, The test are failing due to changes in stdlib thus didn't look in to them part of Project API migration.
> Link to the …
=> Disable failing stdlib integration tests in dist

ballerina/build.gradle, build.gradle
> Adds dev tools (npm builds) dependencies …
=> Add dev tools repo dependency

examples/file-io/file_io.bal, examples/file-io/file_io.description, examples/file-io/file_io.metatags, examples/file-io/file_io.out, examples/index.json
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/573
Use the new high-level IO APIs.
https://github.com/ballerina-platform/module-ballerina-io/pull/31
- macOS
- Java11
-SLP6
=> Improve I/O BBEs to use new high-level APIs

ballerina/build.gradle
=> Enable c2c libs

build.gradle, examples/file-io/file_io.bal
=> Fix jarray packing and file I/O line legth

ballerina/build.gradle, dist-repo-builder/build.gradle, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java, settings.gradle
=> Add a task to populate platform libs

examples/anonymous-functions/anonymous_functions.out
Note $subject.
Actual output and current `.out` files are different with a new line.
=> Fix anonymous-functions output

ballerina/build.gradle
=> Enable output verification

ballerina/build.gradle, build.gradle, examples/index.json
=> Add BBE for Code to cloud

examples/user-defined-error/user_defined_error.bal
=> Fix BBE compilation error

examples/directory-listener/directory_listener.out
=> Update output with log changes

ballerina/build.gradle, examples/local-transactions-with-handlers/tests/local_transactions_with_handlers.bal, examples/local-transactions/tests/local_transactions_test.bal
> Add tests for `Local Transactions` and `Local Transactions with handlers` BBEs (`Non Transaction Retry` and `Retry Transactions` BBEs already contain tests)
related issue https://github.com/ballerina-platform/ballerina-lang/issues/27169
=> Add tests for transactions BBEs

ballerina/build.gradle
=> Enable verification for few BBEs

ballerina/build.gradle
=> Update bbe ignore list

ballerina/build.gradle, build.gradle, gradle.properties
=> Add dev tools version

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal, examples/grpc-client-streaming/grpc_client_streaming_service.bal, examples/grpc-secured-unary/grpc_secured_unary_service.bal, examples/grpc-server-streaming/grpc_server_streaming_service.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service.bal, examples/grpc-unary-non-blocking/grpc_unary_non_blocking_service.bal, stdlib-integration-tests/grpc-bidirectional-streaming/tests/grpc_bidirectional_streaming_service.bal, stdlib-integration-tests/grpc-client-streaming/tests/grpc_client_streaming_service.bal, stdlib-integration-tests/grpc-secured-unary/tests/grpc_secured_unary_service.bal, stdlib-integration-tests/grpc-server-streaming/tests/grpc_server_streaming_service.bal, stdlib-integration-tests/grpc-service-with-http-proxy-gateway/tests/grpc_chat_service.bal, stdlib-integration-tests/grpc-unary-blocking/tests/grpc_unary_blocking_service.bal, stdlib-integration-tests/grpc-unary-non-blocking/tests/grpc_unary_non_blocking_service.bal, stdlib-integration-tests/index.json
=> fix gRPC BBE and add service descriptor annotation

examples/log-api/log_api.out
=> Update error message output in log bbe

resources/tools/INSTALL.txt
> Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/966
=> Update install text

gradle.properties
=> Update ballerina release version

gradle.properties
> Bump dev tools version.
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if …
=> Bump dev tools version

ballerina/build.gradle
This PR resolves ballerinax jar duplication issue in distribution zip. …
=> Fix ballerinax jar duplication in distribution zip

ballerina/build.gradle, build.gradle
=> Set executable permissions for balo

.github/workflows/pull-request.yml
Update workflows to archive distributions
=> Update workflows to archive distributions

ballerina/build.gradle, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
=> Elevate read permissions of distribution balos

ballerina/build.gradle, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
=> Sync stage

ballerina/build.gradle
=> Remove security BBEs from ignore list

ballerina/build.gradle
=> Enable transactions BBE builds

ballerina/build.gradle, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
$subject, now the build will fail if bir or jar is missing in dist repo. …
=> Add bir cache validation

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, build.gradle, gradle.properties
=> Sync SLP7 release branch

ballerina/build.gradle
=> Exclude lang internal and annotations api docs

ballerina/build.gradle
=> Remove crypto stdlib from ignore list

ballerina/build.gradle
> $subject as it has been disabled during the release
=> Enable MIME and HTTP tests

ballerina/build.gradle, examples/jdbc-batch-execute-operation/tests/jdbc_batch_execute_operation_test.bal, examples/log-api/tests/log_api_test.bal, examples/mysql-batch-execute-operation/mysql_batch_execute_operation.out
=> Remove bbes from validation ignore list

ballerina/build.gradle, build.gradle
- Add azure function Github package support
- Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/64
=> Add azure functions Github packages support

ballerina/build.gradle, build.gradle
- Convert docker artifacts to GitHub packages
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/521
=> Convert docker artifacts to GitHub packages

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, build.gradle, gradle.properties
=> Update OpenAPI version

examples/directory-listener/directory_listener.bal
=> Update directory_listener BBE with service changes

ballerina/build.gradle, devtools-integration-tests/testerina-object-mocking-test/service.bal, devtools-integration-tests/testerina-object-mocking-test/tests/main_test.bal
=> Fix Testerina Object Mocking tests

build.gradle, gradle.properties, stdlib-integration-tests/websocket/tests/web_socket_test.bal
=> Add websocket module to the build

build.gradle, gradle.properties
> $subject
To be merged after [#6 in module-ballerina-graphql](https://github.com/ballerina-platform/module-ballerina-graphql/pull/6) and [#728 in Ballerina Standard Library](https://github.com/ballerina-platform/ballerina-standard-library/pull/728) is merged
=> Add Ballerina GraphQL module to the distribution

.github/workflows/main.yml
=> Add manual trigger for master branch build

examples/dynamic-listener/dynamic_listener.bal, examples/dynamic-listener/dynamic_listener.client.out, examples/dynamic-listener/dynamic_listener.description, examples/dynamic-listener/dynamic_listener.metatags, examples/dynamic-listener/dynamic_listener.server.out, examples/index.json
> Add example for DynamicListener
> Add example for the feature implemented in https://github.com/ballerina-platform/ballerina-lang/pull/27020
> Add an example
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? no
> This is a sample
> https://github.com/ballerina-platform/ballerina-lang/pull/27020
> n/a
> Ballerina slp6
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.
=> Add example for DynamicListener

examples/directory-listener/directory_listener.bal, examples/directory-listener/directory_listener.out
=> Update dir_listener bbe with log changes

gradle.properties
=> Re-order stdlib versions with new levels

examples/log-api/log_api.bal, examples/log-api/log_api.description, examples/log-api/log_api.metatags, examples/log-api/log_api.out, examples/log-api/tests/log_api_test.bal
=> Update log bbe and test cases

examples/tcp-socket-listener-client/tcp_socket_listener.bal
> log API changes to tcp listener integration test
=> log API changes to tcp listener integration test

ballerina/build.gradle, examples/task-scheduler-appointment/task_scheduler_appointment.bal, examples/task-scheduler-timer/task_scheduler_timer.bal, examples/task-service-appointment/task_service_appointment.bal, examples/task-service-timer/task_service_timer.bal, stdlib-integration-tests/task/http_service.bal
=> Update task  BBEs with the latest service type changes

examples/graphql-resources-with-record-values/graphql_resources_with_record_values.bal, examples/graphql-resources-with-record-values/graphql_resources_with_record_values.client.out, examples/graphql-resources-with-record-values/graphql_resources_with_record_values.description, examples/graphql-resources-with-record-values/graphql_resources_with_record_values.metatags, examples/graphql-resources-with-record-values/graphql_resources_with_record_values.out, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.bal, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.client.out, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.description, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.metatags, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.out, examples/index.json, gradle.properties
=> Add graphql BBEs to the Distribution

ballerina-test/src/test/resources/openapi/expected/filteredTags.bal
=> Fix OpenAPI tests issues

ballerina/build.gradle
=> Ignore task-service-timer bbe from validation

examples/byte-io/byte_io.bal, examples/data-io/data_io.bal, examples/json-io/json_io.bal, examples/record-io/record_io.bal, examples/xml-io/xml_io.bal
=> Add log API change to the I/O BBEs

devtools-integration-tests/testerina-object-mocking-test/tests/main_test.bal, examples/tcp-socket-listener-client/tcp_socket_listener.out, stdlib-integration-tests/tcp/tests/callback_servers.bal
> tcp callback_servers test refactored with new HTTP service type syntax
=> tcp test refactored with new HTTP service type syntax

examples/send-and-receive-emails/send_and_receive_emails.bal
=> Update Email module BBE

ballerina/build.gradle
=> Disable security BBEs and integration tests

examples/udp-socket-client/udp_socket_client.bal, examples/udp-socket-client/udp_socket_client.description, examples/udp-socket-client/udp_socket_client.out, stdlib-integration-tests/udp/tests/udp_tests.bal
> udp integration test refactored with the new API changes, and BBE added for connection less udp client
=> udp BBE and test updated

stdlib-integration-tests/transaction/tests/xa_transactions_test.bal
=> Add test for XA transactions

examples/http-caching-client/http_caching_client.bal, examples/http-client-endpoint/http_client_endpoint.bal, examples/http-data-binding/http_data_binding.bal, examples/http-filters/http_filters.bal, examples/http-redirects/http_redirects.bal, examples/https-listener/https_listener.bal, examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal, examples/kafka-consumer-client/kafka_consumer_client.bal, examples/kafka-consumer-group-service/kafka_consumer_group_service.bal, examples/kafka-consumer-service/kafka_consumer_service.bal, examples/query-path-matrix-param/query_path_matrix_param.bal, examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal, examples/rabbitmq-consumer/rabbitmq_consumer.bal, examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal, examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal, examples/response-with-multiparts/response_with_multiparts.bal, examples/restrict-by-media-type/restrict_by_media_type.bal
=> Migrate RabbitMQ & Kafka BBEs

examples/content-based-routing/content_based_routing.bal, examples/different-payload-types/different_payload_types.bal, examples/different-payload-types/different_payload_types.out, examples/header-based-routing/header_based_routing.bal, examples/http-100-continue/http_100_continue.bal, examples/http-compression/http_compression.bal, examples/http-cookies/cookie_server.bal, examples/http-cookies/http_client.bal, examples/http-cookies/http_client.out, examples/http-cors/http_cors.bal, examples/http-streaming/http_streaming.bal, examples/passthrough/passthrough.bal, examples/request-with-multiparts/request_with_multiparts.bal
=> Update HTTP BBEs with new service type changes

examples/udp-socket-client/udp_socket_client.bal, stdlib-integration-tests/udp/tests/udp_tests.bal
> Datagram  record changed to udp:Datagram
=> Errors in udp BBE resolved

examples/ballerina-to-openapi/ballerina_to_openapi.bal, examples/content-based-routing/content_based_routing.bal, examples/different-payload-types/different_payload_types.bal, examples/header-based-routing/header_based_routing.bal, examples/hello-world-service/hello_world_service.bal, examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.bal, examples/http-2-0-server-push/http_2_0_service.bal, examples/http-2-0-server-push/http_client.bal, examples/http-circuit-breaker/http_circuit_breaker.bal, examples/http-failover/http_failover.bal, examples/http-load-balancer/http_load_balancer.bal, examples/http-retry/http_retry.bal, examples/http-timeout/http_timeout.bal, examples/jwt-issue-validate/jwt_mock_server.bal, stdlib-integration-tests/http/tests/http_1_1_passthrough_test.bal, stdlib-integration-tests/http/tests/http_2_0_server_push_test.bal, stdlib-integration-tests/udp/tests/udp_tests.bal
=> Fix std lib tests and bbe migration

build.gradle, examples/index.json, examples/log-api/log_api.bal, examples/log-api/log_api.out, examples/log-api/tests/log_api_test.bal, examples/uuid/uuid.description, examples/uuid/uuid.out, examples/uuid/uuid_functions.bal, gradle.properties
=> Add UUID stdlib related bbe

ballerina/build.gradle, examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.out, examples/jdbc-batch-execute-operation/tests/jdbc_batch_execute_operation_test.bal, examples/mysql-batch-execute-operation/mysql_batch_execute_operation.out
=> Revert "Fix bbe transaction logs"

examples/websocket-basic-sample/websocket_basic_sample.bal, examples/websocket-client/websocket_client.bal, examples/websub-hub-client-sample/subscriber_service.bal, examples/websub-internal-hub-sample/subscriber.bal, examples/websub-remote-hub-sample/subscriber.bal, examples/websub-service-integration-sample/order_mgmt_service.bal, examples/websub-service-integration-sample/subscriber.bal, gradle.properties
=> Update websocket and websub BBEs

examples/local-transactions/local_transactions.out, examples/retry-transactions/retry_transactions.out
=> Fix transaction BBE outputs

ballerina/build.gradle, examples/distributed-transactions/distributed_transactions.description, examples/distributed-transactions/distributed_transactions.metatags, examples/distributed-transactions/initiator.bal, examples/distributed-transactions/initiator.out, examples/distributed-transactions/participant.bal, examples/distributed-transactions/participant.out, examples/index.json
> $title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/27481
=> Add BBE for distributed transactions

build.gradle
- Remove duplicate dependencies
=> Remove duplicate dependencies

examples/anydata-type/anydata_type.bal, examples/table/table.out
=> Reformat BBEs

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java, ballerina-test/src/test/resources/openapi/expected/filteredTags.bal, build.gradle, examples/anydata-type/anydata_type.bal, examples/table/table.out
=> Sync Disable openapi test to master

examples/log-api/log_api.bal, examples/log-api/log_api.out
=> Update log BBE

.github/workflows/main.yml
=> Improve workflow to skip tests

examples/class-definition/class_definition.bal, examples/class-definition/class_definition.description, examples/class-definition/class_definition.out
$title.
Updated to include information about the `init` method and other methods.
=> Update the class definition BBE

.github/workflows/main.yml, .github/workflows/pull-request.yml
1. Fix tests always skipped in the manual trigger for branch build
2. Improve PR builds by dividing into two (Run test BBE task separatly)
=> Improve Build workflows

.github/workflows/main.yml, .github/workflows/pull-request.yml, ballerina/build.gradle, build.gradle, gradle.properties
=> Sync master branch with swan lake preview8 Release

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync after Release 1.2.11

examples/secured-service-with-oauth2/secured_service_with_oauth2.bal
=> Fix OAuth2 service example [Swan Lake]

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync after Release 1.2.12 

ballerina-test/pom.xml, ballerina/pom.xml, pom.xml
=> Sync after Release 1.2.13

ballerina/build.gradle, build.gradle, gradle.properties
=> Include custom jre support

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal, examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal, examples/kafka-consumer-client/kafka_consumer_client.bal, examples/kafka-consumer-group-service/kafka_consumer_group_service.bal, examples/kafka-consumer-service/kafka_consumer_service.bal, examples/kafka-producer-transactional/kafka_producer_transactional.bal, examples/kafka-producer/kafka_producer.bal, examples/nats-basic-client/publisher.bal, examples/nats-basic-client/subscriber.bal, examples/nats-streaming-client/publisher.bal, examples/nats-streaming-client/subscriber.bal, examples/nats-streaming-durable-subscriptions/publisher.bal, examples/nats-streaming-durable-subscriptions/subscriber.bal, examples/nats-streaming-queue-group/publisher.bal, examples/nats-streaming-queue-group/queue-group.bal, examples/nats-streaming-start-position/publisher.bal, examples/nats-streaming-start-position/subscriber.bal, examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal, examples/rabbitmq-consumer/rabbitmq_consumer.bal, examples/rabbitmq-producer/rabbitmq_producer.bal, examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/833
> **NOTE: Do not merge until the examples have passed compiling/building successfully :)**
=> Update messaging examples with latest API and Service changes 

.github/workflows/pull-request.yml, ballerina/build.gradle, gradle.properties
> Include bal command for windows installer distribution
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/27680
=> Disable test execution

build.gradle
=> Bump the ballerinaCommandVersion

ballerina/build.gradle, build.gradle, gradle.properties
> Add Observability Extension Ballerina modules. This should be merged after ballerina-platform/module-ballerinax-prometheus#1, ballerina-platform/module-ballerinax-jaeger#1, ballerina-platform/module-ballerinax-choreo#1
> Package Observability extensions into Ballerina Distribution.
> The three extension modules had been added into the Gradle build so that it will be packaged into the final Ballerina Distribution.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
=> Add Observability Extensions

ballerina/lib/run.sh
=> Fix services not killing in macOS

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, gradle.properties
> Update openapi version and disable the tests with known issue …
=> Update OpenAPI version 

examples/user-defined-error/user_defined_error.bal
=> Fix the syntax change in error-constructor-expr

examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal
=> Fix websocket BBE test

build.gradle, gradle.properties, stdlib-integration-tests/websub/tests/web_sub_test.bal
=> Add websubhub package

examples/cache/cache.bal, examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service_client.bal, examples/grpc-bidirectional-streaming/tests/grpc_bidirectional_streaming_test.bal, examples/grpc-client-streaming/tests/grpc_client_streaming_test.bal, examples/grpc-server-streaming/tests/grpc_server_streaming_test.bal, examples/grpc-unary-non-blocking/tests/grpc_unary_non_blocking_test.bal, examples/hello-world-parallel/tests/hello_world_parallel_test.bal, examples/http-circuit-breaker/http_circuit_breaker.bal, examples/http-failover/http_failover.bal, examples/http-retry/http_retry.bal, examples/http-timeout/http_timeout.bal, examples/http-to-websocket-upgrade/tests/http_to_websocket_upgrade_test.bal, examples/task-scheduler-appointment/task_scheduler_appointment.bal, examples/task-scheduler-appointment/tests/task_scheduler_appointment_test.bal, examples/task-scheduler-timer/task_scheduler_timer.bal, examples/task-scheduler-timer/tests/task_scheduler_timer_test.bal, examples/tracing/tracing.bal, examples/websocket-chat-application/tests/websocket_chat_application_test.bal, examples/websocket-proxy-server/tests/websocket_proxy_server_test.bal, examples/websub-hub-client-sample/publisher.bal, examples/websub-hub-client-sample/subscription_change_client.bal, examples/websub-internal-hub-sample/publisher.bal, examples/websub-remote-hub-sample/hub.bal, examples/websub-remote-hub-sample/publisher.bal
=> Change runtime stdlib to langlib

gradle.properties
=> Update extension versions

examples/time/tests/time_test.bal, examples/time/time.bal, examples/time/time.out
=> Update Time BBE with new API changes

examples/index.json
Add the Observability BBEs back in Swan Lake that were removed via [1].
[1] https://github.com/ballerina-platform/ballerina-distribution/pull/879/files
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Add the Observability BBEs Back in Swan Lake

examples/testerina-data-driven-tests/testerina_data_driven_tests.bal
Comments inside test config need to be avoided until issue https://github.com/ballerina-platform/ballerina-lang/issues/27904 is fixed.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Remove comments out of test Config

examples/local-transactions-with-handlers/local_transactions_with_handlers.bal
> Related to https://github.com/ballerina-platform/ballerina-lang/issues/27569 …
=> Sync marking commit/rollback handler type as isolated

examples/graphql-resources-with-record-values/graphql_resources_with_record_values.server.out, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.server.out
=> Change ballerina Command to bal in GraphQL BBEs

examples/config-api/config_api.out, examples/log-api/log_api.out, examples/random/random.out, examples/uuid/uuid.out
=> Change ballerina Command to bal in Random, Config, Log, and UUID modules

ballerina/build.gradle, resources/tools/INSTALL.txt, resources/tools/README.txt, resources/tools/scripts/install, resources/tools/scripts/install.bat
> Update ballerina command to bal command
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/27680
> Link to the …
=> Update ballerina command to bal command

examples/error-handling-in-single-place/error_handling_in_single_place.bal
> Fix error constructor expression in handling errors in single place bbe …
=> Fix error constructor expression in bbe

examples/async/async.bal, examples/fork/fork.bal, examples/worker-interaction/worker_interaction.bal, examples/workers/workers.bal
=> Fix worker BBE compilation errors

examples/distributed-transactions/initiator.bal
> Sync http config api change in bbe …
=> Sync with http api change

examples/testerina-mocking-functions/testerina_mocking_functions_test.bal
=> Update Function mocking BBE

examples/cache/cache.bal, examples/cache/cache.out, examples/cache/tests/cache_test.bal, examples/task-scheduler-appointment/task_scheduler_appointment.description, examples/task-scheduler-appointment/task_scheduler_appointment.out, examples/task-scheduler-appointment/tests/task_scheduler_appointment_test.bal, examples/task-scheduler-timer/task_scheduler_timer.out, examples/task-scheduler-timer/tests/task_scheduler_timer_test.bal, examples/task-service-appointment/task_service_appointment.description, examples/task-service-appointment/task_service_appointment.out, examples/task-service-timer/task_service_timer.out, stdlib-integration-tests/task/http_service.bal
=> Update cache and task BBEs

examples/immutable-values/immutable_values.bal
=> Fix cloneable tostring conversion failure

examples/any-type/any_type.bal
=> remove math module from any_type.bal

examples/user-defined-error/user_defined_error.bal
=> Format error-constructor-expr bbe

examples/testerina-assertions/testerina_assertions.out, examples/testerina-before-and-after-each/testerina_before_and_after_each.out, examples/testerina-before-and-after-groups/testerina_before_and_after_groups.out, examples/testerina-before-and-after-suite/testerina_before_and_after_suite.out, examples/testerina-before-and-after-test/testerina_before_and_after_test.out, examples/testerina-data-driven-tests/testerina_data_driven_tests.out, examples/testerina-group-tests/testerina_group_tests.out, examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.out, examples/testerina-mocking-functions/testerina_mocking_functions_test.out, examples/testerina-mocking-objects/testerina_mocking_objects_main.bal, examples/testerina-mocking-objects/testerina_mocking_objects_test.out
=> Fix object mocking tests

examples/arrays/arrays.bal, examples/arrays/arrays.out
Array reverse is now inline. Also how to use a key when sorting is not clear in the example. …
=> Update Arrays BBE for slp9

examples/directory-listener/directory_listener.out, examples/file/file.out, examples/filepath/filepath.out, examples/time/time.out
> Update Directory Listener, File, Filepath & Time BBEs with bal command change.
=> Update BBEs with bal command

examples/object-constructor-expression/object_constructor_expression.bal, examples/object-constructor-expression/object_constructor_expression.out
=> Update object constructor BBE

examples/filepath/tests/filepath_test.bal, examples/time/tests/time_test.bal
=> Fix filepath & time BBEs test failure

examples/send-and-receive-emails/send_and_receive_emails.bal, stdlib-integration-tests/email/tests/email_test.bal
=> Update email module related BBEs and tests

examples/graphql-resources-with-record-values/graphql_resources_with_record_values.description, examples/graphql-resources-with-scalar-values/graphql_resources_with_scalar_values.description
=> Add API documentation link in graphql BBEs

examples/functions-with-included-record-parameters/functions_with_included_record_parameters.bal, examples/functions-with-included-record-parameters/functions_with_included_record_parameters.description, examples/functions-with-included-record-parameters/functions_with_included_record_parameters.metatags, examples/functions-with-included-record-parameters/functions_with_included_record_parameters.out, examples/index.json
> $title.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
=> Add a BBE for included record parameter

examples/crypto/crypto.bal, examples/crypto/crypto.out, examples/crypto/tests/crypto_test.bal, examples/jwt-issue-validate/jwt_issue_validate.bal, examples/jwt-issue-validate/tests/jwt_issue_validate_test.bal, examples/url-encode-decode/tests/url_encode_decode_test.bal
=> Fix BBEs of security category

stdlib-integration-tests/task/http_service.bal
=> Fix task test failure

examples/websocket-async-client/websocket_async_client.bal, examples/websocket-async-client/websocket_async_client.out, examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal, examples/websocket-basic-sample/websocket_basic_sample.bal, examples/websocket-basic-sample/websocket_basic_sample.out, examples/websocket-chat-application/tests/websocket_chat_application_test.bal, examples/websocket-chat-application/websocket_chat_application.bal, examples/websocket-chat-application/websocket_chat_application.out, examples/websocket-proxy-server/tests/websocket_proxy_server_test.bal, examples/websocket-proxy-server/websocket_proxy_server.bal, examples/websocket-proxy-server/websocket_proxy_server.out, examples/websocket-sync-client/websocket_sync_client.bal, examples/websocket-sync-client/websocket_sync_client.out, stdlib-integration-tests/websocket/tests/web_socket_test.bal
=> Fix websocket related BBEs

ballerina/build.gradle
=> Remove websocket BBEs from ignore list

examples/websocket-chat-application/tests/websocket_chat_application_test.bal, examples/websocket-proxy-server/tests/websocket_proxy_server_test.bal
=> Fix failing ws tests

examples/websocket-chat-application/tests/websocket_chat_application_test.bal, examples/websocket-proxy-server/tests/websocket_proxy_server_test.bal
=> Fix compilation errors in ws BBE tests

examples/retry-transactions/retry_transactions.bal
=> Make transaction handlers isolated in Retry Transactions BBE

examples/taint-checking/taint_checking.bal, examples/taint-checking/taint_checking.out
=> Use predeclared lang.string lib in taint analysis BBE

examples/jwt-issue-validate/jwt_mock_server.bal
=> Update mock JWK server for BBEs

devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTest.java, devtools-integration-tests/src/test/resources/central/projectSnapshot/Ballerina.toml, devtools-integration-tests/src/test/resources/central/projectSnapshot/Package.md, devtools-integration-tests/src/test/resources/central/projectSnapshot/main.bal
=> Add tests to push and pull pre release versions to central

examples/config-api/config_api.out, examples/uuid/uuid.bal
=> Handle toString error in UUID BBE

stdlib-integration-tests/http/tests/http_1_1_passthrough_test.bal, stdlib-integration-tests/http/tests/http_2_0_server_push_test.bal, stdlib-integration-tests/mime/tests/mime_test.bal
=> Fix http/mime integration tests

stdlib-integration-tests/auth/tests/auth_test.bal
=> Disable basic auth integration tests

examples/strings/strings.bal, examples/strings/strings.out
=> Update strings BBE with includes method

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.bal, examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.bal, examples/kafka-consumer-group-service/kafka_consumer_group_service.bal, examples/kafka-consumer-service/kafka_consumer_service.bal, examples/kafka-producer/kafka_producer.bal
=> Update examples with the latest changes

build.gradle, gradle.properties
Config stdlib is deprecated please use https://ballerina.io/swan-lake/learn/by-example/configurable.html instead
=> Remove config stdlib

examples/counter-metrics/counter_metrics.bal, examples/counter-metrics/counter_metrics.client.out, examples/counter-metrics/counter_metrics.description, examples/counter-metrics/counter_metrics.server.out, examples/counter-metrics/tests/counter_metrics_test.bal, examples/gauge-metrics/gauge_metrics.bal, examples/gauge-metrics/gauge_metrics.client.out, examples/gauge-metrics/gauge_metrics.description, examples/gauge-metrics/gauge_metrics.server.out, examples/gauge-metrics/tests/gauge_metrics_test.bal, examples/tracing/tracing.bal, examples/tracing/tracing.description, examples/tracing/tracing.server.out
> Update Observability BBEs for SLP9
=> Update Observability BBEs for SLP9

ballerina/build.gradle
=> Fix typos of ignore list

ballerina/build.gradle
Reverts ballerina-platform/ballerina-distribution#1191
=> Revert "Fix typos of ignore list"

examples/tcp-listener/tcp_listener.bal
> Fix error in tcp_listener BBE
=> Fix error in tcp_listener BBE

examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal, examples/secured-client-with-bearer-token-auth/secured_client_with_bearer_token_auth.bal, examples/secured-client-with-oauth2-client-credentials-grant-type/secured_client_with_oauth2_client_credentials_grant_type.bal, examples/secured-client-with-oauth2-direct-token-type/secured_client_with_oauth2_direct_token_type.bal, examples/secured-client-with-oauth2-password-grant-type/secured_client_with_oauth2_password_grant_type.bal, examples/secured-client-with-self-signed-jwt-auth/secured_client_with_self_signed_jwt_auth.bal, examples/secured-client-with-self-signed-jwt-auth/secured_client_with_self_signed_jwt_auth.metatags
=> Refactor access control BBEs

examples/content-based-routing/content_based_routing.bal, examples/content-based-routing/tests/content_based_routing_test.bal, examples/header-based-routing/header_based_routing.bal, examples/header-based-routing/header_based_routing.server.out, examples/header-based-routing/tests/header_based_routing_test.bal, examples/http-circuit-breaker/http_circuit_breaker.bal, examples/http-circuit-breaker/http_circuit_breaker.server.out, examples/http-circuit-breaker/tests/http_circuit_breaker_test.bal, examples/http-failover/http_failover.bal, examples/http-failover/tests/http_failover_test.bal, examples/http-load-balancer/http_load_balancer.bal, examples/http-load-balancer/tests/http_load_balancer_test.bal, examples/http-retry/http_retry.bal, examples/http-retry/http_retry.server.out, examples/http-retry/tests/http_retry_test.bal, examples/http-timeout/http_timeout.bal, examples/http-timeout/http_timeout.server.out, examples/http-timeout/tests/http_timeout_test.bal, examples/passthrough/passthrough.bal
Fix HTTP Routing and Resiliency Examples
=> Fix HTTP BBE failures

examples/http-cors/http_cors.description
=> Add missing spaces

examples/byte-io/byte_io.bal
=> Minor usability change to the I/O BBE

examples/byte-io/byte_io.bal, examples/csv-io/csv_io.bal, examples/text-io/text_io.bal
=> Enable io:Error? return to the I/O streams

examples/error-match-statement/error_match_statement.bal, examples/error-match-statement/error_match_statement.description, examples/error-match-statement/error_match_statement.out, examples/error-match-statement/tests/error_match_statement_test.bal, examples/index.json, examples/mapping-match-statement/mapping_match_statement.bal, examples/mapping-match-statement/mapping_match_statement.description, examples/mapping-match-statement/mapping_match_statement.out, examples/mapping-match-statement/tests/mapping_match_statement_test.bal, examples/tuple-match-statement/tests/tuple_match_statement_test.bal, examples/tuple-match-statement/tuple_match_statement.bal, examples/tuple-match-statement/tuple_match_statement.description, examples/tuple-match-statement/tuple_match_statement.out
=> Enable match-stmt related BBEs

examples/access-mutate-java-fields/access_mutate_java_fields.bal, examples/create-java-objects/create_java_objects.bal, examples/invoke-java-methods/invoke_java_methods.bal, examples/java-arrays/java_arrays.bal, examples/java-exceptions/java_exceptions.bal, examples/java-varargs/java_varargs.bal, examples/overloaded-methods-constructors/overloaded_methods_constructors.bal
Related Issue: https://github.com/ballerina-platform/ballerina-lang/issues/28034 …
=> Change the `java` langlib module name to `jballerina.java`

stdlib-integration-tests/index.json
Temporary disable grpc integration tests
=> Disable gRPC integration test

build.gradle, examples/java-arrays/java_arrays.bal, gradle.properties
=> Fix java.arrays resolution and the BBE

examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal, examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.out, examples/jdbc-batch-execute-operation/tests/jdbc_batch_execute_operation_test.bal, examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal, examples/jdbc-complex-type-queries/jdbc_complex_type_queries.out, examples/jdbc-complex-type-queries/tests/jdbc_complex_type_queries.bal, examples/jdbc-execute-operation/jdbc_execute_operation.bal, examples/jdbc-execute-operation/jdbc_execute_operation.out, examples/jdbc-init-options/jdbc_init_options.bal, examples/jdbc-init-options/jdbc_init_options.out, examples/jdbc-parameterized-query/jdbc_parameterized_query.bal, examples/jdbc-parameterized-query/jdbc_parameterized_query.out, examples/jdbc-query-operation/jdbc_query_operation.bal, examples/jdbc-query-operation/jdbc_query_operation.out, examples/mysql-batch-execute-operation/mysql_batch_execute_operation.out, examples/mysql-batch-execute-operation/tests/mysql_batch_execute_operation_test.bal, examples/mysql-call-stored-procedures/mysql_call_stored_procedures.out, examples/mysql-call-stored-procedures/tests/mysql_call_stored_procedures_test.bal, examples/mysql-complex-type-queries/mysql_complex_type_queries.out, examples/mysql-complex-type-queries/tests/mysql_complex_type_queries_test.bal, examples/mysql-execute-operation/mysql_execute_operation.out, examples/mysql-execute-operation/tests/mysql_execute_operation_test.bal, examples/mysql-init-options/mysql_init_options.out, examples/mysql-init-options/tests/mysql_init_options_test.bal, examples/mysql-parameterized-query/mysql_parameterized_query.out, examples/mysql-parameterized-query/tests/mysql_parameterized_query_test.bal, examples/mysql-query-operation/mysql_query_operation.out, examples/mysql-query-operation/tests/mysql_query_operation_test.bal
=> Fix database BBEs

examples/url-encode-decode/tests/url_encode_decode_test.bal
=> Fix tests of security BBEs

devtools-integration-tests/src/test/java/org/ballerina/devtools/utils/TestUtils.java
> Change test ballerina command to bal
=> Change test ballerina command to bal

examples/send-and-receive-emails/send_and_receive_emails.bal, examples/tcp-listener/tcp_listener.bal
=> Reduce code line length max to 80

examples/csv-io/csv_io.bal, examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal, examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service_client.bal, examples/grpc-client-streaming/grpc_client_streaming_service.bal, examples/grpc-client-streaming/grpc_client_streaming_service_client.bal, examples/grpc-secured-unary/grpc_secured_unary_service.bal, examples/grpc-secured-unary/grpc_secured_unary_service_client.bal, examples/grpc-server-streaming/grpc_server_streaming_service.bal, examples/grpc-server-streaming/grpc_server_streaming_service_client.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service_client.bal, examples/text-io/text_io.bal
=> Fix I/O and gRPC exceeded length

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
=> Fix issue with OpenAPI test 

examples/websocket-proxy-server/websocket_proxy_server.bal
=> Fix line lengths in websocket BBEs

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.bal, examples/http-2-0-server-push/http_client.bal
=> Fix line lengths in HTTP BBEs

examples/websocket-async-client/websocket_async_client.bal, examples/websocket-basic-sample/websocket_basic_sample.bal, examples/websocket-proxy-server/websocket_proxy_server.bal
=> Fix websocket related BBE comments

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service_client.bal, examples/grpc-server-streaming/grpc_server_streaming_service_client.bal
=> Minor fix to the gRPC bidi and server streaming clients

examples/proto-to-ballerina/proto_to_ballerina.out
=> Change ballerina->bal in gRPC proto to Ballerina

examples/arrays/arrays.bal, examples/basic-https-listener-client/https_client.bal, examples/distributed-transactions/initiator.bal, examples/error-handling-in-single-place/error_handling_in_single_place.bal, examples/error-match-statement/error_match_statement.bal, examples/header-based-routing/header_based_routing.bal, examples/mapping-match-statement/mapping_match_statement.bal, examples/mutual-ssl/ssl_client.bal
=> Fix long lines in BBEs

devtools-integration-tests/src/test/resources/debug/project-based-tests/service-tests/tests/hello_service_test.bal
=> Fix dev tools integration test

examples/java-arrays/java_arrays.bal
=> Fix java.arrays org ballerina->ballerinax

stdlib-integration-tests/sql/tests/jdbc-integration-test.bal
=> Update jdbc import

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java
=> Skip debug tests

examples/nats-streaming-queue-group/queue-group.bal
=> Fix NATS BBE failure

ballerina/build.gradle
=> Remove security modules from exclude list

devtools-integration-tests/src/test/resources/debug/single-file-tests/hello_service.bal
This PR will fix service debug test in distribution.
=> Fix service debug test

examples/hello-world-client/hello_world_client.bal, examples/hello-world-parallel/tests/hello_world_parallel_test.bal, examples/hello-world-service/tests/hello_world_service_test.bal, examples/http-100-continue/tests/http_100_continue_test.bal, examples/http-access-logs/tests/http_access_logs_test.bal, examples/http-cors/tests/http_cors_test.bal
=> Fix BBE compiler failures

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java
This PR will enable ServiceDebugTest.
=> Enable service debug test

.github/workflows/pull-request.yml
=> disable tests

examples/secured-service-with-basic-auth-ldap-user-store/secured_service_with_basic_auth_ldap_user_store.bal
=> Fix API change of LDAP config

devtools-integration-tests/src/test/resources/testng.xml
=> Disable Central Test

examples/index.json
=> Remove websub bbes from docs

examples/log-api/tests/log_api_test.bal
Fix log_api_test with the proper mock function objects …
=> Fix log_api_test

ballerina/build.gradle, examples/any-type/tests/any_type_test.bal, examples/async/tests/async_test.bal, examples/dynamic-listener/dynamic_listener.bal, examples/fail/tests/fail_test.bal, examples/foreach/foreach.bal, examples/function-pointers/tests/function_pointers_test.bal, examples/modules/modules.bal, examples/optional-type/tests/optional_type_test.bal, examples/while/tests/while_test.bal, examples/worker-interaction/tests/worker_interaction_test.bal, examples/workers/tests/worker_test.bal, examples/xml-attributes/tests/xml_attributes_test.bal
=> Fix several BBEs and tests

examples/local-transactions/local_transactions.bal, examples/retry-transactions/retry_transactions.bal, examples/xa-transactions/xa_transactions.bal
=> Fix transaction BBEs

examples/counter-metrics/counter_metrics.description, examples/counter-metrics/counter_metrics_config.out, examples/counter-metrics/counter_metrics_config.toml, examples/gauge-metrics/gauge_metrics.description, examples/gauge-metrics/gauge_metrics_config.out, examples/gauge-metrics/gauge_metrics_config.toml, examples/tracing/tracing.description, examples/tracing/tracing_config.out, examples/tracing/tracing_config.toml
> Remove `Config.toml` files from observability BBEs
=> Remove Config.toml files from observability BBEs

examples/ballerina-to-openapi/tests/ballerina_to_openapi_test.bal
=> Fix ballerina-to-openapi BBE test

ballerina/build.gradle, examples/local-transactions-with-handlers/tests/local_transactions_with_handlers.bal, examples/local-transactions/tests/local_transactions_test.bal, examples/non-transaction-retry/tests/non_transaction_retry_test.bal, examples/retry-transactions/tests/retry_transactions_test.bal, examples/xa-transactions/tests/xa_transactions_test.bal
Fix and enable transaction BBE tests mentioned in https://github.com/ballerina-platform/ballerina-distribution/issues/1242.
=> Fix and enable transaction BBE tests

examples/counter-metrics/counter_metrics.description, examples/gauge-metrics/gauge_metrics.description, examples/tracing/tracing.description
> Change the learn page link in observability BBEs
=> Change the learn page link in observability BBEs

examples/csv-io/csv_io.out, examples/grpc-secured-unary/grpc_secured_unary_service.bal, examples/grpc-secured-unary/grpc_secured_unary_service.out, examples/grpc-secured-unary/grpc_secured_unary_service_client.bal, examples/grpc-secured-unary/grpc_secured_unary_service_client.out, examples/json-io/json_io.out
=> Fix gRPC BBE config path and ballerina->bal change

examples/hello-world-service/hello_world_service.bal
=> Simplify the service sample

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal, examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service_client.bal, examples/grpc-client-streaming/grpc_client_streaming_service.bal, examples/grpc-client-streaming/grpc_client_streaming_service_client.bal, examples/grpc-server-streaming/grpc_server_streaming_service.bal, examples/grpc-server-streaming/grpc_server_streaming_service_client.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service_client.bal
=> Fix grpc samples with updated syntax

gradle.properties
=> Update stdlib and ballerina lang versions

ballerina/build.gradle, stdlib-integration-tests/auth/tests/auth_test.bal, stdlib-integration-tests/auth/tests/resources/openldap/bootstrap.ldif
=> Update auth integration tests for LDAP user store

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, build.gradle, gradle.properties
=> Remove SNAPSHOT from versions

examples/task-scheduler-appointment/task_scheduler_appointment.bal, examples/task-scheduler-timer/task_scheduler_timer.bal
=> Fix out verification failure of task scheduler BBE

examples/taint-checking/taint_checking.description, examples/taint-checking/taint_checking.out
=> Update taint checking example with --taint-check

build.gradle, gradle.properties
=> Update OAuth2 naming convention

examples/anydata-type/anydata_type.description
Fix the "next/previous" links of the "Anydata BBE". …
=> Fix the "next/previous" Links of the "Anydata BBE"

gradle.properties
=> Release swan lake alpha1

examples/log-api/log_api.bal, examples/log-api/log_api.out
=> Update log BBE with json support example

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, ballerina/build.gradle, build.gradle, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java, gradle.properties
> Rename balo to bala
> Fixes ballerina-platform/ballerina-lang#28476
=> Rename balo to bala

ballerina-test/build.gradle, ballerina-test/src/test/java/org/ballerinalang/distribution/test/BallerinaCommandTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java, ballerina-test/src/test/resources/testng.xml, ballerina/build.gradle, build.gradle, gradle.properties
> $title
Fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/80 …
=> Add ballerina commands test

ballerina/build.gradle
> Fix updated distribution name
=> Fix updated distribution name

.gitignore, ballerina/build.gradle
> Change JRE downloads dir to avoid deletion by clean task …
=> Change JRE downloads dir to avoid deletion by clean task

resources/tools/INSTALL.txt
> Update INSTALL.txt version output
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1254
=> Update INSTALL.txt version output

examples/union-type/union_type.bal
=> Fix the union type BBE

examples/index.json
Disable Playground in BBEs with services. …
=> Disable Playground in BBEs with Services

examples/websocket-async-binary-client/websocket_async_binary_client.bal, examples/websocket-async-binary-client/websocket_async_binary_client.description, examples/websocket-async-text-client/websocket_async_text_client.bal, examples/websocket-async-text-client/websocket_async_text_client.description, examples/websocket-basic-sample/websocket_basic_sample.bal, examples/websocket-basic-sample/websocket_basic_sample.description, examples/websocket-binary-client/websocket_binary_client.bal, examples/websocket-binary-client/websocket_binary_client.description, examples/websocket-proxy-server/websocket_proxy_server.description
=> Update doc links in websocket

stdlib-integration-tests/crypto/tests/crypto_test.bal, stdlib-integration-tests/jwt/tests/jwt_test.bal
=> Update integration tests of security modules with API changes

examples/websocket-async-binary-client/websocket_async_binary_client.bal
=> Fix line length in websocket BBE

examples/index.json
Remove the play icon in SL BBEs accepting user input. …
=> Remove the Play Icon in SL BBEs Accepting User Input

examples/index.json
Remove the Play icon in SL Transaction BBEs. …
=> Remove the Play Icon in SL Transaction BBEs

ballerina/build.gradle
> Remove b7a.home arg from BBE tests
=> Remove b7a.home arg from BBE tests

ballerina/build.gradle
=> Replace new email BBE entries

devtools-integration-tests/src/test/resources/testng.xml
> Include debug tests to ignore list
=> Include emails bbe to ignore list

examples/udp-client/udp_client.bal, examples/udp-connect-client/udp_connect_client.bal, examples/udp-listener/udp_listener.bal
=> Updat udp BBE

devtools-integration-tests/src/test/resources/testng.xml
$subject.
Partially fixes #1314 …
=> Enable debugger breakpoint tests

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java, devtools-integration-tests/src/test/resources/testng.xml
$subject. 
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1314. …
=> Enable service debug tests

examples/index.json
=> Remove BBEs which use HTTP trace, access logs

ballerina-test/src/test/java/org/ballerinalang/distribution/test/BallerinaCommandTest.java
=> Fix ballerina command test

.github/workflows/pull-request.yml, README.md, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
> Include instructions for windows env variable and fixes https://github.com/ballerina-platform/ballerina-distribution/issues/1317
=> Fix windows build failures

gradle.properties
=> Bump dependencies to stable versions

.github/workflows/daily-build.yml
> Disabling tests here as well, we will need to put another effort and enable all the tests in windows https://github.com/ballerina-platform/ballerina-distribution/issues/1319
=> Skip all the windows tests

ballerina-test/src/test/java/org/ballerinalang/distribution/test/BallerinaCommandTest.java, ballerina/build.gradle, gradle.properties
> Update testing pack to final zip pack
=> Update testing pack to final zip pack

examples/index.json
=> Correct the title capitalization

examples/log-api/log_api.bal, examples/log-api/log_api.out
=> Update log output configuration info

examples/index.json
=> Refactor names of the WebSocket BBEs

examples/http-streaming/http_streaming.bal
Fix the broken link in the HTTP Streaming BBE. …
=> Fix the Broken Link in the HTTP Streaming BBE

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, gradle.properties
=> Update dependency snapshot versions

examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.description, examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.description, examples/kafka-consumer-client/kafka_consumer_client.description, examples/kafka-consumer-group-service/kafka_consumer_group_service.description, examples/kafka-consumer-service/kafka_consumer_service.description, examples/kafka-producer-transactional/kafka_producer_transactional.description, examples/kafka-producer/kafka_producer.description, examples/nats-basic-client/nats_basic_client.description, examples/nats-streaming-client/nats_streaming_client.description, examples/nats-streaming-durable-subscriptions/nats_streaming_durable_subscriptions.description, examples/nats-streaming-queue-group/nats_streaming_queue_group.description, examples/nats-streaming-start-position/nats_streaming_start_position.description, examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.description, examples/rabbitmq-consumer/rabbitmq_consumer.description, examples/rabbitmq-producer/rabbitmq_producer.description, examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.description, examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.description
> Changes (kafka, rabbitmq, nats) api docs links to central. …
=> Change links to central docs

examples/configurable/Config.toml, examples/configurable/configurable.bal, examples/configurable/configurable.description, examples/configurable/configurable.out
Include information on record & table type support
- Unit tests 
> Code coverage information
https://github.com/ballerina-platform/ballerina-lang/pull/28461
> jdk 11, ubuntu
=> Improve `configurable` BBE

examples/absolute-path-and-path/absolute_path_and_path.metatags, examples/configurable/configurable.metatags, examples/http-circuit-breaker/http_circuit_breaker.metatags, examples/http-failover/http_failover.metatags, examples/http-load-balancer/http_load_balancer.metatags, examples/http-retry/http_retry.metatags, examples/http-timeout/http_timeout.metatags, examples/json-arrays/json_arrays.description, examples/json-objects/json_objects.description, examples/udp-listener/udp_listener.metatags
=> Fix Issues in BBE Descriptions and Meta Tags

examples/index.json
Add Docker Extension Without Annotation BBE. …
=> Add Docker Extension Without Annotation BBE

examples/json-arrays/json_arrays.metatags, examples/json-objects/json_objects.metatags
Remove colon in the metatags description of JSON BBEs. …
=> Remove Colon in the Metatags Description of JSON BBEs

gradle.properties
=> Sync master with slalpha2 release branch

examples/bytes-io/bytes_io.out, examples/different-payload-types/different_payload_types.server.out, examples/http-streaming/http_streaming.server.out, examples/json-csv/json_csv.out, examples/json-io/json_io.out, examples/request-with-multiparts/request_with_multiparts.server.out, examples/response-with-multiparts/response_with_multiparts.server.out, examples/xml-io/xml_io.out
Update the BBE .out files of the BBEs having the .bal files below on creating the required `/files/` artifacts.
1. bytes_io.bal 
2. http_streaming.bal 
3. xml_io.bal 
4. json_io.bal 
5. response_with_multiparts.bal 
6. json_csv.bal 
7. request_with_multiparts.bal
8. different_payload_types.bal 
Fixes #728 
> Brief description of the new feature or bug fix as it will …
=> Update the BBE .out Files on Creating the Required Artifacts

gradle.properties
=> Update ballerina lang dependency version

doc-guidelines.md
=> Add More BBE Guidelines

examples/worker-interaction/worker_interaction.bal
=> Reduce the Usage of "checkpanic" in Worker Interactions

examples/workers/workers.bal, examples/workers/workers.out
=> Remove unwanted usage of "checkpanic"

examples/index.json, examples/secured-service-with-basic-auth-file-user-store/Config.toml, examples/secured-service-with-basic-auth-file-user-store/sample-users.toml, examples/secured-service-with-basic-auth-file-user-store/secured_service_with_basic_auth_file_user_store.bal, examples/secured-service-with-basic-auth-file-user-store/secured_service_with_basic_auth_file_user_store.description, examples/secured-service-with-basic-auth-file-user-store/secured_service_with_basic_auth_file_user_store.out
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/862
=> Enable BBE of basic auth file user store

stdlib-integration-tests/url/tests/url_test.bal
$subject related to https://github.com/ballerina-platform/module-ballerina-url/pull/88
=> Fix URL encode/decode stdlib test

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java, ballerina/build.gradle, dist-repo-builder/build.gradle, dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java, gradle.properties
=> Add doc gen from balas

build.gradle, gradle.properties
$Subject
Resolves [#1051](https://github.com/ballerina-platform/ballerina-standard-library/issues/1051) & [#760 ](https://github.com/ballerina-platform/ballerina-standard-library/issues/760)
=> Remove runtime and reflect modules

examples/jdbc-init-options/jdbc_init_options.bal, examples/mysql-init-options/mysql_init_options.bal
> this is to change the BBEs for java.jdbc and mysql init_options.bal files after fixing [#967](https://github.com/ballerina-platform/ballerina-standard-library/issues/967)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
=> Change BBEs after time durations change in stdlibs

stdlib-integration-tests/auth/tests/auth_test.bal, stdlib-integration-tests/ftp/tests/ftp_test.bal, stdlib-integration-tests/grpc/modules/grpc_secured_unary/tests/grpc_secured_unary_service.bal, stdlib-integration-tests/grpc/modules/grpc_secured_unary/tests/grpc_secured_unary_test.bal, stdlib-integration-tests/grpc/modules/grpc_service_with_http_proxy_gateway/tests/grpc_chat_client.bal, stdlib-integration-tests/grpc/modules/grpc_service_with_http_proxy_gateway/tests/grpc_chat_service.bal, stdlib-integration-tests/grpc/modules/grpc_service_with_http_proxy_gateway/tests/http_proxy_service.bal, stdlib-integration-tests/jwt/tests/jwt_test.bal, stdlib-integration-tests/oauth2/tests/oauth2_test.bal
=> Update stdlib integration tests for SecureSocket API change

examples/basic-https-listener-client/basic_https_listener.bal, examples/basic-https-listener-client/https_client.bal, examples/basic-https-listener-client/tests/basic_https_listener_client_test.bal, examples/crypto/crypto.out, examples/grpc-secured-unary/grpc_secured_unary_service.bal, examples/grpc-secured-unary/grpc_secured_unary_service_client.bal, examples/grpc-secured-unary/tests/grpc_secured_unary_test.bal, examples/header-based-routing/header_based_routing.bal, examples/https-listener/https_listener.bal, examples/https-listener/tests/https_listener_test.bal, examples/jwt-issue-validate/jwt_issue_validate.bal, examples/jwt-issue-validate/jwt_mock_server.bal, examples/mutual-ssl/mutual_ssl_service.bal, examples/mutual-ssl/ssl_client.bal, examples/mutual-ssl/tests/mutual_ssl_test.bal, examples/secured-client-with-basic-auth/secured_client_with_basic_auth.bal, examples/secured-client-with-bearer-token-auth/secured_client_with_bearer_token_auth.bal, examples/secured-client-with-oauth2-client-credentials-grant-type/secured_client_with_oauth2_client_credentials_grant_type.bal, examples/secured-client-with-oauth2-direct-token-type/secured_client_with_oauth2_direct_token_type.bal, examples/secured-client-with-oauth2-password-grant-type/secured_client_with_oauth2_password_grant_type.bal, examples/secured-client-with-self-signed-jwt-auth/secured_client_with_self_signed_jwt_auth.bal, examples/secured-service-with-basic-auth-file-user-store/secured_service_with_basic_auth_file_user_store.bal, examples/secured-service-with-basic-auth-ldap-user-store/secured_service_with_basic_auth_ldap_user_store.bal, examples/secured-service-with-jwt-auth/secured_service_with_jwt_auth.bal, examples/secured-service-with-oauth2/secured_service_with_oauth2.bal
=> Update BBEs for SecureSocket API change

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java, ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java
This PR adds a additional check for code to cloud tooling jar in lang server folder in the final distribution pack.
> Link to the …
=> Add c2c tooling lib check to distribution

devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTest.java, devtools-integration-tests/src/test/java/org/ballerina/devtools/central/CentralTestUtils.java
=> Fix central tests by removing version from executable jar

stdlib-integration-tests/tcp/tests/tcp_tests.bal
> Update timeoutInMillis to timeout in tcp integration test
=> Update timeoutInMillis to timeout in tcp integration test

examples/log-api/log_api.bal, examples/log-api/log_api.metatags, examples/log-api/log_api.out, examples/log-api/tests/log_api_test.bal
=> Update log BBE and test case

stdlib-integration-tests/auth/tests/auth_test.bal
=> Update ldap user store config

examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.bal
=> Fix graphql BBE compilation error

examples/graphql-hello-world/graphql_hello_world.client.out
=> Fix graphql BBE output validation failure

examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal, examples/websocket-basic-sample/websocket_basic_sample.bal
=> Fix log module API changes in websocket BBEs

examples/tcp-listener/tcp_listener.bal, stdlib-integration-tests/udp/tests/mock_servers.bal, stdlib-integration-tests/udp/tests/udp_tests.bal
> Update udp integration tests
> Format tcp_listener BBE
=> Update udp integration tests

examples/filepath/filepath.bal
=> Update file path BBE

ballerina/build.gradle, examples/index.json, examples/tcp-transport-security/tcp-transport-security.description, examples/tcp-transport-security/tcp-transport-security.metatags, examples/tcp-transport-security/tcp_client.bal, examples/tcp-transport-security/tcp_client.out, examples/tcp-transport-security/tcp_listener.bal, examples/tcp-transport-security/tcp_listener.out
=> Implement new BBE for tcp secureSocket

ballerina/build.gradle, build.gradle, gradle.properties
> Include update tool artifact migration
=> Include update tool artifact migration

examples/receive-email-using-client/receive_email_using_client.bal, examples/receive-email-using-listener/receive_email_using_listener.bal, examples/send-email/send_email.bal
=> Update BBEs of Email Module

examples/http-data-binding/http_data_binding.bal
$title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/28986 …
=> Remove empty mapping constructor from http-data-binding bbe

examples/log-api/log_api.bal
=> Fix line length in log BBE

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming_service.bal, examples/grpc-client-streaming/grpc_client_streaming_service.bal, examples/grpc-secured-unary/grpc_secured_unary_service.bal, examples/grpc-server-streaming/grpc_server_streaming_service.bal, examples/grpc-unary-blocking/grpc_unary_blocking_service.bal, stdlib-integration-tests/grpc/modules/grpc_bidirectional_streaming/tests/grpc_bidirectional_streaming_service.bal, stdlib-integration-tests/grpc/modules/grpc_client_streaming/tests/grpc_client_streaming_service.bal, stdlib-integration-tests/grpc/modules/grpc_secured_unary/tests/grpc_secured_unary_service.bal, stdlib-integration-tests/grpc/modules/grpc_server_streaming/tests/grpc_server_streaming_service.bal, stdlib-integration-tests/grpc/modules/grpc_service_with_http_proxy_gateway/tests/grpc_chat_service.bal, stdlib-integration-tests/grpc/modules/grpc_service_with_http_proxy_gateway/tests/http_proxy_service.bal, stdlib-integration-tests/grpc/modules/grpc_unary_blocking/tests/grpc_unary_blocking_service.bal, stdlib-integration-tests/grpc/modules/grpc_unary_non_blocking/tests/grpc_unary_non_blocking_service.bal
=> Migrate grpc BBEs and integration test to new log APIs

examples/task-frequency-job-execution/task_frequency_job_execution.bal
=> Change line length in task BBE

ballerina/build.gradle, examples/http-client-with-basic-auth/http_client_with_basic_auth.out, examples/http-client-with-bearer-token-auth/http_client_with_bearer_token_auth.out, examples/http-client-with-oauth2-client-credentials-grant-type/http_client_with_oauth2_client_credentials_grant_type.out, examples/http-client-with-oauth2-direct-token-type/http_client_with_oauth2_direct_token_type.metatags, examples/http-client-with-oauth2-password-grant-type/http_client_with_oauth2_password_grant_type.out, examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.bal, examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.description, examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.metatags, examples/http-client-with-oauth2-refresh-token-grant-type/http_client_with_oauth2_refresh_token_grant_type.out, examples/http-client-with-self-signed-jwt-auth/http_client_with_self_signed_jwt_auth.out, examples/http-service-with-basic-auth-file-user-store/http_service_with_basic_auth_file_user_store.out, examples/http-service-with-basic-auth-ldap-user-store/http_service_with_basic_auth_ldap_user_store.out, examples/http-service-with-jwt-auth/http_service_with_jwt_auth.out, examples/http-service-with-oauth2/http_service_with_oauth2.out, examples/index.json
$subject
Related to https://github.com/ballerina-platform/module-ballerina-oauth2/pull/111
=> Update BBE for oauth2 refresh token grant config API

stdlib-integration-tests/index.json, stdlib-integration-tests/url/tests/url_test.bal
=> Update index.json for security tests

examples/jdbc-complex-type-queries/jdbc_complex_type_queries.bal, examples/mysql-complex-type-queries/mysql_complex_type_queries.bal, stdlib-integration-tests/sql/tests/jdbc-integration-test.bal
> $Subject
Fixes: [#1079
](https://github.com/ballerina-platform/ballerina-standard-library/issues/1079)
> https://github.com/ballerina-platform/module-ballerina-time/pull/68
=> Change BBEs for db clients due to new Time APIs and a bug fix

examples/response-with-multiparts/response_with_multiparts.bal
=> Fix length issue

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java, devtools-integration-tests/src/test/resources/debug/project-based-tests/service-tests/tests/hello_service_test.bal, devtools-integration-tests/src/test/resources/debug/single-file-tests/hello_service.bal
> This PR will fix the service debug test failures.
=> Disable service debug test failures
