examples/index.json

Rename `Working over the network` category to `Network libraries`. …

Rename `Working over the network` category to `Network libraries`

---

examples/graphql-interceptors/graphql_interceptors.md

Update GraphQL Interceptor BBE

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming.md

Updategrpc bbe out file name

---

examples/isolated-functions/isolated_functions.bal
examples/isolated-functions/isolated_functions.md

Update Isolated Functions BBE

---

examples/readonly-and-isolated/readonly_and_isolated.bal
examples/readonly-and-isolated/readonly_and_isolated.md

Update readonly and isolated BBE

---

examples/readonly-type/readonly_type.bal
examples/readonly-type/readonly_type.md

Update readonly-type BBE

---

examples/xml-data-model/xml_data_model.bal
examples/xml-namespaces/xml_namespaces.bal
examples/xml-namespaces/xml_namespaces.md
examples/xml-navigation/xml_navigation.bal
examples/xml-operations/xml_operations.bal
examples/xml-operations/xml_operations.md
examples/xml-subtyping/xml_subtyping.bal
examples/xml-subtyping/xml_subtyping.md
examples/xmlns-declarations/xmlns_declarations.bal
examples/xmlns-declarations/xmlns_declarations.md

Improve the XML BBEs

---

examples/variables-and-types/variables_and_types.description

Update the description

---

examples/io-csv-datamapping/io_csv_datamapping.bal
examples/io-csv-datamapping/io_csv_datamapping.md
examples/io-csv-datamapping/io_csv_datamapping.out

Fix issues in csv-datamapping-BBE

---

examples/io-csv-datamapping/io_csv_datamapping.out

Update io_csv_datamapping.out with new BBE standards

---

examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
examples/index.json

Update GraphQL BBEs

---

gradle.properties

Update Stdlib Versions to the Newest Timestamp Builds

---

examples/constraint-validations/constraint_validations.bal
examples/constraint-validations/constraint_validations.description
examples/constraint-validations/constraint_validations.md
examples/constraint-validations/constraint_validations.metatags
examples/constraint-validations/constraint_validations.out
examples/index.json

> $Subject
> Fixes : [`Add a BBE for constraint module #3208`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3208)

Add Constraint BBE

---

gradle.properties

Update AsyncAPI version for Ballerina 2201.2.0-rc1.5

---

gradle.properties

Bump c2c timestamp for update 2

---

examples/jdbc-atomic-batch-execute-operation/jdbc_atomic_batch_execute_operation.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-batch-execute-operation/mysql_atomic_batch_execute_operation.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

Update md files of database BBEs

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-client-basic-auth/grpc_client_basic_auth.md
examples/grpc-client-bearer-token-auth/grpc_client_bearer_token_auth.md
examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.md
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.md
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.md
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.md
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.md
examples/grpc-client-self-signed-jwt-auth/grpc_client_self_signed_jwt_auth.md
examples/grpc-client-ssl-tls/grpc_client_ssl_tls.md
examples/grpc-client-streaming/grpc_client_streaming.md
examples/grpc-server-streaming/grpc_server_streaming.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.md
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.md
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.md
examples/grpc-service-oauth2/grpc_service_oauth2.md
examples/grpc-service-ssl-tls/grpc_service_ssl_tls.md
examples/grpc-simple-with-headers/grpc_simple_with_headers.md
examples/grpc-simple/grpc_simple.md
examples/proto-to-ballerina/proto_to_ballerina.description
examples/proto-to-ballerina/proto_to_ballerina.md
examples/proto-to-ballerina/proto_to_ballerina.out

Update grpc bbes

---

examples/ftp-client/ftp_client.md
examples/ftp-listener/ftp_listener.md
examples/kafka-authentication-sasl-plain-consumer/kafka_authentication_sasl_plain_consumer.md
examples/kafka-authentication-sasl-plain-producer/kafka_authentication_sasl_plain_producer.md
examples/kafka-consumer-client-poll-consumer-record/kafka_consumer_client_poll_consumer_record.md
examples/kafka-consumer-client-poll-payload/kafka_consumer_client_poll_payload.md
examples/kafka-consumer-service/kafka_consumer_service.md
examples/kafka-producer-transactional/kafka_producer_transactional.md
examples/kafka-producer/kafka_producer.md
examples/nats-basic-pub-sub/nats_basic_pub_sub.md
examples/nats-basic-request-reply/nats_basic_request_reply.md
examples/nats-basic-secure-connection/nats_basic_secure_connection.md
examples/nats-streaming-durable-subscriptions/nats_streaming_durable_subscriptions.md
examples/nats-streaming-pub-sub/nats_streaming_pub_sub.md
examples/nats-streaming-queue-group/nats_streaming_queue_group.md
examples/nats-streaming-secure-connection/nats_streaming_secure_connection.md
examples/nats-streaming-start-position/nats_streaming_start_position.md
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.md
examples/rabbitmq-consumer/rabbitmq_consumer.md
examples/rabbitmq-producer/rabbitmq_producer.md
examples/rabbitmq-secure-connection/rabbitmq_secure_connection.md
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.md
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.md
examples/sftp-client/sftp_client.md
examples/sftp-listener/sftp_listener.md

Update line breaks in BBEs

---

gradle.properties

Update dependency versions for SL Update 2

---

gradle.properties

Update c2c timestamp version

---

ballerina-test-automation/gradle.properties
gradle.properties

Update spec version for update 2

---

devtools-integration-tests/src/test/resources/testng.xml

$subject.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3034

Enable debugger evaluation tests for remote action invocations

---

examples/index.json

Update the `index.json` for Docker and K8S. …

Update the `index.json` for Docker and K8S

---

.github/workflows/publish-release-artifacts.yml

Currently release artifacts have been publishing to the s3 bucket using a jenkin job. With this workflow, the process has been migrated to github actions.
Since jenkin jobs require a physical machine to run, we can reduce external resources which our release process depends on.
https://github.com/ballerina-platform/ballerina-distribution/issues/2994
> Link(s) to product documentation …

Add workflow to publish release artifacts

---

.github/workflows/publish-release-artifacts-1.2.x.yml

Currently 1.2.x release artifacts have been published using a jenkin job. This workflow will release 1.2.x artifacts along with docker image.
Reduce external dependencies on release process. …

Add workflow to publish 1.2.x release artifacts

---

.github/workflows/publish-release-artifacts.yml

Fix version error

---

gradle.properties

Update lang version for 2201.1.2-rc1

---

examples/default-values-for-record-fields/default_values_for_record_fields.bal
examples/default-values-for-record-fields/default_values_for_record_fields.md
examples/default-values-for-record-fields/default_values_for_record_fields.metatags
examples/default-values-for-record-fields/default_values_for_record_fields.out
examples/dependent-types/dependent_types.bal
examples/dependent-types/dependent_types.md
examples/dependent-types/dependent_types.metatags
examples/dependent-types/dependent_types.out
examples/ensureType-function/ensureType_function.bal
examples/ensureType-function/ensureType_function.md
examples/ensureType-function/ensureType_function.metatags
examples/ensureType-function/ensureType_function.out
examples/included-record-parameters/included_record_parameters.bal
examples/included-record-parameters/included_record_parameters.md
examples/included-record-parameters/included_record_parameters.metatags
examples/included-record-parameters/included_record_parameters.out
examples/index.json
examples/type-inclusion-for-records/type_inclusion_for_records.bal
examples/type-inclusion-for-records/type_inclusion_for_records.md
examples/type-inclusion-for-records/type_inclusion_for_records.metatags
examples/type-inclusion-for-records/type_inclusion_for_records.out

Add the following BBEs.
- Type inclusion for records
- Included record parameters
- Default values for record fields
- ensureType function
- Dependent types

Add new records and ensureType related BBEs

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming.md

Fix the duplicated section

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

[1.1.x ]Update openAPI version for update1 patch 2 version

---

examples/graphql-interceptors/graphql_interceptors.client.out
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interceptors/graphql_interceptors.server.out
examples/graphql-subscriptions/graphql_subscriptions.md
examples/graphql-subscriptions/graphql_subscriptions.server.out

Fix missing GraphQL BBE updates. …

Fix missing GraphQL BBE updates

---

examples/grpc-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-client-basic-auth/grpc_client_basic_auth.md
examples/grpc-client-bearer-token-auth/grpc_client_bearer_token_auth.md
examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.md
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.md
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.md
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.md
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.md
examples/grpc-client-self-signed-jwt-auth/grpc_client_self_signed_jwt_auth.md
examples/grpc-client-ssl-tls/grpc_client_ssl_tls.md
examples/grpc-client-streaming/grpc_client_streaming.md
examples/grpc-server-streaming/grpc_server_streaming.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.md
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.md
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.md
examples/grpc-service-oauth2/grpc_service_oauth2.md
examples/grpc-service-ssl-tls/grpc_service_ssl_tls.md
examples/grpc-simple-with-headers/grpc_simple_with_headers.md
examples/grpc-simple/grpc_simple.md

Fix the issues in the gRPC and gRPC security BBEs. …

Fix the issues in the gRPC and gRPC security BBEs

---

examples/testerina-assertions/testerina_assertions.md
examples/testerina-before-and-after-each/testerina_before_and_after_each.md
examples/testerina-before-and-after-groups/testerina_before_and_after_groups.md
examples/testerina-before-and-after-suite/testerina_before_and_after_suite.md
examples/testerina-before-and-after-test/testerina_before_and_after_test.md
examples/testerina-data-driven-tests/testerina_data_driven_tests.md
examples/testerina-group-tests/testerina_group_tests.md
examples/testerina-guarantee-test-execution-order/testerina_guarantee_test_execution_order.md
examples/testerina-mocking-functions/testerina_mocking_functions.md
examples/testerina-mocking-objects/testerina_mocking_objects.md

Fixes : #3116 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

Fix testerina learn page links

---

gradle.properties

Add c2c timestamped version

---

ballerina-test-automation/gradle.properties

Update SL latest version for 2201.1.2

---

examples/grpc-client-basic-auth/grpc_client_basic_auth.md
examples/grpc-client-bearer-token-auth/grpc_client_bearer_token_auth.md
examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.md
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.md
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.md
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.md
examples/grpc-client-self-signed-jwt-auth/grpc_client_self_signed_jwt_auth.md
examples/grpc-client-ssl-tls/grpc_client_ssl_tls.md
examples/grpc-client-streaming/grpc_client_streaming.md
examples/grpc-server-streaming/grpc_server_streaming.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.md
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.md
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.md
examples/grpc-service-oauth2/grpc_service_oauth2.md
examples/grpc-simple-with-headers/grpc_simple_with_headers.md
examples/grpc-simple/grpc_simple.md
examples/nats-streaming-start-position/nats_streaming_start_position.md

Update gRPC and NATS BBEs

---

examples/backtick-templates/backtick_templates.md
examples/combining-isolated-functions-and-lock/combining_isolated_functions_and_lock.md
examples/isolated-functions/isolated_functions.md

Remove list elements from BBEs. …

Remove list elements from BBEs

---

ballerina-test-automation/gradle.properties

Update tool versions for 2201.1.2

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java

Fix c2c bbes tests

---

ballerina-test/src/test/java/org/ballerinalang/distribution/lengthValidation/LengthValidator.java

> Increase maximum line length

Increase maximum line length

---

.github/workflows/publish-release-artifacts.yml

Fix login to dockerhub

---

examples/configurable-variables/configurable_variables.md
examples/counter-metrics/counter_metrics.md
examples/gauge-metrics/gauge_metrics.md
examples/sequence-diagrams/sequence_diagrams.md
examples/tracing/tracing.md

Fix BBE broken links and image. …

Fix BBE broken links and image

---

examples/configurable-variables/configurable_variables.md
examples/counter-metrics/counter_metrics.md
examples/gauge-metrics/gauge_metrics.md
examples/sequence-diagrams/sequence_diagrams.md
examples/tracing/tracing.md

Fix BBE links and image in master branch. …

Fix BBE links and image in master branch

---

gradle.properties

Update stdlib versions for SL update 2 RC3

---

gradle.properties

Update AsyncAPI tool version for 2201.2.0-rc3

---

gradle.properties

[2201.1.x] Bump c2c timestamp version

---

gradle.properties

Bump lang & openapi version

---

examples/http-trace-logs/http_trace_logs.bal

Add resource path to HTTP tracelog BBE

---

gradle.properties

[patch 2201.1.2-rc3.1]Update openAPI version

---

gradle.properties

Bump c2c timestamp in 2201.1.x

---

gradle.properties

Update AsyncAPI tool version for 2201.2.0-rc3.2

---

gradle.properties

Update Open API version

---

gradle.properties

Update stdlib dependency versions for update 2

---

gradle.properties

Bump c2c to 2.2.1

---

gradle.properties

Bump c2c to 2.3.0

---

gradle.properties

Update asyncapi version for Ballerina 2201.2.0

---

gradle.properties

[Patch 2201.1.2] Update OpenAPI version

---

gradle.properties

Update graphql version

---

examples/index.json

Update Serdes BBE section

---

examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.server.out
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.server.out
examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.md
examples/http-service-basic-auth-file-user-store/http_service_basic_auth_file_user_store.server.out
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.md
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.server.out

Fixes: [#3336](https://github.com/ballerina-platform/ballerina-standard-library/issues/3336)

Update `Basic Auth file user store` BBEs

---

gradle.properties

Update lang version to 2201.2.1-rc1

---

gradle.properties

Release 2201.2.0

---

.github/workflows/pull-request.yml

Enable PR check for 2201.2.x branch

---

gradle.properties

Update lang version to 2201.2.1-rc1.1

---

examples/table-syntax/table_syntax.md

Fix typo error in the Table syntax BBE

---

examples/index.json

Correct the C2C BBE category

---

examples/binding-patterns-in-assignment/binding_patterns_in_assignment.bal
examples/binding-patterns-in-assignment/binding_patterns_in_assignment.md
examples/binding-patterns-in-assignment/binding_patterns_in_assignment.metatags
examples/binding-patterns-in-assignment/binding_patterns_in_assignment.out
examples/index.json

Add new BBE for Binding pattern in assignment

---

examples/graphql-client/graphql_client.bal
examples/graphql-client/graphql_client.md
examples/graphql-client/graphql_client.metatags
examples/graphql-client/graphql_client.out
examples/index.json

> Fixes: [#3300](https://github.com/ballerina-platform/ballerina-standard-library/issues/3300) …

Add GraphQL client BBE

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync with release 1.2.32

---

examples/index.json
examples/never-type/never_type.bal
examples/never-type/never_type.md
examples/never-type/never_type.metatags
examples/never-type/never_type.out

Add new BBE for never-type

---

gradle.properties

Update the GraphQL version to 1.4.2

---

.github/workflows/publish-release-artifacts.yml

Fix path to deb installer in publish release artifacts workflow

---

examples/typedesc-type/typedesc_type.md

Fix the filenames in the `typedesc_type.md` file. …

Fix the filenames in the `typedesc_type.md` file

---

examples/error-cause/error_cause.md

Fix filenames in the `error_cause.md` file. …

Fix filenames in the `error_cause.md` file

---

examples/synchronize-message-passing/synchronize_message_passing.md

Fix  filenames in the `synchronize_message_passing.md` file. …

Fix  filenames in  `synchronize_message_passing.md`

---

examples/asynchronize-message-passing/asynchronize_message_passing.md

Fix filenames in the `asynchronize-message-passing.md` file. …

Fix filenames in `asynchronize-message-passing.md` file

---

examples/graphql-directives/graphql_directives.md

Fix filenames in the `graphql_directives.md` file. …

Fix filenames in the `graphql_directives.md` file

---

ballerina/build.gradle

Remove cache generation for minor stdlib versions

---

gradle.properties

Update log module version

---

examples/asynchronize-message-passing/asynchronize_message_passing.md
examples/synchronize-message-passing/synchronize_message_passing.md

Correct BBE title name for sync send and async send

---

examples/graphql-interfaces/graphql_interfaces.bal
examples/graphql-interfaces/graphql_interfaces.client.out
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.bal
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.bal
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.bal
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.bal
examples/graphql-service-oauth2/graphql_service_oauth2.bal
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.bal
examples/index.json
gradle.properties

- Add `GraphQL Interfaces` BBE
- Change the GraphQL BBE ports to 4000
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3412

Update and Enable GraphQL Interfaces BBE

---

.github/workflows/publish-release.yml

Remove post release PR task from publish release workflow

---

.github/workflows/publish-release-artifacts-1.2.x.yml

Fix artifact urls

---

.github/workflows/publish-release.yml
installers/linux-deb/build-ballerina-linux-deb-x64.sh
installers/linux-rpm/resources/ballerina-tools.spec
installers/mac/build-ballerina-macos-x64.sh
installers/windows/build-ballerina-windows-x64.bat

Fix installer name

---

examples/index.json

> Remove duplucate bbe in index.json …

Remove duplucate bbe in index.json

---

.github/workflows/publish-release-artifacts-1.2.x.yml
.github/workflows/publish-release-artifacts.yml

Fix aws cli login

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync with Release 1.2.33

---

examples/type-inference/type_inference.bal

> A minor change to the comment …

Added space on comment

---

gradle.properties

Update latest released module versions

---

gradle.properties

Bump the GraphQL Version to 1.3.4

---

ballerina-test-automation/gradle.properties

Update versions to 2201.2.2 in installer tests

---

gradle.properties

Update ballerinaLangVersion to 2201.2.2-rc1

---

gradle.properties

Update `ballerinaLangVersion` to `2201.2.2-rc1.1`

---

gradle.properties

Bump c2c timestamped version

---

build.gradle
gradle.properties

> $Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3484

Add persist module and persist tool to distribution

---

gradle.properties

Update ballerina lang version to latest time stamped version and the spec version

---

ballerina-test-automation/gradle.properties

Update versions in installer tests

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/DistributionArtifactCheckTest.java
ballerina-test/src/test/java/org/ballerinalang/distribution/test/PlatformDistributionArtifactCheckTest.java
build.gradle
gradle.properties

Modify c2c name as per gradle plugin migration

---

examples/index.json

> $subject
https://github.com/ballerina-platform/ballerina-dev-website/issues/5663 …

Fix alignment issues in Expression-oriented style section

---

gradle.properties

Update lang version to `2201.2.2`

---

gradle.properties

Bump c2c to 2.3.1 for update 2

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ExpressionEvaluationTest.java

$subject due to a regression issue due function closure changes introduced for SL update3 release.  
Created https://github.com/ballerina-platform/ballerina-distribution/issues/3309 to track the issue. …

Disable debugger remote call evaluation test

---

gradle.properties

Update asyncapi version for bal version 2201.3.0-20221014-074800-bbf5f7a2

---

gradle.properties

Update ballerinaLangVersion to the latest timestamped version

---

gradle.properties

Update `ballerinaLangVersion` to `2201.3.0-rc1`

---

project-api-tests/src/test/java/org/ballerina/projectapi/BuildTimeTest.java

Disable testResolutionTimeReduction test case

---

devtools-integration-tests/testerina-object-mocking-test/tests/main_test.bal

Enable mock test after testerina object mocking fix

---

examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal

Fix error in RabbitMQ BBE

---

gradle.properties

Bump Update3 rc1 c2c timestamp

---

gradle.properties

Update graphql module version

---

gradle.properties

Bump c2c timestamp version

---

gradle.properties

Update asyncapi version for Ballerina 2201.3.0-rc1

---

gradle.properties

Update GraphQL Tool version for 2201.3.0-rc1

---

gradle.properties

Update Stdlibs to the latest timestamp

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Set up java version for installer tests

---

.github/workflows/daily-build-2201.1.x.yml
.github/workflows/daily-build.yml

Update starting time for scheduled builds

---

examples/strings/strings.md

Update `strings.md` description text

---

examples/outer-join-clause/outer_join_clause.bal
examples/outer-join-clause/outer_join_clause.md
examples/outer-join-clause/outer_join_clause.metatags
examples/outer-join-clause/outer_join_clause.out

> Add Ballerina by examples to `outer join`.

Add outer join BBE

---

examples/index.json

(cherry picked from commit 922264cb16099d2efab875fb2a9582a2555c28f4)
> Link(s) to product documentation that addresses the …

Add outer join bbe to generation script

---

examples/azure-functions-deployment/az_deploy.out
examples/azure-functions-deployment/azure_functions_deployment.bal
examples/azure-functions-deployment/azure_functions_deployment.md
examples/azure-functions-deployment/bal_build.out
examples/azure-functions-deployment/execute_function.out

Add azure functions 3.0.0 related BBE to master

---

gradle.properties

Update with HTTP timestamped version

---

ballerina-test/src/test/resources/openapi/expected/client.bal
ballerina-test/src/test/resources/openapi/expected/types.bal
gradle.properties

[2201.3.0] Update openapi version

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
ballerina-test/src/test/resources/openapi/expected/client.bal
ballerina-test/src/test/resources/openapi/expected/types.bal
gradle.properties

[2201.2.3] Update openapi version

---

.github/workflows/daily-build-2201.2.x.yml

> Replace 2201.1.x with 2201.2.x daily build

Replace 2201.1.x with 2201.2.x daily build

---

ballerina-test-automation/gradle.properties

Change version to `2201.2.3` in installer tests

---

gradle.properties

Update http module version

---

examples/run-strands-safely-on-separate-threads/run_strands_safely_on_separate_threads.md

Update markdown file of isolation inference

---

gradle.properties

[2201.2.x] Update http patch version

---

gradle.properties

[2201.2.x] Update OAuth2 patch version

---

gradle.properties

Bump the GraphQL version to 1.4.4

---

examples/expression-oriented-style/expression_oriented_style.md

Add BBE Title

---

.github/workflows/daily-build-2201.2.x.yml
.github/workflows/daily-build.yml
.github/workflows/main.yml
.github/workflows/publish-release-artifacts-1.2.x.yml
.github/workflows/publish-release-artifacts.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
project-api-tests/build.gradle
project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2839
Clean the packages pushed to central after project api test suites 
Running a gh workflow that cleans created packages. This is done in the @Aftersuite method of project-api-tests.
For calling the workflow, BALLERINA_BOT_TOKEN has been added as an environment var in each gh workflows that runs project-api-tests. …

Remove central packages pushed during project api tests

---

gradle.properties

[2201.2.x]Update openAPI version

---

gradle.properties

Change lang version to `2201.2.3-rc2.1`

---

gradle.properties

[2201.2.x] Update http patch version #3358

---

project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

The functionality of https://github.com/ballerina-platform/ballerina-distribution/pull/3359 is not working as expected since BALLERINA_BOT_TOKEN does not have access to `wso2-enterprise/ballerina-registry` repo. Hence the AfterSuite method that calls the workflow is failing causing the test suite to fail.
Related to: https://github.com/ballerina-platform/ballerina-distribution/issues/2839
Avoid failing tests until the correct token is received to be used instead of the BALLERINA_BOT_TOKEN.
The AfterSuite method is disabled. …

Disable AfterSuite until the token is received

---

gradle.properties

Change lang version to `2201.2.3`

---

gradle.properties

Update openapi module verison to stable

---

pom.xml

Update staging urls for 1.2.34 release

---

ballerina-test-automation/gradle.properties

Update lang version for installer tests

---

examples/graphql-idl-support/Ballerina.toml
examples/graphql-idl-support/graphql.config.yaml
examples/graphql-idl-support/graphql_idl_support.bal
examples/graphql-idl-support/graphql_idl_support.md
examples/graphql-idl-support/graphql_idl_support.out
examples/graphql-idl-support/queries/query-country.graphql
examples/index.json

Add a BBE for GraphQL IDL support

---

gradle.properties

[2201.3.x] Update graphql module version

---

examples/function-pointers/function_pointers.bal
examples/function-pointers/function_pointers.md
examples/function-pointers/function_pointers.metatags
examples/function-pointers/function_pointers.out
examples/index.json

[2201.3.x] Add new BBE for function pointers

---

examples/function-pointers/function_pointers.bal
examples/function-pointers/function_pointers.md
examples/function-pointers/function_pointers.metatags
examples/function-pointers/function_pointers.out
examples/index.json

[Master] Add new BBE for function pointers

---

examples/graphql-idl-support/queries/query-country.graphql

Fix a minor typo

---

examples/default-values-for-function-parameters/default_values_for_function_parameters.md

Update markdown file of default values for function parameters

---

examples/default-values-for-function-parameters/default_values_for_function_parameters.md

[2201.3.x] Update markdown file of default values for function parameters

---

examples/index.json

Temporarily disable sequence diagram BBE test

---

examples/index.json
examples/outer-join-clause/outer_join_clause.bal
examples/outer-join-clause/outer_join_clause.md
examples/outer-join-clause/outer_join_clause.metatags
examples/outer-join-clause/outer_join_clause.out

[Master] - Add Outer join BBE

---

examples/index.json
examples/outer-join-clause/outer_join_clause.bal
examples/outer-join-clause/outer_join_clause.md
examples/outer-join-clause/outer_join_clause.metatags
examples/outer-join-clause/outer_join_clause.out

[2201.3.x]- Add Outer join BBE

---

.github/workflows/pull-request.yml

Add 3.x branch to PR build

---

gradle.properties

Reverts ballerina-platform/ballerina-distribution#3372

Revert "[Automated] Sync master after 2201.2.3 release"

---

gradle.properties

Bump the GraphQL version to 1.4.5

---

gradle.properties

Update Graphql version to 1.3.5

---

.github/workflows/daily-build-2201.2.x.yml
.github/workflows/daily-build.yml
.github/workflows/main.yml
.github/workflows/publish-release-artifacts-1.2.x.yml
.github/workflows/publish-release-artifacts.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

$ subject
The BALLERINA_BOT_TOKEN did not have enough permissions to run the [test package cleaning workflow](https://github.com/wso2-enterprise/ballerina-registry/actions/workflows/delete_test_package_dev_scheduled.yml). Hence a new token `BALLERINA_BOT_WORKFLOW` is introduced.
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/2839
> Brief …

Update token for cleaning test packages in the Central

---

examples/index.json
examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-execute-operation/mysql_execute_operation.md

$subject 
1. Improve titles
2. Remove usage of var

[2201.3.x] Improve SQL BBEs

---

examples/index.json
examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.bal
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-execute-operation/mysql_execute_operation.md

$subject 
1. Improve titles
2. Remove usage of var

Improve SQL BBEs

---

.github/workflows/daily-build-2201.2.x.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Fix windows installer build

---

examples/index.json

Disable test in client data binding

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Update dotnet-guid version

---

examples/index.json

Rearange the order of BBEs

---

examples/query-actions/query_actions.bal
gradle.properties

It will be nil if completes normally and an error if completes abruptly
> $subject …

Update query action result type in BBE

---

examples/websocket-client-basic-auth/websocket_client_basic_auth.md
examples/websocket-client-bearer-token-auth/websocket_client_bearer_token_auth.md
examples/websocket-client-mutual-ssl/websocket_client_mutual_ssl.md
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.md
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.md
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.md
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.md
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.md
examples/websocket-client-ssl-tls/websocket_client_ssl_tls.md
examples/websocket-retry-client/websocket_retry_client.md
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.md
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.md
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.md
examples/websocket-service-mutual-ssl/websocket_service_mutual_ssl.md
examples/websocket-service-oauth2/websocket_service_oauth2.md
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.md

Change BBE titles

---

examples/websocket-client-bearer-token-auth/websocket_client_bearer_token_auth.bal
examples/websocket-client-mutual-ssl/websocket_client_mutual_ssl.bal
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.bal
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.bal
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.bal
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.bal
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.bal
examples/websocket-client-ssl-tls/websocket_client_ssl_tls.bal

Move client creation to main function

---

examples/sftp-service-read/sftp_service_read.md

Fix missing filenames

---

examples/ftp-client-read/ftp_client_read.md
examples/ftp-client-write/ftp_client_write.md
examples/ftp-service-read/ftp_service_read.md
examples/sftp-client-read/sftp_client_read.md
examples/sftp-client-write/sftp_client_write.md
examples/sftp-service-read-write/sftp_service_read_write.md
examples/sftp-service-read/sftp_service_read.md

Fix ftp bbe filenames

---

examples/index.json
examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-atomic-transaction/jdbc_atomic_transaction.out
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.out
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.out
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.out
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-operation/jdbc_query_operation.out
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.out
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.out
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.out
examples/mysql-call-stored-procedures/initialize.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.out
examples/mysql-call-stored-procedures/process_result_stream.bal
examples/mysql-call-stored-procedures/process_student_stream.bal
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-execute-operation/mysql_execute_operation.out
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.out
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-operation/mysql_query_operation.out
examples/mysql-query-row-operation/mysql_query_row_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.out

Improve MySQL Call Stored Procedures example

---

examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

Improve titles of the SQL BBEs

---

examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

$subject 
Original PR https://github.com/ballerina-platform/ballerina-distribution/pull/3506

[Master] Improve titles of the SQL BBEs

---

examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-service/receive_email_using_service.md
examples/send-email/send_email.md

[3.x] Update BBE titles

---

examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-service/receive_email_using_service.md
examples/send-email/send_email.md

[Master] Update BBE titles

---

examples/grpc-client-basic-auth/grpc_client_basic_auth.md
examples/grpc-client-bearer-token-auth/grpc_client_bearer_token_auth.md
examples/grpc-client-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-client-client-streaming/grpc_client_streaming.md
examples/grpc-client-headers/grpc_simple_with_headers.md
examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.md
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.md
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.md
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.md
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.md
examples/grpc-client-self-signed-jwt-auth/grpc_client_self_signed_jwt_auth.md
examples/grpc-client-server-streaming/grpc_server_streaming.md
examples/grpc-client-simple/grpc_simple.md
examples/grpc-client-ssl-tls/grpc_client_ssl_tls.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.md
examples/grpc-service-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-service-client-streaming/grpc_client_streaming.md
examples/grpc-service-headers/grpc_simple_with_headers.md
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.md
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.md
examples/grpc-service-oauth2/grpc_service_oauth2.md
examples/grpc-service-server-streaming/grpc_server_streaming.md
examples/grpc-service-simple/grpc_simple.md
examples/grpc-service-ssl-tls/grpc_service_ssl_tls.md

Update example page titles(master)

---

examples/grpc-client-basic-auth/grpc_client_basic_auth.md
examples/grpc-client-bearer-token-auth/grpc_client_bearer_token_auth.md
examples/grpc-client-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-client-client-streaming/grpc_client_streaming.md
examples/grpc-client-headers/grpc_simple_with_headers.md
examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.md
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.md
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.md
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.md
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.md
examples/grpc-client-self-signed-jwt-auth/grpc_client_self_signed_jwt_auth.md
examples/grpc-client-server-streaming/grpc_server_streaming.md
examples/grpc-client-simple/grpc_simple.md
examples/grpc-client-ssl-tls/grpc_client_ssl_tls.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-basic-auth-ldap-user-store/grpc_service_basic_auth_ldap_user_store.md
examples/grpc-service-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-service-client-streaming/grpc_client_streaming.md
examples/grpc-service-headers/grpc_simple_with_headers.md
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.md
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.md
examples/grpc-service-oauth2/grpc_service_oauth2.md
examples/grpc-service-server-streaming/grpc_server_streaming.md
examples/grpc-service-simple/grpc_simple.md
examples/grpc-service-ssl-tls/grpc_service_ssl_tls.md

Update example page titles(3.x)

---

examples/index.json

This was removed while resolving a git merge conflict.

Add graphiql client BBE in index.json

---

examples/index.json

Fix columns

---

examples/index.json
examples/nats-basic-pub/nats-basic-pub.md
examples/nats-basic-reply/nats-basic-reply.md
examples/nats-basic-request/nats-basic-request.md
examples/nats-basic-sub/nats-basic-sub.md
examples/nats-client-basic-auth/nats-client-basic-auth.md
examples/nats-client-secure-connection/nats-client-secure-connection.md
examples/nats-service-basic-auth/nats-service-basic-auth.md
examples/nats-service-secure-connection/nats-service-secure-connection.md
examples/rabbitmq-client-basic-auth/rabbitmq-client-basic-auth.md
examples/rabbitmq-client-secure-connection/rabbitmq-client-secure-connection.md
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.md
examples/rabbitmq-consumer/rabbitmq_consumer.md
examples/rabbitmq-producer/rabbitmq_producer.md
examples/rabbitmq-service-basic-auth/rabbitmq-service-basic-auth.md
examples/rabbitmq-service-secure-connection/rabbitmq-service-secure-connection.md
examples/rabbitmq-sync-consumer/rabbitmq-sync-consumer.md
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.md
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.md

Update messaging BBE order

---

examples/index.json
examples/websocket-client-basic-auth/websocket_client_basic_auth.bal
examples/websocket-client-basic-auth/websocket_client_basic_auth.md
examples/websocket-client-bearer-token-auth/websocket_client_bearer_token_auth.md
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.md
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.md
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.md
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.md
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.bal
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.md
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.bal
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.md
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.bal
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.md
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.bal
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.md

Rename Auth to authentication

---

examples/graphql-graphiql/graphql_graphiql.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
examples/index.json

Update the titles from Auth to Authentication

---

examples/index.json
examples/kafka-client-consumer-ssl/kafka_client_consumer_ssl.md
examples/kafka-client-producer-ssl/kafka_client_producer_ssl.md
examples/kafka-service-ssl/kafka_service_ssl.md

Update headings and order

---

examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md

Fix formatting

---

examples/ftp-client-read/ftp_client_read.md
examples/ftp-client-write/ftp_client_write.md
examples/ftp-service-read-write/ftp_service_read_write.md
examples/ftp-service-read/ftp_service_read.md
examples/grpc-client-client-streaming/grpc_client_streaming.md
examples/grpc-client-server-streaming/grpc_server_streaming.md
examples/grpc-service-client-streaming/grpc_client_streaming.md
examples/grpc-service-server-streaming/grpc_server_streaming.md
examples/index.json
examples/sftp-client-read/sftp_client_read.md
examples/sftp-client-write/sftp_client_write.md
examples/sftp-service-read-write/sftp_service_read_write.md
examples/sftp-service-read/sftp_service_read.md

Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3526 …

Add minor changes to grpc/ftp/kafka bbes

---

examples/grpc-server-reflection/grpc_server_reflection.bal
examples/grpc-server-reflection/grpc_server_reflection.md
examples/grpc-server-reflection/grpc_server_reflection.metatags
examples/grpc-server-reflection/grpc_server_reflection.out
examples/grpc-server-reflection/grpc_server_reflection_grpcurl.out
examples/index.json

Add grpc reflection bbe

---

examples/http-client-basic-authentication/http_client_basic_authentication.md
examples/http-client-bearer-token-authentication/http_client_bearer_token_authentication.md
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.md
examples/http-service-basic-authentication-file-user-store/http_service_basic_authentication_file_user_store.md
examples/http-service-basic-authentication-ldap-user-store/http_service_basic_authentication_ldap_user_store.md
examples/http-service-data-binding/http_service_data_binding.md
examples/http-service-jwt-authentication/http_service_jwt_authentication.md

Update md files with new file names

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.bal
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.metatags
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.out
examples/graphql-client/graphql_client.metatags
examples/graphql-client/graphql_client.out
examples/index.json

Update GraphQL client BBE

---

examples/index.json
examples/nats-basic-pub/nats-basic-pub.md
examples/nats-basic-reply/nats-basic-reply.md
examples/nats-basic-request/nats-basic-request.md
examples/nats-basic-sub/nats-basic-sub.md
examples/nats-client-basic-auth/nats-client-basic-auth.md
examples/nats-client-secure-connection/nats-client-secure-connection.md
examples/nats-service-basic-auth/nats-service-basic-auth.md
examples/nats-service-secure-connection/nats-service-secure-connection.md
examples/rabbitmq-client-basic-auth/rabbitmq-client-basic-auth.bal
examples/rabbitmq-client-secure-connection/rabbitmq-client-secure-connection.bal
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.md
examples/rabbitmq-consumer/rabbitmq_consumer.md
examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-producer/rabbitmq_producer.md
examples/rabbitmq-queue-declare/rabbitmq-queue-declare.bal
examples/rabbitmq-queue-declare/rabbitmq-queue-declare.md
examples/rabbitmq-queue-declare/rabbitmq-queue-declare.metatags
examples/rabbitmq-queue-declare/rabbitmq-queue-declare.out
examples/rabbitmq-service-basic-auth/rabbitmq-service-basic-auth.md
examples/rabbitmq-sync-consumer/rabbitmq-sync-consumer.bal
examples/rabbitmq-sync-consumer/rabbitmq-sync-consumer.md
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.md

Update messaging BBE headings

---

examples/rabbitmq-sync-consumer/rabbitmq-sync-consumer.md

Update heading of sync consumer

---

examples/tcp-client/tcp_client.bal
examples/tcp-listener/tcp_listener.bal
examples/udp-client/udp_client.bal
examples/udp-connect-client/udp_connect_client.bal
examples/udp-listener/udp_listener.bal

Change port numbers

---

examples/index.json
examples/tcp-client/tcp_client.bal
examples/udp-client/udp_client.bal
examples/udp-connect-client/udp_connect_client.bal
examples/websocket-client-basic-auth/websocket_client_basic_auth.md
examples/websocket-client-bearer-token-auth/websocket_client_bearer_token_auth.md
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.md
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.md
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.md
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.md
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.md
examples/websocket-retry-client/websocket_retry_client.bal
examples/websocket-retry-client/websocket_retry_client.md

Update the WebSocket, TCP, and UDP BBEs as per the review suggestions.

Address review suggestions

---

examples/kafka-client-consumer-record-data-binding/kafka_client_consumer_record_data_binding.bal
examples/kafka-client-consumer-sasl/kafka_client_consumer_sasl.bal
examples/kafka-client-consumer-ssl/kafka_client_consumer_ssl.bal
examples/kafka-client-payload-data-binding/kafka_client_payload_data_binding.bal
examples/kafka-service-consume-message/kafka_service_consume_message.bal
examples/kafka-service-sasl/kafka_service_sasl.bal
examples/kafka-service-ssl/kafka_service_ssl.bal

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3694 …

Change topic array to string

---

examples/graphql-hello-world/graphql_hello_world.md

Move the API docs link to the bottom of the BBE

---

examples/configurable-variables/configurable_variables.bal

$subject 
https://github.com/wso2-enterprise/internal-support-ballerina/issues/210
This is to reduce wrong configurable usages in choreo. …

[master] Improve configurable BBE

---

examples/configurable-variables/configurable_variables.bal

$subject 
https://github.com/wso2-enterprise/internal-support-ballerina/issues/210
This is to reduce wrong configurable usages in choreo. …

[2201.3.x] Improve configurable BBE

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md
examples/graphql-context/graphql_context.md
examples/graphql-directives/graphql_directives.md
examples/graphql-documentation/graphql_documentation.md
examples/graphql-file-upload/graphql_file_upload.md
examples/graphql-graphiql/graphql_graphiql.md
examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md
examples/graphql-input-objects/graphql_input_objects.md
examples/graphql-input-types/graphql_input_types.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
examples/graphql-service-oauth2/graphql_service_oauth2.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
examples/graphql-subscriptions/graphql_subscriptions.md

Add related links section in the GraphQL BBEs

---

examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

$subject.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/5863

Improve links to API documentation from sql bbes

---

examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

Fix specification link

---

examples/index.json
examples/serdes-simple/serdes_simple.md

> This pr updates the title and adds a related link section …

Update serdes bbe

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md
examples/graphql-context/graphql_context.md
examples/graphql-directives/graphql_directives.md
examples/graphql-documentation/graphql_documentation.md
examples/graphql-file-upload/graphql_file_upload.md
examples/graphql-graphiql/graphql_graphiql.md
examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md
examples/graphql-input-objects/graphql_input_objects.md
examples/graphql-input-types/graphql_input_types.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
examples/graphql-service-oauth2/graphql_service_oauth2.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
examples/graphql-subscriptions/graphql_subscriptions.md

Remove the fullstop in the related links section in GraphQL BBEs

---

examples/serdes-simple/serdes_simple.md

Remove full stop from related links section in serdes bbe

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md
examples/graphql-context/graphql_context.md
examples/graphql-directives/graphql_directives.md
examples/graphql-documentation/graphql_documentation.md
examples/graphql-file-upload/graphql_file_upload.md
examples/graphql-graphiql/graphql_graphiql.md
examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md
examples/graphql-input-objects/graphql_input_objects.md
examples/graphql-input-types/graphql_input_types.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
examples/graphql-service-oauth2/graphql_service_oauth2.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
examples/graphql-subscriptions/graphql_subscriptions.md

Fix related links section title

---

examples/nats-basic-pub/nats-basic-pub.md
examples/nats-basic-reply/nats-basic-reply.md
examples/nats-basic-request/nats-basic-request.md
examples/nats-basic-sub/nats-basic-sub.md
examples/nats-client-basic-auth/nats-client-basic-auth.md
examples/nats-client-secure-connection/nats-client-secure-connection.md
examples/nats-service-basic-auth/nats-service-basic-auth.md
examples/nats-service-secure-connection/nats-service-secure-connection.md
examples/rabbitmq-client-basic-auth/rabbitmq_client_basic_auth.md
examples/rabbitmq-client-secure-connection/rabbitmq_client_secure_connection.md
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.md
examples/rabbitmq-consumer/rabbitmq_consumer.md
examples/rabbitmq-producer/rabbitmq_producer.md
examples/rabbitmq-queue-declare/rabbitmq_queue_declare.md
examples/rabbitmq-service-basic-auth/rabbitmq_service_basic_auth.md
examples/rabbitmq-service-secure-connection/rabbitmq_service_secure_connection.md
examples/rabbitmq-sync-consumer/rabbitmq_sync_consumer.md
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.md
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.md

Add related links section in the NATS and RabbitMQ BBEs 

---

examples/grpc-client-unary/grpc_client_unary.md

Update bal file name

---

examples/websocket-basic-sample/websocket_basic_sample.md
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.md

Restructure BBEs

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md
examples/graphql-context/graphql_context.md
examples/graphql-directives/graphql_directives.md
examples/graphql-documentation/graphql_documentation.md
examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md
examples/graphql-input-objects/graphql_input_objects.md
examples/graphql-input-types/graphql_input_types.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-subscriptions/graphql_subscriptions.md

Change the client info to a tip in GraphQL BBEs

---

examples/index.json

Move `HTTP client resiliency` section to column 0

---

examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-service/receive_email_using_service.bal
examples/receive-email-using-service/receive_email_using_service.md
examples/receive-email-using-service/receive_email_using_service.out
examples/send-email/send_email.bal
examples/send-email/send_email.md
examples/websub-webhook-sample/websub_webhook_sample.bal
examples/websub-webhook-sample/websub_webhook_sample.md

Fix related links of Websub and Email BBEs

---

gradle.properties

Update the standard library dependency versions

---

examples/tcp-client/tcp_client.bal
examples/tcp-client/tcp_client.md
examples/tcp-client/tcp_client.out
examples/tcp-listener/tcp_listener.out

Fix tcp BBEs

---

examples/http-1-1-to-2-0-protocol-switch/http_1_1_to_2_0_protocol_switch.md
examples/http-access-logs/http_access_logs.md
examples/http-basic-rest-service/http_basic_rest_service.md
examples/http-caching-client/http_caching_client.md
examples/http-circuit-breaker/http_circuit_breaker.md
examples/http-client-data-binding/http_client_data_binding.md
examples/http-client-redirects/http_client_redirects.md
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.md
examples/http-default-resource/http_default_resource.md
examples/http-error-handling/http_error_handling.md
examples/http-failover/http_failover.md
examples/http-header-param/http_header_param.md
examples/http-interceptor-error-handling/http_interceptor_error_handling.md
examples/http-load-balancer/http_load_balancer.md
examples/http-path-param/http_path_param.md
examples/http-query-parameter/http_query_parameter.md
examples/http-request-interceptors/http_request_interceptors.md
examples/http-response-interceptors/http_response_interceptors.md
examples/http-retry/http_retry.md
examples/http-send-different-status-codes/http_send_different_status_codes.md
examples/http-send-response/http_send_response.md
examples/http-service-chunking/http_service_chunking.md
examples/http-service-path-and-resource-name/http_service_path_and_resource_name.md
examples/http-service-redirects/http_service_redirects.md
examples/http-timeout/http_timeout.md
examples/http-trace-logs/http_trace_logs.md
examples/index.json
examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-service/receive_email_using_service.md
examples/websub-webhook-sample/websub_webhook_sample.md

Fix HTTP BBEs inconsistencies

---

gradle.properties

Update GraphQL version for rc3 pack

---

examples/tcp-client-ssl-tls/tcp_client_ssl_tls.md
examples/tcp-client/tcp_client.md
examples/tcp-listener/tcp_listener.md
examples/tcp-service-ssl-tls/tcp_service_ssl_tls.md
examples/udp-client/udp_client.md
examples/udp-connect-client/udp_connect_client.md
examples/udp-listener/udp_listener.md
examples/websocket-basic-sample/websocket_basic_sample.md
examples/websocket-client-basic-auth/websocket_client_basic_auth.bal
examples/websocket-client-basic-auth/websocket_client_basic_auth.md
examples/websocket-client-bearer-token-auth/websocket_client_bearer_token_auth.md
examples/websocket-client-mutual-ssl/websocket_client_mutual_ssl.md
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.md
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.md
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.md
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.md
examples/websocket-client-self-signed-jwt-auth/websocket_client_self_signed_jwt_auth.md
examples/websocket-client-ssl-tls/websocket_client_ssl_tls.md
examples/websocket-retry-client/websocket_retry_client.md
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.md
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.md
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.md
examples/websocket-service-mutual-ssl/websocket_service_mutual_ssl.md
examples/websocket-service-oauth2/websocket_service_oauth2.md
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.md

Revamp TCP, UDP, WebSocket BBE md files

---

examples/tcp-client-ssl-tls/tcp_client_ssl_tls.md
examples/tcp-client/tcp_client.md
examples/websocket-client/websocket_client.md

Add missing run command

---

examples/tcp-client-ssl-tls/tcp_client_ssl_tls.md

Replace start a with start the

---

examples/tcp-client-ssl-tls/tcp_client_ssl_tls.bal
examples/tcp-listener/tcp_listener.md
examples/udp-client/udp_client.out
examples/udp-connect-client/udp_connect_client.bal
examples/udp-connect-client/udp_connect_client.out
examples/udp-listener/udp_listener.out
examples/websocket-basic-sample/websocket_basic_sample.md
examples/websocket-client/websocket_client.md
examples/websocket-client/websocket_client.out
examples/websocket-retry-client/websocket_retry_client.out
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.server.out

Update WebSocket, TCP and UDP BBEs

Update WebSocket, TCP and UDP BBEs

---

gradle.properties

Ballerina lang version bump

---

examples/kafka-service-consume-message/kafka_service_consume_message.bal

Update variable name

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md

Reword the prerequisite in the GraphQL client BBE

---

examples/nats-basic-pub/nats-basic-pub.md
examples/nats-basic-reply/nats-basic-reply.bal
examples/nats-basic-reply/nats-basic-reply.md
examples/nats-basic-request/nats-basic-request.bal
examples/nats-basic-request/nats-basic-request.md
examples/nats-basic-sub/nats-basic-sub.bal
examples/nats-basic-sub/nats-basic-sub.md
examples/nats-client-basic-auth/nats-client-basic-auth.md
examples/nats-client-secure-connection/nats-client-secure-connection.md
examples/nats-service-basic-auth/nats-service-basic-auth.md
examples/nats-service-secure-connection/nats-service-secure-connection.md

Update NATS BBE content

---

examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.bal
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.bal
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.bal
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.bal
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.bal
examples/mysql-query-row-operation/mysql_query_row_operation.md

Add prerequisites section to sql bbes

---

examples/jdbc-atomic-transaction/jdbc_atomic_transaction.md
examples/jdbc-batch-execute-operation/jdbc_batch_execute_operation.md
examples/jdbc-execute-operation/jdbc_execute_operation.md
examples/jdbc-query-column-mapping/jdbc_query_column_mapping.md
examples/jdbc-query-operation/jdbc_query_operation.md
examples/jdbc-query-row-operation/jdbc_query_row_operation.md
examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

Remove execution command from Prerequisites

---

examples/http-caching-client/http_caching_client.md
examples/http-client-basic-authentication/http_client_basic_authentication.md
examples/http-client-data-binding/http_client_data_binding.md
examples/http-client-file-upload/http_client_file_upload.md
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.md
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.md
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.md
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.md
examples/http-client-redirects/http_client_redirects.md
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.md
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.md
examples/http-client-ssl-tls/http_client_ssl_tls.md

Fix inconsistencies in HTTP BBEs

---

examples/http-circuit-breaker/http_circuit_breaker.bal
examples/http-circuit-breaker/http_circuit_breaker.md
examples/http-client-chunking/http_client_chunking.bal
examples/http-client-chunking/http_client_chunking.md
examples/http-client-data-binding/http_client_data_binding.md
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.md
examples/http-failover/http_failover.bal
examples/http-failover/http_failover.md
examples/http-load-balancer/http_load_balancer.bal
examples/http-load-balancer/http_load_balancer.md
examples/http-retry/http_retry.bal
examples/http-retry/http_retry.md
examples/http-timeout/http_timeout.bal
examples/http-timeout/http_timeout.md

> $Subject
> $Subject
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. …

Refactor HTTP BBEs to use basic REST service as prerequisite

---

examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.bal
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.bal
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.bal
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.bal
examples/graphql-service-oauth2/graphql_service_oauth2.bal
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.bal

Update GraphQL Security BBEs with Profile Type

---

examples/graphql-client-query-endpoint/graphql_client_query_endpoint.bal

Remove the Http Part from GraphQL Client Endpoint URL

---

examples/http-service-mutual-ssl/http_service_mutual_ssl.md
examples/tcp-listener/tcp_listener.md
examples/udp-listener/udp_listener.md
examples/websocket-basic-sample/websocket_basic_sample.md
examples/websocket-client/websocket_client.md
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.md
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.md
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.md
examples/websocket-service-mutual-ssl/websocket_service_mutual_ssl.md
examples/websocket-service-oauth2/websocket_service_oauth2.md
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.md

Add missing tips

---

examples/serdes-simple/serdes_simple.md

Add description before program output in serdes BBE

---

examples/http-caching-client/http_caching_client.md
examples/http-circuit-breaker/http_circuit_breaker.md
examples/http-client-basic-authentication/http_client_basic_authentication.md
examples/http-client-bearer-token-authentication/http_client_bearer_token_authentication.md
examples/http-client-chunking/http_client_chunking.md
examples/http-client-data-binding/http_client_data_binding.md
examples/http-client-file-upload/http_client_file_upload.md
examples/http-client-mutual-ssl/http_client_mutual_ssl.md
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.md
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.md
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.md
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.md
examples/http-client-redirects/http_client_redirects.md
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.md
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.md
examples/http-client-ssl-tls/http_client_ssl_tls.md
examples/http-failover/http_failover.md
examples/http-load-balancer/http_load_balancer.md
examples/http-retry/http_retry.md
examples/http-service-basic-authentication-ldap-user-store/http_service_basic_authentication_ldap_user_store.md
examples/http-service-mutual-ssl/http_service_mutual_ssl.md
examples/http-service-oauth2/http_service_oauth2.md
examples/http-service-ssl-tls/http_service_ssl_tls.md
examples/http-timeout/http_timeout.md

Make HTTP BBEs consistent

---

examples/nats-basic-pub/nats-basic-pub.bal
examples/nats-basic-pub/nats-basic-pub.md
examples/nats-basic-reply/nats-basic-reply.bal
examples/nats-basic-reply/nats-basic-reply.md
examples/nats-basic-request/nats-basic-request.bal
examples/nats-basic-request/nats-basic-request.md
examples/nats-basic-sub/nats-basic-sub.bal
examples/nats-basic-sub/nats-basic-sub.md
examples/nats-client-basic-auth/nats-client-basic-auth.bal
examples/nats-client-basic-auth/nats-client-basic-auth.md
examples/nats-client-secure-connection/nats-client-secure-connection.bal
examples/nats-client-secure-connection/nats-client-secure-connection.md
examples/nats-service-basic-auth/nats-service-basic-auth.md
examples/nats-service-secure-connection/nats-service-secure-connection.md

Update NATS BBEs

---

examples/http-basic-rest-service/http_basic_rest_service.md
examples/http-client-basic-authentication/http_client_basic_authentication.bal
examples/http-client-bearer-token-authentication/http_client_bearer_token_authentication.bal
examples/http-client-mutual-ssl/http_client_mutual_ssl.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.bal
examples/http-client-ssl-tls/http_client_ssl_tls.bal

Revamp HTTP BBEs

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

$ subject
- Related to - https://github.com/ballerina-platform/ballerina-distribution/issues/2839 …

Log the gh workflow HTTP response

---

examples/ftp-client-read/ftp_client_read.bal
examples/ftp-client-write/ftp_client_write.bal
examples/ftp-service-read-write/ftp_service_read_write.bal
examples/kafka-client-constraint-validation/kafka_client_constraint_validation.bal
examples/kafka-client-consumer-record-data-binding/kafka_client_consumer_record_data_binding.bal
examples/kafka-client-consumer-sasl/kafka_client_consumer_sasl.bal
examples/kafka-client-consumer-ssl/kafka_client_consumer_ssl.bal
examples/kafka-client-payload-data-binding/kafka_client_payload_data_binding.bal
examples/kafka-client-produce-message/kafka_client_produce_message.bal
examples/kafka-client-producer-sasl/kafka_client_producer_sasl.bal
examples/kafka-client-producer-ssl/kafka_client_producer_ssl.bal
examples/kafka-service-consume-message/kafka_service_consume_message.bal
examples/kafka-service-sasl/kafka_service_sasl.bal
examples/kafka-service-ssl/kafka_service_ssl.bal
examples/sftp-client-read/sftp_client_read.bal
examples/sftp-client-write/sftp_client_write.bal
examples/sftp-service-read-write/sftp_service_read_write.bal

Update ftp/kafka bbes according to the reviews

---

examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
examples/rabbitmq-consumer/rabbitmq_consumer.bal
examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-queue-declare/rabbitmq_queue_declare.bal
examples/rabbitmq-sync-consumer/rabbitmq_sync_consumer.bal
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

Add review changes to RabbitMQ BBEs

---

gradle.properties

Update cloud stable version for 2201.3.0 release

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync 1.2.x with release 1.2.34

---

examples/nats-basic-pub/nats-basic-pub.bal
examples/nats-basic-reply/nats-basic-reply.bal
examples/nats-basic-request/nats-basic-request.bal
examples/nats-basic-sub/nats-basic-sub.bal
examples/nats-client-basic-auth/nats-client-basic-auth.bal
examples/nats-client-secure-connection/nats-client-secure-connection.bal
examples/nats-service-secure-connection/nats-service-secure-connection.bal

$subject
**Verified running.**

Add review changes to NATS BBEs

---

gradle.properties

Update asyncapi version for 2201.3.0

---

examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md

> $Subject
Related to : https://github.com/ballerina-platform/ballerina-standard-library/issues/3728
> Link to the PR for changes …

Update graphql security BBEs with spec links

---

gradle.properties

Update versions for 2201.3.0 release

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/resources/central/projectE/Ballerina.toml
project-api-tests/src/test/resources/central/projectE/Package.md
project-api-tests/src/test/resources/central/projectE/main.bal
project-api-tests/src/test/resources/central/projectF/Ballerina.toml
project-api-tests/src/test/resources/central/projectF/Package.md
project-api-tests/src/test/resources/central/projectF/main.bal
project-api-tests/src/test/resources/central/projectG/Ballerina.toml
project-api-tests/src/test/resources/central/projectG/Package.md
project-api-tests/src/test/resources/central/projectG/main.bal

Fixes - https://github.com/ballerina-platform/ballerina-distribution/issues/3622
Related issue - https://github.com/ballerina-platform/ballerina-lang/issues/37513
Tests if calling `bal pull <package_org>/<package_name>` pulls all dependencies including indirect dependencies.
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question …

Add central tests to test if `bal pull` pulls all dependencies of the pulled package

---

examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
examples/graphql-input-objects/graphql_input_objects.bal
examples/graphql-mutations/graphql_mutations.bal
examples/graphql-mutations/graphql_mutations.client.out
examples/graphql-mutations/graphql_mutations.graphql
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md

Rewrite GraphQL BBEs using tables

---

examples/http-client-basic-authentication/http_client_basic_authentication.bal
examples/http-client-bearer-token-authentication/http_client_bearer_token_authentication.bal
examples/http-client-chunking/http_client_chunking.bal
examples/http-client-data-binding/http_client_data_binding.bal
examples/http-client-mutual-ssl/http_client_mutual_ssl.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.bal
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.md
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.metatags
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.out
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.bal
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.bal
examples/http-client-ssl-tls/http_client_ssl_tls.bal
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.bal
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.client.out
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.md
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.metatags
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.server.out
examples/http-service-payload-constraint-validation/tests/http_service_payload_constraint_validation.bal
examples/http-timeout/http_timeout.bal
examples/index.json

Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3484 …

Add http constraint validation bbes

---

examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.md
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.md
examples/mysql-execute-operation/mysql_execute_operation.md
examples/mysql-query-column-mapping/mysql_query_column_mapping.md
examples/mysql-query-operation/mysql_query_operation.md
examples/mysql-query-row-operation/mysql_query_row_operation.md

Fix tip formatting

---

gradle.properties

Update grpc version for 2201.2.x

---

examples/provide-function-arguments-by-name/provide_function_arguments_by_name.md

Add the `code` and `out` prefixes to the `provide_function_arguments_by_name.md`file. …

Add prefixes to the `provide_function_arguments_by_name.md` file

---

examples/index.json
examples/websocket-client-payload-constraint-validation/websocket_client_payload_constraint_validation.bal
examples/websocket-client-payload-constraint-validation/websocket_client_payload_constraint_validation.md
examples/websocket-client-payload-constraint-validation/websocket_client_payload_constraint_validation.metatags
examples/websocket-client-payload-constraint-validation/websocket_client_payload_constraint_validation.out
examples/websocket-service-payload-constraint-validation/websocket_service_payload_constraint_validation.bal
examples/websocket-service-payload-constraint-validation/websocket_service_payload_constraint_validation.md
examples/websocket-service-payload-constraint-validation/websocket_service_payload_constraint_validation.metatags
examples/websocket-service-payload-constraint-validation/websocket_service_payload_constraint_validation.out

Add WebSocket constraint BBEs

---

examples/graphql-client-error-handling/graphql_client_error_handling.bal
examples/graphql-client-error-handling/graphql_client_error_handling.md
examples/graphql-client-error-handling/graphql_client_error_handling.metatags
examples/graphql-client-error-handling/graphql_client_error_handling.out
examples/index.json

> Fixes: [#3743](https://github.com/ballerina-platform/ballerina-standard-library/issues/3743) …

Add graphql client error handling BBE

---

examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

Fix formatting in RabbitMQ BBEs

---

examples/graphql-client-error-handling/graphql_client_error_handling.md

Fix a typo in GraphQL client BBE

---

examples/graphql-client-error-handling/graphql_client_error_handling.md
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md
examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.md
examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
examples/graphql-context/graphql_context.md
examples/graphql-directives/graphql_directives.md
examples/graphql-documentation/graphql_documentation.md
examples/graphql-file-upload/graphql_file_upload.md
examples/graphql-graphiql/graphql_graphiql.md
examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md
examples/graphql-input-objects/graphql_input_objects.md
examples/graphql-input-types/graphql_input_types.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
examples/graphql-service-oauth2/graphql_service_oauth2.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
examples/graphql-subscriptions/graphql_subscriptions.md

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-distribution/issues/3672

Make specification links consistent

---

examples/http-client-header-parameter/http_client_header_parameter.bal
examples/http-client-header-parameter/http_client_header_parameter.md
examples/http-client-header-parameter/http_client_header_parameter.metatags
examples/http-client-header-parameter/http_client_header_parameter.out
examples/http-client-path-parameter/http_client_path_parameter.bal
examples/http-client-path-parameter/http_client_path_parameter.md
examples/http-client-path-parameter/http_client_path_parameter.metatags
examples/http-client-path-parameter/http_client_path_parameter.out
examples/http-client-query-parameter/http_client_query_parameter.bal
examples/http-client-query-parameter/http_client_query_parameter.md
examples/http-client-query-parameter/http_client_query_parameter.metatags
examples/http-client-query-parameter/http_client_query_parameter.out
examples/index.json

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3694 …

Add path,query and header parameter BBEs

---

examples/websocket-client-payload-constraint-validation/websocket_client_payload_constraint_validation.bal
examples/websocket-client-payload-constraint-validation/websocket_client_payload_constraint_validation.md
examples/websocket-service-payload-constraint-validation/websocket_service_payload_constraint_validation.md

Address review suggestions in constraint BBEs

---

examples/index.json
examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-service/receive_email_using_service.md
examples/send-email/send_email.md
examples/websub-webhook-sample/websub_webhook_sample.md

Address review suggestions in email/websub bbes

---

.github/workflows/daily-build-2201.2.x.yml
.github/workflows/daily-build.yml

Run project-api-tests in a seperate job

---

gradle.properties

Update stdlib version to the latest

---

examples/nil/nil.md

Remove backticks in the word nil. …

Remove backticks in the word nil

---

examples/http-client-header-parameter/http_client_header_parameter.bal
examples/http-client-path-parameter/http_client_path_parameter.bal
examples/http-client-path-parameter/http_client_path_parameter.md
examples/http-client-path-parameter/http_client_path_parameter.out
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.bal
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.md
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.out
examples/http-client-query-parameter/http_client_query_parameter.bal
examples/http-client-query-parameter/http_client_query_parameter.md
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.bal
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.md
examples/kafka-client-constraint-validation/kafka_client_constraint_validation.bal
examples/kafka-client-constraint-validation/kafka_client_constraint_validation.md
examples/kafka-service-constraint-validation/kafka_service_constraint_validation.bal
examples/kafka-service-constraint-validation/kafka_service_constraint_validation.md

Add changes from review comments

---

examples/nats-service-constraint-validation/nats_service_constraint_validation.bal
examples/nats-service-constraint-validation/nats_service_constraint_validation.md
examples/nats-service-constraint-validation/nats_service_constraint_validation.metatags
examples/nats-service-constraint-validation/nats_service_constraint_validation.out
examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.bal
examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.md
examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.metatags
examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.out
examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.bal
examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.md
examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.metatags
examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.out

Add constraint BBEs for NATS and RabbitMQ

---

examples/mysql-atomic-transaction/mysql_atomic_transaction.md
examples/mysql-atomic-transaction/mysql_atomic_xa_transaction.bal

(cherry picked from commit 2ceec0556929bf8eece8d8a9309d7fe8ae806f76)
$subject

Move code snippet to separate bal file

---

gradle.properties

[master]Update OpenAPI version

---

examples/index.json
examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-service/receive_email_using_service.md
examples/send-email/send_email.md
examples/websub-webhook-sample/websub_webhook_sample.bal
examples/websub-webhook-sample/websub_webhook_sample.md

Include review suggestions for websub/email bbes

---

examples/index.json

Add NATS and RabbitMQ constraint BBEs to index.json

Update examples index.json

---

examples/graphql-file-upload/graphql_file_upload.client.out

Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3779 …

Fix curl command of graphql file upload BBE

---

examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.bal

> Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3781 …

Fix graphql client basic auth BBE indentation

---

examples/http-2-prior-knowledge-client/http_2_prior_knowledge_client.bal
examples/http-client-chunking/http_client_chunking.bal
examples/http-client-header-parameter/http_client_header_parameter.md
examples/http-client-header-parameter/http_client_header_parameter_header.bal
examples/http-client-query-parameter/http_client_query_parameter.bal
examples/http-client-query-parameter/http_client_query_parameter.md
examples/http-client-query-parameter/http_client_query_parameter.out
examples/http-client-query-parameter/http_client_query_parameter_post.bal
examples/http-client-redirects/http_client_redirects.md
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.bal
examples/http-client-send-request-receive-response/http_client_send_request_receive_response.md
examples/http-query-parameter/http_query_parameter.bal
examples/http-query-parameter/http_query_parameter.client.out

Add changes from reviews

---

examples/http-send-different-status-codes-with-payload/http_send_different_status_codes_with_payload.md

Fix missing file error

---

examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.md
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md

Fix typo in graphql BBE

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/resources/central/projectE/Ballerina.toml
project-api-tests/src/test/resources/central/projectE/Package.md
project-api-tests/src/test/resources/central/projectE/main.bal
project-api-tests/src/test/resources/central/projectF/Ballerina.toml
project-api-tests/src/test/resources/central/projectF/Package.md
project-api-tests/src/test/resources/central/projectF/main.bal
project-api-tests/src/test/resources/central/projectG/Ballerina.toml
project-api-tests/src/test/resources/central/projectG/Package.md
project-api-tests/src/test/resources/central/projectG/main.bal

Fixes - https://github.com/ballerina-platform/ballerina-distribution/issues/3622
Related issue - https://github.com/ballerina-platform/ballerina-lang/issues/37513
Master PR - https://github.com/ballerina-platform/ballerina-distribution/pull/3422
Tests if calling bal pull <package_org>/<package_name> pulls all dependencies including indirect dependencies.
> Link(s) to product …

[2201.3.x] Add central tests to test if bal pull pulls all dependencies of the pulled package

---

gradle.properties

Update `http` version

---

gradle.properties

Bump c2c version

---

.github/workflows/daily-build.yml

Run project-api tests in a separate job

---

ballerina-test-automation/gradle.properties
gradle.properties

Update version to 2201.2.4-rc1

---

ballerina/build.gradle

Fix xmldata BBE output verification failure

---

examples/http-2-to-1-1-downgrade-service/tests/http_2_0_to_1_1_downgrade_service_test.bal
examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal

[2201.3.x] Fix BBE test failures

---

examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.bal
examples/grpc-client-set-deadline/grpc_simple.proto
examples/grpc-server-reflection/grpc_simple.proto
examples/grpc-service-check-deadline/grpc_simple.proto
examples/grpc-service-unary/grpc_service_unary.bal

Fix bbe build failures in grpc

---

examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.bal
examples/grpc-client-set-deadline/grpc_simple.proto
examples/grpc-server-reflection/grpc_simple.proto
examples/grpc-service-check-deadline/grpc_simple.proto
examples/grpc-service-unary/grpc_service_unary.bal

[2201.3.x] Fix grpc bbe build failures

---

.github/workflows/daily-build-2201.3.x.yml

Add daily build for 2201.3.x

---

gradle.properties

Update serdes version

---

gradle.properties

Update xmldata package version

---

examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.bal
examples/grpc-client-set-deadline/grpc_simple.proto
examples/grpc-server-reflection/grpc_simple.proto
examples/grpc-service-check-deadline/grpc_simple.proto
examples/grpc-service-unary/grpc_service_unary.bal
examples/http-2-to-1-1-downgrade-service/tests/http_2_0_to_1_1_downgrade_service_test.bal
examples/http-matrix-param/tests/http_matrix_param_test.bal
examples/http-query-parameter/tests/http_query_parameter_test.bal
examples/http-retry/tests/http_retry_test.bal
examples/http-service-redirects/tests/http_service_redirects_test.bal
examples/index.json
examples/websocket-basic-sample/tests/websocket_basic_sample_test.bal

Fix BBE build failures

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml

Set dotnet-guid version in windows installer build

---

gradle.properties

$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517 …

Bump versions for type-reference support

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
ballerina-test/src/test/resources/openapi/expected/types.bal
gradle.properties

[Master]Update OpenAPI version and tests

---

examples/http-client-query-parameter/http_client_query_parameter.md
examples/http-query-parameter/http_query_parameter.md

Rewrite query param service/client BBEs

---

gradle.properties

Change lang version to `2201.2.4`

---

examples/http-basic-rest-service/http_basic_rest_service.server.out
examples/http-query-parameter/http_query_parameter.md

Align file name with dir name

---

examples/ftp-client-read/ftp_client_read.bal
examples/ftp-client-write/ftp_client_write.bal
examples/ftp-service-read-write/ftp_service_read_write.bal
examples/ftp-service-read/ftp_service_read.bal
examples/sftp-client-read/sftp_client_read.bal
examples/sftp-client-write/sftp_client_write.bal
examples/sftp-service-read-write/sftp_service_read_write.bal

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3804 …

Update ftp examples

---

gradle.properties

Update observe version

---

gradle.properties

Update ballerinai-observe version

---

examples/grpc-client-basic-auth/grpc_client_basic_auth.md
examples/grpc-client-bearer-token-auth/grpc_client_bearer_token_auth.md
examples/grpc-client-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-client-client-streaming/grpc_client_streaming.md
examples/grpc-client-headers/grpc_simple_with_headers.md
examples/grpc-client-mutual-ssl/grpc_client_mutual_ssl.md
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.md
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.md
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.md
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.md
examples/grpc-client-self-signed-jwt-auth/grpc_client_self_signed_jwt_auth.md
examples/grpc-client-server-streaming/grpc_server_streaming.md
examples/grpc-client-set-deadline/grpc_client_set_deadline.md
examples/grpc-client-ssl-tls/grpc_client_ssl_tls.md
examples/grpc-client-unary/grpc_client_unary.md
examples/grpc-server-reflection/grpc_server_reflection.md
examples/grpc-service-basic-auth-file-user-store/grpc_service_basic_auth_file_user_store.md
examples/grpc-service-bidirectional-streaming/grpc_bidirectional_streaming.md
examples/grpc-service-check-deadline/grpc_service_check_deadline.md
examples/grpc-service-client-streaming/grpc_client_streaming.md
examples/grpc-service-headers/grpc_simple_with_headers.md
examples/grpc-service-jwt-auth/grpc_service_jwt_auth.md
examples/grpc-service-mutual-ssl/grpc_service_mutual_ssl.md
examples/grpc-service-oauth2/grpc_service_oauth2.md
examples/grpc-service-server-streaming/grpc_server_streaming.md

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3804 …

Update execute step words

---

examples/serdes-simple/serdes_simple.md

Update the serdes bbes description
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3820
> Link …

Improve serdes bbe

---

examples/http-basic-rest-service/http_basic_rest_service.client.1.out
examples/http-basic-rest-service/http_basic_rest_service.client.2.out
examples/http-basic-rest-service/http_basic_rest_service.md

> $subject
Part of [#3812](https://github.com/ballerina-platform/ballerina-standard-library/issues/3812)

Separate curl commands in basic REST service

---

examples/graphql-client-error-handling/graphql_client_error_handling.out
examples/graphql-interfaces/graphql_interfaces.bal
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-union-types/graphql_service_union_types.bal
examples/graphql-service-union-types/graphql_service_union_types.graphql
examples/graphql-service-union-types/graphql_service_union_types.md
examples/graphql-service-union-types/graphql_service_union_types.metatags
examples/graphql-service-union-types/graphql_service_union_types.out
examples/graphql-service-union-types/graphql_service_union_types.server.out
examples/index.json

- Adding GraphQL union types BBE (Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3826)
- Fixing GraphQL BBE issues (Fixes: #3766)
- Fix small typographical errors in GraphQL BBEs

Add GraphQL Union Types BBE

---

examples/graphql-client-error-handling/graphql_client_error_handling.md
examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.md
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md

Update the graphql client bbes description so that it could answer following questions.
What does it do?
How to use it?
When to use it?
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3798
> Link(s) to product documentation that addresses the changes …

Improve graphql client bbes descriptions

---

examples/nats-client-secure-connection/nats_client_secure_connection.md

Rename incorrect file name

---

examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.md
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.md
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.md
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.md

> $Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3799 …

Rewrite HTTP OAuth2 client BBEs

---

examples/aws-lambda-deployment/aws_lambda_deployment.md
examples/azure-functions-deployment/azure_functions_deployment.md

$Subject
Resolves https://github.com/ballerina-platform/ballerina-distribution/issues/3814
Resolves https://github.com/ballerina-platform/ballerina-distribution/issues/3813
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

[master] Fix FaaS broken links in BBEs

---

examples/aws-lambda-deployment/aws_lambda_deployment.md
examples/azure-functions-deployment/azure_functions_deployment.md

[2201.3.x] Fix FaaS broken links in BBEs

---

examples/aws-lambda-deployment/aws_lambda_deployment.md
examples/azure-functions-deployment/azure_functions_deployment.md

[2201.2.x] Fix FaaS broken links in BBEs

---

examples/index.json

Fix typo in task BBE

---

examples/serdes-simple/serdes_simple.md

> Part of std-lib bbe hackathon …

Improve serdes BBE description

---

examples/graphql-client-error-handling/graphql_client_error_handling.bal
examples/graphql-client-error-handling/graphql_client_error_handling.md
examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.bal
examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.md
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.bal
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.md

> Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3798 …

Improve graphql client bbes

---

ballerina-test-automation/gradle.properties

Update lang version in installer tests

---

examples/http-service-jwt-authentication/http_service_jwt_authentication.md
examples/http-service-oauth2/http_service_oauth2.md

Reword authorization for JWT/OAuth2

---

examples/nats-basic-pub/nats_basic_pub.md
examples/nats-basic-reply/nats_basic_reply.md
examples/nats-basic-request/nats_basic_request.md
examples/nats-basic-sub/nats_basic_sub.md
examples/nats-client-basic-auth/nats_client_basic_auth.md
examples/nats-service-basic-auth/nats_service_basic_auth.md
examples/rabbitmq-client-basic-auth/rabbitmq_client_basic_auth.md
examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.md
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.md
examples/rabbitmq-consumer/rabbitmq_consumer.md
examples/rabbitmq-producer/rabbitmq_producer.md
examples/rabbitmq-queue-declare/rabbitmq_queue_declare.md
examples/rabbitmq-service-basic-auth/rabbitmq_service_basic_auth.md
examples/rabbitmq-sync-consumer/rabbitmq_sync_consumer.md
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.md
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.md

Update NATS and RabbitMQ BBE descriptions

---

examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.bal
examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.md
examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.bal
examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.bal
examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.bal
examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.bal
examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.bal
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.bal
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.bal
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.bal
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
examples/graphql-service-oauth2/graphql_service_oauth2.bal
examples/graphql-service-oauth2/graphql_service_oauth2.md
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.bal
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md

Fixes: [#3832](https://github.com/ballerina-platform/ballerina-standard-library/issues/3832)

Update GraphQL Security BBEs

---

examples/http-client-basic-authentication/http_client_basic_authentication.md
examples/http-client-bearer-token-authentication/http_client_bearer_token_authentication.md

Update the descriptions

---

examples/serdes-simple/serdes_simple.md

Update related links to sentence case

---

examples/http-circuit-breaker/http_circuit_breaker.md
examples/http-client-bearer-token-authentication/http_client_bearer_token_authentication.md
examples/http-client-payload-constraint-validation/http_client_payload_constraint_validation.md
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.md
examples/http-client-self-signed-jwt-authentication/http_client_self_signed_jwt_authentication.out
examples/http-cookies-client/http_cookies_client.md
examples/http-header-param/http_header_param.md
examples/http-interceptor-error-handling/http_interceptor_error_handling.bal
examples/http-service-mutual-ssl/http_service_mutual_ssl.client.out
examples/http-service-payload-constraint-validation/http_service_payload_constraint_validation.md
examples/http-service-ssl-tls/http_service_ssl_tls.client.out
examples/http-timeout/http_timeout.md

Fix inconsistencies with HTTP BBEs

---

examples/mysql-prerequisite/README.md
examples/mysql-prerequisite/create_stored_procedure.bal
examples/mysql-prerequisite/setup_database.bal

$subject
This is to fix the broken link issue in the pre-prod environment. this will not link to the prod-environment.

Add mysql prerequisit sample for the bbe revamp

---

examples/graphql-directives/graphql_directives.md

Fixes: [#3837](https://github.com/ballerina-platform/ballerina-distribution/issues/3837)

Fix Typo in GraphQL Directives BBE

---

examples/graphql-subscriptions/graphql_subscriptions.md

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-distribution/issues/3726

Update the GraphQL subscriptions BBE

---

examples/http-100-continue/http_100_continue.md
examples/http-compression/http_compression.bal
examples/http-compression/http_compression.md
examples/http-cors/http_cors.md
examples/http-default-resource/http_default_resource.bal
examples/http-default-resource/http_default_resource.md
examples/http-restrict-by-media-type/http_restrict_by_media_type.md
examples/http-service-file-upload/http_service_file_upload.bal
examples/http-service-file-upload/http_service_file_upload.md
examples/http-service-redirects/http_service_redirects.md

Reword HTTP advanced BBEs

---

examples/nats-basic-pub/nats_basic_pub.md
examples/nats-basic-sub/nats_basic_sub.md

Fix NATS subscriber description

---

gradle.properties

Update dev-tools version

---

examples/graphql-context/graphql_context.bal
examples/graphql-directives/graphql_directives.bal
examples/graphql-graphiql/graphql_graphiql.bal
examples/graphql-interceptors/graphql_interceptors.bal
examples/graphql-mutations/graphql_mutations.bal
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.bal
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.bal
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.bal
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.bal
examples/graphql-service-oauth2/graphql_service_oauth2.bal
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.bal
examples/graphql-subscriptions/graphql_subscriptions.bal

$Subject
Part of stdlib bbe hackathon …

Add or remove new lines to/from graphql service BBEs

---

examples/graphql-context/graphql_context.bal
examples/graphql-directives/graphql_directives.bal
examples/graphql-file-upload/graphql_file_upload.bal
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.bal
examples/graphql-input-objects/graphql_input_objects.bal
examples/graphql-interceptors/graphql_interceptors.bal
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.bal
examples/graphql-interfaces/graphql_interfaces.bal
examples/graphql-mutations/graphql_mutations.bal
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.bal
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-service-union-types/graphql_service_union_types.bal
examples/graphql-subscriptions/graphql_subscriptions.bal
examples/graphql-subscriptions/graphql_subscriptions.md

Update GraphQL BBE codes to match convention

---

examples/serdes-simple/serdes_simple.bal

Remove empty line from serdes bbe

---

examples/index.json

Update FTP urls

---

examples/websub-webhook-sample/websub_webhook_sample.md

> $subject
Part of [#3837](https://github.com/ballerina-platform/ballerina-standard-library/issues/3837)

Update websub bbe description

---

examples/serdes-simple/serdes_simple.bal

Part of standard library BBE hackathon …

Remove space after new keyword

---

examples/nats-basic-pub/nats_basic_pub.bal
examples/nats-basic-reply/nats_basic_reply.bal
examples/nats-basic-request/nats_basic_request.bal
examples/nats-basic-sub/nats_basic_sub.bal
examples/nats-client-basic-auth/nats_client_basic_auth.bal
examples/nats-client-secure-connection/nats_client_secure_connection.bal
examples/nats-client-secure-connection/nats_client_secure_connection.md
examples/nats-service-basic-auth/nats_service_basic_auth.bal
examples/nats-service-constraint-validation/nats_service_constraint_validation.bal
examples/nats-service-secure-connection/nats_service_secure_connection.bal
examples/nats-service-secure-connection/nats_service_secure_connection.md
examples/rabbitmq-client-basic-auth/rabbitmq_client_basic_auth.bal
examples/rabbitmq-client-secure-connection/rabbitmq_client_secure_connection.bal
examples/rabbitmq-client-secure-connection/rabbitmq_client_secure_connection.md
examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.bal
examples/rabbitmq-consumer/rabbitmq_consumer.bal
examples/rabbitmq-producer/rabbitmq_producer.bal
examples/rabbitmq-service-basic-auth/rabbitmq_service_basic_auth.bal
examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.bal
examples/rabbitmq-service-secure-connection/rabbitmq_service_secure_connection.bal
examples/rabbitmq-service-secure-connection/rabbitmq_service_secure_connection.md
examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.bal
examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.bal

Update NATS and RabbitMQ BBEs with latest conventions

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update versions for `2201.3.1-rc1`

---

examples/graphql-client-error-handling/graphql_client_error_handling.bal
examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.bal
examples/graphql-client-query-endpoint/graphql_client_query_endpoint.bal
examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.bal
examples/graphql-returning-service-objects/graphql_returning_service_objects.bal
examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.bal
examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.bal
examples/graphql-service-jwt-auth/graphql_service_jwt_auth.bal
examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.bal
examples/graphql-service-oauth2/graphql_service_oauth2.bal
examples/graphql-service-ssl-tls/graphql_service_ssl_tls.bal
examples/graphql-service-union-types/graphql_service_union_types.bal

Reverts ballerina-platform/ballerina-distribution#3875

Revert "Remove space after new keyword in graphql BBEs"

---

examples/nats-client-basic-auth/nats_client_basic_auth.bal
examples/nats-client-secure-connection/nats_client_secure_connection.bal
examples/nats-service-basic-auth/nats_service_basic_auth.bal
examples/nats-service-secure-connection/nats_service_secure_connection.bal
examples/rabbitmq-service-basic-auth/rabbitmq_service_basic_auth.bal
examples/rabbitmq-service-secure-connection/rabbitmq_service_secure_connection.bal

Fix formatting in NATS and RabbitMQ BBEs

---

examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.bal
examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.bal
examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.bal
examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.bal
examples/serdes-simple/serdes_simple.bal

> Part of stdlib bbe hackathon …

Add space after new keyword in graphql and serdes bbes

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update sql version for `2201.3.1-rc1`

---

examples/mysql-query-column-mapping/mysql_query_column_mapping.bal
examples/mysql-query-operation/mysql_simple_query.bal

Remove unnecessary check keyword

---

examples/websocket-basic-sample/websocket_basic_sample.bal
examples/websocket-service-basic-auth-file-user-store/websocket_service_basic_auth_file_user_store.bal
examples/websocket-service-basic-auth-ldap-user-store/websocket_service_basic_auth_ldap_user_store.bal
examples/websocket-service-jwt-auth/websocket_service_jwt_auth.bal
examples/websocket-service-mutual-ssl/websocket_service_mutual_ssl.bal
examples/websocket-service-oauth2/websocket_service_oauth2.bal
examples/websocket-service-payload-constraint-validation/websocket_service_payload_constraint_validation.bal
examples/websocket-service-ssl-tls/websocket_service_ssl_tls.bal

Replace `websocket:Error` with `error`

---

examples/receive-email-using-client/receive_email_using_client.bal
examples/receive-email-using-client/receive_email_using_client.md
examples/receive-email-using-client/receive_email_using_client.out
examples/receive-email-using-service/receive_email_using_service.bal
examples/receive-email-using-service/receive_email_using_service.md
examples/send-email/send_email.md

> $subject
Part of [#3837](https://github.com/ballerina-platform/ballerina-standard-library/issues/3837)

Update descriptions of email BBEs

---

examples/mysql-atomic-transaction/mysql_atomic_transaction.bal
examples/mysql-batch-execute-operation/mysql_batch_execute_operation.bal
examples/mysql-call-stored-procedures/mysql_call_stored_procedures.bal
examples/mysql-execute-operation/mysql_execute_operation.bal
examples/mysql-prerequisite/create_stored_procedure.bal
examples/mysql-query-column-mapping/mysql_query_column_mapping.bal
examples/mysql-query-operation/mysql_simple_query.bal
examples/mysql-query-row-operation/mysql_query_row.bal

Remove parameter names from new expression

---

examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.bal
examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.md
examples/graphql-client-handle-partial-response/graphql_client_handle_partial_response.out
examples/graphql-service-error-handling/graphql_service_error_handling.1.client.out
examples/graphql-service-error-handling/graphql_service_error_handling.1.graphql
examples/graphql-service-error-handling/graphql_service_error_handling.2.client.out
examples/graphql-service-error-handling/graphql_service_error_handling.2.graphql
examples/graphql-service-error-handling/graphql_service_error_handling.bal
examples/graphql-service-error-handling/graphql_service_error_handling.md
examples/graphql-service-error-handling/graphql_service_error_handling.metatags
examples/graphql-service-error-handling/graphql_service_error_handling.server.out
examples/index.json

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3863

Add GraphQL Service Error Handling BBE

---

examples/tcp-service-ssl-tls/tcp_service_ssl_tls.bal

Fix comments in tcp BBE

---

examples/http-default-error-handling/http_default_error_handling.server.out

Align dir name and output file name of http_default_error_handling

---

.github/workflows/main.yml

Skip project api tests in master branch build

---

examples/kafka-producer-produce-message/kafka_producer_produce_message.curl.out
examples/kafka-producer-sasl/kafka_producer_sasl.curl.out
examples/kafka-producer-ssl/kafka_producer_ssl.curl.out
examples/kafka-service-error-handling/kafka_service_error_handling.bal
examples/kafka-service-error-handling/kafka_service_error_handling.md
examples/kafka-service-error-handling/kafka_service_error_handling.metatags
examples/kafka-service-error-handling/kafka_service_error_handling.out

$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3804
Found an issue related to this,
https://github.com/ballerina-platform/ballerina-standard-library/issues/3884 …

Add kafka error handling bbe

---

examples/graphql-interceptors/graphql_interceptors.bal
examples/graphql-mutations/graphql_mutations.md

Add note te describe using remote methods for mutations

---

examples/index.json

Add error handling to index.json

---

examples/index.json

Rename error handler BBE

---

examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-subscriptions/graphql_subscriptions.md

Fix incorrect formatting in notes in BBEs

---

examples/http-error-handling/http_error_handling.bal
examples/http-interceptor-error-handling/http_interceptor_error_handling.bal
examples/index.json

Reposition error handling BBE and refactor interceptor BBEs

---

examples/grpc-service-simple/grpc_service_simple.bal

Fix descriptor name

---

.github/workflows/daily-build-2201.2.x.yml
.github/workflows/daily-build-2201.3.x.yml
.github/workflows/main.yml
.github/workflows/publish-release-artifacts-1.2.x.yml
.github/workflows/publish-release-artifacts.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
ballerina-test/src/test/resources/openapi/expected/types.bal
examples/aws-lambda-deployment/aws_lambda_deployment.md
examples/azure-functions-deployment/azure_functions_deployment.md
examples/http-query-parameter/tests/http_query_parameter_test.bal
examples/index.json
examples/jdbc-atomic-transaction/jdbc_atomic_transaction.out
examples/mysql-prerequisite/README.md
gradle.properties
project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

This reverts commit 8230536aae1c8109dbfeef9bc9d22ecd6a0b555f. …

Revert mistaken revert merge

---

ballerina-test-automation/gradle.properties
gradle.properties

Update version in installer tests

---

examples/email-client-ssl-tls/email_client_ssl_tls.bal
examples/email-client-ssl-tls/email_client_ssl_tls.md
examples/email-client-ssl-tls/email_client_ssl_tls.metatags
examples/email-client-ssl-tls/email_client_ssl_tls.out
examples/email-service-ssl-tls/email_service_ssl_tls.bal
examples/email-service-ssl-tls/email_service_ssl_tls.md
examples/email-service-ssl-tls/email_service_ssl_tls.metatags
examples/email-service-ssl-tls/email_service_ssl_tls.out
examples/index.json

> $subject
Fixes [#3878](https://github.com/ballerina-platform/ballerina-standard-library/issues/3878)

Add security BBEs for email module

---

examples/langlib-functions/langlib_functions.bal
examples/langlib-functions/langlib_functions.md
examples/langlib-functions/langlib_functions.out

This PR will update `Langlib functions BBE`.

Update BBE related to `Langlib functions`

---

examples/index.json
examples/init-function/init_function.bal
examples/init-function/init_function.md
examples/init-function/init_function.metatags
examples/init-function/init_function.out
examples/main-function/main_function.bal
examples/main-function/main_function.md
examples/main-function/main_function.metatags
examples/main-function/main_function.out

Add new BBEs for `main` , `init` functions 

---

examples/http-2-to-1-1-downgrade-client/http_2_to_1_1_downgrade_client.md
examples/http-2-to-1-1-downgrade-service/http_2_to_1_1_downgrade_service.md

Update HTTP/2 to HTTP/1.1 BBE with ALPN content

---

gradle.properties

Update log version to latest

---

examples/controlling-openness/controlling_openness.bal
examples/controlling-openness/controlling_openness.md
examples/controlling-openness/controlling_openness.metatags
examples/controlling-openness/controlling_openness.out
examples/default-values-for-record-fields/default_values_for_record_fields.bal
examples/default-values-for-record-fields/default_values_for_record_fields.md
examples/default-values-for-record-fields/default_values_for_record_fields.metatags
examples/default-values-for-record-fields/default_values_for_record_fields.out
examples/open-records/open_records.bal
examples/open-records/open_records.md
examples/open-records/open_records.metatags
examples/open-records/open_records.out
examples/type-inclusion-for-records/type_inclusion_for_records.bal
examples/type-inclusion-for-records/type_inclusion_for_records.md
examples/type-inclusion-for-records/type_inclusion_for_records.metatags
examples/type-inclusion-for-records/type_inclusion_for_records.out

Revamps the following BBEs
- Open records
- Controlling openness
- Type inclusion for records
- Default values for record fields
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3709

Revamp records related BBEs

---

examples/arrays/arrays.md
examples/binary-data/binary_data.md
examples/filler-values-of-a-list/filler_values_of_a_list.md
examples/list-equality/list_equality.md
examples/list-subtyping/list_subtyping.md
examples/nested-arrays/nested_arrays.md
examples/rest-type-in-tuples/rest_type_in_tuples.md
examples/tuples/tuples.md

Remove `- Ballerina by example` suffix from related links

---

examples/computed-field-key/computed_field_key.bal
examples/computed-field-key/computed_field_key.md
examples/computed-field-key/computed_field_key.metatags
examples/computed-field-key/computed_field_key.out
examples/maps/maps.bal
examples/maps/maps.md
examples/maps/maps.metatags
examples/maps/maps.out
examples/optional-fields/optional_fields.bal
examples/optional-fields/optional_fields.md
examples/optional-fields/optional_fields.metatags
examples/optional-fields/optional_fields.out
examples/records/records.bal
examples/records/records.md
examples/records/records.metatags
examples/records/records.out

This PR modifies the following BBEs.
- Maps BBE
- Records BBE
- Computed field key BBE
- Optional fields BBE
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/3709

Revamp mappings related BBEs

---

examples/index.json

Fix the name mismatch in `index.json`

---

examples/arrays/arrays.bal
examples/arrays/arrays.md
examples/binary-data/binary_data.md
examples/filler-values-of-a-list/filler_values_of_a_list.md
examples/list-equality/list_equality.bal
examples/list-equality/list_equality.md
examples/list-subtyping/list_subtyping.bal
examples/nested-arrays/nested_arrays.bal
examples/nested-arrays/nested_arrays.md
examples/rest-type-in-tuples/rest_type_in_tuples.md

Fix second set of issues related to list `BBEs`

---

examples/index.json

Disable playground icon in client BBEs

---

examples/function-values/function_values.md
examples/functions/functions.bal
examples/index.json

Correct mistakes in functions BBEs

---

examples/converting-from-json-to-user-defined-type-with-langlib-functions/converting_from_json_to_user_defined_type_with_langlib_functions.md

Change bal file name in md file

---

examples/http-client-redirects/http_client_redirects.bal
examples/http-client-redirects/http_client_redirects.md
examples/http-client-redirects/http_client_redirects.out
examples/http-client-redirects/tests/http_client_redirects_test.bal
examples/http-service-redirects/http_service_redirects.bal
examples/http-service-redirects/http_service_redirects.client.out
examples/http-service-redirects/http_service_redirects.md
examples/http-service-redirects/tests/http_service_redirects_test.bal

Rewrite redirect BBE

---

examples/http-request-with-multiparts/http_request_with_multiparts.md

Fix invalid file name

---

examples/index.json

Update index.json for client and service class BBE

---

examples/computed-field-key/computed_field_key.bal
examples/computed-field-key/computed_field_key.md
examples/computed-field-key/computed_field_key.metatags
examples/computed-field-key/computed_field_key.out
examples/maps/maps.bal
examples/maps/maps.md
examples/maps/maps.metatags
examples/maps/maps.out
examples/optional-fields/optional_fields.bal
examples/optional-fields/optional_fields.md
examples/optional-fields/optional_fields.metatags
examples/optional-fields/optional_fields.out
examples/records/records.bal
examples/records/records.md
examples/records/records.metatags
examples/records/records.out

Reverts ballerina-platform/ballerina-distribution#3884 which was merged to `master` instead of `bbe-revamp`.

Revert "Revamp mappings related BBEs"

---

examples/binding-patterns/binding_patterns.bal
examples/binding-patterns/binding_patterns.md
examples/binding-patterns/binding_patterns.metatags
examples/binding-patterns/binding_patterns.out
examples/index.json
examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.bal
examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.md
examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.metatags
examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.out
examples/list-binding-pattern/list_binding_pattern.bal
examples/list-binding-pattern/list_binding_pattern.md
examples/list-binding-pattern/list_binding_pattern.metatags
examples/list-binding-pattern/list_binding_pattern.out
examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.bal
examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.md
examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.metatags
examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.out
examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.bal
examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.md
examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.metatags
examples/rest-binding-pattern-in-list-binding-pattern/rest_binding_pattern_in_list_binding_pattern.out
examples/typed-binding-pattern/typed_binding_pattern.bal
examples/typed-binding-pattern/typed_binding_pattern.md
examples/typed-binding-pattern/typed_binding_pattern.metatags
examples/typed-binding-pattern/typed_binding_pattern.out
examples/wildcard-binding-pattern/wildcard_binding_pattern.bal
examples/wildcard-binding-pattern/wildcard_binding_pattern.md
examples/wildcard-binding-pattern/wildcard_binding_pattern.metatags
examples/wildcard-binding-pattern/wildcard_binding_pattern.out

This PR adds new BBEs for
- Binding patterns
- Typed binding pattern
- Wildcard binding pattern
- List binding pattern
- Rest binding pattern in list binding pattern
- List binding pattern in match statement
- Mapping binding pattern in match statement
Fixes : https://github.com/ballerina-platform/ballerina-distribution/issues/3710

Add new BBEs on binding patterns

---

examples/casting-json-to-user-defined-type/casting_json_to_user_defined_type.md
examples/converting-from-json-to-user-defined-type-with-langlib-functions/converting_from_json_to_user_defined_type_with_langlib_functions.md
examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.md

Change a related link in JSON BBE

---

examples/continue-statement/continue_statement.md

Fix continue statement BBE

---

examples/create-tables-with-query/create_tables_with_query.bal
examples/let-clause/let_clause.md
examples/querying-tables/querying_tables.bal

Fix issues related to query expression

---

build.gradle
gradle.properties

Add persist modules to the distribution

---

gradle.properties

update persist tool version

---

gradle.properties

Update persist module to latest nightly version

---

examples/http-caller/http_caller.md
examples/index.json

Append object part to request/response and caller

---

examples/http-caller/http_caller.md
examples/http-request-response/http_request_response.md

Append service part to request/response and caller

---

.github/workflows/daily-build-2201.2.x.yml
.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build.yml
.github/workflows/main.yml

Fix archieving short name zip

---

gradle.properties

Update persist module and tool version

---

examples/start-service-from-service-class-definition/start_service_from_service_class_definition.md

Correct file name name in service class BBE

---

examples/access-optional-json-elements/access_optional_json_elements.bal
examples/access-optional-json-elements/access_optional_json_elements.md
examples/access-optional-json-elements/access_optional_json_elements.out

> Fix `access optional json elements` BBE

Fix JSON BBE

---

examples/filler-values-of-a-list/filler_values_of_a_list.md

Temporary delete filler values table

---

examples/xml-templates-and-query/xml_templates_and_query.md

Fix BBE related changes

---

examples/access-optional-json-elements/access_optional_json_elements.md
examples/json-numbers/json_numbers.md
examples/resource-method-typing/resource_method_typing.md

Fix related links in JSON BBEs

---

examples/defining-classes/defining_classes.md
examples/distinct-object-types/distinct_object_types.md
examples/object/object.md
examples/visibility-of-object-fields-and-methods/visibility_of_object_fields_and_methods.md

Fix related links for object BBEs

---

examples/if-statement/if_statement.md
examples/if-statement/if_statement.out
examples/index.json

Fix BBE changes

---

examples/multiple-key-fields/multiple_key_fields.md
examples/structured-keys/structured_keys.md

Fix related links in table BBEs

---

examples/index.json

Reorder BBEs in BBE landing page

---

examples/index.json

Fix iteration BBE

---

examples/multiple-key-fields/multiple_key_fields.md
examples/resource-method-typing/resource_method_typing.md

Fix related links in BBEs

---

examples/index.json

Fix iteration BBEs

---

examples/c2c-docker-deployment/c2c_docker_deployment.md
examples/c2c-k8s-deployment/c2c_k8s_deployment.md

$Subject
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/6227 …

Fix broken links in c2c bbes

---

examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.bal

> Replace repetitive refreshConfig record with INFER_REFRESH_CONFIG
> Update scopes field with string value …

Update bbes realted to oauth2 password grant

---

examples/http-2-prior-knowledge-client/http_2_prior_knowledge_client.bal
examples/http-2-to-1-1-downgrade-client/http_2_to_1_1_downgrade_client.bal
examples/http-circuit-breaker/http_circuit_breaker.bal
examples/http-client-chunking/http_client_chunking.bal
examples/http-client-redirects/http_client_redirects.bal
examples/http-failover/http_failover.bal
examples/http-load-balancer/http_load_balancer.bal
examples/http-retry/http_retry.bal
examples/http-timeout/http_timeout.bal

Update return type to Album[]

---

examples/http-2-prior-knowledge-client/http_2_prior_knowledge_client.bal
examples/http-2-to-1-1-downgrade-client/http_2_to_1_1_downgrade_client.bal
examples/http-circuit-breaker/http_circuit_breaker.bal
examples/http-client-chunking/http_client_chunking.bal
examples/http-client-redirects/http_client_redirects.bal
examples/http-failover/http_failover.bal
examples/http-load-balancer/http_load_balancer.bal
examples/http-retry/http_retry.bal
examples/http-timeout/http_timeout.bal

[2201.3.x]Update return type to Album[]

---

build.gradle
gradle.properties

> Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3828

Add protoc tool to distribution

---

gradle.properties

update persist module version

---

examples/graphql-context/graphql_context.bal
examples/graphql-context/graphql_context.md
examples/graphql-directives/graphql_directives.md
examples/graphql-documentation/graphql_documentation.md
examples/graphql-hello-world/graphql_hello_world.md
examples/graphql-hierarchical-resource-paths/graphql_hierarchical_resource_paths.md
examples/graphql-input-objects/graphql_input_objects.md
examples/graphql-input-types/graphql_input_types.md
examples/graphql-interceptors/graphql_interceptors.md
examples/graphql-interfaces-implementing-interfaces/graphql_interfaces_implementing_interfaces.md
examples/graphql-interfaces/graphql_interfaces.md
examples/graphql-mutations/graphql_mutations.md
examples/graphql-returning-record-values/graphql_returning_record_values.md
examples/graphql-returning-service-objects/graphql_returning_service_objects.md
examples/graphql-service-field-object/graphql_service_field_object.1.client.out
examples/graphql-service-field-object/graphql_service_field_object.1.graphql
examples/graphql-service-field-object/graphql_service_field_object.2.client.out
examples/graphql-service-field-object/graphql_service_field_object.2.graphql
examples/graphql-service-field-object/graphql_service_field_object.bal
examples/graphql-service-field-object/graphql_service_field_object.md
examples/graphql-service-field-object/graphql_service_field_object.metatags
examples/graphql-service-field-object/graphql_service_field_object.server.1.out
examples/graphql-service-field-object/graphql_service_field_object.server.2.out
examples/graphql-service-field-object/graphql_service_field_object.server.3.out
examples/graphql-service-union-types/graphql_service_union_types.bal
examples/graphql-service-union-types/graphql_service_union_types.md
examples/index.json
gradle.properties

Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3997

Add BBE for GraphQL field object

---

ballerina-test/src/test/resources/openapi/expected/types.bal
gradle.properties

Update OpenAPI version and tests

---

examples/tracing/tracing.md

Remove extra new lines

---

gradle.properties

Update stdlib timestamp version

---

gradle.properties

Bump c2c for 2201.4.0 RC 1

---

gradle.properties

Update protoc tool version

---

gradle.properties

Update AsyncAPI tool version for 2201.4.0-20230206-091900-3d0899b2

---

gradle.properties

Update the GraphQL version to 1.5.1

---

examples/consuming-services/consuming_services.md
examples/converting-from-json-to-user-defined-type-with-langlib-functions/converting_from_json_to_user_defined_type_with_langlib_functions.md
examples/converting-from-user-defined-type-to-json/converting_from_user_defined_type_to_json.md
examples/create-maps-with-query/create_maps_with_query.md
examples/create-streams-with-query/create_streams_with_query.md
examples/ignoring-return-values-and-errors/ignoring_return_values_and_errors.md
examples/index.json
examples/inferring-isolated/inferring_isolated.md
examples/iterating-over-xml-with-query/iterating_over_xml_with_query.md
examples/joining-iterable-objects/joining_iterable_objects.md
examples/json-type/json_type.md
examples/let-clause/let_clause.md
examples/limit-clause/limit_clause.md
examples/on-conflict-clause/on_conflict_clause.md
examples/providing-services/providing_services.md
examples/querying-tables/querying_tables.md
examples/querying-with-streams/querying_with_streams.md
examples/readonly-type/readonly_type.md
examples/testerina-data-driven-tests/testerina_data_driven_tests.md

Fix sentence case in BBE titles. …

Fix sentence case in BBE titles

---

examples/index.json

Fix the URL of the `destructure-records-using-query` BBE. …

Fix URL of `destructure-records-using-query` BBE

---

gradle.properties

Update stdlib module versions

---

gradle.properties

Update sql version to latest

---

pom.xml

Update nexus staging urls and versions for 1.2.35 release

---

gradle.properties

Update `dist` version

---

.github/workflows/publish-release.yml

Set dotnet-guid version

---

gradle.properties

Update dev-tools module timestamp versions

---

.github/workflows/daily-build-2201.4.x.yml

Add daily build for 2201.4.x

---

gradle.properties

Bump c2c for 2201.4.0 rc2

---

gradle.properties

update GraphQL Tool version for 2201.4.0-rc2

---

gradle.properties

Update persist and persist tool timestamp version

---

gradle.properties

Update Asyncapi version for 0.4.0-20230215-161100-a8c7136

---

pom.xml

Update nexus staging urls and versions for `1.2.36` release

---

ballerina-test/pom.xml
ballerina/pom.xml

Update version for `1.2.36` release

---

gradle.properties

Update OpenAPI version in branch 2201.4.x-rc1

---

ballerina-test-automation/gradle.properties

[2201.3.x] Update version for installer tests

---

examples/azure-functions-deployment/bal_build.out

Update Azure Functions BBE for 2201.4.0

---

ballerina-test-automation/gradle.properties

Update versions for installer tests

---

gradle.properties

Update HTTP version in 3.x branch

---

gradle.properties

Update patch version of TCP module

---

gradle.properties

Update with the latest constraint version

---

.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build-2201.4.x.yml
.github/workflows/daily-build.yml

Update scheduled time for daily build

---

gradle.properties

Update dependancy versions

---

gradle.properties

Bump c2c to 2.5.0

---

gradle.properties

Update Async API tool version for Ballerina 2201.4.0

---

gradle.properties

Update dev-tools version for 2201.4.0

---

gradle.properties

Update observe module versions for 2201.4.0 release

---

gradle.properties

Update protoc tool version for Ballerina 2201.4.0

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

Update lang and OpenAPI versions for 2201.3.3 RC1

---

ballerina-test-automation/gradle.properties

Update update-tool version in installer tests

---

.github/workflows/publish-release.yml

Change windows version to 2019

---

gradle.properties

Upgrade sql package version

---

gradle.properties

Update OpenAPI version and Ballerina version

---

gradle.properties

Update version to ballerina 2201.3.4 RC1

---

examples/controlling-openness/controlling_openness.md
examples/default-values-for-record-fields/default_values_for_record_fields.md
examples/function-values/function_values.md
examples/init-function/init_function.md
examples/main-function/main_function.md
examples/maps/maps.md
examples/open-records/open_records.md
examples/optional-fields/optional_fields.md
examples/provide-function-arguments-by-name/provide_function_arguments_by_name.md
examples/structured-keys/structured_keys.md
examples/type-inclusion-for-records/type_inclusion_for_records.md

Fix more broken links

---

gradle.properties

Update xmldata version to 2.3.2

---

examples/graphql-graphiql/graphql_graphiql.md

Update GraphiQL client spec link in BBE

---

gradle.properties

Update xmldata and sql package versions

---

ballerina/build.gradle

(cherry picked from commit 3671f3f89db2b05e8f7c7c017b5013c068f1f302)
$subject

Add bal clean phase before testing with staging

---

ballerina/build.gradle

Fix clean getting executed in teststdlibs

---

gradle.properties

Update oauth2 and graphql versions

---

gradle.properties

Bump cloud version to 2.5.1

---

ballerina-test-automation/gradle.properties
gradle.properties

Update ballerna-lang rc version and installer tests

---

gradle.properties

Update dev tools version

---

ballerina/build.gradle

This pr includes the jars of the newly added LS extension (https://github.com/ballerina-platform/ballerina-dev-tools/pull/179) to the distribution.
note - These jars should be added with update 5
Related pr sent to 5.x branch https://github.com/ballerina-platform/ballerina-distribution/pull/4184
> Brief description of the new feature or bug fix as it will appear in the …

[master] Add devtools graphql artifacts to distribution

---

ballerina/build.gradle
gradle.properties

This pr includes the jars of the newly added LS extension (https://github.com/ballerina-platform/ballerina-dev-tools/pull/179) to the distribution. 
note - These jars should be added with **update 5** …

Include devTool's graphQL jars to the distribution

---

gradle.properties

[3.x] Update gRPC version

---

gradle.properties

[master] Update gRPC version

---

gradle.properties

[4.x] Update gRPC version

---

gradle.properties

Update websubhub latest version for 2201.3.x

---

gradle.properties

Move persist module to latest version

---

gradle.properties

Update to latest persist version

---

gradle.properties

[2201.5.x] Update dev tools version

---

pom.xml

Update nexus staging urls and versions for 1.2.37 release

---

ballerina-test/pom.xml
ballerina/pom.xml

Update version for 1.2.37 release

---

.github/workflows/publish-release.yml

Fix publish release workflow

---

gradle.properties

Update observe module version

---

gradle.properties

[2201.5.x] Update observe version 2201.5.x

---

examples/index.json
examples/regexp-type/regexp_type.bal
examples/regexp-type/regexp_type.md
examples/regexp-type/regexp_type.metatags
examples/regexp-type/regexp_type.out

$subject
>  fix [issue](https://github.com/ballerina-platform/ballerina-lang/issues/39631)
Update 5 PR #4193

[Master] Add bbe for RegExp type

---

project-api-tests/src/test/java/org/ballerina/projectapi/DistributionCompatibilityTest.java

$subject, as the tests have been failing intermittently.
Created https://github.com/ballerina-platform/ballerina-distribution/issues/4240 to enable once fixed. …

Disable failing DistributionCompatibility test cases

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ExpressionEvaluationTest.java

$subject, as the test has been failing intermittently.
Created https://github.com/ballerina-platform/ballerina-distribution/issues/4239 to enable once fixed. …

Disable testObjectMethodEvaluation test

---

gradle.properties

[2201.4.1]Update OpenAPI Version 

---

gradle.properties

[2201.4.x] Update Lang version

---

examples/index.json
examples/regexp-operations/regexp_operations.bal
examples/regexp-operations/regexp_operations.md
examples/regexp-operations/regexp_operations.metatags
examples/regexp-operations/regexp_operations.out

$subject
> Fix: [issue](https://github.com/ballerina-platform/ballerina-lang/issues/39631)

[Master] Add bbe for regexp langlib function usage

---

gradle.properties

Sync 2201.4.x after 2201.4.1 release

---

gradle.properties

Bump c2c for 2201.5.0

---

examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.bal
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.bal
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.bal
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.bal
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.bal
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.bal

Fixes: https://github.com/ballerina-platform/ballerina-distribution/issues/3941 …

[2201.5.x] Update BBE with oauth2 API changes

---

examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.bal
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.bal
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.bal
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.bal
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.bal
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.bal

> Fixes: https://github.com/ballerina-platform/ballerina-distribution/issues/3941 …

[Master] Update BBE with OAuth2 API changes

---

examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-client-credentials-grant-type/grpc_client_oauth2_client_credentials_grant_type.bal
examples/grpc-client-oauth2-jwt-bearer-grant-type/grpc_client_oauth2_jwt_bearer_grant_type.bal
examples/grpc-client-oauth2-password-grant-type/grpc_client_oauth2_password_grant_type.bal
examples/grpc-client-oauth2-refresh-token-grant-type/grpc_client_oauth2_refresh_token_grant_type.bal
examples/http-client-oauth2-client-credentials-grant-type/http_client_oauth2_client_credentials_grant_type.bal
examples/http-client-oauth2-jwt-bearer-grant-type/http_client_oauth2_jwt_bearer_grant_type.bal
examples/http-client-oauth2-password-grant-type/http_client_oauth2_password_grant_type.bal
examples/http-client-oauth2-refresh-token-grant-type/http_client_oauth2_refresh_token_grant_type.bal
examples/websocket-client-oauth2-client-cred-grant-type/websocket_client_oauth2_client_cred_grant_type.bal
examples/websocket-client-oauth2-jwt-bearer-grant-type/websocket_client_oauth2_jwt_bearer_grant_type.bal
examples/websocket-client-oauth2-password-grant-type/websocket_client_oauth2_password_grant_type.bal
examples/websocket-client-oauth2-refresh-token-grant-type/websocket_client_oauth2_refresh_token_grant_type.bal

> Fixes: https://github.com/ballerina-platform/ballerina-distribution/issues/3941 …

[2201.4.x] Update BBE with oauth2 API changes

---

examples/index.json
examples/regexp-operations/regexp_operations.bal
examples/regexp-operations/regexp_operations.out
examples/regexp-type/regexp_type.bal
examples/regexp-type/regexp_type.md

[Master] Improve RegExp type related bbes

---

gradle.properties

[2201.3.x] Update task version to 2.3.1

---

examples/index.json
examples/regexp-operations/regexp_operations.bal
examples/regexp-operations/regexp_operations.out
examples/regexp-type/regexp_type.bal
examples/regexp-type/regexp_type.md

[2201.5.x] Improve RegExp type related bbes

---

examples/http-default-error-handling/http_default_error_handling.client.out
examples/http-default-error-handling/tests/http_default_error_handling_test.bal
gradle.properties

Update Dependencies (Ballerina Lang : 2201.5.0-20230329-131700-0f497d97)

---

examples/constraint-validations/constraint_validations.bal

Update constraint sample with pattern constraint

---

gradle.properties

Update dev-tools version-2201.5.x

---

gradle.properties

Update c2c version for u5

---

.github/workflows/publish-release-artifacts.yml

Update artifact publishing workflow to include mac-arm installer details.

Update artifact publish workflow

---

gradle.properties

Update tool versions

---

gradle.properties

[2201.4.x]Update GraphQL Version to 1.6.2

---

ballerina-test-automation/gradle.properties

Update test versions

---

gradle.properties

[2201.4.x] Bump c2c to 2.5.2

---

gradle.properties

Update lang version for 2201.4.2

---

.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
ballerina-test-automation/gradle.properties
ballerina/build.gradle
gradle.properties
installers/mac/build-ballerina-macos-x64.sh

Add extra installer for macos-arm architecture

[2201.5.x] MacOS ARM Installer 

---

.github/workflows/publish-release-artifacts.yml

[2201.5.x] Update artifacts releasing workflow

---

examples/http-restrict-by-media-type/http_restrict_by_media_type.bal
examples/regular-expressions/regular_expressions.md

$subject
Fixes #4262 
Related PRs: #4266 (Master)

[2201.5.x] Update regex usages with a depreciation msg

---

gradle.properties

[4.x] Update http version

---

ballerina-test-automation/gradle.properties

Update distribution version

---

gradle.properties

Update c2c, openapi, dev-tools versions for 2201.5.0

---

project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java
project-api-tests/src/test/resources/hierarchical-packages/PackageI/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageK/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageL.test/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageM/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageN/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageQ.test/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageR.test/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageS/Dependencies-template.toml
project-api-tests/src/test/resources/hierarchical-packages/PackageU/Dependencies-template.toml

Replace dependencies.toml distribution-version field with the latest ballerina short version in HierarchicalPackagesTest

---

.github/workflows/publish-release.yml

> Update mac-arm installer location

Update mac-arm installer location

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync release 1.2.37 with ballerina-1.2.x and update nexus urls

---

examples/http-restrict-by-media-type/http_restrict_by_media_type.bal
examples/regular-expressions/regular_expressions.md

$subject
Fixes #4262 
Related PRs #4288 (5.x)

[Master] Update regex usages with a depreciation msg

---

examples/backtick-templates/backtick_templates.bal

Format backtick_templates.bal

---

gradle.properties

Update websubhub latest version for 2201.4.x

---

examples/regular-expressions/regular_expressions.md

Fix links in deprecated RegEx BBE. …

[Master] Fix links in deprecated RegEx BBE

---

ballerina-test/pom.xml
ballerina/pom.xml
pom.xml

Sync `ballerina-1.2.x` with `release-1.2.38`

---

build.gradle
gradle.properties

Add math.vector to the 5.x distribution

---

gradle.properties

Update std libs with the released versions for U5

---

gradle.properties

Update language extensions versions for `2201.5.x`

---

build.gradle
gradle.properties

Reverts ballerina-platform/ballerina-distribution#4310

Revert "Add math.vector to the 5.x distribution"

---

examples/constraint-validations/constraint_validations.bal

[2201.5.x] Update constraint sample with pattern constraint

---

gradle.properties

Update dev-tools dependency version

---

gradle.properties

[Update 6] Update GraphQL version

---

.github/workflows/publish-release-artifacts.yml

[2201.5.x] Fix metadata generation

---

.github/workflows/publish-release-artifacts.yml

Fix metadata generation

---

examples/regular-expressions/regular_expressions.md

Add deprecation notice in blockquotes . …

[Master] - Add deprecation notice in blockquotes 

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

[2201.4.x]Update OpenAPI version and test

---

gradle.properties

Update tool version

---

gradle.properties

Update lang to latest timestamped version

---

examples/http-request-interceptor/http_request_interceptor.bal

Update Request Interceptor BBE

---

gradle.properties

Update dev-tools latest timestamped version

---

examples/http-request-interceptor/http_request_interceptor.bal

[2201.5.x] Update RequestInterceptor BBE

---

ballerina-test-automation/gradle.properties

Increment update tool version to 1.3.14

---

ballerina-test-automation/gradle.properties

Update installer test version

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

[master]Update OpenAPI version and test

---

ballerina-test-automation/gradle.properties

Update test version

---

gradle.properties

[2201.4.x] Update task package version

---

gradle.properties

[2201.4.x] Update OpenAPI version

---

gradle.properties

Update the GraphQL version to 1.6.3

---

gradle.properties

Update task package version

---

gradle.properties

Update dev-tools to release version

---

gradle.properties

[2201.4.x]Update lang and openAPI versions

---

gradle.properties

Downgrade graphql version

---

gradle.properties

[2201.3.x]Update lang and graphql tool version

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

[2201.3.x] Update OpenAPI Version and test

---

examples/index.json

Disable task BBEs due to intermittant test failures

---

project-api-tests/src/test/java/org/ballerina/projectapi/BuildTimeTest.java
project-api-tests/src/test/resources/build-time/Project2/Ballerina.toml
project-api-tests/src/test/resources/build-time/Project2/main.bal
project-api-tests/src/test/resources/build-time/Project3/Ballerina.toml
project-api-tests/src/test/resources/build-time/Project3/main.bal
project-api-tests/src/test/resources/build-time/Project3/tests/test.bal

Related to https://github.com/ballerina-platform/ballerina-lang/issues/40024
> Link(s) to product documentation that addresses …

Add test for offline compilation during code generation compiler plugin

---

examples/graphql-service-interceptors/graphql_service_interceptors.md

[2201.6.x]Rename GraphQL Service Interceptor BBE

---

examples/aws-lambda-context-execution/aws-lambda-context-execution.md

Fix error in BBE generation

---

examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
examples/aws-lambda-dynamodb-trigger/bal_build.out
examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.md
examples/aws-lambda-s3-trigger/bal_build.out

Fix more BBE gen errors

---

examples/azure-functions-hello-world/azure-functions-hello-world.md

Fix generation error in Azure BBE. …

Fix generation error in Azure BBE

---

examples/xslt-transformation/xslt_transformation.md

[Master] Update docs.central.ballerina.io links. …

[Master] Update docs.central.ballerina.io links

---

examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.md

Remove `target_blank` from hyperlinks. …

Remove `target_blank` from hyperlinks

---

examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
examples/azure-functions-cosmosdb-trigger/azure-functions-cosmosdb-trigger.bal
examples/azure-functions-cosmosdb-trigger/azure-functions-cosmosdb-trigger.md
examples/azure-functions-cosmosdb-trigger/execute_function.out
examples/azure-functions-hello-world/azure-functions-hello-world.bal
examples/azure-functions-http-trigger/azure-functions-http-trigger.bal
examples/azure-functions-http-trigger/azure-functions-http-trigger.md
examples/azure-functions-http-trigger/execute_function.out

Update Azure BBEs

---

examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.metatags
examples/aws-lambda-execution-context/aws-lambda-execution-context.metatags
examples/aws-lambda-hello-world/aws-lambda-hello-world.metatags
examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.md
examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.metatags
examples/azure-functions-cosmosdb-trigger/azure-functions-cosmosdb-trigger.metatags
examples/azure-functions-hello-world/azure-functions-hello-world.metatags
examples/azure-functions-http-trigger/azure-functions-http-trigger.metatags
examples/azure-functions-timer-trigger/azure-functions-timer-trigger.metatags

Add metatags files to all C2C BBEs. …

Add metatags files to all C2C BBEs

---

.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml

Add daily build 2201.5.x & 2201.6.x

---

gradle.properties

> Bump gRPC version to 1.7.1-20230510-201900-dd60eae …

Update gRPC version to the latest time stamped version

---

gradle.properties

Update xmldata version to latest released version

---

.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build-2201.4.x.yml
.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml
.github/workflows/daily-build.yml

Update installer-test configs in daily builds

---

.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build-2201.4.x.yml
.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml
.github/workflows/daily-build.yml

Setup centos in daily builds

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/java/org/ballerina/projectapi/DistributionCompatibilityTest.java
project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

> $subject
Fixes [#4240](https://github.com/ballerina-platform/ballerina-distribution/issues/4240)
> Link to the PR for changes …

[2201.4.x] Update dist compatibility tests to use random package names

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
project-api-tests/src/test/java/org/ballerina/projectapi/DistributionCompatibilityTest.java
project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java

Update dist compatibility tests to use random package names

---

gradle.properties

Update sql and persist modules version

---

gradle.properties

Update GraphQL version to latest timestamp version

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/GrpcToolingTest.java
ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java
gradle.properties

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4446 …

Add grpc help command tests

---

gradle.properties

Sync master after 2201.4.2 release 

---

gradle.properties

Update module-ballerina-persist and persist-tools version

---

.github/workflows/daily-build.yml

>Include trivy scan for daily build

Include trivy scan for daily build

---

gradle.properties

Update xmldata version

---

ballerina-test-automation/gradle.properties
gradle.properties

Update distribution version to `2201.6.0`

---

build.gradle
gradle.properties

Add YAML and TOML modules to distribution

---

.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build-2201.4.x.yml
.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml
.github/workflows/daily-build.yml

Fix updating versions for installer tests

---

.github/workflows/daily-build.yml

Fix installer names

---

gradle.properties

[2201.6.x]Update xmldata version

---

gradle.properties

Update extensions.json branch for 2201.3.x

---

gradle.properties

Update extensions.json branch for 2201.4.x

---

.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build-2201.4.x.yml
.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml
.github/workflows/daily-build.yml

Fix updating versions in centos

---

gradle.properties

[2201.4.x] Update xmldata version

---

gradle.properties

[2201.5.x] Update xmldata version

---

gradle.properties

Update version in master

---

.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml

Fix macos arm installer build

---

gradle.properties

Update stdlib Versions

---

gradle.properties

Update yaml module timestamp version

---

gradle.properties

Bump c2c version for 2201.6.x

---

gradle.properties

Update Dev-Tools timestamped version

---

.github/workflows/daily-build-2201.5.x.yml
.github/workflows/daily-build-2201.6.x.yml
.github/workflows/daily-build.yml

Update macos-arm installer path

---

.github/workflows/daily-build-2201.3.x.yml
.github/workflows/daily-build-2201.4.x.yml

Fix setting up installer test versions

---

gradle.properties

Update async api versions for u6

---

gradle.properties

Update math.vector version

---

pom.xml

update nexus versions for lang and azure

---

build.gradle
gradle.properties

Add math.vector package to 2201.5.x branch.
Fixes: https://github.com/wso2-enterprise/choreo/issues/21420

[2201.5.x] Add math.vector package

---

build.gradle
gradle.properties

Add math.vector package to 2201.4.x branch.
Fixes: https://github.com/wso2-enterprise/choreo/issues/21420

[2201.4.x] Add math.vector package

---

pom.xml

update nexus for lang and azure

update nexus for lang,azure,docker,kubenetes and aws

---

build.gradle

[2201.6.x] Add yaml and toml module to build.gradle

---

build.gradle
gradle.properties

Include edi module

---

gradle.properties

Modify math.vector version
Fixes: https://github.com/wso2-enterprise/choreo/issues/21509

[2201.6.x] Modify math.vector version

---

gradle.properties

Update graphQL version for 2201.6.0 release

---

gradle.properties

Bump c2c version to 2.7.0

---

gradle.properties

Update devtools version for 2201.6.0 release

---

installers/linux-deb/resources/DEBIAN/postinst
installers/linux-rpm/resources/ballerina-runtime.spec
installers/linux-rpm/resources/ballerina-tools.spec
installers/mac/darwin/scripts/postinstall

$title
fixes https://github.com/ballerina-platform/ballerina-update-tool/issues/65

Fix version display issue after installation

---

examples/index.json

Removing duplicate logging config from index JSON. …

Removing duplicate logging config from index JSON

---

gradle.properties

Change all dependency versions to stable versions

---

examples/index.json

Avoid PR check failures and daily build failures …

Disable verify output for xml-from-record-conversion BBE

---

gradle.properties

Update xmldata, regex and uuid packages' version

---

examples/index.json
gradle.properties

Enable verifying output for BBE 'xml-from-record-conversion'

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

> This PR is to update distribution 2201.5.x branch with the HTTP latest versions, according to choreo requirements
> Link to the …

Update OpenAPI version and Http version

---

gradle.properties

Modify math.vector version
Fixes: https://github.com/wso2-enterprise/choreo/issues/21509

[2201.5.x] Modify math.vector version

---

gradle.properties

Update dependency versions with latest

---

gradle.properties

Remove duplicate properties

---

gradle.properties

update balstdlibBranch in gradle.properties in master

update balstdlibBranch in gradle.properties in master

---

devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ExpressionEvaluationTest.java

Increase debugger evaluation test timeout

---

ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
gradle.properties

[1.5.x] Update OpenAPI version and tests

---

gradle.properties

[2201.6.x] Update distribution version in 6.x branch

[2201.6.x] Update distribution version in 6.x branch

---

gradle.properties

Update yaml and toml timestamp versions

---

pom.xml

Update nexus staging urls for 1.2.40 release

---

ballerina-test-automation/test-automation/src/main/java/io/ballerina/test/Utils.java

Fix trust manager

---

pom.xml

Update ballerina dist version to 1.2.40-SNAPSHOT

---

ballerina-test/pom.xml
ballerina/pom.xml

Update dist version in ballerina and ballerina-test

---

gradle.properties

Remove lang timestamp in 6.x branch

Remove lang timestamp in 6.x branch

---

.github/workflows/daily-build-2201.7.x.yml

Include daily build for 2201.7.x branch

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java

will be enabled after fixing https://github.com/ballerina-platform/ballerina-distribution/issues/4578 …

[2201.7.x] Disable testBuildPackage test tempoarrily

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java

will be enabled after fixing https://github.com/ballerina-platform/ballerina-distribution/issues/4578 …

Disable testBuildPackage test tempoarrily

---

ballerina-test-automation/gradle.properties

[2201.7.x] Update spec version

---

installers/mac/darwin/scripts/postinstall

[2201.7.x] Remove version check after installation

---

installers/mac/darwin/scripts/postinstall

Remove version check after installation

---

gradle.properties

Update lang timestamp version for 2201.5.1 release

---

pom.xml

Update nexus staging urls for 1.2.40 release 

---

project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
project-api-tests/src/test/resources/central/projectB/Ballerina.toml

> Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/4578 …

Fix graalvm compatibility for `bal pack` test

---

gradle.properties

[2201.5.1]Update openAPI version

---

gradle.properties

[2201.5.x]Update time and IO versions

---

gradle.properties

Update ballerina lang timestamp version

---

ballerina-test-automation/gradle.properties
gradle.properties

Update spec version and display text for update 7 relase

---

installers/mac/darwin/scripts/postinstall

[2201.6.x] Remove version check in post installation

---

examples/edi-to-record/codegen_command.out
examples/record-to-edi/codegen_command.out

[2201.6.x] Update edi code generation command

---

examples/edi-to-record/codegen_command.out
examples/record-to-edi/codegen_command.out

Update edi code generation command

---

examples/edi-to-record/codegen_command.out
examples/record-to-edi/codegen_command.out

[2201.7.x] Update edi code generation command

---

examples/index.json
examples/nats-jetstream-pub/nats_jetstream_pub.bal
examples/nats-jetstream-pub/nats_jetstream_pub.md
examples/nats-jetstream-pub/nats_jetstream_pub.metatags
examples/nats-jetstream-pub/nats_jetstream_pub.out
examples/nats-jetstream-pub/nats_jetstream_pub.server.out
examples/nats-jetstream-sub/nats_jestream_sub.bal
examples/nats-jetstream-sub/nats_jestream_sub.md
examples/nats-jetstream-sub/nats_jestream_sub.metatags
examples/nats-jetstream-sub/nats_jestream_sub.out

$title
PR to master: https://github.com/ballerina-platform/ballerina-distribution/pull/4599

Add BBEs for NATS JetStream - 2201.7.x

---

examples/index.json
examples/nats-jetstream-pub/nats_jetstream_pub.bal
examples/nats-jetstream-pub/nats_jetstream_pub.md
examples/nats-jetstream-pub/nats_jetstream_pub.metatags
examples/nats-jetstream-pub/nats_jetstream_pub.out
examples/nats-jetstream-pub/nats_jetstream_pub.server.out
examples/nats-jetstream-sub/nats_jestream_sub.bal
examples/nats-jetstream-sub/nats_jestream_sub.md
examples/nats-jetstream-sub/nats_jestream_sub.metatags
examples/nats-jetstream-sub/nats_jestream_sub.out

$title
fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3917

Add BBEs for NATS JetStream

---

examples/http-default-error-handling/http_default_error_handling.client.out
examples/http-error-handling/http_error_handling.bal
examples/http-interceptor-error-handling/http_interceptor_error_handling.bal
examples/http-request-interceptor/http_request_interceptor.bal
examples/http-request-interceptor/http_request_interceptor.md
examples/http-response-interceptor/http_response_interceptor.bal
examples/http-response-interceptor/http_response_interceptor.md

$subject
Related issue - https://github.com/ballerina-platform/ballerina-standard-library/issues/4580 …

Update http bbes with latest changes
