ballerina-platform/ballerina-distribution

- examples/http-default-error-handling/http_default_error_handling.client.out
- examples/http-error-handling/http_error_handling.bal
- examples/http-interceptor-error-handling/http_interceptor_error_handling.bal
- examples/http-request-interceptor/http_request_interceptor.bal
- examples/http-request-interceptor/http_request_interceptor.md
- examples/http-response-interceptor/http_response_interceptor.bal
- examples/http-response-interceptor/http_response_interceptor.md
$subject
Related issue - https://github.com/ballerina-platform/ballerina-standard-library/issues/4580 …
> [2201.7.x] Update http bbes with latest changes

- gradle.properties
> [2201.7.0] Update OpenAPI version

- examples/edi-to-record/edi_to_record.md
- examples/edi-to-record/tool_pull_command.out
- examples/record-to-edi/record_to_edi.md
- examples/record-to-edi/tool_pull_command.out
> Add instructions for getting the EDI tool
> Add instructions for getting the EDI tool

- dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
> Skip generating API docs for graphql

- .github/workflows/publish-release.yml
- .github/workflows/sign-installers.yml
> [2201.7.x] Cosign integration

- examples/http-service-payload-constraint-validation/tests/http_service_payload_constraint_validation.bal
- gradle.properties
> Update stdlib timestamp versions for update 7

- gradle.properties
> [2201.5.1] Update OpenAPI version

- gradle.properties
> [2201.5.x] Update lang version for 2201.5.1 release

- project-api-tests/build.gradle
> Fix checkstyle test execution order

- pom.xml
> Update nexus urls for 1.2.40-release

- .github/workflows/publish-release.yml
> Remove Project API tests temporarily

- pom.xml
> Update azure functions nexus url

- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
- project-api-tests/src/test/java/org/ballerina/projectapi/DistributionCompatibilityTest.java
- project-api-tests/src/test/java/org/ballerina/projectapi/HierarchicalPackagesTest.java
> $subject 
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/4240 …
> [2201.5.x] Update dist compatibility tests to use random package names

- .github/workflows/publish-release.yml
> Fix typo in URL

- gradle.properties
> Bump the graphql-tools version

- examples/http-service-payload-constraint-validation/tests/http_service_payload_constraint_validation.bal
- gradle.properties
> Update gradle.properties with update 7 compatible versions

- gradle.properties
> [6.x] Update http and grpc versions

- gradle.properties
- project-api-tests/build.gradle
> $subject
Fixes https://github.com/ballerina-platform/ballerina-distribution/issues/4536 …
> Add check to skip project-api tests if Asgadeo dev is not available

- gradle.properties
> [5.x] Update http and grpc versions

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build-2201.5.x.yml
- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build-2201.7.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/sign-installers.yml
- .github/workflows/test-installers.yml
- README.md
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- ballerina/build.gradle
- build.gradle
- cache-generator/src/main/java/io/ballerina/gencache/cmd/GenCacheCmd.java
- config/checkstyle/build.gradle
- dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
- docs/build-ballerina-from-source.md
- examples/raw-templates/Ballerina.toml
- gradle.properties
- gradle/javaProject.gradle
- gradle/wrapper/gradle-wrapper.properties
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
- project-api-tests/src/test/resources/central/projectB/Ballerina.toml
- settings.gradle
> Migrate to Java 17

- gradle.properties
> [2201.6.x] Update Web-Socket, TCP and UDP version 

- gradle.properties
> [2201.5.x] Update Web-Socket, TCP and UDP version

- .github/workflows/publish-release.yml
> [2201.7.x] Change markdown url

- examples/object-type-inclusion/object_type_inclusion.bal
> Fix minor typo

- examples/index.json
> Fix NATS BBE build errors

- examples/index.json
Update NATS service constraint BBE directory name. …
> Update NATS service constraint BBE directory name

- gradle.properties
> [2201.7.x] Update dependency versions for 2201.7.0 release

- .github/workflows/publish-release-artifacts.yml
Reverts ballerina-platform/ballerina-distribution#4637
> Revert "Integrate `Notation` to sign Ballerina Images"

- examples/index.json
Fix typo in JetStream Pub BBE. …
> Fix typo in JetStream Pub BBE

- .github/workflows/publish-release.yml
> Fix md file path

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.6.x]Update OpenAPI version and test

- examples/index.json
> [Master] Update index.json for aggregation

- ballerina/build.gradle
- build.gradle
- gradle/javaProject.gradle
- gradle/wrapper/gradle-wrapper.properties
- project-api-tests/build.gradle
> Fix gradle build failures due to missing dependencies with Java 17

- .github/workflows/daily-build.yml
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/BallerinaCommandTest.java
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
> Update installer build target to Java 17

- gradle.properties
> [2201.6.x] Update OpenAPI version

- examples/graphql-client-error-handling/graphql_client_error_handling.md
- examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.md
- examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
- examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
- examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
- examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
- examples/graphql-context/graphql_context.md
- examples/graphql-field-interceptors/graphql_field_interceptors.md
- examples/graphql-file-upload/graphql_file_upload.md
- examples/graphql-graphiql/graphql_graphiql.md
- examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md
- examples/graphql-interceptor-configurations/graphql_interceptor_configurations.md
- examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
- examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
- examples/graphql-service-error-handling/graphql_service_error_handling.md
- examples/graphql-service-field-object/graphql_service_field_object.md
- examples/graphql-service-interceptors/graphql_service_interceptors.md
- examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
- examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
- examples/graphql-service-oauth2/graphql_service_oauth2.md
- examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
> This is done as part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4466. Need to merge this before Update 8. 
Related: https://github.com/ballerina-platform/module-ballerina-graphql/pull/1513
> [2201.8.0] - Update GraphQL spec links in BBEs

- examples/graphql-client-error-handling/graphql_client_error_handling.md
- examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.md
- examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
- examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
- examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
- examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
- examples/graphql-context/graphql_context.md
- examples/graphql-field-interceptors/graphql_field_interceptors.md
- examples/graphql-file-upload/graphql_file_upload.md
- examples/graphql-graphiql/graphql_graphiql.md
- examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md
- examples/graphql-interceptor-configurations/graphql_interceptor_configurations.md
- examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
- examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
- examples/graphql-service-error-handling/graphql_service_error_handling.md
- examples/graphql-service-field-object/graphql_service_field_object.md
- examples/graphql-service-interceptors/graphql_service_interceptors.md
- examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
- examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
- examples/graphql-service-oauth2/graphql_service_oauth2.md
- examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
> This is done as part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4466. Need to merge this before Update 8. 
Related: https://github.com/ballerina-platform/module-ballerina-graphql/pull/1513
> Update GraphQL spec links in BBEs

- examples/aggregation/aggregation.bal
- examples/aggregation/aggregation.md
- examples/aggregation/aggregation.metatags
- examples/aggregation/aggregation.out
Add the aggregation BBE to the master branch. …
> Add the aggregation BBE to master branch

- examples/aggregation/aggregation.bal
- examples/aggregation/aggregation.md
- examples/aggregation/aggregation.metatags
- examples/aggregation/aggregation.out
Add the aggregation BBE to Update 8. …
> Add the aggregation BBE to Update 8

- examples/aggregation/aggregation.bal
- examples/aggregation/aggregation.md
- examples/aggregation/aggregation.metatags
- examples/aggregation/aggregation.out
Add aggregation BBEs to the FaaS review branch. …
> Add aggregation BBEs to the FaaS review branch

- .github/workflows/publish-release.yml
Reverts ballerina-platform/ballerina-distribution#4618
> Revert "Remove Project API tests temporarily"

- gradle.properties
> [2201.6.1] Update openAPI version

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build-2201.5.x.yml
- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build-2201.7.x.yml
- .github/workflows/daily-build.yml
> [java_17_migration] Disable 'Install Ballerina DEB' and 'Run Installer Tests' tasks temporarily

- examples/graphql-client-error-handling/graphql_client_error_handling.md
- examples/graphql-client-security-basic-auth/graphql_client_security_basic_auth.md
- examples/graphql-client-security-mutual-ssl/graphql_client_security_mutual_ssl.md
- examples/graphql-client-security-oauth2-password-grant-type/graphql_client_security_oauth2_password_grant_type.md
- examples/graphql-client-security-self-signed-jwt-authentication/graphql_client_security_self_signed_jwt_authentication.md
- examples/graphql-client-security-ssl-tls/graphql_client_security_ssl_tls.md
- examples/graphql-context/graphql_context.md
- examples/graphql-field-interceptors/graphql_field_interceptors.md
- examples/graphql-file-upload/graphql_file_upload.md
- examples/graphql-graphiql/graphql_graphiql.md
- examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md
- examples/graphql-interceptor-configurations/graphql_interceptor_configurations.md
- examples/graphql-service-basic-auth-file-user-store/graphql_service_basic_auth_file_user_store.md
- examples/graphql-service-basic-auth-ldap-user-store/graphql_service_basic_auth_ldap_user_store.md
- examples/graphql-service-error-handling/graphql_service_error_handling.md
- examples/graphql-service-field-object/graphql_service_field_object.md
- examples/graphql-service-interceptors/graphql_service_interceptors.md
- examples/graphql-service-jwt-auth/graphql_service_jwt_auth.md
- examples/graphql-service-mutual-ssl/graphql_service_mutual_ssl.md
- examples/graphql-service-oauth2/graphql_service_oauth2.md
- examples/graphql-service-ssl-tls/graphql_service_ssl_tls.md
> [2201.7.x] Update GraphQL spec links in BBEs

- examples/azure-functions-hello-world/azure-functions-hello-world.md
Update Azure Functions Hello World BBE. …
> Update Azure Functions Hello World BBE

- gradle.properties
> [2201.7.x] Update file version

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.7.x]Update OpenAPI version

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update the lang version

- gradle.properties
> [2201.7.x] Update OpenAPI version

- gradle.properties
- project-api-tests/build.gradle
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
- project-api-tests/src/test/resources/central/projectB/Ballerina.toml
> Fix project API test failures

- examples/stop-handler/stop_handler.client.out
- examples/stop-handler/stop_handler.md
- examples/stop-handler/stop_handler.server.out
$title
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/7239
> Link(s) to product documentation that …
> [2201.7.x] Improve StopHandler BBE

- ballerina/build.gradle
- gradle.properties
> Update ballerina custom JRE version

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync `1.2.x` after `1.2.40` release

- pom.xml
> Update nexus staging urls and versions for `1.2.41` release

- ballerina/build.gradle
- gradle.properties
> Add JRE with Java 17 support

- pom.xml
> Update nexus staging urls and versions for 1.2.41 release

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync `1.2.x` after `1.2.41` release

- gradle.properties
> Bump stdlib versions

- gradle.properties
> Update file version

- .github/workflows/language_server_simulator_fhir.yml
- .github/workflows/language_server_simulator_nballerina.yml
- language-server-simulator/build.gradle
> Add necessary env vars for LS simulator workflow

- pom.xml
> Update nexus staging urls and versions for `1.2.42` release

- language-server-simulator/build.gradle
> Add missing configurations for LS Simulator

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> This is sending ofr separate branch to creat a distribution pack for testing purposes.
> [openapi-fix]Update OpenAPI version and lang version

- .github/workflows/language_server_simulator_fhir.yml
- .github/workflows/language_server_simulator_nballerina.yml
> Remove unwanted branches in LS simulator workflow

- .github/workflows/publish-release.yml
- .github/workflows/sign-installers.yml
> Update publish release and sign installers yaml

- examples/aws-lambda-dynamodb-trigger/bal_new.out
- examples/aws-lambda-execution-context/bal_new.out
- examples/aws-lambda-hello-world/bal_new.out
- examples/aws-lambda-s3-trigger/bal_new.out
- examples/azure-functions-cosmosdb-trigger/bal_new.out
- examples/azure-functions-hello-world/az_deploy.out
- examples/azure-functions-hello-world/bal_new.out
- examples/azure-functions-http-trigger-with-queue/bal_new.out
- examples/azure-functions-timer-trigger/bal_new.out
Address FaaS BBEs review comments. …
> Address FaaS BBEs review comments

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync `1.2.x` after `1.2.42`

- examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
> Add the DynamoDB link in BBE

- examples/aws-lambda-dynamodb-trigger/bal_build.out
- examples/aws-lambda-dynamodb-trigger/bal_new.out
- examples/aws-lambda-execution-context/bal_build.out
- examples/aws-lambda-execution-context/bal_new.out
- examples/aws-lambda-hello-world/bal_build.out
- examples/aws-lambda-hello-world/bal_new.out
- examples/aws-lambda-s3-trigger/bal_build.out
- examples/aws-lambda-s3-trigger/bal_new.out
- examples/azure-functions-cosmosdb-trigger/az_deploy.out
- examples/azure-functions-cosmosdb-trigger/bal_build.out
- examples/azure-functions-cosmosdb-trigger/bal_new.out
- examples/azure-functions-hello-world/az_deploy.out
- examples/azure-functions-hello-world/bal_build.out
- examples/azure-functions-hello-world/bal_new.out
- examples/azure-functions-http-trigger-with-queue/az_deploy.out
- examples/azure-functions-http-trigger-with-queue/bal_build.out
- examples/azure-functions-http-trigger-with-queue/bal_new.out
- examples/azure-functions-timer-trigger/az_deploy.out
- examples/azure-functions-timer-trigger/azure-functions-timer-trigger.bal
- examples/azure-functions-timer-trigger/bal_build.out
- examples/azure-functions-timer-trigger/bal_new.out
Verify and update FaaS BBE outputs. …
> Verify and update FaaS BBE outputs

- ballerina-test-automation/installer-test/build.gradle
> Remove classifier property from testJar task

- .github/workflows/language_server_simulator_fhir.yml
- .github/workflows/language_server_simulator_nballerina.yml
> Fix simulator workflows to run with JDK17

- gradle.properties
> [7.x] Update http version

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update lang timestamp version for `2201.7.2`

- examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md
> Fix broken spec link on GraphQL constraints BBE

- examples/graphql-input-constraint-validation/graphql_input_constraint_validation.md
> Fix Broken Link on GraphQL Constraints BBE

- pom.xml
> Update nexus staging urls and versions for `1.2.43` release

- gradle.properties
> [2201.7.x] Update xmldata version

- examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
Fix numbered bullets in the DynamoDB BBE. …
> [2201.8.x] - Fix numbered bullets in the DynamoDB BBE

- examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
Fixed numbered bullets in the DynamoDB BBE. …
> [Master] - Fixed numbered bullets in the DynamoDB BBE

- examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
- examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.md
Fix formatting issues of DynamoDB and S3 BBEs. …
> Fix formatting issues of DynamoDB and S3 BBEs

- .trivyignore
> Remove a resolved CVE

- examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
Update FaaS BBEs in master branch. …
> Update FaaS BBEs in master branch

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync `ballerina-1.2.x` after  `1.2.43` release

- ballerina/build.gradle
> Remove additional intermediate directory in dependency directory

- examples/custom-prefetch-methods/custom_prefetch_methods.md
> Update graphql custom prefetch method BBE

- gradle.properties
> Bump c2c timestamp for update 8

- gradle.properties
> [2201.4.x]Update ballerina-io patch version

- gradle.properties
> Update graphql and graphql-tool time stamp version

- gradle.properties
> Update ballerina-lang version

- gradle.properties
> Update graphql tools version

- build.gradle
- gradle.properties
> Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4394
> Add soap module to distribution

- gradle.properties
> Update GraphQL Tools timestamp version

- build.gradle
- gradle.properties
> [8.x] Add mqtt module to distribution

- .trivyignore
> Update .trivyignore file

- gradle.properties
> [Master] Update Websocket timestamp version

- gradle.properties
> [2201.8.x] Update Websocket timestamp version

- gradle.properties
> Update soap module version

- gradle.properties
> Update soap module and protoc tool versions

- pom.xml
> Update nexus staging urls and versions for 1.2.44 release

- gradle.properties
> [openapi-pre-check] Update openapi version

- examples/aws-lambda-dynamodb-trigger/aws-lambda-dynamodb-trigger.md
- examples/aws-lambda-execution-context/aws-lambda-execution-context.md
- examples/aws-lambda-hello-world/aws-lambda-hello-world.md
- examples/aws-lambda-s3-trigger/aws-lambda-s3-trigger.md
- examples/azure-functions-cosmosdb-trigger/azure-functions-cosmosdb-trigger.md
- examples/azure-functions-hello-world/azure-functions-hello-world.md
- examples/azure-functions-http-trigger-with-queue/azure-functions-http-trigger-with-queue.md
- examples/azure-functions-timer-trigger/azure-functions-timer-trigger.md
- examples/c2c-docker-deployment/c2c_docker_deployment.md
- examples/c2c-k8s-deployment/c2c_k8s_deployment.md
- examples/configurable-variables/configurable_variables.md
- examples/configuring-via-cli/configuring_via_cli.md
- examples/configuring-via-toml/configuring-via-toml.md
- examples/docker-hello-world/docker-hello-world.md
- examples/grpc-client-bidirectional-streaming/grpc_bidirectional_streaming.md
- examples/grpc-client-client-streaming/grpc_client_streaming.md
- examples/grpc-client-server-streaming/grpc_server_streaming.md
- examples/grpc-client-simple/grpc_client_simple.md
- examples/grpc-service-bidirectional-streaming/grpc_bidirectional_streaming.md
- examples/grpc-service-client-streaming/grpc_client_streaming.md
- examples/grpc-service-server-streaming/grpc_server_streaming.md
- examples/grpc-service-simple/grpc_service_simple.md
- examples/kubernetes-hello-world/kubernetes-hello-world.md
Fix links post learn revamp in the Update 8 branch. …
> [2201.8.x] - Fix links post learn revamp in the Update 8 branch

- examples/kafka-consumer-constraint-validation/kafka_consumer_constraint_validation.bal
- examples/kafka-consumer-consumer-record-data-binding/kafka_consumer_consumer_record_data_binding.bal
- examples/kafka-consumer-payload-data-binding/kafka_consumer_payload_data_binding.bal
- examples/kafka-consumer-sasl/kafka_consumer_sasl.bal
- examples/kafka-consumer-ssl/kafka_consumer_ssl.bal
- examples/kafka-producer-produce-message/kafka_producer_produce_message.bal
- examples/kafka-producer-sasl/kafka_producer_sasl.bal
- examples/kafka-producer-ssl/kafka_producer_ssl.bal
- examples/kafka-service-constraint-validation/kafka_service_constraint_validation.bal
- examples/kafka-service-consume-message/kafka_service_consume_message.bal
- examples/kafka-service-error-handling/kafka_service_error_handling.bal
- examples/kafka-service-sasl/kafka_service_sasl.bal
- examples/kafka-service-ssl/kafka_service_ssl.bal
> [master] Update kafka BBEs

- examples/kafka-consumer-constraint-validation/kafka_consumer_constraint_validation.bal
- examples/kafka-consumer-consumer-record-data-binding/kafka_consumer_consumer_record_data_binding.bal
- examples/kafka-consumer-payload-data-binding/kafka_consumer_payload_data_binding.bal
- examples/kafka-consumer-sasl/kafka_consumer_sasl.bal
- examples/kafka-consumer-ssl/kafka_consumer_ssl.bal
- examples/kafka-producer-produce-message/kafka_producer_produce_message.bal
- examples/kafka-producer-sasl/kafka_producer_sasl.bal
- examples/kafka-producer-ssl/kafka_producer_ssl.bal
- examples/kafka-service-constraint-validation/kafka_service_constraint_validation.bal
- examples/kafka-service-consume-message/kafka_service_consume_message.bal
- examples/kafka-service-error-handling/kafka_service_error_handling.bal
- examples/kafka-service-sasl/kafka_service_sasl.bal
- examples/kafka-service-ssl/kafka_service_ssl.bal
> [2201.8.x] Update kafka BBEs

- .github/workflows/daily-build-2201.8x.yml
> Add daily build for 2201.8.x branch

- gradle.properties
> Update lang timestamp

- .github/workflows/daily-build-2201.8.x.yml
> Fix daily build for 2201.8.x

- .trivyignore
- gradle.properties
> [2201.8.x] Update .trivyignore file for false positive CVE

- installers/linux-deb/resources/DEBIAN/postinst
> Update postinstall script

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync 1.2.x with release-1.2.44

- gradle.properties
> [2201.5.x] Update IO patch version

- gradle.properties
> Update task timestamp version

- gradle.properties
> [2201.8.x] Update task timestamp version

- .github/workflows/daily-build-2201.8.x.yml
> Fix 2201.8.x daily build workflow

- .github/workflows/daily-build-2201.8.x.yml
> Add Java setup for Windows build

- gradle.properties
> Bump c2c to 2.10.0 for 2201.7.x

- .github/workflows/publish-release.yml
> Update publish-release.yml for test pack release

- gradle.properties
> [8.x] Update latest dependencies

- gradle.properties
> [2201.8.x] Update openapi version

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> Update OpenAPI after merging https://github.com/ballerina-platform/openapi-tools/pull/1524
> [2201.5.x] Update openapi version

- examples/index.json
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.bal
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.curl.out
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.md
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.metatags
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.out
- examples/mqtt-client-publish-message/mqtt_client_publish_message.bal
- examples/mqtt-client-publish-message/mqtt_client_publish_message.curl.out
- examples/mqtt-client-publish-message/mqtt_client_publish_message.md
- examples/mqtt-client-publish-message/mqtt_client_publish_message.metatags
- examples/mqtt-client-publish-message/mqtt_client_publish_message.out
- examples/mqtt-client-ssl/mqtt_client_ssl.bal
- examples/mqtt-client-ssl/mqtt_client_ssl.curl.out
- examples/mqtt-client-ssl/mqtt_client_ssl.md
- examples/mqtt-client-ssl/mqtt_client_ssl.metatags
- examples/mqtt-client-ssl/mqtt_client_ssl.out
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.bal
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.md
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.metatags
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.out
- examples/mqtt-service-ssl/mqtt_service_ssl.bal
- examples/mqtt-service-ssl/mqtt_service_ssl.md
- examples/mqtt-service-ssl/mqtt_service_ssl.metatags
- examples/mqtt-service-ssl/mqtt_service_ssl.out
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.bal
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.md
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.metatags
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.out
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4747 …
> Add MQTT BBEs

- devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java
- devtools-integration-tests/src/test/resources/debug/project-based-tests/service-tests/hello_service.bal
$subject
Self-variable expressions of a service object are similar to type-definition with default value expressions. 
Both should behave similarly in code coverage and debugger features. 
While addressing the issue https://github.com/wso2-enterprise/internal-support-ballerina/issues/353, 
it is decided to remove code-coverage and debugger functionality for lines of defaultable expressions in a class/object/record definitions. Therefore, the `service` debugger tests need to be modified to support this behavior. 
The actual fix will be added to lang through PR 
https://github.com/ballerina-platform/ballerina-lang/pull/41320
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this …
> Modify debugger tests to remove invalid service breakpoints

- gradle.properties
> [2201.8.x] Update GraphQL Version

- examples/index.json
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.bal
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.curl.out
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.md
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.metatags
- examples/mqtt-client-basic-authentication/mqtt_client_basic_authentication.out
- examples/mqtt-client-publish-message/mqtt_client_publish_message.bal
- examples/mqtt-client-publish-message/mqtt_client_publish_message.curl.out
- examples/mqtt-client-publish-message/mqtt_client_publish_message.md
- examples/mqtt-client-publish-message/mqtt_client_publish_message.metatags
- examples/mqtt-client-publish-message/mqtt_client_publish_message.out
- examples/mqtt-client-ssl/mqtt_client_ssl.bal
- examples/mqtt-client-ssl/mqtt_client_ssl.curl.out
- examples/mqtt-client-ssl/mqtt_client_ssl.md
- examples/mqtt-client-ssl/mqtt_client_ssl.metatags
- examples/mqtt-client-ssl/mqtt_client_ssl.out
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.bal
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.md
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.metatags
- examples/mqtt-service-basic-authentication/mqtt_service_basic_authentication.out
- examples/mqtt-service-ssl/mqtt_service_ssl.bal
- examples/mqtt-service-ssl/mqtt_service_ssl.md
- examples/mqtt-service-ssl/mqtt_service_ssl.metatags
- examples/mqtt-service-ssl/mqtt_service_ssl.out
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.bal
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.md
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.metatags
- examples/mqtt-service-subscribe-message/mqtt_service_subscribe_message.out
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4747 …
> Add mqtt bbes for 2201.8.x

- gradle.properties
>$subject
Related to https://github.com/ballerina-platform/graphql-tools/issues/218
> [2201.8.x] Update the GraphQL Tool Version

- gradle.properties
> [2201.6.x] Update crypto module version

- gradle.properties
> [2201.5.x] Update crypto module version

- gradle.properties
> [6.x] Update grpc version

- gradle.properties
> [2201.7.x ] Update crypto module version

- gradle.properties
> [2201.4.x] Update crypto module version

- gradle.properties
> [2201.8.x] Update crypto timestamp version

- gradle.properties
> [Master] Update crypto timestamp version

- gradle.properties
> [5.x] Update grpc version

- gradle.properties
> [6.x] Update lang version

- gradle.properties
> [2201.8.x] Update persist tools version

- gradle.properties
> [master] Update persist tools version

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/GraphqlToolTest.java
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIArtifactBuildTest.java
- ballerina-test/src/test/java/org/ballerinalang/distribution/utils/TestUtils.java
- ballerina-test/src/test/resources/graphql/client-gen/project_1/graphql_endpoint.config.yaml
- ballerina-test/src/test/resources/graphql/client-gen/project_1/query_country.graphql
- ballerina-test/src/test/resources/graphql/client-gen/project_2/graphql_schema.config.yaml
- ballerina-test/src/test/resources/graphql/client-gen/project_2/queries/query_country.graphql
- ballerina-test/src/test/resources/graphql/client-gen/project_2/schema_country.graphql
- ballerina-test/src/test/resources/graphql/schema-gen/project_1/Ballerina.toml
- ballerina-test/src/test/resources/graphql/schema-gen/project_1/main.bal
- ballerina-test/src/test/resources/graphql/schema-gen/service.bal
- ballerina-test/src/test/resources/graphql/service-gen/schema_book.graphql
- ballerina-test/src/test/resources/graphql/service-gen/schema_starwars.graphql
- ballerina-test/src/test/resources/testng.xml
- gradle.properties
Fixes: [#224](https://github.com/ballerina-platform/graphql-tools/issues/224)
> Add Integration Tests for GraphQL Tool

- gradle.properties
> [7.x] Update http and grpc versions

- gradle.properties
> [5.x] Update lang version

- gradle.properties
> [5.x] Update openapi and u-tool versions

- ballerina-test-automation/gradle.properties
- ballerina/LICENSE
> Update test data with latest update tool version

- ballerina-test-automation/gradle.properties
> Update test automation properties

- ballerina-test-automation/gradle.properties
> [8.x] Update update tool version

- .github/workflows/publish-release.yml
Reverts ballerina-platform/ballerina-distribution#4863
> Revert "Update publish-release.yml for test pack release"

- gradle.properties
> [7.x] Update lang version

- ballerina-test-automation/gradle.properties
> [master] Update update tool version

- gradle.properties
> [8.x] Update dependency versions

- gradle.properties
> [2201.8.x] Update graphql dependent modules timestamp version

- examples/persist-get-all/persist_get_all.md
Remove extra line in the `Get persist all` BBE. …
> Remove extra line in the `Get persist all` BBE

- examples/index.json
- examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.bal
- examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.md
- examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.metatags
- examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.out
- examples/jms-consumer-consume-message/jms_consumer_consume_message.bal
- examples/jms-consumer-consume-message/jms_consumer_consume_message.md
- examples/jms-consumer-consume-message/jms_consumer_consume_message.metatags
- examples/jms-consumer-consume-message/jms_consumer_consume_message.out
- examples/jms-producer-produce-message/jms_producer_produce_message.bal
- examples/jms-producer-produce-message/jms_producer_produce_message.curl.out
- examples/jms-producer-produce-message/jms_producer_produce_message.md
- examples/jms-producer-produce-message/jms_producer_produce_message.metatags
- examples/jms-producer-produce-message/jms_producer_produce_message.out
- examples/jms-producer-transaction/jms_producer_transaction.bal
- examples/jms-producer-transaction/jms_producer_transaction.curl.out
- examples/jms-producer-transaction/jms_producer_transaction.md
- examples/jms-producer-transaction/jms_producer_transaction.metatags
- examples/jms-producer-transaction/jms_producer_transaction.out
- examples/jms-service-consume-message/jms_service_consume_message.bal
- examples/jms-service-consume-message/jms_service_consume_message.md
- examples/jms-service-consume-message/jms_service_consume_message.metatags
- examples/jms-service-consume-message/jms_service_consume_message.out
> [2201.8.x] Add JMS BBEs

- gradle.properties
> [Master] Update graphql dependent modules timestamp version

- gradle.properties
This reverts commit 8724bf61b672fa0aeba3071a0644204ae172ae9d. …
> [2201.8.x] Revert "Update dev-tools version"

- gradle.properties
> [2201.7.x] Update the GraphQL Tool Version

- examples/index.json
> Add the AWS BBEs back

- examples/index.json
> [Master] Update graphql service advanced BBE section

- examples/index.json
> [2201.8.x] Update graphql service advanced BBE section

- examples/custom-prefetch-methods/custom_prefetch_methods.bal
- examples/graphql-context/graphql_context.bal
- examples/graphql-dataloader/graphql_dataloader.bal
> [Master] Move contextInit function definition outside the graphql:ServiceConfig annotation

- gradle.properties
> Update ballerina std-lib versions for 7.x releases

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update timestamp versions for 2201.7.3 RC2

- examples/programs-and-modules/programs_and_modules.bal
Update the `ballerina library` word . …
> Update the `ballerina library` word

- .github/workflows/publish-release.yml
> Skip adding release notes for RC release

- ballerina-test-automation/gradle.properties
> [2201.6.x] Update swan-lake-latest versions to 2201.6.2

- gradle.properties
> [2201.7.x] Update lang version to 2201.7.3

- gradle.properties
> [2201.7.x] Update the tool version

- ballerina-test-automation/gradle.properties
> Update swan-lake-latest versions

- gradle.properties
> [2201.8.x] Update `http` patch verison

- gradle.properties
> [2201.8.x] Bump c2c to latest

- project-api-tests/src/test/resources/testng.xml
> [8.x] Disable project API tests

- gradle.properties
> [8.x] Update grpc version

- ballerina-test-automation/gradle.properties
> Update tool version for test automation

- gradle.properties
> [8.x] Update lang version for 2201.8.1

- gradle.properties
> [2201.7.x] Update `http` patch verison

- project-api-tests/src/test/resources/testng.xml
Reverts ballerina-platform/ballerina-distribution#4969
> Revert "[8.x] Disable project API tests"

- gradle.properties
> Update library versions to fix netty vulnerability

- ballerina-test-automation/gradle.properties
> Update test automation version

- project-api-tests/src/test/java/org/ballerina/projectapi/MavenCustomRepoTest.java
> Disable the failing github repo test

- .trivyignore
Ignoring as there's no fixed version provided for `org.json:json` (graphql-cli-0.8.0.jar).  …
> Ignore `CVE-2023-5072` vulnerability

- pom.xml
> Update nexus staging urls and versions for 1.2.45 release

- gradle.properties
> [2201.6.x] Update library versions to fix netty vulnerability

- gradle.properties
> [2201.7.x] Update library versions to fix netty vulnerability

- gradle.properties
> Upgrade to latest sql patch release

- gradle.properties
> [2201.5.x] Update library versions to fix netty vulnerability

- gradle.properties
> [2201.6.x] Update observei version

- gradle.properties
> [2201.7.x] Update observei version

- gradle.properties
> [2201.5.x] Update observei version

- project-api-tests/src/test/java/org/ballerina/projectapi/MavenCustomRepoTest.java
- project-api-tests/src/test/resources/testng.xml
Fixes the reason to disable https://github.com/ballerina-platform/ballerina-distribution/pull/4988 
> Link(s) to product …
> [2201.8.x] Fix project API build failure

- gradle.properties
>$subject
Related to : https://github.com/ballerina-platform/ballerina-standard-library/issues/4942
> [2201.6.x] Update the GraphQL Tool Version

- gradle.properties
> [2201.3.x] Update library versions to fix netty vulnerability

- gradle.properties
> [2201.4.x] Update library versions to fix netty vulnerability

- .trivyignore
> Ignore netty vulnerability 

- .trivyignore
- ballerina-test-automation/gradle.properties
- ballerina/LICENSE
- gradle.properties
> Update 2201.7.4 release details

- examples/sequence-diagrams/sequence_diagrams.bal
> Update endpoint url

- ballerina-test-automation/gradle.properties
- gradle.properties
> Fix dependency permission issue on Linux platform

- ballerina-test-automation/gradle.properties
- examples/sequence-diagrams/sequence_diagrams.bal
- gradle.properties
> [2201.8.x] Fix dependency permission issue on Linux platform

- ballerina-test-automation/gradle.properties
- examples/sequence-diagrams/sequence_diagrams.bal
- gradle.properties
> [2201.7.x] Fix dependency permission issue on Linux platform

- ballerina-test-automation/gradle.properties
- examples/sequence-diagrams/sequence_diagrams.bal
- gradle.properties
> [2201.6.x] Update endpoint url for sequence-diagrams BBE

- devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ExpressionEvaluationTest.java
- devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ServiceDebugTest.java
> Disable failing debugger tests

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Update nexus urls and release version

- gradle.properties
> Update versions for 2201.6.3 release

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update the update-tool versions for 1.4.2

- ballerina-test-automation/gradle.properties
- devtools-integration-tests/src/test/resources/testng.xml
- examples/sequence-diagrams/sequence_diagrams.bal
- gradle.properties
> Update 2201.5.4 release details

- ballerina-test-automation/gradle.properties
- devtools-integration-tests/src/test/resources/testng.xml
- examples/sequence-diagrams/sequence_diagrams.bal
- gradle.properties
> Disable failing debugger tests and update sequence diagram tests

- gradle.properties
> Bump distribution versions to update 9

- .trivyignore
> [2201.7.x] Stop ignoring json vulnerability

- .trivyignore
> [2201.8.x] Stop ignoring json vulnerability

- gradle.properties
update the devtools version for 8.x release
> update the devtools version for 8.x release

- ballerina-test-automation/gradle.properties
- gradle.properties
Update distribution versions for 2201.8.3 rc1 release
> Update distribution versions for 2201.8.3 rc1 release

- gradle.properties
> Update http patch version

- build-time-tests/build.gradle
- gradle/javaProject.gradle
- project-api-tests/build.gradle
> [2201.8.x] Update fasterxml jackson version

- gradle.properties
update the latest versions in distribution repo for 2201.4.3 release
> update the latest versions in distribution repo for 2201.4.3 release

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.8.x] Update OpenAPI tool version

- gradle.properties
> [2201.8.x]Update persist-tool version

- project-api-tests/src/test/java/org/ballerina/projectapi/MavenCustomRepoTest.java
> [2201.8.x] Disable failing project api tests

- .trivyignore
Related workflow failure - https://github.com/ballerina-platform/ballerina-distribution/actions/runs/6938385739/job/18874022072
> Disable guava package related issues

- ballerina/LICENSE
- gradle.properties
Update license for 2201.8.3 release
> [2201.8.x]Update license for 2201.8.3 release

- gradle.properties
> Update the GraphQL tool version

- ballerina-test-automation/gradle.properties
- gradle.properties
> [2201.8.x]Update lang version and test automation properties

- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release-temp.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
> Update token naming to `BALLERINA_CENTRAL_DEV_ACCESS_TOKEN`

- gradle.properties
> [2201.8.4]Update ballerina lang version

- .github/workflows/daily-build-2201.2.x.yml
- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
> Update token naming to BALLERINA_CENTRAL_DEV_ACCESS_TOKEN

- docs/build-ballerina-from-source.md
> Fix path variable configuration for Windows

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build-2201.5.x.yml
- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
> Update token names to BALLERINA_CENTRAL_DEV_ACCESS_TOKEN

- .trivyignore
Related to : [https://github.com/ballerina-platform/ballerina-release/issues/2603](https://github.com/ballerina-platform/ballerina-release/issues/2603)
> Ignore guava vulnerability for 2201.7.5 relase

- .github/workflows/publish-release.yml
> [2201.8.x] Include installer tests in publish release

- .github/workflows/publish-release.yml
> [2201.7.x] Include installer tests in publish release

- .github/workflows/publish-release.yml
> Include installer tests in publish release

- gradle.properties
$title
fixes https://github.com/ballerina-platform/ballerina-release/issues/2599
> Bump GraphQL Tool version

- ballerina-test-automation/gradle.properties
> [2201.4.x]Update test automation gradle properties

- gradle.properties
> [8.x] Update http version

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync release 1.2.47 with ballerina-1.2.x

- pom.xml
> Update pom.xml with nexus staging URLs for 1.2.48 release

- gradle.properties
> [2201.8.x] Update constraint version

- gradle.properties
> Update gradle.properties for 2201.7.5 release

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build-2201.5.x.yml
- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build-2201.7.x.yml
- .github/workflows/daily-build-2201.8.x.yml
- .github/workflows/daily-build-editor.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/pull-request.yml
> Change dev central access token name

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build-2201.5.x.yml
- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build-2201.7.x.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
> [2201.8.x] Change dev central access token name

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build-2201.5.x.yml
- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
> [2201.6.x] Change dev central access token name

- .github/workflows/daily-build-2201.3.x.yml
- .github/workflows/daily-build-2201.4.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
> [2201.5.x] Change dev central access token name

- .github/workflows/pull-request.yml
> [2201.4.x] Change dev central access token name

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync with release 1.2.48

- .github/workflows/daily-build-2201.2.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts-1.2.x.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- examples/sequence-diagrams/sequence_diagrams.bal
> [2201.3.x] Change dev central access token name

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.5.x]Update OpenAPI version

- gradle.properties
> Update gradle.properties with `SNAPSHOT` suffix in version

- ballerina-test-automation/gradle.properties
$title
Fix installer test failure for release 2201.7.5
> Update latest Swan Lake version for Update 7

- ballerina-test-automation/gradle.properties
$title
Fix installer test failures for Update 4
> Update latest Swan Lake for Update 4

- ballerina-test-automation/gradle.properties
> Update gradle.properties with latest swan-lake version

- .github/workflows/publish-release.yml
> [2201.7.x] Update publish-release workflow

- .github/workflows/publish-release.yml
> [2201.8.x] Update publish-release workflow

- .github/workflows/daily-build-editor.yml
> Update worker model workflow

- .github/workflows/daily-build-editor.yml
> Remove version replace logic
> Remove version replace logic

- examples/ftp-client-receive-file/ftp_client_receive_file.metatags
- examples/ftp-client-send-file/ftp_client_send_file.metatags
- examples/ftp-service-receive-file/ftp_service_receive_file.metatags
- examples/ftp-service-send-file/ftp_service_send_file.metatags
- examples/kafka-consumer-constraint-validation/kafka_consumer_constraint_validation.metatags
- examples/kafka-consumer-consumer-record-data-binding/kafka_consumer_consumer_record_data_binding.metatags
- examples/kafka-consumer-payload-data-binding/kafka_consumer_payload_data_binding.metatags
- examples/kafka-consumer-sasl/kafka_consumer_sasl.metatags
- examples/kafka-consumer-ssl/kafka_consumer_ssl.metatags
- examples/kafka-producer-produce-message/kafka_producer_produce_message.metatags
- examples/kafka-producer-sasl/kafka_producer_sasl.metatags
- examples/kafka-producer-ssl/kafka_producer_ssl.metatags
- examples/kafka-service-constraint-validation/kafka_service_constraint_validation.metatags
- examples/kafka-service-consume-message/kafka_service_consume_message.metatags
- examples/kafka-service-error-handling/kafka_service_error_handling.metatags
- examples/kafka-service-sasl/kafka_service_sasl.metatags
- examples/kafka-service-ssl/kafka_service_ssl.metatags
- examples/sftp-client-receive-file/sftp_client_receive_file.metatags
- examples/sftp-client-send-file/sftp_client_send_file.metatags
- examples/sftp-service-receive-file/sftp_service_receive_file.metatags
- examples/sftp-service-send-file/sftp_service_send_file.metatags
> Update metatags of Kafka and FTP BBEs

- examples/nats-basic-pub/nats_basic_pub.metatags
- examples/nats-basic-reply/nats_basic_reply.metatags
- examples/nats-basic-request/nats_basic_request.metatags
- examples/nats-basic-sub/nats_basic_sub.metatags
- examples/nats-client-basic-auth/nats_client_basic_auth.metatags
- examples/nats-client-secure-connection/nats_client_secure_connection.metatags
- examples/nats-jetstream-pub/nats_jetstream_pub.metatags
- examples/nats-jetstream-sub/nats_jestream_sub.metatags
- examples/nats-service-basic-auth/nats_service_basic_auth.metatags
- examples/nats-service-constraint-validation/nats_service_constraint_validation.metatags
- examples/nats-service-secure-connection/nats_service_secure_connection.metatags
- examples/rabbitmq-client-basic-auth/rabbitmq_client_basic_auth.metatags
- examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.metatags
- examples/rabbitmq-client-secure-connection/rabbitmq_client_secure_connection.metatags
- examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.metatags
- examples/rabbitmq-consumer/rabbitmq_consumer.metatags
- examples/rabbitmq-producer/rabbitmq_producer.metatags
- examples/rabbitmq-queue-declare/rabbitmq_queue_declare.metatags
- examples/rabbitmq-service-basic-auth/rabbitmq_service_basic_auth.metatags
- examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.metatags
- examples/rabbitmq-service-secure-connection/rabbitmq_service_secure_connection.metatags
- examples/rabbitmq-sync-consumer/rabbitmq_sync_consumer.metatags
- examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.metatags
- examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.metatags
> Fix SEO descriptions in messaging modules

- examples/ftp-client-receive-file/ftp_client_receive_file.metatags
- examples/ftp-client-send-file/ftp_client_send_file.metatags
- examples/ftp-service-receive-file/ftp_service_receive_file.metatags
- examples/ftp-service-send-file/ftp_service_send_file.metatags
- examples/kafka-consumer-constraint-validation/kafka_consumer_constraint_validation.metatags
- examples/kafka-consumer-consumer-record-data-binding/kafka_consumer_consumer_record_data_binding.metatags
- examples/kafka-consumer-payload-data-binding/kafka_consumer_payload_data_binding.metatags
- examples/kafka-consumer-sasl/kafka_consumer_sasl.metatags
- examples/kafka-consumer-ssl/kafka_consumer_ssl.metatags
- examples/kafka-producer-produce-message/kafka_producer_produce_message.metatags
- examples/kafka-producer-sasl/kafka_producer_sasl.metatags
- examples/kafka-producer-ssl/kafka_producer_ssl.metatags
- examples/kafka-service-constraint-validation/kafka_service_constraint_validation.metatags
- examples/kafka-service-consume-message/kafka_service_consume_message.metatags
- examples/kafka-service-error-handling/kafka_service_error_handling.metatags
- examples/kafka-service-sasl/kafka_service_sasl.metatags
- examples/kafka-service-ssl/kafka_service_ssl.metatags
- examples/sftp-client-receive-file/sftp_client_receive_file.metatags
- examples/sftp-client-send-file/sftp_client_send_file.metatags
- examples/sftp-service-receive-file/sftp_service_receive_file.metatags
- examples/sftp-service-send-file/sftp_service_send_file.metatags
> [8.x] Improve meta descriptions in Kafka and FTP BBEs

- ballerina/build.gradle
> Copy worker model to the distribution

- .github/workflows/publish-release.yml
> Fix installer tests failure in windows

- examples/nats-basic-pub/nats_basic_pub.metatags
- examples/nats-basic-reply/nats_basic_reply.metatags
- examples/nats-basic-request/nats_basic_request.metatags
- examples/nats-basic-sub/nats_basic_sub.metatags
- examples/nats-client-basic-auth/nats_client_basic_auth.metatags
- examples/nats-client-secure-connection/nats_client_secure_connection.metatags
- examples/nats-jetstream-pub/nats_jetstream_pub.metatags
- examples/nats-jetstream-sub/nats_jestream_sub.metatags
- examples/nats-service-basic-auth/nats_service_basic_auth.metatags
- examples/nats-service-constraint-validation/nats_service_constraint_validation.metatags
- examples/nats-service-secure-connection/nats_service_secure_connection.metatags
- examples/rabbitmq-client-basic-auth/rabbitmq_client_basic_auth.metatags
- examples/rabbitmq-client-constraint-validation/rabbitmq_client_constraint_validation.metatags
- examples/rabbitmq-client-secure-connection/rabbitmq_client_secure_connection.metatags
- examples/rabbitmq-consumer-with-client-acknowledgement/rabbitmq_consumer_with_client_acknowledgement.metatags
- examples/rabbitmq-consumer/rabbitmq_consumer.metatags
- examples/rabbitmq-producer/rabbitmq_producer.metatags
- examples/rabbitmq-queue-declare/rabbitmq_queue_declare.metatags
- examples/rabbitmq-service-basic-auth/rabbitmq_service_basic_auth.metatags
- examples/rabbitmq-service-constraint-validation/rabbitmq_service_constraint_validation.metatags
- examples/rabbitmq-service-secure-connection/rabbitmq_service_secure_connection.metatags
- examples/rabbitmq-sync-consumer/rabbitmq_sync_consumer.metatags
- examples/rabbitmq-transaction-consumer/rabbitmq_transaction_consumer.metatags
- examples/rabbitmq-transaction-producer/rabbitmq_transaction_producer.metatags
> Update SEO descriptions of RabbitMQ and NATS

- .github/workflows/daily-build-editor.yml
Sends a daily notification to Google Chat once the daily build editor successfully generates a release.
> Send daily release notification for editor

- .github/workflows/daily-build-editor.yml
> Update upload-artificat version in the daily build editor

- .github/workflows/publish-release-artifacts.yml
> Change branch for docker build

- .github/workflows/daily-build-editor.yml
> Replace ballerina timestamp version with snapshot in daily-build-editor

- .github/workflows/daily-build-editor.yml
> Fix replace command for updating ballerina timestamp in the daily build editor

- gradle.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-release/issues/2623 …
> [8.x] Update grpc and http versions

- examples/graphql-directives/graphql_directives.bal
- examples/graphql-file-upload/graphql_file_upload.md
Fixes: [#8650](https://github.com/ballerina-platform/ballerina-dev-website/issues/8650)
Fixes: [#8646](https://github.com/ballerina-platform/ballerina-dev-website/issues/8646)
> Update Descriptions in GraphQL BBE

- examples/graphql-directives/graphql_directives.bal
- examples/graphql-file-upload/graphql_file_upload.md
Fixes: [#8650](https://github.com/ballerina-platform/ballerina-dev-website/issues/8650)
Fixes: [#8646](https://github.com/ballerina-platform/ballerina-dev-website/issues/8646)
> [2201.8.x] Update Descriptions in GraphQL BBE

- examples/index.json
- examples/list-subtyping/list_subtyping.bal
- examples/list-subtyping/list_subtyping.out
Sending the same PR #5191 to 8.x branch
Fixes ballerina-platform/ballerina-dev-website#8668
> [2201.8.x] Fix list subtyping BBE output

- examples/open-records/open_records.bal
$subject. 
Fixes ballerina-platform/ballerina-dev-website#8669
> [Master] Fix open records BBE comment

- pom.xml
> Update nexus staging urls for 1.2.49 release

- pom.xml
> [1.2.x] Sync ballerina-1.2.49-stage branch with 1.2.x

- examples/open-records/open_records.bal
Sending the same PR #5192 to 8.x branch
Fixes ballerina-platform/ballerina-dev-website#8669
> [2201.8.x] Fix open records BBE comment

- .github/workflows/publish-release.yml
> Update docker build branch in publish release

- gradle.properties
> Update cache and crypto versions

- gradle.properties
> [2201.8.x] Update ballerina-lang latest time-stamp version

- gradle.properties
> [2201.8.x]Update persist tool version

- ballerina-test-automation/gradle.properties
> Update swanlake version for installer tests

- gradle.properties
> [2201.8.x] Update OpenAPI version 

- gradle.properties
> [8.x] Update dev-tools version

- gradle.properties
> [8.5-stage] Update gradle.properties

- .github/workflows/publish-release.yml
> Fix downloading windows zip in publish release

- examples/index.json
- gradle.properties
> Bump FTP version

- .github/workflows/publish-release.yml
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- examples/index.json
- gradle.properties
> Sync with 2201.8.x

- .github/workflows/publish-release.yml
> Fix windows installer tests

- .github/workflows/publish-release.yml
> [2201.7.x] Fix MacOS installer tests

- .github/workflows/publish-release.yml
> [2201.8.x] Fix MacOS installer tests

- .github/workflows/publish-release.yml
> Fix MacOS installer tests

- .github/workflows/daily-build-editor.yml
- ballerina/build.gradle
$title as we are discontinuing the worker model.
> Update the daily build editor to use the flow chart model

- gradle.properties
> [2201.5.x] Update http version

- gradle.properties
> [2201.7.x] Update http version

- gradle.properties
> [2201.8.x] Update http version

- gradle.properties
> [2201.6.x] Update http version

- gradle.properties
>$subject 
Updated to 1.3.3-20240307-162800-940a309
> Update dev tools version to a timestamped version

- ballerina-test-automation/gradle.properties
- gradle.properties
> Add necessary timestamped versions for 2201.8.6

- gradle.properties
> $subject
To fix the `./gradlew clean` command in the `http` library module
> Update http version to 2.10.10

- gradle.properties
> [8.x] Update to stable versions after 2201.8.6 lang release

- .github/workflows/daily-build-2201.6.x.yml
- .github/workflows/daily-build-2201.7.x.yml
- .github/workflows/daily-build-2201.8.x.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
> Fix windows installer build in publish release

- .github/workflows/publish-release.yml
> [2201.6.x] Fix windows installer build in publish release

- gradle.properties
> [2201.8.x] Bump c2c version

- examples/edi-to-record/codegen_command.out
- examples/record-to-edi/codegen_command.out
> Update the Ballerina By Examples pages with EDI Tool release 1.0.0 changes.
Related to: https://github.com/ballerina-platform/ballerina-dev-website/issues/8804 …
> Update the BBE pages with EDI Tool v1.0 enhancements

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
$subject
>  Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Type …
> Update URLs for 1.2.50

- ballerina-test/pom.xml
- ballerina/pom.xml
> Remove 1.2.50-SNAPSHOT part in versions

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync Ballerina 1.2.50

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Re-add SNAPSHOT part in versions

- gradle.properties
> Update new http patch version

- ballerina/build.gradle
- stdlib-integration-tests/http/tests/rest_introspection_test.bal
Resolves https://github.com/ballerina-platform/ballerina-distribution/issues/4625
This build.gradle was updated to utilize the `bal test` command for executing standard library tests instead of the previously used `bal build` command.
> Type “Sent” when you have provided new/updated …
> Fix standard library integration tests not executing properly

- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
> [1.2.x] Fix windows installer build

- examples/ftp-service-receive-file/ftp_service_receive_file.bal
- examples/ftp-service-send-file/ftp_service_send_file.bal
- examples/sftp-service-receive-file/sftp_service_receive_file.bal
- examples/sftp-service-send-file/sftp_service_send_file.bal
> [master] Update ftp file api used in the BBEs

- gradle.properties
> Bump GraphQL dependencies

- examples/graphql-field-interceptors/graphql_field_interceptors.md
- examples/graphql-service-interceptors/graphql_service_interceptors.md
Fixes: [#8647](https://github.com/ballerina-platform/ballerina-dev-website/issues/8647)
> [2201.8.x] Update GraphQL BBEs

- examples/interface-to-external-code/interface_to_external_code.md
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8798
> Fix a typo

- gradle.properties
> Update the WebSocket, TCP and UDP module versions

- .trivyignore
> Update Trivy ignore

- .trivyignore
> Include unfixed CVE to Trivy ignorelist
> Include unfixed CVE to Trivy ignorelist

- gradle.properties
> Update `ballerinaLangVersion` timestamp version

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update the lang timestamp for update 9 release

- examples/index.json
- examples/xml-to-record-with-projection/xml_to_record_with_projection.bal
- examples/xml-to-record-with-projection/xml_to_record_with_projection.md
- examples/xml-to-record-with-projection/xml_to_record_with_projection.metatags
- examples/xml-to-record-with-projection/xml_to_record_with_projection.out
- examples/xml-to-record/xml_to_record.bal
- examples/xml-to-record/xml_to_record.md
- examples/xml-to-record/xml_to_record.metatags
- examples/xml-to-record/xml_to_record.out
- Added BBE for convert XML to record
- Added BBE for convert XML to record with projection
> Add BBEs for Xmldata Module

- examples/index.json
- examples/json-to-record-with-projection/json_to_record_with_projection.bal
- examples/json-to-record-with-projection/json_to_record_with_projection.md
- examples/json-to-record-with-projection/json_to_record_with_projection.metatags
- examples/json-to-record-with-projection/json_to_record_with_projection.out
- examples/json-to-record/json_to_record.bal
- examples/json-to-record/json_to_record.md
- examples/json-to-record/json_to_record.metatags
- examples/json-to-record/json_to_record.out
- Added BBE for convert JSON to record
- Added BBE for convert JSON to record with projection
> Add BBEs for Jsondata Module

- gradle.properties
Update the latest gRPC version in distribution …
> Update gRPC version in gradle.properties

- examples/index.json
- examples/json-to-record-with-projection/json_to_record_with_projection.bal
- examples/json-to-record-with-projection/json_to_record_with_projection.md
- examples/json-to-record-with-projection/json_to_record_with_projection.metatags
- examples/json-to-record-with-projection/json_to_record_with_projection.out
- examples/json-to-record/json_to_record.bal
- examples/json-to-record/json_to_record.md
- examples/json-to-record/json_to_record.metatags
- examples/json-to-record/json_to_record.out
- Added BBE for convert JSON to record
- Added BBE for convert JSON to record with projection
> [2201.9.x] Add BBEs for Jsondata Module

- examples/index.json
- examples/xml-to-record-with-projection/xml_to_record_with_projection.bal
- examples/xml-to-record-with-projection/xml_to_record_with_projection.md
- examples/xml-to-record-with-projection/xml_to_record_with_projection.metatags
- examples/xml-to-record-with-projection/xml_to_record_with_projection.out
- examples/xml-to-record/xml_to_record.bal
- examples/xml-to-record/xml_to_record.md
- examples/xml-to-record/xml_to_record.metatags
- examples/xml-to-record/xml_to_record.out
- Added BBE for convert XML to record
- Added BBE for convert XML to record with projection
> [2201.9.x] Add BBEs for Xmldata Module

- build.gradle
- gradle.properties
> Update dependencies for 2201.9.0 release

- gradle.properties
> [9.x] Update dependency versions

- gradle.properties
> Remove duplicated stdlib versions in gradle.properties

- project-api-tests/src/test/resources/testng.xml
Fixes https://github.com/ballerina-platform/ballerina-release/issues/2652
> Disable project api test in 9.x branch

- .github/workflows/publish-release.yml
- .github/workflows/sign-installers.yml
> Update Cosign version

- .github/workflows/publish-release.yml
- .github/workflows/sign-installers.yml
> Update cosign version in 2201.9.x branch

- project-api-tests/src/test/resources/bal-tool/cmd-outputs/tool-update-with-new-patch-and-minor.txt
- project-api-tests/src/test/resources/testng.xml
Fixes https://github.com/ballerina-platform/ballerina-release/issues/2652
There has been a new CLI log addition due to the hash validation feature in package pushing. This corrects the expected test o/p to handle that.
Project API test report - https://github.com/ballerina-platform/ballerina-distribution/actions/runs/8684999835/job/23813585540
> Brief description of the …
> [2201.9.x] Fix failing project API tests

- build.gradle
- gradle.properties
> Add Avro dependency to the distribution

- gradle.properties
Fixes https://github.com/ballerina-platform/ballerina-library/issues/6323
> Update the edi module version to latest

- gradle.properties
Fixes https://github.com/ballerina-platform/ballerina-library/issues/6323
> Update edi to latest version

- examples/avro/avro_serdes.bal
- examples/avro/avro_serdes.md
- examples/avro/avro_serdes.metatags
- examples/avro/avro_serdes.out
- examples/index.json
> Add BBEs for the Avro module

- gradle.properties
> Update the persist tool version

- gradle.properties
> Update GraphQL, GraphQL tools, and dev tools versions

- examples/avro-serdes/avro_serdes.md
- examples/index.json
> Update the topic of the Avro BBE

- examples/graphql-dataloader/graphql_dataloader.bal
- examples/graphql-documentation/graphql_documentation.bal
- examples/graphql-documentation/graphql_documentation.md
- examples/graphql-service-interceptors/graphql_service_interceptors.bal
- examples/graphql-subscriptions/graphql_subscriptions.bal
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6314
> Fix GraphQL BBE issues

- gradle.properties
To update the persist tool timestamp version …
> Update persistTool timestamp version

- project-api-tests/src/test/resources/bal-tool/cmd-outputs/tool-update-with-new-patch-and-minor.txt
$ subject
Fixes https://github.com/ballerina-platform/ballerina-release/issues/2652
Master PR of https://github.com/ballerina-platform/ballerina-distribution/pull/5326 …
> [master] Fix failing project API tests

- examples/fork/fork.bal
- examples/fork/fork.md
- examples/fork/fork.metatags
- examples/fork/fork.out
- examples/index.json
> [2201.9.x] Add bbe for fork statement

- gradle.properties
> Change lang and c2c versions

- ballerina-test/src/test/resources/openapi/expected/utils.bal
- gradle.properties
> Update dependency versions and update openapi test case

- examples/soap-client-send-receive/soap_client_send_receive.md
> Update the description of a SOAP BBE

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync `1.2.x` after `1.2.50` release

- pom.xml
> Update nexus staging urls and versions for `1.2.51` release

- ballerina-test/src/test/resources/openapi/expected/client.bal
- ballerina-test/src/test/resources/openapi/expected/types.bal
- ballerina-test/src/test/resources/openapi/expected/utils.bal
- gradle.properties
> Update openapi tool changes

- gradle.properties
> Update Standard Library Dependencies (Ballerina Lang : 2201.9.0-20240502-141200-0a49fa42)

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.9.0] Update OpenAPI version

- build.gradle
- gradle.properties
> Update dependencies with stable versions

- examples/conditional-send/conditional_send.bal
- examples/conditional-send/conditional_send.md
- examples/conditional-send/conditional_send.metatags
- examples/conditional-send/conditional_send.out
- examples/index.json
$subject
Sending same [PR](https://github.com/ballerina-platform/ballerina-distribution/pull/5292) to master
> [Master] Add conditional-send bbe

- pom.xml
> Update nexus staging urls and versions for 1.2.51 release

- gradle.properties
> [6.x] Update http version

- gradle.properties
> [5.x] Update http version

- examples/avro-serdes/avro_serdes.md
> Update the description of the Avro BBE

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync 1.2.x after 1.2.51 release

- examples/index.json
- gradle.properties
Update the library to the latest version to fix the build failure caused by an output mismatch in the Avro BBE.
https://github.com/ballerina-platform/ballerina-distribution/actions/runs/9102412265/job/25021940100#step:4:562
> Bump the Avro library version to 1.0.0

- gradle.properties
> [2201.8.x]Update lang version

- ballerina-test-automation/gradle.properties
> [2201.8.x]Update `swan-lake-latest-version` and `swan-lake-latest-version-display-text` to their latest versions

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> Update openapi version
Http version update PR: https://github.com/ballerina-platform/ballerina-distribution/pull/5424
> [2201.9.x] Update library and tool versions

- .trivyignore
> Skip bouncy castle vulnerabilities

- devtools-integration-tests/src/test/java/org/ballerina/devtools/debug/ExpressionEvaluationTest.java
Related to https://github.com/ballerina-platform/ballerina-distribution/issues/4511 …
> Disable testObjectMethodEvaluation debugger test

- gradle.properties
> Update the TCP, UDP and WebSocket versions

- gradle.properties
> Update the Crypto version after BC version update

- gradle.properties
> [2201.9.x] Bump c2c to 3.0.1

- gradle.properties
> [2201.8.x] Update http patch version

- gradle.properties
> Update the GraphQL dependency versions

- gradle.properties
> Update Ballerina-Lang timestamped version

- gradle.properties
> [2201.8.x] Update crypto version

- gradle.properties
> [8.x] Bump grpc version

- gradle.properties
This reverts commit 55424388510d70d0fd9e43822b987542a5a92ffe. …
> Revert "Update crypto version"

- .trivyignore
$title, due to trivy check failure.
Issue to track this: https://github.com/ballerina-platform/ballerina-distribution/issues/5474 …
> Ignore netty-codec & bouncycastle vulnerabilities for 2201.8.7 release

- .github/workflows/publish-release.yml
> Update Cosign version for macOS
> Update Cosign version for macOS

- gradle.properties
> Update ballerinai-transaction version

- gradle.properties
> [2201.8.x] Update Ballerina-Lang and Std-Lib stable versions

- ballerina-test/src/test/resources/grpc/expected-files/route_guide_pb.bal
- gradle.properties
> [9.x] Update gRPC version

- pom.xml
> Update nexus staging urls for 1.2.52 release

- pom.xml
> [1.2.x] Update nexus staging urls for 1.2.52 release

- gradle.properties
> Update graphql version to 1.13.1

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.9.x] Update openAPI version

- gradle.properties
> [2201.9.x] Update dependency versions

- .trivyignore
> [2201.9.x] Remove BC vulnerabilities from the ignore list

- .trivyignore
> [2201.8.x] Remove BC vulnerabilities from the ignore list

- .github/workflows/daily-build-2201.9.x.yml
> Include Daily build for 2201.9.x

- examples/http-service-and-resource-paths/http_service_and_resource_paths.bal
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/8734
> [2201.9.x] Fix the explanation on HTTP dot resource path

- project-api-tests/src/test/resources/hierarchical-packages/PackageK/Ballerina.toml
- project-api-tests/src/test/resources/hierarchical-packages/PackageM/Ballerina.toml
- project-api-tests/src/test/resources/hierarchical-packages/PackageN/Ballerina.toml
- project-api-tests/src/test/resources/hierarchical-packages/PackageP/Ballerina.toml
- project-api-tests/src/test/resources/hierarchical-packages/PackageR/Ballerina.toml
- project-api-tests/src/test/resources/hierarchical-packages/PackageS/Ballerina.toml
HierrarchicalPackagesTests have been failing due to a corrupted Dependencies.toml file. This was a newly added improvement to lang. The reason was printing of a warning due to a change in the org name in the Ballerina.toml and Dependencies.toml
Failed daily build - https://scans.gradle.com/s/imo6smtrvcd52/tests/overview?outcome=FAILED
> Brief description of the new …
> [master] Rename test resource org to avoid corrupted dep.toml error

- gradle.properties
> [9.x] Update ftp version

- gradle.properties
> [master] Update ftp version

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Update nexus URLS and versions for 1.2.54 release

- gradle.properties
> [2201.9.x] Update Auth Version

- examples/graphql-service-query-complexity/graphql_service_query_complexity.1.graphql
- examples/graphql-service-query-complexity/graphql_service_query_complexity.2.graphql
- examples/graphql-service-query-complexity/graphql_service_query_complexity.bal
- examples/graphql-service-query-complexity/graphql_service_query_complexity.client.1.out
- examples/graphql-service-query-complexity/graphql_service_query_complexity.client.2.out
- examples/graphql-service-query-complexity/graphql_service_query_complexity.md
- examples/graphql-service-query-complexity/graphql_service_query_complexity.metatags
- examples/graphql-service-query-complexity/graphql_service_query_complexity.server.out
- examples/index.json
- gradle.properties
> Add GraphQL Query Complexity BBE

- gradle.properties
> Add data.yaml module to the distribution

- examples/json-to-record-with-projection/json_to_record_with_projection.md
- examples/xml-to-record-with-projection/xml_to_record_with_projection.md
> [2201.9.x] Correct output field in md files of data bbes

- examples/json-to-record-with-projection/json_to_record_with_projection.md
- examples/xml-to-record-with-projection/xml_to_record_with_projection.md
> Correct output field in md files of data bbes

- .github/workflows/daily-build-2201.10.x.yml
> Include daily build for 2201.10.x

- build.gradle
- gradle.properties
> [2201.10.x] Add data.yaml module to the distribution

- gradle.properties
> Update data.yaml timestamp version

- gradle.properties
> Update the IO version

- gradle.properties
> [2201.9.x] Update standard library latest versions

- build.gradle
- gradle.properties
> Add LDAP module into the Ballerina distribution

- gradle.properties
> [2201.9.x] Update time-stamp versions for 9.3

- build.gradle
- gradle.properties
> [Master] Add LDAP module into the Ballerina distribution

- examples/http-access-logs/Config.toml
- examples/http-access-logs/http_access_logs.bal
- examples/http-access-logs/http_access_logs.md
- examples/http-access-logs/http_access_logs.server.out
> $title
Tracked Issue: https://github.com/ballerina-platform/ballerina-library/issues/6726 …
> Update BBEs for AccessLog Improvements

- gradle.properties
> Update stable versions for 2201.9.3 release

- gradle.properties
> Update c2c and dev-tools timestamp versions for 2201.10.0-rc1

- gradle.properties
> Bump ldap module version

- gradle.properties
> [2201.9.x] Update the Auth Version

- gradle.properties
> [2201.9.3-stage] Update auth version

- ballerina/LICENSE
> Update license file for 2201.9.3

- examples/graphql-client-security-jwt-authentication/graphql_client_security_jwt_authentication.md
> [2201.10.0-stage] Fix incorrect file path in GraphQL JWT BBE

- examples/graphql-client-security-jwt-authentication/graphql_client_security_jwt_authentication.md
> [Master] Fix incorrect file path in GraphQL JWT BBE

- examples/graphql-client-security-jwt-authentication/graphql_client_security_jwt_authentication.md
> [2201.10.x] Fix incorrect file path in GraphQL JWT BBE

- gradle.properties
> Update XSLT module version

- examples/http-sse-client/http_sse_client.bal
- examples/http-sse-client/http_sse_client.client.out
- examples/http-sse-client/http_sse_client.md
- examples/http-sse-client/http_sse_client.metatags
- examples/http-sse-service/http_sse_service.bal
- examples/http-sse-service/http_sse_service.client.out
- examples/http-sse-service/http_sse_service.md
- examples/http-sse-service/http_sse_service.metatags
- examples/http-sse-service/http_sse_service.server.out
- examples/index.json
> Add Server-Sent Events BBE

- examples/index.json
- examples/ldap-add-remove-entry/ldap_add_remove_entry.bal
- examples/ldap-add-remove-entry/ldap_add_remove_entry.md
- examples/ldap-add-remove-entry/ldap_add_remove_entry.metatags
- examples/ldap-add-remove-entry/ldap_add_remove_entry.server.out
- examples/ldap-search-entry/ldap_search_entry.bal
- examples/ldap-search-entry/ldap_search_entry.md
- examples/ldap-search-entry/ldap_search_entry.metatags
- examples/ldap-search-entry/ldap_search_entry.server.out
> Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6882
> Add BBEs for the LDAP module

- gradle.properties
> [2201.10.x] Update library dependency versions

- examples/http-sse-service/http_sse_service.md
> [2201.10.0-stage] Add client invocation tip for SSE server

- examples/graphql-service-query-complexity/graphql_service_query_complexity.md
> Update GraphQL Query Complexity BBE

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update lang timestamp version and update-tool version

- examples/http-sse-service/http_sse_service.md
> [2201.10.x] Add client invocation tip for SSE server

- gradle.properties
> [2201.8.x] Update http latest version

- .github/workflows/daily-build-2201.10.x.yml
- .github/workflows/daily-build-2201.7.x.yml
- .github/workflows/daily-build-2201.8.x.yml
- .github/workflows/daily-build-2201.9.x.yml
$ subject
Related to https://github.com/ballerina-platform/ballerina-distribution/issues/5541 …
> Add prod central token to the 7.x ,8.x ,9.x ,10.x daily builds

- examples/index.json
> Disable output verification sequence-diagrams

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update project version to 2201.10.1

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update project version to 2201.11.0

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update project version to 2201.8.9

- .github/workflows/daily-build-editor.yml
> Set the ballerina lang timestamp version for the editor worflow

- examples/index.json
- examples/multiple-receive/multiple_receive.bal
- examples/multiple-receive/multiple_receive.md
- examples/multiple-receive/multiple_receive.metatags
- examples/multiple-receive/multiple_receive.out
Sending this https://github.com/ballerina-platform/ballerina-distribution/pull/5291 to 2201.9.x  …
> [2201.9.x] Add multiple-receive bbe

- examples/index.json
$title. Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9280.
> Reorganize examples landing page columns

- examples/time-formatting-and-parsing/tests/time_formatting_and_parsing_test.bal
- examples/time-formatting-and-parsing/time_formatting_and_parsing.bal
- examples/time-formatting-and-parsing/time_formatting_and_parsing.out
- gradle.properties
> [2201.10.x] Update Ballerina time version

- examples/time-formatting-and-parsing/tests/time_formatting_and_parsing_test.bal
- examples/time-formatting-and-parsing/time_formatting_and_parsing.bal
- examples/time-formatting-and-parsing/time_formatting_and_parsing.out
- gradle.properties
> [2201.9.x] Update Ballerina time version

- examples/time-formatting-and-parsing/tests/time_formatting_and_parsing_test.bal
- examples/time-formatting-and-parsing/time_formatting_and_parsing.bal
- examples/time-formatting-and-parsing/time_formatting_and_parsing.out
- gradle.properties
> Update Ballerina time version

- ballerina/build.gradle
> Copy sequence model diagram JARs to the distribution

- examples/json-type/json_type.md
Related to https://github.com/ballerina-platform/ballerina-distribution/pull/5635
> Fix reference link in json type BBE

- examples/gauge-metrics/gauge_metrics.md
- examples/index.json
* Fix https://github.com/ballerina-platform/ballerina-dev-website/issues/9302 …
> [master] Rearrange observability bbe menus and fix content

- examples/byte-type/byte_type.md
- examples/byte-type/byte_type.metatags
> Add `unsigned8` reference into byte bbe

- examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.bal
- examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.out
- examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.bal
- examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.out
Closes https://github.com/ballerina-platform/ballerina-dev-website/issues/9305
> Update binding patterns BBEs

- gradle.properties
> [2201.10.x] Update http patch version

- gradle.properties
> [2201.9.x] Update http patch version

- examples/csv-string-to-record-array/csv_string_to_record_array.bal
- examples/csv-string-to-record-array/csv_string_to_record_array.md
- examples/csv-string-to-record-array/csv_string_to_record_array.metatags
- examples/csv-string-to-record-array/csv_string_to_record_array.out
- examples/index.json
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9448
> Add bbe for convert csv string into records

- .trivyignore
- gradle.properties
> Update versions for 2201.10.1 patch

- examples/index.json
> Disable output verification temporarily - 2201.10.1

- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.bal
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.md
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.metatags
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.out
- examples/index.json
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9449
> Add bbe for converting csv string to `anydata[][]`

- gradle.properties
> [2201.9.x] Update protobuf and grpc versions in gradle.properties

- gradle.properties
> [2201.8.x] Update protobuf and grpc versions in gradle.properties

- gradle.properties
> Update protobuf and grpc versions in gradle.properties

- gradle.properties
> Update 2201.9.4 versions

- gradle.properties
> Update 2201.9.4 lang version

- examples/index.json
- examples/parse-csv-lists/parse_csv_lists_to_ballerina_types.bal
- examples/parse-csv-lists/parse_csv_lists_to_ballerina_types.md
- examples/parse-csv-lists/parse_csv_lists_to_ballerina_types.metatags
- examples/parse-csv-lists/parse_csv_lists_to_ballerina_types.out
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9457
> Add bbe for csv `parseList` functionality

- examples/docker-hello-world/docker_hello_world.md
- examples/kubernetes-hello-world/kubernetes_hello_world.md
- Document the required command for c2c build in MacOS
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9431
- Resolves https://github.com/ballerina-platform/module-ballerina-c2c/issues/813
> Document the required command for c2c build in MacOS

- examples/csv-user-configurations/csv_user_configurations.bal
- examples/csv-user-configurations/csv_user_configurations.md
- examples/csv-user-configurations/csv_user_configurations.metatags
- examples/csv-user-configurations/csv_user_configurations.out
- examples/index.json
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9461
> Add bbe for csv with custom configs

- examples/index.json
- examples/unary-operators/unary_operators.bal
- examples/unary-operators/unary_operators.md
- examples/unary-operators/unary_operators.metatags
- examples/unary-operators/unary_operators.out
Add bbe for unary operators
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9441
> Add bbe for unary operators

- examples/binary-operators/binary_operators.bal
- examples/binary-operators/binary_operators.md
- examples/binary-operators/binary_operators.metatags
- examples/binary-operators/binary_operators.out
- examples/index.json
- examples/unary-operators/unary_operators.bal
- examples/unary-operators/unary_operators.md
- examples/unary-operators/unary_operators.metatags
- examples/unary-operators/unary_operators.out
$Subject
This PR is a combination of https://github.com/ballerina-platform/ballerina-distribution/pull/5667 & https://github.com/ballerina-platform/ballerina-distribution/pull/5666
> Add binary and Unary operators for U10

- examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.bal
- examples/list-binding-pattern-in-match-statement/list_binding_pattern_in_match_statement.out
- examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.bal
- examples/mapping-binding-pattern-in-match-statement/mapping_binding_pattern_in_match_statement.out
Sending the changes in https://github.com/ballerina-platform/ballerina-distribution/pull/5657 to 10.x
> [2201.10.x] Update binding patterns BBEs

- examples/backtick-templates/backtick_templates.bal
- examples/backtick-templates/backtick_templates.out
Sending the changes sent [here](https://github.com/ballerina-platform/ballerina-distribution/pull/5688) to 10.x
> Link to the PR …
> [2201.10.x] Add string template splitting section

- examples/parse-csv-lists/parse_csv_lists.bal
> Update checkstyles in csv ballerina by examples

- examples/index.json
Done this until the `csv` module pack with the distribution in next release
> Disable verify output for csv bbes

- examples/csv-streams-to-record-arrays/csv_streams_to_record_array.bal
- examples/csv-streams-to-record-arrays/csv_streams_to_record_array.md
- examples/csv-streams-to-record-arrays/csv_streams_to_record_array.metatags
- examples/csv-streams-to-record-arrays/csv_streams_to_record_array.out
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.bal
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.md
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.metatags
- examples/csv-string-to-anydata-array/csv_string_to_anydata_array.out
- examples/csv-string-to-record-array/csv_string_to_record_array.bal
- examples/csv-string-to-record-array/csv_string_to_record_array.md
- examples/csv-string-to-record-array/csv_string_to_record_array.metatags
- examples/csv-string-to-record-array/csv_string_to_record_array.out
- examples/csv-user-configurations/csv_user_configurations.bal
- examples/csv-user-configurations/csv_user_configurations.md
- examples/csv-user-configurations/csv_user_configurations.metatags
- examples/csv-user-configurations/csv_user_configurations.out
- examples/index.json
- examples/parse-csv-lists/parse_csv_lists.bal
- examples/parse-csv-lists/parse_csv_lists.md
- examples/parse-csv-lists/parse_csv_lists.metatags
- examples/parse-csv-lists/parse_csv_lists.out
- examples/transform-csv-records-to-custom-types/transform_csv_records_to_custom_types.bal
- examples/transform-csv-records-to-custom-types/transform_csv_records_to_custom_types.md
- examples/transform-csv-records-to-custom-types/transform_csv_records_to_custom_types.metatags
- examples/transform-csv-records-to-custom-types/transform_csv_records_to_custom_types.out
> Add CSV Ballerina by examples for U10

- gradle.properties
> Remove timestamped version

- ballerina-test-automation/gradle.properties
- gradle.properties
> [2201.9.x] Update tool version

- examples/graphql-context/graphql_context.bal
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/9354 …
> Update graphql context BBE example to include an object type

- ballerina/LICENSE
- gradle.properties
> [2201.9.x] Update avro-module version

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update lang timestamp version

- .trivyignore
> Igonre CVE-2024-47554 Vulnerability

- gradle.properties
> Bump the Avro version to 1.0.1

- gradle.properties
> [2201.10.x] Update SQL version

- gradle.properties
> [Master] Bump the Avro version to 1.0.1

- examples/unions/unions.bal
- examples/unions/unions.out
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9300
> Improve the unions BBE for type narrowing

- .trivyignore
> $title. https://github.com/wso2-enterprise/internal-support-ballerina/issues/800 …
> [2201.10.x] Ignore the `commons:io` vulnerability

- gradle.properties
> [2201.9.x] Update sql patch version

- gradle.properties
> [2201.8.x] Update sql version

- gradle.properties
> Update the lang version for 2201.10.2 release

- examples/check-expression/check_expression.bal
- examples/error-reporting/error_reporting.bal
- examples/error-reporting/error_reporting.out
- examples/error-subtyping/error_subtyping.bal
- examples/error-subtyping/error_subtyping.md
- examples/error-type-intersection/error_type_intersection.bal
- examples/error-type-intersection/error_type_intersection.md
> Add suggestions from Error BBE PR

- examples/check-expression/check_expression.bal
- examples/error-reporting/error_reporting.bal
- examples/error-reporting/error_reporting.out
- examples/error-subtyping/error_subtyping.bal
- examples/error-subtyping/error_subtyping.md
- examples/error-type-intersection/error_type_intersection.bal
- examples/error-type-intersection/error_type_intersection.md
Add suggestions from to 10.x branc
https://github.com/ballerina-platform/ballerina-distribution/pull/5709
> Add suggestions from Error BBE PR to 10.x

- gradle.properties
> Update distribution version into 10.2

- .trivyignore
- build.gradle
Update the Apache common io jar version
> Update the Apache common io jar version

- examples/docker-hello-world/docker_hello_world.md
- examples/kubernetes-hello-world/kubernetes_hello_world.md
- Fix formatting in code to cloud guide
> Fix formatting in code to cloud guide

- examples/error-subtyping/error_subtyping.md
> Fix typo in error subtyping BBE

- .trivyignore
- build.gradle
> Update commons-io version

- gradle.properties
> Bump the Avro version to 1.0.2

- gradle.properties
> Update the `avro` version to 1.0.2

- .trivyignore
> Temporary ignore trivy failures

- .github/workflows/daily-build.yml
> Fix archive linux-arm deb hashes

- gradle.properties
> [2201.7.x] Update HTTP patch version

- gradle.properties
> [2201.5.x] Update HTTP patch version

- examples/regexp-type/regexp_type.bal
- examples/regexp-type/regexp_type.md
- examples/regexp-type/regexp_type.out
$title.
Closes https://github.com/ballerina-platform/ballerina-dev-website/issues/9316
> Update the RegExp type BBE

- .github/workflows/publish-release.yml
> Include linux-arm installer build to release

- examples/joining-iterable-objects/joining_iterable_objects.md
Fix https://github.com/ballerina-platform/ballerina-dev-website/issues/9285
> Improve Join Iterable objects BBE

- .github/workflows/publish_release_bi.yml
> Add release workflow for BI distribution release

- .github/workflows/publish_release_bi.yml
> Set NodeJS version

- .github/workflows/publish_release_bi.yml
> Remove directory after build

- .github/workflows/publish_release_bi.yml
> Remove sigining artifacts

- examples/raw-templates/Ballerina.toml
- examples/raw-templates/raw_templates.bal
- examples/raw-templates/raw_templates.md
- examples/raw-templates/raw_templates.out
Add changes in #5749 to 10.x branch
> Update raw-template BBE to remove external dependency 10.x

- .github/workflows/publish_release_bi.yml
> Update Kola release workflow to run on schedule

- examples/regexp-match-operations/regexp_match_operations.md
- examples/regexp-replace-operations/regexp_replace_operations.md
> [2201.10.x] Fix regex operations bbe topics

- examples/regexp-match-operations/regexp_match_operations.md
- examples/regexp-replace-operations/regexp_replace_operations.md
> Fix regex operations bbe topics

- ballerina-test-automation/gradle.properties
- gradle.properties
$subject for 2201.9.5 release
https://github.com/ballerina-platform/ballerina-distribution/issues/5812 …
> [2201.9.x] Update lang timestamp version

- gradle.properties
> [Master] Update SQL version

- examples/index.json
> Disable output verification for sequence-diagram bbe
> Disable output verification for sequence-diagram bbe

- gradle.properties
> [2201.6.x] Update HTTP patch version

- ballerina/build.gradle
> Part of https://github.com/ballerina-platform/ballerina-lang/issues/13448. This PR renames the new "proxy script" from https://github.com/ballerina-platform/ballerina-lang/pull/43481 to `bal` and excludes it from the Linux build
> Link(s) to product documentation that addresses the …
> Rename `bal.windows.gitbash` to `bal` in windows distribution

- .github/workflows/daily-build-2201.10.x.yml
- .github/workflows/daily-build-2201.8.x.yml
- .github/workflows/daily-build-2201.9.x.yml
- .github/workflows/daily-build-editor.yml
- .github/workflows/daily-build.yml
- .github/workflows/language_server_simulator_fhir.yml
- .github/workflows/language_server_simulator_nballerina.yml
- .github/workflows/main.yml
- .github/workflows/publish-release-artifacts.yml
- .github/workflows/publish-release.yml
- .github/workflows/publish_release_bi.yml
- .github/workflows/pull-request.yml
- README.md
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/BallerinaCommandTest.java
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- ballerina/build.gradle
- build.gradle
- cache-generator/src/main/java/io/ballerina/gencache/cmd/GenCacheCmd.java
- dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
- docs/build-ballerina-from-source.md
- examples/index.json
- gradle.properties
- gradle/javaProject.gradle
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTest.java
- project-api-tests/src/test/java/org/ballerina/projectapi/CentralTestUtils.java
- project-api-tests/src/test/resources/central/projectB/Ballerina.toml
- resources/tools/INSTALL.txt
> Migrate to Java 21

- .github/workflows/publish-release.yml
- Add multiple architecture support for Docker images
- https://github.com/ballerina-platform/ballerina-lang/issues/43570
> Add multiple architecture support for Docker images

- pom.xml
> Update versions for 1.2.55

- .github/workflows/daily-build-2201.10.x.yml
- gradle.properties
> $Subject
Trivy scan: https://github.com/ballerina-platform/ballerina-distribution/actions/runs/11908056223/job/33182794411
> [2201.10.x] Fix netty trivy failure

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.10.x] Update OpenAPI version

- ballerina-test-automation/gradle.properties
> Update lang latest version for 2201.10.3

- .github/workflows/publish-release.yml
- pom.xml
> Update URL versions for Ballerina 1.2.55

- examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.md
- examples/jms-consumer-consume-message/jms_consumer_consume_message.md
- examples/jms-service-consume-message/jms_service_consume_message.md
> [2201.10.x] Fix broken links in the JMS consumer BBEs

- examples/jms-consumer-acknowledgement/jms_consumer_acknowledgement.md
- examples/jms-consumer-consume-message/jms_consumer_consume_message.md
> Fix typo in JMS consumer samples

- gradle.properties
> [2201.10.x] Update Websubhub version

- gradle.properties
> [2201.9.x] Update Websubhub version

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Update version after 1.2.55 release 

- examples/index.json
- examples/singleton-types/singleton_types.bal
- examples/singleton-types/singleton_types.md
- examples/singleton-types/singleton_types.metatags
- examples/singleton-types/singleton_types.out
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9308
> Add a BBE for singleton types

- gradle.properties
> Update the library versions for 2201.9.6 release

- ballerina-test-automation/gradle.properties
> Update test automation for 2201.9.6

- gradle.properties
Update `data.xmldata` version for u11 and its dependent libraries
> Update xmldata dependencies for u11

- .github/workflows/daily-build-editor.yml
$title as the latest changes are now in master
> Use the `main` branch of the `ballerina-dev-tools` repository for the daily build editor workflow

- gradle.properties
> Update ballerina jre version

- .github/workflows/publish_release_bi.yml
> Use ballerina-dev-tools main branch for kola release

- ballerina/build.gradle
> Add trigger model LS extension to the Ballerina distribution 

- gradle.properties
> Update the dev-tools version to the latest timestamp

- ballerina-test-automation/gradle.properties
- gradle.properties
> Update update-tool version [2201.11.x]

- .github/workflows/publish_release_bi.yml
> Update kola release workflow

- .github/workflows/publish-release.yml
> $subject to possibly fix docker build step failure …
> [2201.11.x] Upgrade docker actions in the release pipeline

- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/publish_release_bi.yml
> [2201.11.x]Fix windows installer build

- .github/workflows/publish-release.yml
- Remove load parameter from Docker action
> Remove load parameter from Docker action

- .github/workflows/publish-release.yml
- Remove multi aarch support for release-test image
> Remove multi-arch support for release-test image

- .github/workflows/publish-release-artifacts.yml
- Add multi arch support for base image
> Add multi arch support for base image

- .github/workflows/publish-release-artifacts.yml
> Fix publish release artifacts workflow docker build

- .github/workflows/publish-release-artifacts.yml
> [2201.11.x] Fix variable references in publish release artifact workflow steps

- .github/workflows/publish-release-artifacts.yml
> Copy .deb artifact for devcontainer build

- build.gradle
> Add csv data module into gradle files

- build.gradle
> Add csv data library into the gradle

- .github/workflows/publish-release.yml
> Sync master with 2201.11.x

- gradle.properties
> Update IO and xmldata versions

- gradle.properties
> Update the TCP and UDP versions

- gradle.properties
> Update http and grpc patch versions

- .github/workflows/daily-build.yml
> Temporary disable project-api tests

- project-api-tests/src/test/java/org/ballerina/projectapi/BalToolTest.java
$ subject
Project api test run - https://github.com/ballerina-platform/ballerina-distribution/actions/runs/12425750205
> Link to …
> [2201.10.x] Fix project API failures

- gradle.properties
> [2201.8.x] Update dependencies versions

- project-api-tests/src/test/java/org/ballerina/projectapi/BalToolTest.java
$ subject
Project api test run - https://github.com/ballerina-platform/ballerina-distribution/actions/runs/12425900929
> Link to …
> [2201.9.x] Fix project API failures

- ballerina/build.gradle
> Add service model generator to distribution

- .github/workflows/daily-build-2201.10.x.yml
- .github/workflows/daily-build-2201.11.x.yml
- .github/workflows/daily-build-2201.8.x.yml
- .github/workflows/daily-build-2201.9.x.yml
> Include daily build for 2201.11.x

- .github/workflows/daily-build-2201.10.x.yml
- .github/workflows/daily-build-2201.11.x.yml
> Fix generating windows installer

- pom.xml
> Update staging URLs for 1.2.56 release

- .github/workflows/daily-build-2201.11.x.yml
> Temporary skip project-api tests in daily build

- build.gradle
- gradle.properties
> [Master] Update version keys for jsondata module

- build.gradle
- gradle.properties
> [2201.11.x] Update version keys u11

- examples/logging/tests/log_api_test.bal
- gradle.properties
> [2201.11.x] Update dependency versions

- gradle.properties
> [2201.11.x] Update lang version

- examples/advanced-conflict-handling/advanced_conflict_handling.md
> [2201.11.x] Add missing `.out` extension

- examples/advanced-conflict-handling/advanced_conflict_handling.md
> [Master] Add missing .`out` extension

- gradle.properties
> 2201.10.4 lang version

- .trivyignore
> Skip CVE-2024-9143 vulnerability for 2201.10.4 release

- ballerina/build.gradle
> Pack the test-manager-service to distribution

- ballerina-test-automation/gradle.properties
> Update tool version in tests
> Update tool version in tests

- .github/workflows/publish_release_bi.yml
$title as the download link is not working.
> Fix the broken links in the notification

- .github/workflows/publish_release_bi.yml
$title as the download link is not available
> Fix the download link of the publish release

- gradle.properties
> [2201.11.x] Update patch versions

- gradle.properties
> [2201.10.x] Update patch versions

- ballerina-test-automation/gradle.properties
- gradle.properties
> Upgrade versions for Update 12

- gradle.properties
> Bump GraphQL library version and dependent versions

- pom.xml
> Update versions for 1.2.57 release

- gradle.properties
> Upgrade lang timestamp version

- gradle.properties
> Update openapi-tool and http module version

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> [2201.12.x] Bump library timestamp versions for 2201.12.0

- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- gradle.properties
> Bump library timestamp versions for 2201.12.0

- gradle.properties
> [2201.9.x] Update GraphQL Version

- gradle.properties
> [2201.12.x] Update OpenAPI version

- gradle.properties
> [2201.12.x] Update dependency versions

- gradle.properties
> Update lang version to `2210.12.0` in `master`

- gradle.properties
> Update dependency versions for 2201.12.0 release

- gradle.properties
> Bump lang version to 2201.12.1

- gradle.properties
> Bump xslt version to 2.9.1

- ballerina-test-automation/gradle.properties
- gradle.properties
> Bump versions for 2201.12.1

- gradle.properties
> Bump devtools version

- gradle.properties
> Bump master after update 12 releases

- gradle.properties
> [2201.9.x] Bump the GraphQL library version

- gradle.properties
> [2201.11.x] Bump the GraphQL library version

- gradle.properties
> [2201.12.x] Bump the GraphQL library version

- .trivyignore
$subject.
Will be tracked in: https://github.com/wso2-enterprise/internal-support-ballerina/issues/938 …
> [2201.12.x] Temporarily ignore trivy failure

- gradle.properties
> [2201.12.x] Bump dev-tools version

- .trivyignore
> Temporarily ignore failing trivy scan

- gradle.properties
> [2201.12.x] Bump c2c version

- gradle.properties
> [master] Bump c2c version

- gradle.properties
> Bump dev-tools version

- gradle.properties
> [2201.9.x] Update the GraphQL Version

- gradle.properties
> [2201.10.x] Update the GraphQL version

- pom.xml
> Update nexus staging urls for 1.2.58 release

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Update dist versions after 1.2.57 release

- gradle.properties
> Update lang,ftp versions

- build.gradle
- gradle.properties
> Add the np module

- .github/workflows/publish-release.yml
> Remove only -SNAPSHOT and skip prerelesae versions
> Remove only -SNAPSHOT and skip prerelesae versions

- ballerina/build.gradle
> Fix short version

- .github/workflows/publish-release.yml
> Skip Installer tests

- .github/workflows/publish-release-artifacts.yml
> Fix pre release support for artifact publishing
> Fix pre release support for artifact publishing

- .trivyignore
> Remove outdated cve vulnerability entries

- ballerina-test-automation/gradle.properties
- gradle.properties
> Bump the lang,dev-tool versions for 13-m2

- .trivyignore
> Ignore vulnerabilities temporarily 

- .trivyignore
> Ignore vulnerabilities

- .github/workflows/publish-release-artifacts.yml
> Change upload-artifact actions version

- ballerina-test-automation/gradle.properties
- gradle.properties
> Bump the lang version for 2201.12.4 release

- ballerina-test-automation/gradle.properties
- ballerina-test/src/test/java/org/ballerinalang/distribution/test/OpenAPIDistributionArtifactCheck.java
- ballerina/LICENSE
- gradle.properties
> Bump the lang version for 2201.12.5 release

- ballerina/LICENSE
- gradle.properties
> Bump the dev-tools for 2201.12.6 release

- examples/cdc-advanced-service/cdc_advanced_service.bal
- examples/cdc-advanced-service/cdc_advanced_service.md
- examples/cdc-advanced-service/cdc_advanced_service.metatags
- examples/cdc-advanced-service/cdc_advanced_service.out
- examples/cdc-prerequisite/README.md
- examples/cdc-prerequisite/setup_finance_db.bal
- examples/cdc-prerequisite/setup_store_db.bal
- examples/cdc-prerequisite/test_cdc_advanced_service.bal
- examples/cdc-prerequisite/test_cdc_service.bal
- examples/cdc-service/cdc_service.bal
- examples/cdc-service/cdc_service.md
- examples/cdc-service/cdc_service.metatags
- examples/cdc-service/cdc_service.out
- examples/index.json
> [2201.12.x] Add cdc examples

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Update nexus staging urls for 1.2.59 release

- .trivyignore
> Skip the trivyscan failure

- gradle.properties
> Bump the ai,np versions for m3 release

- gradle.properties
> Update std lib dependency versions

- ballerina/build.gradle
- build.gradle
- dist-repo-builder/src/main/java/io/ballerina/dist/DistRepoBuilder.java
- gradle.properties
> Add support for bal-tools.toml generation
> Add support for bal-tools.toml generation

- ballerina-test-automation/installer-test/src/test/java/io/ballerina/installer/test/TestUtils.java
> Fix handling pre-release versions
> Fix handling pre-release versions

- ballerina-test/pom.xml
- ballerina/pom.xml
- pom.xml
> Sync 1.2.x after release 1.2.62

- ballerina/build.gradle
> Remove a redundant step in dependency copy task

- gradle.properties
> Update stdlibFtpVersion to 2.14.1

- gradle.properties
> Bump versions for Update 13

- examples/ai-agent-external-endpoint-integration/ai_agent_external_endpoint_integration.bal
- examples/ai-agent-external-endpoint-integration/ai_agent_external_endpoint_integration.md
- examples/ai-agent-external-endpoint-integration/ai_agent_external_endpoint_integration.metatags
- examples/ai-agent-external-endpoint-integration/ai_agent_external_endpoint_integration.out
- examples/ai-agent-local-tools/ai_agent_local_tools.bal
- examples/ai-agent-local-tools/ai_agent_local_tools.md
- examples/ai-agent-local-tools/ai_agent_local_tools.metatags
- examples/ai-agent-local-tools/ai_agent_local_tools.out
- examples/ai-agent-mcp-integration/ai_agent_mcp_integration.bal
- examples/ai-agent-mcp-integration/ai_agent_mcp_integration.md
- examples/ai-agent-mcp-integration/ai_agent_mcp_integration.metatags
- examples/ai-agent-mcp-integration/ai_agent_mcp_integration.out
- examples/index.json
$title.
Part IV of https://github.com/ballerina-platform/ballerina-library/issues/8263
> Add the agent examples

- examples/index.json
- examples/natural-expressions/natural_expressions.bal
- examples/natural-expressions/natural_expressions.md
- examples/natural-expressions/natural_expressions.metatags
- examples/natural-expressions/natural_expressions.out
Part V of https://github.com/ballerina-platform/ballerina-library/issues/8263
> Add the natural expression example

- gradle.properties
> Update stdlibHttpVersion to 2.14.6

- gradle.properties
> Update stdlibCryptoVersion to 2.9.1

- gradle.properties
> Update latest versions

- gradle.properties
> Update Ballerina CLI Tools to the Latest Timestamp Versions

- gradle.properties
> Update OpenAPI module and tool versions
